// Re-export all types from the canonical source in lib/supabase/types.ts
export type {
  Database,
  Json,
  Robot,
  Review,
  RoboScoreBreakdown,
  RobotStatus,
  ReviewType,
  SubscriptionTier,
  RobotCategory,
  Manufacturer,
  User,
  AdvisorConversation,
  PriceHistory,
  NewsletterSubscriber,
  RobotImage,
  ConversationMessage,
  RobotWithRelations,
  ReviewWithRobot,
  LeaseInquiry,
  LeaseTransfer,
  RobotTimeShare,
  TimeShareBooking,
  RcoCertification,
  RcoExamSession,
  RcoCredential,
  ServiceRequest,
  PartsListing,
  TradeInValuation,
  CpoListing,
  RobotInsuranceInquiry,
  RspFleetStatus,
  RspMaintenanceLog,
  RspInvoice,
} from "@/lib/supabase/types";
