// Re-export all types from the canonical source in lib/supabase/types.ts
export type {
  Database,
  Json,
  Robot,
  Review,
  RoboScoreBreakdown,
  RobotStatus,
  ReviewType,
  SubscriptionTier,
  RobotCategory,
  Manufacturer,
  User,
  AdvisorConversation,
  PriceHistory,
  NewsletterSubscriber,
  RobotImage,
  ConversationMessage,
  RobotWithRelations,
  ReviewWithRobot,
} from "@/lib/supabase/types";
