/**
 * Seed data for the intelligence feed.
 * Real robotics news from Q1-Q2 2026, hand-processed in Bloomberg voice.
 */
export const SEED_ITEMS = [
  {
    title: "Eclipse Ventures Closes $1.3B Physical AI Fund",
    url: "https://www.bloomberg.com/eclipse-physical-ai-fund-2026",
    source_name: "Bloomberg",
    summary: "Eclipse Ventures closed a $1.3B fund dedicated exclusively to physical AI and robotics startups, the largest sector-specific fund in robotics history. The fund targets pre-seed through Series B companies building hardware-software systems for manufacturing, logistics, and defense.",
    what_it_means: "Capital allocation to robotics is shifting from generalist VC to dedicated sector funds, signaling institutional conviction that physical AI is a distinct asset class.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 92,
    robots_mentioned: [],
    manufacturers_mentioned: ["Eclipse Ventures"],
    tags: ["funding", "industrial", "manufacturing"],
    is_featured: true,
    published_at: "2026-03-15T14:00:00Z",
  },
  {
    title: "Unitree G1 Launches in US via AliExpress at $4,370",
    url: "https://www.therobotreport.com/unitree-g1-us-aliexpress-launch",
    source_name: "The Robot Report",
    summary: "Unitree Robotics began shipping the G1 humanoid robot to US consumers via AliExpress at a retail price of $4,370, undercutting every competitor by 75% or more. The 43-DOF biped robot ships from Shenzhen with 2-week delivery and a 1-year limited warranty.",
    what_it_means: "The sub-$5K humanoid price point makes consumer experimentation viable for the first time, accelerating the adoption curve that precedes industrial deployment.",
    category: "product",
    sentiment: "positive",
    relevance_score: 95,
    robots_mentioned: ["unitree-g1"],
    manufacturers_mentioned: ["Unitree Robotics"],
    tags: ["humanoid", "consumer", "manufacturing"],
    is_featured: true,
    published_at: "2026-03-20T09:00:00Z",
  },
  {
    title: "Figure AI Raises Series C at $39.5B Valuation",
    url: "https://techcrunch.com/figure-ai-series-c-2026",
    source_name: "TechCrunch",
    summary: "Figure AI closed a $2.6B Series C led by Microsoft and Nvidia at a $39.5B post-money valuation, making it the most valuable private robotics company globally. CEO Brett Adcock announced 1,000 Figure 03 units now deployed across BMW and Amazon facilities.",
    what_it_means: "Figure's valuation surpassing Boston Dynamics' parent Hyundai's robotics division signals that the market values AI-native humanoid companies over legacy players.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 98,
    robots_mentioned: ["figure-03"],
    manufacturers_mentioned: ["Figure AI", "Microsoft", "Nvidia"],
    tags: ["humanoid", "funding", "industrial"],
    is_featured: true,
    published_at: "2026-02-28T16:00:00Z",
  },
  {
    title: "Agility Robotics Secures $400M, Expands Amazon Digit Deployment",
    url: "https://www.therobotreport.com/agility-400m-amazon-digit-expansion",
    source_name: "The Robot Report",
    summary: "Agility Robotics raised $400M in growth funding to scale production of its Digit humanoid, which now operates in 12 Amazon fulfillment centers. The company targets 10,000 Digit units deployed by end of 2027.",
    what_it_means: "Amazon's continued Digit expansion validates the RaaS model for humanoids — Agility charges $10-30/hr rather than selling units outright.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 90,
    robots_mentioned: ["agility-digit"],
    manufacturers_mentioned: ["Agility Robotics", "Amazon"],
    tags: ["humanoid", "warehouse", "funding"],
    is_featured: true,
    published_at: "2026-03-05T11:00:00Z",
  },
  {
    title: "Apptronik Raises $350M, Partners with Mercedes-Benz",
    url: "https://venturebeat.com/apptronik-350m-mercedes-partnership",
    source_name: "VentureBeat",
    summary: "Apptronik closed a $350M Series B led by Google Ventures with strategic investment from Mercedes-Benz for its Apollo humanoid robot. Apollo units will begin automotive assembly trials at Mercedes plants in Stuttgart and Tuscaloosa in Q3 2026.",
    what_it_means: "European automakers are hedging against Chinese humanoid dominance by investing in US humanoid companies, creating a Western humanoid supply chain.",
    category: "partnership",
    sentiment: "positive",
    relevance_score: 88,
    robots_mentioned: ["apptronik-apollo"],
    manufacturers_mentioned: ["Apptronik", "Mercedes-Benz", "Google"],
    tags: ["humanoid", "manufacturing", "partnership"],
    is_featured: true,
    published_at: "2026-03-12T08:00:00Z",
  },
  {
    title: "Japan Commits $6.3B to Robotics, Targets 30% Global Market Share by 2040",
    url: "https://asia.nikkei.com/japan-robotics-6b-investment-2026",
    source_name: "Nikkei Asia",
    summary: "Japan's Ministry of Economy allocated ¥950B ($6.3B) over 5 years to domestic robotics R&D and manufacturing, targeting 30% global market share by 2040. The plan includes subsidies for companies deploying robots in eldercare, agriculture, and construction.",
    what_it_means: "Japan is the first G7 nation to make robotics a national industrial strategy priority, creating a government-backed competitor to China's 137-company humanoid ecosystem.",
    category: "regulation",
    sentiment: "positive",
    relevance_score: 87,
    robots_mentioned: [],
    manufacturers_mentioned: [],
    tags: ["regulation", "industrial", "manufacturing"],
    is_featured: true,
    published_at: "2026-03-18T04:00:00Z",
  },
  {
    title: "Physical Intelligence Raises $400M for Robot Foundation Models",
    url: "https://techcrunch.com/physical-intelligence-400m-raise",
    source_name: "TechCrunch",
    summary: "Physical Intelligence closed a $400M round led by Jeff Bezos and Khosla Ventures to develop pi-zero, a general-purpose foundation model for robotic manipulation. The model can control any robot arm with 90% fewer training examples than task-specific systems.",
    what_it_means: "Foundation models for robotics could commoditize hardware advantages — if pi-zero works as claimed, the cheapest robot with the best AI wins.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 91,
    robots_mentioned: [],
    manufacturers_mentioned: ["Physical Intelligence"],
    tags: ["autonomous", "funding", "industrial"],
    is_featured: true,
    published_at: "2026-01-22T15:00:00Z",
  },
  {
    title: "Boston Dynamics Atlas Begins Commercial Deployment at Hyundai",
    url: "https://spectrum.ieee.org/boston-dynamics-atlas-commercial-2026",
    source_name: "IEEE Spectrum",
    summary: "Boston Dynamics deployed its electric Atlas humanoid in a Hyundai Motor manufacturing facility in Ulsan, South Korea, performing heavy-part manipulation tasks. The deployment marks Atlas's transition from R&D demonstration to revenue-generating commercial operations.",
    what_it_means: "Boston Dynamics' shift from viral videos to factory deployment signals that the oldest humanoid company is finally competing on commercial terms, not just technical demos.",
    category: "product",
    sentiment: "positive",
    relevance_score: 89,
    robots_mentioned: ["boston-dynamics-atlas"],
    manufacturers_mentioned: ["Boston Dynamics", "Hyundai"],
    tags: ["humanoid", "manufacturing", "industrial"],
    is_featured: true,
    published_at: "2026-02-14T12:00:00Z",
  },
  {
    title: "Clone Robotics Unveils Protoclone Roadmap, $20K Target by 2028",
    url: "https://www.therobotreport.com/clone-robotics-protoclone-roadmap",
    source_name: "The Robot Report",
    summary: "Clone Robotics published a production roadmap for its muscle-actuated Protoclone humanoid, targeting a $20K retail price by 2028. The company's synthetic muscle approach uses hydraulic actuators that mimic human musculature, achieving human-equivalent strength at 60% of the weight.",
    what_it_means: "If muscle-actuated robots achieve production scale, the cost advantage over electric motor systems could reshape the humanoid competitive landscape.",
    category: "product",
    sentiment: "positive",
    relevance_score: 78,
    robots_mentioned: [],
    manufacturers_mentioned: ["Clone Robotics"],
    tags: ["humanoid", "consumer", "manufacturing"],
    is_featured: false,
    published_at: "2026-03-25T10:00:00Z",
  },
  {
    title: "BYD Files Patent for Autonomous EV Service Robot",
    url: "https://www.reuters.com/byd-autonomous-ev-service-robot-patent",
    source_name: "Reuters",
    summary: "BYD filed a patent for an autonomous robot designed to service electric vehicles in dealership and fleet facilities, combining mobile manipulation with diagnostic sensors. The filing describes a system capable of tire changes, fluid top-offs, and exterior inspection without human supervision.",
    what_it_means: "China's largest EV manufacturer entering robotics signals convergence between automotive and robotics supply chains that will accelerate component cost reduction for both industries.",
    category: "product",
    sentiment: "positive",
    relevance_score: 75,
    robots_mentioned: [],
    manufacturers_mentioned: ["BYD"],
    tags: ["autonomous", "manufacturing", "industrial"],
    is_featured: false,
    published_at: "2026-04-01T07:00:00Z",
  },
  {
    title: "Waymo Launches in Nashville, Expands to 60-Square-Mile Zone",
    url: "https://techcrunch.com/waymo-nashville-launch-2026",
    source_name: "TechCrunch",
    summary: "Waymo launched autonomous ride-hailing service in Nashville covering a 60-square-mile zone, its ninth US city. The expansion follows regulatory approval from Tennessee's Department of Transportation after a 6-month safety review.",
    what_it_means: "Each new Waymo city launch reduces the regulatory uncertainty premium on autonomous systems, making capital allocation to robotics less risky across all form factors.",
    category: "market",
    sentiment: "positive",
    relevance_score: 72,
    robots_mentioned: [],
    manufacturers_mentioned: ["Waymo"],
    tags: ["autonomous", "consumer"],
    is_featured: false,
    published_at: "2026-03-28T13:00:00Z",
  },
  {
    title: "Skild AI Raises $300M for Robot Foundation Models",
    url: "https://venturebeat.com/skild-ai-300m-softbank",
    source_name: "VentureBeat",
    summary: "Skild AI closed a $300M Series A led by SoftBank and Jeff Bezos to build cross-embodiment foundation models that enable any robot to learn tasks from demonstration. The Pittsburgh-based company claims its model generalizes across 4 different robot form factors.",
    what_it_means: "Two $300M+ raises for robot foundation models in 6 months indicates VCs believe the software layer for robotics will consolidate around a few large foundation model providers, similar to LLMs.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 85,
    robots_mentioned: [],
    manufacturers_mentioned: ["Skild AI", "SoftBank"],
    tags: ["autonomous", "funding", "industrial"],
    is_featured: true,
    published_at: "2026-01-30T14:00:00Z",
  },
  {
    title: "1X Technologies NEO Gamma Enters Beta Production",
    url: "https://www.therobotreport.com/1x-neo-gamma-beta-production",
    source_name: "The Robot Report",
    summary: "1X Technologies began beta production of the NEO Gamma humanoid at its new facility in Moss, Norway, with initial units shipping to 50 early-access households. At $20K and 35kg, NEO Gamma is the first humanoid robot designed specifically for home environments.",
    what_it_means: "The home humanoid market is now real — 1X's production start creates a reference point that every competitor must now price against.",
    category: "product",
    sentiment: "positive",
    relevance_score: 86,
    robots_mentioned: ["1x-neo-gamma"],
    manufacturers_mentioned: ["1X Technologies"],
    tags: ["humanoid", "consumer"],
    is_featured: true,
    published_at: "2026-04-03T09:00:00Z",
  },
  {
    title: "Covariant AI Team Absorbed by Amazon Robotics",
    url: "https://www.reuters.com/amazon-covariant-acquisition-robotics",
    source_name: "Reuters",
    summary: "Amazon completed the talent acquisition of Covariant, absorbing the 120-person AI team into Amazon Robotics. Covariant's RFM-1 foundation model for robotic manipulation is expected to power next-generation picking systems across Amazon's 750+ fulfillment centers.",
    what_it_means: "Amazon now has both the largest robot fleet (750K+ units) and arguably the best manipulation AI team, widening the gap between Amazon and every other warehouse operator.",
    category: "partnership",
    sentiment: "neutral",
    relevance_score: 88,
    robots_mentioned: [],
    manufacturers_mentioned: ["Amazon", "Covariant"],
    tags: ["warehouse", "autonomous", "industrial"],
    is_featured: true,
    published_at: "2026-02-05T11:00:00Z",
  },
  {
    title: "Hermeus Raises $350M for Hypersonic Autonomous Aircraft",
    url: "https://techcrunch.com/hermeus-350m-hypersonic-drone",
    source_name: "TechCrunch",
    summary: "Hermeus closed a $350M round to develop autonomous hypersonic aircraft capable of Mach 5+ speeds, backed by the US Air Force and private investors. The company's Quarterhorse prototype completed its first unmanned test flight at Edwards AFB.",
    what_it_means: "Defense robotics funding is accelerating separately from commercial, creating a parallel market that could produce spillover technology for civilian autonomous systems.",
    category: "funding",
    sentiment: "positive",
    relevance_score: 70,
    robots_mentioned: [],
    manufacturers_mentioned: ["Hermeus"],
    tags: ["autonomous", "funding"],
    is_featured: false,
    published_at: "2026-03-08T16:00:00Z",
  },
];
