/**
 * Social Content Generator
 * Generates weekly social media content for X (Twitter) and LinkedIn.
 * Pulls real data from Supabase and uses Claude for content generation.
 *
 * Usage: npx tsx scripts/generate-social-content.ts
 */

import "dotenv/config";
import { createClient } from "@supabase/supabase-js";
import Anthropic from "@anthropic-ai/sdk";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const today = new Date();
const weekStr = today.toISOString().slice(0, 10);
const outputDir = join(process.cwd(), "docs");

interface Robot {
  name: string;
  manufacturer: string;
  category: string;
  price_range: string | null;
  robo_score: number | null;
  description: string | null;
}

async function getRecentRobots(): Promise<Robot[]> {
  const { data } = await supabase
    .from("robots")
    .select("name, manufacturer, category, price_range, robo_score, description")
    .order("created_at", { ascending: false })
    .limit(5);
  return (data as Robot[]) || [];
}

async function getTopRobots(): Promise<Robot[]> {
  const { data } = await supabase
    .from("robots")
    .select("name, manufacturer, category, price_range, robo_score, description")
    .not("robo_score", "is", null)
    .order("robo_score", { ascending: false })
    .limit(10);
  return (data as Robot[]) || [];
}

async function getRobotCount(): Promise<number> {
  const { count } = await supabase
    .from("robots")
    .select("id", { count: "exact", head: true });
  return count || 0;
}

async function generateContent(prompt: string): Promise<string> {
  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 2000,
    messages: [{ role: "user", content: prompt }],
  });
  const block = response.content[0];
  return block.type === "text" ? block.text : "";
}

async function main() {
  console.log(`Generating social content for week of ${weekStr}...`);

  const [recentRobots, topRobots, robotCount] = await Promise.all([
    getRecentRobots(),
    getTopRobots(),
    getRobotCount(),
  ]);

  const robotOfWeek = topRobots[Math.floor(Math.random() * Math.min(5, topRobots.length))];
  const newRobot = recentRobots[0];

  const context = `
Brand: Robotomated — the intelligence layer for the robotics era.
Tone: authoritative, accessible, data-driven. No emojis.
Database: ${robotCount} robots tracked.
Robot of the Week: ${robotOfWeek?.name} by ${robotOfWeek?.manufacturer} (RoboScore: ${robotOfWeek?.robo_score}/100, ${robotOfWeek?.category})
Newest Robot: ${newRobot?.name} by ${newRobot?.manufacturer} (${newRobot?.category})
Top 5 robots by score: ${topRobots.slice(0, 5).map(r => `${r.name} (${r.robo_score})`).join(", ")}
  `.trim();

  // Generate Twitter content
  const twitterPrompt = `${context}

Generate 7 tweets for X/Twitter (one per day, Mon-Sun). Each tweet should be 240 characters max. No emojis. Include relevant hashtags like #robotics #automation #warehousing.

Format each as:
[DAY]: [tweet text]

Monday: Robot of the week spotlight
Tuesday: Industry stat or insight
Wednesday: "Did you know?" robot fact
Thursday: ROI/cost data point
Friday: New robot added announcement
Saturday: Quick case study highlight
Sunday: Week in robotics roundup

Make them informative and engaging. Link to robotomated.com where relevant.`;

  const linkedinPrompt = `${context}

Generate 3 LinkedIn posts (Mon/Wed/Fri). LinkedIn tone: professional, insightful, thought-leadership.

Monday (500 words): Industry analysis post about a trend in commercial robotics.
Wednesday (200 words): Practical tip for robot buyers.
Friday (200 words): Platform update / what's new at Robotomated.

Format each as:
[DAY]
---
[post content]
---

No emojis. Include a call to action at the end of each post.`;

  console.log("Generating Twitter content...");
  const twitterContent = await generateContent(twitterPrompt);

  console.log("Generating LinkedIn content...");
  const linkedinContent = await generateContent(linkedinPrompt);

  const output = `# Social Content — Week of ${weekStr}
Generated: ${new Date().toISOString()}
Robot Count: ${robotCount}
Robot of the Week: ${robotOfWeek?.name || "N/A"}

---

## Twitter/X (7 posts)

${twitterContent}

---

## LinkedIn (3 posts)

${linkedinContent}

---

*Generated by Robotomated content engine. Review before publishing.*
`;

  if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });
  const outputPath = join(outputDir, `social-content-${weekStr}.md`);
  writeFileSync(outputPath, output);

  console.log(`Social content written to: ${outputPath}`);
  console.log("Done.");
}

main().catch(console.error);
