/**
 * Robotomated — Wave 16 Robot Import: 50 New Robots
 * Focus: Machine vision inspection, quality control, surface inspection, dimensional measurement
 * Run: npx tsx scripts/import-robots-wave16.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  { slug: "cognex", name: "Cognex", country: "US", founded_year: 1981, website: "https://cognex.com" },
  { slug: "keyence", name: "Keyence", country: "JP", founded_year: 1974, website: "https://keyence.com" },
  { slug: "isra-vision", name: "ISRA Vision", country: "DE", founded_year: 1985, website: "https://isravision.com" },
  { slug: "elementary-ai", name: "Elementary", country: "US", founded_year: 2017, website: "https://elementary.ai" },
  { slug: "instrumental-ai", name: "Instrumental", country: "US", founded_year: 2015, website: "https://instrumental.com" },
  { slug: "landing-ai", name: "Landing AI", country: "US", founded_year: 2017, website: "https://landing.ai" },
  { slug: "neurala", name: "Neurala", country: "US", founded_year: 2006, website: "https://neurala.com" },
  { slug: "visio-ai", name: "Visio.AI", country: "US", founded_year: 2019, website: "https://visio.ai" },
];

// ═══════════════════════════════════════════════════════════════
// ROBOTS — 50 total (8 Cognex, 8 Keyence, 6 ISRA, 6 Elementary, 6 Instrumental, 6 Landing AI, 5 Neurala, 5 other)
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

// ═══ Cognex Vision Systems (8) ═══
{slug:"cognex-insight-3800",name:"Cognex In-Sight 3800",mfr:"cognex",cat:"manufacturing",price:8500,year:2024,status:"active",desc:"High-performance embedded vision system with edge-learning AI for defect detection and classification. Processes 300+ parts per minute inline. Self-contained camera, lighting, and processing in IP67 housing.",specs:{type:"Embedded vision system",throughput:"300+ parts/min",ai:"Edge Learning classification",resolution:"5 MP",housing:"IP67 self-contained",lighting:"Integrated multi-color LED",interface:"EtherNet/IP, PROFINET"},score:cs({performance:84,reliability:86,ease_of_use:80,intelligence:82,value:78,ecosystem:84,safety:78,design:78}),breakdown:{performance:84,reliability:86,ease_of_use:80,intelligence:82,value:78,ecosystem:84,safety:78,design:78}},
{slug:"cognex-insight-2800",name:"Cognex In-Sight 2800",mfr:"cognex",cat:"manufacturing",price:4500,year:2024,status:"active",desc:"Compact vision sensor combining traditional machine vision with edge-learning AI. Detects presence, measures dimensions, and reads codes in a single device. 2 MP sensor with autofocus for flexible deployment.",specs:{type:"Compact vision sensor",resolution:"2 MP",focus:"Autofocus",ai:"Edge Learning + traditional",functions:"Presence, measurement, code reading",housing:"IP67 compact",price_point:"Mid-range entry"},score:cs({performance:78,reliability:86,ease_of_use:84,intelligence:78,value:84,ecosystem:84,safety:78,design:78}),breakdown:{performance:78,reliability:86,ease_of_use:84,intelligence:78,value:84,ecosystem:84,safety:78,design:78}},
{slug:"cognex-visionpro-dl",name:"Cognex VisionPro Deep Learning",mfr:"cognex",cat:"software",price:null,year:2024,status:"active",desc:"PC-based deep learning software for complex visual inspection tasks. Pre-trained neural networks classify defects, segment surfaces, and detect anomalies. Runs on standard GPU hardware. Licensed from $15K.",specs:{type:"Deep learning vision software",ai:"Pre-trained + custom neural nets",functions:"Classification, segmentation, anomaly detection",platform:"PC + GPU",gpu:"NVIDIA CUDA compatible",training:"Image-based, no coding",license_from:15000},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:90,value:76,ecosystem:84,safety:78,design:74}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:90,value:76,ecosystem:84,safety:78,design:74}},
{slug:"cognex-3d-a5000",name:"Cognex 3D-A5000 Area Scanner",mfr:"cognex",cat:"manufacturing",price:18000,year:2024,status:"active",desc:"High-resolution 3D area scan sensor for surface and dimensional inspection. Captures 2 million 3D points per scan at 0.01 mm accuracy. Inspects complex surfaces for dents, scratches, and dimensional deviations.",specs:{type:"3D area scan sensor",points_per_scan:"2 million",accuracy_mm:0.01,technology:"Structured light",scan_area_mm:"200x200",application:"Surface, dimensional inspection",speed:"5 scans/sec"},score:cs({performance:86,reliability:86,ease_of_use:74,intelligence:80,value:74,ecosystem:84,safety:78,design:76}),breakdown:{performance:86,reliability:86,ease_of_use:74,intelligence:80,value:74,ecosystem:84,safety:78,design:76}},
{slug:"cognex-dataman-580",name:"Cognex DataMan 580",mfr:"cognex",cat:"manufacturing",price:6500,year:2024,status:"active",desc:"Fixed-mount barcode reader with AI-powered decoding for damaged and low-contrast codes. Reads 1D and 2D codes at 120 reads per second including DPM (Direct Part Mark) on metal and plastic.",specs:{type:"Fixed-mount barcode reader",reads_per_sec:120,codes:"1D, 2D, DPM",ai:"AI-powered decode algorithms",surface:"Metal, plastic, curved",connection:"Industrial Ethernet",housing:"IP67"},score:cs({performance:84,reliability:88,ease_of_use:84,intelligence:76,value:80,ecosystem:86,safety:78,design:76}),breakdown:{performance:84,reliability:88,ease_of_use:84,intelligence:76,value:80,ecosystem:86,safety:78,design:76}},
{slug:"cognex-3d-l4000",name:"Cognex 3D-L4000 Line Scanner",mfr:"cognex",cat:"manufacturing",price:15000,year:2024,status:"active",desc:"Laser line profiler for inline 3D inspection of moving parts on conveyors. 4K resolution at scan rates up to 18 kHz. Measures height, volume, angle, and cross-sectional profiles of automotive and electronics parts.",specs:{type:"3D laser line profiler",resolution:"4K",scan_rate_khz:18,measurements:"Height, volume, angle, profile",application:"Automotive, electronics inline",mounting:"Over conveyor",field_of_view_mm:300},score:cs({performance:86,reliability:86,ease_of_use:72,intelligence:78,value:76,ecosystem:84,safety:78,design:74}),breakdown:{performance:86,reliability:86,ease_of_use:72,intelligence:78,value:76,ecosystem:84,safety:78,design:74}},
{slug:"cognex-edge-intelligence",name:"Cognex Edge Intelligence",mfr:"cognex",cat:"software",price:null,year:2024,status:"active",desc:"Factory-wide analytics platform aggregating inspection data from all Cognex devices. Tracks defect trends, identifies root causes, and predicts quality issues. Dashboard accessible via web browser. SaaS pricing.",specs:{type:"Quality analytics platform",functions:"Trend analysis, root cause, prediction",data_source:"All Cognex devices",dashboard:"Web-based",deployment:"Cloud or on-premise",model:"SaaS subscription"},score:cs({performance:80,reliability:84,ease_of_use:82,intelligence:84,value:76,ecosystem:86,safety:78,design:78}),breakdown:{performance:80,reliability:84,ease_of_use:82,intelligence:84,value:76,ecosystem:86,safety:78,design:78}},
{slug:"cognex-insight-7800",name:"Cognex In-Sight 7800",mfr:"cognex",cat:"manufacturing",price:12000,year:2024,status:"active",desc:"High-speed vision system processing 900+ parts per minute for high-volume packaging and labeling inspection. 12 MP sensor with line-scan mode for continuous web inspection of printed materials.",specs:{type:"High-speed vision system",throughput:"900+ parts/min",resolution:"12 MP",mode:"Area + line-scan",application:"Packaging, label, print inspection",speed:"Sub-millisecond exposure",interface:"GigE, EtherNet/IP"},score:cs({performance:88,reliability:86,ease_of_use:76,intelligence:80,value:76,ecosystem:84,safety:78,design:76}),breakdown:{performance:88,reliability:86,ease_of_use:76,intelligence:80,value:76,ecosystem:84,safety:78,design:76}},

// ═══ Keyence Inspection Systems (8) ═══
{slug:"keyence-xg-x2900",name:"Keyence XG-X2900 Vision System",mfr:"keyence",cat:"manufacturing",price:14000,year:2024,status:"active",desc:"Multi-camera vision system supporting up to 8 cameras simultaneously. 21 MP maximum resolution with sub-pixel measurement accuracy. Used in automotive, electronics, and medical device inspection lines.",specs:{type:"Multi-camera vision system",cameras_max:8,resolution:"21 MP max",accuracy:"Sub-pixel",processing:"Dedicated FPGA + CPU",application:"Automotive, electronics, medical",controller:"XG-X standalone"},score:cs({performance:88,reliability:88,ease_of_use:76,intelligence:80,value:74,ecosystem:82,safety:78,design:76}),breakdown:{performance:88,reliability:88,ease_of_use:76,intelligence:80,value:74,ecosystem:82,safety:78,design:76}},
{slug:"keyence-cv-x490f",name:"Keyence CV-X490F AI Vision",mfr:"keyence",cat:"manufacturing",price:9500,year:2024,status:"active",desc:"AI-powered machine vision with built-in deep learning for defect detection. Learns from as few as 20 sample images. No programming required — visual workflow builder. 12 MP sensor with integrated lighting.",specs:{type:"AI vision system",ai:"Built-in deep learning",training:"From 20 images",programming:"Visual workflow — no code",resolution:"12 MP",lighting:"Integrated multi-angle",setup_time:"Hours, not days"},score:cs({performance:84,reliability:86,ease_of_use:88,intelligence:84,value:80,ecosystem:82,safety:78,design:78}),breakdown:{performance:84,reliability:86,ease_of_use:88,intelligence:84,value:80,ecosystem:82,safety:78,design:78}},
{slug:"keyence-lj-x8900",name:"Keyence LJ-X8900 3D Profiler",mfr:"keyence",cat:"manufacturing",price:22000,year:2024,status:"active",desc:"Ultra-high-speed 3D profile measurement sensor scanning at 64,000 profiles per second. 3200-point resolution per profile for detailed surface topography. Measures sub-micron height variations in semiconductor and precision manufacturing.",specs:{type:"3D laser profiler",profiles_per_sec:64000,points_per_profile:3200,accuracy:"Sub-micron",application:"Semiconductor, precision mfg",technology:"Blue laser triangulation",measurement:"Height, width, angle, volume"},score:cs({performance:90,reliability:88,ease_of_use:72,intelligence:78,value:72,ecosystem:82,safety:78,design:76}),breakdown:{performance:90,reliability:88,ease_of_use:72,intelligence:78,value:72,ecosystem:82,safety:78,design:76}},
{slug:"keyence-im-8000",name:"Keyence IM-8000 Image Dimension Measurement",mfr:"keyence",cat:"manufacturing",price:45000,year:2024,status:"active",desc:"Instant measurement system capturing up to 300 dimensions simultaneously from a single image. Place part, press button, get results in seconds. No fixtures or programming needed. Accuracy of +/- 1 micron.",specs:{type:"Instant dimension measurement",dimensions_per_image:300,accuracy_micron:1,measurement_time:"Seconds",fixture:"None required",programming:"None — place and measure",application:"QC lab, inline inspection"},score:cs({performance:86,reliability:88,ease_of_use:92,intelligence:78,value:74,ecosystem:82,safety:78,design:82}),breakdown:{performance:86,reliability:88,ease_of_use:92,intelligence:78,value:74,ecosystem:82,safety:78,design:82}},
{slug:"keyence-vr-6200",name:"Keyence VR-6200 3D Measurement",mfr:"keyence",cat:"manufacturing",price:55000,year:2024,status:"active",desc:"Wide-area 3D measurement macroscope scanning 200mm x 100mm surfaces in 1 second. Captures full 3D surface profile without contact. Used for weld bead measurement, surface roughness, and wear analysis.",specs:{type:"3D surface measurement",scan_area_mm:"200x100",scan_time_s:1,resolution:"Sub-micron Z axis",application:"Weld bead, roughness, wear",method:"Non-contact optical",data:"Full 3D surface profile"},score:cs({performance:86,reliability:86,ease_of_use:84,intelligence:76,value:72,ecosystem:80,safety:78,design:80}),breakdown:{performance:86,reliability:86,ease_of_use:84,intelligence:76,value:72,ecosystem:80,safety:78,design:80}},
{slug:"keyence-ix-1000",name:"Keyence IX-1000 Image-Based Sensor",mfr:"keyence",cat:"manufacturing",price:3200,year:2024,status:"active",desc:"Compact image-based laser sensor for simple pass/fail inspection at high speeds. Detects shape, edge, and presence in 0.5 ms. Entry-level vision for production lines without dedicated vision engineers.",specs:{type:"Image-based sensor",inspection_time_ms:0.5,functions:"Shape, edge, presence",skill_level:"No vision expertise needed",housing:"IP67 compact",interface:"IO-Link",application:"High-speed pass/fail"},score:cs({performance:76,reliability:86,ease_of_use:90,intelligence:68,value:88,ecosystem:80,safety:78,design:76}),breakdown:{performance:76,reliability:86,ease_of_use:90,intelligence:68,value:88,ecosystem:80,safety:78,design:76}},
{slug:"keyence-sr-5000",name:"Keyence SR-5000 3D Code Reader",mfr:"keyence",cat:"manufacturing",price:4800,year:2024,status:"active",desc:"Ultra-wide-field code reader covering 1200mm width for reading codes on moving packages at belt speeds up to 3 m/s. AI-powered decoding handles damaged, skewed, and low-contrast codes on any surface.",specs:{type:"Wide-field code reader",field_width_mm:1200,belt_speed_m_s:3,codes:"1D, 2D, DPM",ai:"AI decode algorithms",application:"Logistics, packaging lines",read_rate:"99.9%+"},score:cs({performance:84,reliability:86,ease_of_use:84,intelligence:76,value:80,ecosystem:82,safety:78,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:84,intelligence:76,value:80,ecosystem:82,safety:78,design:76}},
{slug:"keyence-tm-3000",name:"Keyence TM-3000 Telecentric Measurement",mfr:"keyence",cat:"manufacturing",price:28000,year:2024,status:"active",desc:"Telecentric 2D measurement system for precise edge-to-edge dimensional measurement. Eliminates parallax error common in standard cameras. 0.1-micron display resolution for sub-micron repeatability.",specs:{type:"Telecentric 2D measurement",resolution_micron:0.1,parallax:"Eliminated — telecentric optic",repeatability:"Sub-micron",application:"Precision parts, connectors, pins",method:"Shadow/transmitted light",measurement:"Edge-to-edge dimensional"},score:cs({performance:86,reliability:88,ease_of_use:80,intelligence:72,value:74,ecosystem:80,safety:78,design:76}),breakdown:{performance:86,reliability:88,ease_of_use:80,intelligence:72,value:74,ecosystem:80,safety:78,design:76}},

// ═══ ISRA Vision Surface Inspection (6) ═══
{slug:"isra-surface-master",name:"ISRA Vision SurfaceMaster",mfr:"isra-vision",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Inline surface inspection system for painted and glossy surfaces. Detects dents, scratches, orange peel, and inclusions at speeds up to 2 m/s. Deployed in automotive paint shops at BMW, Audi, and Toyota. From $250K.",specs:{type:"Surface inspection system",defects:"Dents, scratches, orange peel, inclusions",speed_m_s:2,resolution_micron:50,application:"Automotive paint inspection",customers:"BMW, Audi, Toyota",system_price:250000},score:cs({performance:86,reliability:86,ease_of_use:72,intelligence:84,value:72,ecosystem:78,safety:78,design:74}),breakdown:{performance:86,reliability:86,ease_of_use:72,intelligence:84,value:72,ecosystem:78,safety:78,design:74}},
{slug:"isra-printstar",name:"ISRA Vision PrintSTAR",mfr:"isra-vision",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Web inspection system for continuous print quality monitoring on packaging lines. Inspects at speeds up to 15 m/s with 100% coverage. Detects color deviations, registration errors, and missing print. From $180K.",specs:{type:"Print/web inspection",speed_m_s:15,coverage:"100%",defects:"Color deviation, registration, missing print",application:"Packaging, labels, flexible packaging",resolution:"0.1 mm",system_price:180000},score:cs({performance:86,reliability:84,ease_of_use:74,intelligence:80,value:76,ecosystem:76,safety:78,design:74}),breakdown:{performance:86,reliability:84,ease_of_use:74,intelligence:80,value:76,ecosystem:76,safety:78,design:74}},
{slug:"isra-glass-master",name:"ISRA Vision GlassMaster",mfr:"isra-vision",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Glass surface and edge inspection for automotive and architectural glass. Detects bubbles, inclusions, scratches, and edge chips at line speeds up to 3 m/s. Used in 60%+ of global automotive glass production. From $300K.",specs:{type:"Glass inspection system",defects:"Bubbles, inclusions, scratches, edge chips",speed_m_s:3,market_share:"60%+ automotive glass",application:"Automotive, architectural glass",resolution_micron:30,system_price:300000},score:cs({performance:88,reliability:86,ease_of_use:70,intelligence:82,value:70,ecosystem:78,safety:78,design:72}),breakdown:{performance:88,reliability:86,ease_of_use:70,intelligence:82,value:70,ecosystem:78,safety:78,design:72}},
{slug:"isra-metal-master",name:"ISRA Vision MetalMaster",mfr:"isra-vision",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Inline metal surface inspection for steel coils, aluminum sheets, and metal strips. Detects surface defects at rolling speeds up to 30 m/s. Classification AI distinguishes 50+ defect types. From $350K.",specs:{type:"Metal surface inspection",speed_m_s:30,defect_types:50,materials:"Steel coils, aluminum, metal strip",application:"Steel mills, aluminum rolling",resolution_micron:100,system_price:350000},score:cs({performance:88,reliability:86,ease_of_use:68,intelligence:84,value:68,ecosystem:76,safety:78,design:72}),breakdown:{performance:88,reliability:86,ease_of_use:68,intelligence:84,value:68,ecosystem:76,safety:78,design:72}},
{slug:"isra-plasticstar",name:"ISRA Vision PlasticSTAR",mfr:"isra-vision",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Surface inspection for plastic films, sheets, and extruded products. Detects gels, black specs, holes, and thickness variations inline. Covers film widths up to 6 m at 10 m/s. From $200K.",specs:{type:"Plastic film inspection",defects:"Gels, black specs, holes, thickness",film_width_m:6,speed_m_s:10,application:"Plastic film, extrusion",resolution_micron:50,system_price:200000},score:cs({performance:84,reliability:84,ease_of_use:72,intelligence:80,value:74,ecosystem:76,safety:78,design:72}),breakdown:{performance:84,reliability:84,ease_of_use:72,intelligence:80,value:74,ecosystem:76,safety:78,design:72}},
{slug:"isra-texturestudio",name:"ISRA Vision TextureSTUDIO",mfr:"isra-vision",cat:"software",price:null,year:2024,status:"active",desc:"AI-powered texture and surface analysis software for automated quality grading. Learns surface quality standards from sample images and grades production output. Integrates with all ISRA inspection hardware. From $50K license.",specs:{type:"Surface analysis AI software",ai:"Texture classification neural net",training:"Sample image learning",grading:"Automated quality grading",integration:"All ISRA hardware",deployment:"Edge + server",license_from:50000},score:cs({performance:82,reliability:82,ease_of_use:76,intelligence:86,value:76,ecosystem:78,safety:78,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:76,intelligence:86,value:76,ecosystem:78,safety:78,design:74}},

// ═══ Elementary.ai Defect Detection (6) ═══
{slug:"elementary-inspector-360",name:"Elementary Inspector 360",mfr:"elementary-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI visual inspection platform combining cameras with deep learning for manufacturing defect detection. Inspects 360-degree surfaces of parts on conveyors. Learns new defect types from as few as 10 images. From $4,000/mo.",specs:{type:"AI visual inspection platform",coverage:"360-degree surface",training:"10 images minimum",speed:"120 parts/min",ai:"Deep learning defect detection",deployment:"Edge computing",subscription_monthly:4000},score:cs({performance:82,reliability:80,ease_of_use:84,intelligence:86,value:78,ecosystem:72,safety:78,design:78}),breakdown:{performance:82,reliability:80,ease_of_use:84,intelligence:86,value:78,ecosystem:72,safety:78,design:78}},
{slug:"elementary-inspector-micro",name:"Elementary Inspector Micro",mfr:"elementary-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Microscopy-grade AI inspection for detecting sub-millimeter defects on small components. 50-micron resolution catches hairline cracks, contamination, and micro-scratches. Deployed in semiconductor and medical device lines. From $5,500/mo.",specs:{type:"Micro AI inspection",resolution_micron:50,defects:"Cracks, contamination, micro-scratch",application:"Semiconductor, medical devices",ai:"High-resolution deep learning",magnification:"Up to 20x",subscription_monthly:5500},score:cs({performance:84,reliability:80,ease_of_use:82,intelligence:88,value:74,ecosystem:72,safety:78,design:76}),breakdown:{performance:84,reliability:80,ease_of_use:82,intelligence:88,value:74,ecosystem:72,safety:78,design:76}},
{slug:"elementary-cloud-analytics",name:"Elementary Cloud Analytics",mfr:"elementary-ai",cat:"software",price:null,year:2024,status:"active",desc:"Cloud-based quality analytics dashboard aggregating inspection data from all Elementary stations. Tracks defect trends, yield rates, and process drift across multiple production lines and facilities. SaaS included with inspection.",specs:{type:"Cloud quality analytics",functions:"Defect trends, yield, process drift",scope:"Multi-line, multi-facility",visualization:"Web dashboard",alerting:"Real-time anomaly alerts",included:"With inspection subscription"},score:cs({performance:78,reliability:82,ease_of_use:84,intelligence:82,value:80,ecosystem:74,safety:78,design:78}),breakdown:{performance:78,reliability:82,ease_of_use:84,intelligence:82,value:80,ecosystem:74,safety:78,design:78}},
{slug:"elementary-inspector-weld",name:"Elementary Weld Inspector",mfr:"elementary-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Specialized AI inspection for weld quality assessment. Detects porosity, undercut, spatter, and incomplete fusion in arc and spot welds. Replaces manual visual weld inspection with consistent AI grading. From $4,500/mo.",specs:{type:"AI weld inspection",defects:"Porosity, undercut, spatter, incomplete fusion",weld_types:"Arc, spot, laser",ai:"Weld-specific deep learning",replacement:"Manual visual inspection",grading:"Automated pass/fail + severity",subscription_monthly:4500},score:cs({performance:82,reliability:80,ease_of_use:82,intelligence:86,value:76,ecosystem:72,safety:80,design:74}),breakdown:{performance:82,reliability:80,ease_of_use:82,intelligence:86,value:76,ecosystem:72,safety:80,design:74}},
{slug:"elementary-inspector-label",name:"Elementary Label Inspector",mfr:"elementary-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI inspection system for label placement, print quality, and content verification on packaging lines. Checks alignment, text legibility, barcode readability, and color accuracy at 200+ packages per minute. From $3,500/mo.",specs:{type:"AI label inspection",throughput:"200+ packages/min",checks:"Alignment, text, barcode, color",ai:"OCR + deep learning",application:"Packaging lines",accuracy:"99.8% detection rate",subscription_monthly:3500},score:cs({performance:82,reliability:80,ease_of_use:84,intelligence:84,value:80,ecosystem:72,safety:78,design:76}),breakdown:{performance:82,reliability:80,ease_of_use:84,intelligence:84,value:80,ecosystem:72,safety:78,design:76}},
{slug:"elementary-inspector-assembly",name:"Elementary Assembly Inspector",mfr:"elementary-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI visual verification for assembly completeness and correctness. Confirms presence, position, and orientation of components in assembled products. Catches missing screws, reversed parts, and misaligned connectors. From $4,000/mo.",specs:{type:"AI assembly verification",checks:"Presence, position, orientation",defects:"Missing parts, reversed, misaligned",ai:"Deep learning + rule-based hybrid",training:"Photo examples per station",speed:"60 assemblies/min",subscription_monthly:4000},score:cs({performance:80,reliability:80,ease_of_use:84,intelligence:84,value:78,ecosystem:72,safety:78,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:84,intelligence:84,value:78,ecosystem:72,safety:78,design:76}},

// ═══ Instrumental Visual Inspection (6) ═══
{slug:"instrumental-station-v4",name:"Instrumental Station V4",mfr:"instrumental-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"High-resolution inspection station capturing images of every unit on production lines. AI analyzes images for cosmetic defects, assembly errors, and process deviations. Deployed at electronics contract manufacturers. From $6,000/mo.",specs:{type:"Production line inspection station",resolution:"20 MP multi-camera",coverage:"Top, bottom, sides",ai:"Deep learning defect detection",deployment:"Electronics CM lines",data:"100% unit traceability",subscription_monthly:6000},score:cs({performance:84,reliability:82,ease_of_use:78,intelligence:86,value:74,ecosystem:74,safety:78,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:78,intelligence:86,value:74,ecosystem:74,safety:78,design:78}},
{slug:"instrumental-discover",name:"Instrumental Discover AI",mfr:"instrumental-ai",cat:"software",price:null,year:2024,status:"active",desc:"Unsupervised anomaly detection that automatically finds new defect types without labeled training data. Learns normal appearance and flags deviations. Critical for detecting unknown failure modes in new product launches. From $3,000/mo.",specs:{type:"Unsupervised anomaly detection",ai:"Unsupervised — no labels needed",detection:"Unknown/novel defects",learning:"Normal appearance modeling",application:"New product launches, NPI",deployment:"Cloud + edge",subscription_monthly:3000},score:cs({performance:80,reliability:80,ease_of_use:82,intelligence:88,value:78,ecosystem:74,safety:78,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:82,intelligence:88,value:78,ecosystem:74,safety:78,design:76}},
{slug:"instrumental-trace",name:"Instrumental Trace Analytics",mfr:"instrumental-ai",cat:"software",price:null,year:2024,status:"active",desc:"Unit-level traceability platform linking inspection images to individual serial numbers. Enables root cause analysis when field failures occur by reviewing manufacturing images of specific failed units. SaaS included.",specs:{type:"Unit traceability platform",function:"Image-to-serial-number linking",analysis:"Root cause from field failures",retention:"Full production history",search:"Serial number image lookup",included:"With Instrumental subscription"},score:cs({performance:78,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:74,safety:78,design:76}),breakdown:{performance:78,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:74,safety:78,design:76}},
{slug:"instrumental-go",name:"Instrumental GO Portable Inspector",mfr:"instrumental-ai",cat:"manufacturing",price:null,year:2025,status:"active",desc:"Portable inspection unit for temporary production lines and pilot runs. Self-contained camera, lighting, and edge AI in a cart-mounted unit. Deploy in minutes for quick quality checks during ramp-up. From $2,500/mo.",specs:{type:"Portable inspection unit",form_factor:"Cart-mounted self-contained",setup_time:"Minutes",ai:"Edge AI processing",application:"Pilot runs, temporary lines, NPI",camera:"12 MP + ring light",subscription_monthly:2500},score:cs({performance:76,reliability:78,ease_of_use:86,intelligence:80,value:80,ecosystem:72,safety:78,design:78}),breakdown:{performance:76,reliability:78,ease_of_use:86,intelligence:80,value:80,ecosystem:72,safety:78,design:78}},
{slug:"instrumental-solder-check",name:"Instrumental Solder Inspector",mfr:"instrumental-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Specialized AI model for solder joint inspection on PCBs. Detects cold solder, bridging, insufficient solder, and tombstoning. Augments AOI with deep learning for defects traditional AOI misses. From $5,000/mo.",specs:{type:"AI solder joint inspection",defects:"Cold solder, bridging, insufficient, tombstone",application:"PCB assembly lines",ai:"Solder-specific deep learning",augments:"Traditional AOI systems",throughput:"Inline at conveyor speed",subscription_monthly:5000},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:88,value:74,ecosystem:74,safety:78,design:74}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:88,value:74,ecosystem:74,safety:78,design:74}},
{slug:"instrumental-comparator",name:"Instrumental Visual Comparator",mfr:"instrumental-ai",cat:"software",price:null,year:2024,status:"active",desc:"Side-by-side visual comparison tool for golden sample vs production unit analysis. Highlights pixel-level differences between reference and inspected parts. Used in incoming quality inspection and supplier audits. From $2,000/mo.",specs:{type:"Visual comparison tool",method:"Golden sample vs production",analysis:"Pixel-level difference mapping",application:"IQC, supplier audits",visualization:"Side-by-side overlay",accuracy:"Sub-pixel alignment",subscription_monthly:2000},score:cs({performance:78,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:72,safety:78,design:76}),breakdown:{performance:78,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:72,safety:78,design:76}},

// ═══ Landing AI Visual Inspection (6) ═══
{slug:"landing-ai-visual-platform",name:"Landing AI Visual Inspection Platform",mfr:"landing-ai",cat:"software",price:null,year:2024,status:"active",desc:"Andrew Ng's data-centric AI platform for manufacturing visual inspection. Emphasizes small-dataset training with 20-50 images per defect class. Browser-based labeling and model training. From $3,000/mo per model.",specs:{type:"Data-centric AI platform",founder:"Andrew Ng",training:"20-50 images per class",labeling:"Browser-based",methodology:"Data-centric AI",deployment:"Edge + cloud",subscription_monthly:3000},score:cs({performance:82,reliability:80,ease_of_use:84,intelligence:88,value:78,ecosystem:72,safety:78,design:78}),breakdown:{performance:82,reliability:80,ease_of_use:84,intelligence:88,value:78,ecosystem:72,safety:78,design:78}},
{slug:"landing-ai-landinglens",name:"Landing AI LandingLens",mfr:"landing-ai",cat:"software",price:null,year:2024,status:"active",desc:"End-to-end visual AI tool from data labeling to edge deployment. Guided labeling workflow helps domain experts create training data without ML knowledge. Exports models to NVIDIA Jetson and industrial PCs. From $2,500/mo.",specs:{type:"End-to-end visual AI tool",workflow:"Label, train, deploy",export:"NVIDIA Jetson, industrial PC",skill_level:"Domain experts, no ML needed",labeling:"Guided consensus workflow",models:"Classification, detection, segmentation",subscription_monthly:2500},score:cs({performance:80,reliability:80,ease_of_use:86,intelligence:86,value:80,ecosystem:72,safety:78,design:78}),breakdown:{performance:80,reliability:80,ease_of_use:86,intelligence:86,value:80,ecosystem:72,safety:78,design:78}},
{slug:"landing-ai-edge-runtime",name:"Landing AI Edge Runtime",mfr:"landing-ai",cat:"software",price:null,year:2024,status:"active",desc:"Optimized inference runtime for deploying Landing AI models on edge devices. Runs on NVIDIA Jetson, Intel OpenVINO, and ARM processors. Sub-50ms inference for real-time inline inspection. From $500/mo per device.",specs:{type:"Edge inference runtime",platforms:"Jetson, OpenVINO, ARM",inference_ms:50,optimization:"Model compression + quantization",deployment:"Edge devices",updates:"OTA model updates",subscription_monthly:500},score:cs({performance:82,reliability:82,ease_of_use:78,intelligence:82,value:82,ecosystem:74,safety:78,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:78,intelligence:82,value:82,ecosystem:74,safety:78,design:74}},
{slug:"landing-ai-pcb-inspector",name:"Landing AI PCB Inspector",mfr:"landing-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Pre-trained AI model for PCB defect detection including solder bridges, missing components, and contamination. Fine-tunes to specific PCB layouts with minimal additional training. Integrates with existing AOI camera feeds. From $3,500/mo.",specs:{type:"Pre-trained PCB inspection AI",defects:"Solder bridges, missing components, contamination",pre_trained:true,fine_tuning:"Minimal per PCB layout",integration:"Existing AOI cameras",speed:"Inline at production speed",subscription_monthly:3500},score:cs({performance:82,reliability:80,ease_of_use:80,intelligence:86,value:76,ecosystem:72,safety:78,design:74}),breakdown:{performance:82,reliability:80,ease_of_use:80,intelligence:86,value:76,ecosystem:72,safety:78,design:74}},
{slug:"landing-ai-textile-check",name:"Landing AI Textile Inspector",mfr:"landing-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI inspection model for textile and fabric defect detection. Identifies holes, stains, weaving defects, and color variations on moving fabric rolls at speeds up to 2 m/s. From $2,500/mo.",specs:{type:"Textile inspection AI",defects:"Holes, stains, weaving defects, color variation",speed_m_s:2,fabric_types:"Woven, knit, nonwoven",resolution:"0.1 mm",application:"Textile mills, garment QC",subscription_monthly:2500},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:84,value:78,ecosystem:70,safety:78,design:74}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:84,value:78,ecosystem:70,safety:78,design:74}},
{slug:"landing-ai-food-inspect",name:"Landing AI Food Safety Inspector",mfr:"landing-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Visual AI for food production line inspection detecting foreign objects, contamination, and product defects. Trained on food-specific datasets for bakery, meat, produce, and packaged goods. FDA 21 CFR Part 11 compliant. From $3,000/mo.",specs:{type:"Food safety visual AI",defects:"Foreign objects, contamination, product defects",compliance:"FDA 21 CFR Part 11",food_types:"Bakery, meat, produce, packaged",speed:"200+ items/min",ai:"Food-specific deep learning",subscription_monthly:3000},score:cs({performance:82,reliability:80,ease_of_use:80,intelligence:84,value:76,ecosystem:70,safety:84,design:74}),breakdown:{performance:82,reliability:80,ease_of_use:80,intelligence:84,value:76,ecosystem:70,safety:84,design:74}},

// ═══ Neurala AI Inspection (5) ═══
{slug:"neurala-brain-builder",name:"Neurala Brain Builder",mfr:"neurala",cat:"software",price:null,year:2024,status:"active",desc:"No-code AI platform for building visual inspection models. Lifelong Learning AI (L-LLN) continuously improves models in production without retraining from scratch. Runs on CPU — no GPU required. From $2,000/mo.",specs:{type:"No-code visual AI platform",ai:"Lifelong Learning (L-LLN)",gpu_required:false,training:"No-code drag-and-drop",continuous_learning:true,deployment:"CPU-based edge",subscription_monthly:2000},score:cs({performance:78,reliability:78,ease_of_use:86,intelligence:84,value:82,ecosystem:68,safety:78,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:86,intelligence:84,value:82,ecosystem:68,safety:78,design:76}},
{slug:"neurala-viai-inspector",name:"Neurala VIA Inspector",mfr:"neurala",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Turnkey AI inspection appliance with pre-configured camera, lighting, and edge computer. Out-of-the-box defect detection deployable in under 1 hour. Targets SMEs without machine vision expertise. From $3,500/mo.",specs:{type:"Turnkey AI inspection appliance",components:"Camera, lighting, edge compute",setup_time_hr:1,target:"SMEs without vision expertise",ai:"Neurala Brain pre-configured",form_factor:"Self-contained station",subscription_monthly:3500},score:cs({performance:76,reliability:78,ease_of_use:88,intelligence:80,value:80,ecosystem:68,safety:78,design:78}),breakdown:{performance:76,reliability:78,ease_of_use:88,intelligence:80,value:80,ecosystem:68,safety:78,design:78}},
{slug:"neurala-drone-inspect",name:"Neurala Drone Inspection AI",mfr:"neurala",cat:"software",price:null,year:2024,status:"active",desc:"AI model optimized for drone-captured inspection imagery. Detects structural defects in infrastructure, solar panels, and wind turbines from aerial images. Runs on drone edge compute for real-time alerts. From $1,500/mo.",specs:{type:"Drone inspection AI",application:"Infrastructure, solar, wind turbine",deployment:"Drone edge compute",detection:"Structural defects, panel damage",processing:"Real-time on-drone",alerts:"In-flight defect alerts",subscription_monthly:1500},score:cs({performance:78,reliability:76,ease_of_use:80,intelligence:82,value:80,ecosystem:68,safety:78,design:74}),breakdown:{performance:78,reliability:76,ease_of_use:80,intelligence:82,value:80,ecosystem:68,safety:78,design:74}},
{slug:"neurala-auto-label",name:"Neurala AutoLabel",mfr:"neurala",cat:"software",price:null,year:2024,status:"active",desc:"Semi-automated labeling tool that suggests annotations as users label training images. Reduces labeling time by 70% for building custom inspection models. Integrated with Brain Builder platform. From $800/mo add-on.",specs:{type:"Semi-automated labeling tool",time_savings:"70% faster labeling",method:"AI-suggested annotations",integration:"Brain Builder platform",export:"Standard formats",addon_monthly:800},score:cs({performance:76,reliability:78,ease_of_use:84,intelligence:82,value:84,ecosystem:68,safety:78,design:76}),breakdown:{performance:76,reliability:78,ease_of_use:84,intelligence:82,value:84,ecosystem:68,safety:78,design:76}},
{slug:"neurala-edge-kit",name:"Neurala Edge Inspection Kit",mfr:"neurala",cat:"manufacturing",price:null,year:2025,status:"active",desc:"Portable edge AI inspection kit in a ruggedized case. Includes industrial camera, adjustable mount, ring light, and pre-loaded Neurala Brain. For field inspections, pop-up QC stations, and pilot programs. From $2,200/mo.",specs:{type:"Portable edge inspection kit",components:"Camera, mount, ring light, edge AI",form_factor:"Ruggedized portable case",application:"Field inspection, pilot QC",setup:"15 minutes",ai:"Pre-loaded Neurala Brain",subscription_monthly:2200},score:cs({performance:74,reliability:76,ease_of_use:86,intelligence:78,value:80,ecosystem:66,safety:78,design:76}),breakdown:{performance:74,reliability:76,ease_of_use:86,intelligence:78,value:80,ecosystem:66,safety:78,design:76}},

// ═══ Other Vision/QC Systems (5) ═══
{slug:"visio-ai-surface-scanner",name:"Visio.AI Surface Scanner",mfr:"visio-ai",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI-powered surface defect scanner for metal, plastic, and composite parts. Detects scratches, dents, and discoloration at 500+ parts per hour. Cloud-based model updates improve detection over time. From $3,000/mo.",specs:{type:"AI surface defect scanner",materials:"Metal, plastic, composite",throughput:"500+ parts/hr",defects:"Scratches, dents, discoloration",updates:"Cloud model updates",ai:"Continuously improving",subscription_monthly:3000},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:82,value:78,ecosystem:68,safety:78,design:76}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:82,value:78,ecosystem:68,safety:78,design:76}},
{slug:"fanuc-irv-robot-inspect",name:"FANUC iRVision Integrated Inspection",mfr:"fanuc",cat:"manufacturing",price:15000,year:2024,status:"active",desc:"Integrated robot vision system embedded in FANUC industrial robots. Combines 2D/3D vision with robot motion for inline part inspection during handling. Eliminates separate inspection stations by inspecting parts mid-process.",specs:{type:"Robot-integrated vision",vision:"2D + 3D embedded",integration:"FANUC robot controller native",application:"Inline inspection during handling",advantage:"Eliminates separate inspection station",processing:"On-controller real-time",addon:"For existing FANUC robots"},score:cs({performance:82,reliability:86,ease_of_use:74,intelligence:76,value:82,ecosystem:86,safety:80,design:74}),breakdown:{performance:82,reliability:86,ease_of_use:74,intelligence:76,value:82,ecosystem:86,safety:80,design:74}},
{slug:"abb-3dqi-inspection",name:"ABB 3DQI Quality Inspection",mfr:"abb-robotics",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Robot-mounted 3D scanning system for automated dimensional inspection of car bodies and large parts. ABB robot carries structured-light scanner through programmed scan paths. Measures against CAD with 0.05 mm accuracy. From $200K.",specs:{type:"Robot-mounted 3D inspection",accuracy_mm:0.05,method:"Structured light on robot",reference:"CAD comparison",application:"Car body, large part dimensional",robot:"ABB 6-axis carrier",system_price:200000},score:cs({performance:86,reliability:84,ease_of_use:72,intelligence:80,value:72,ecosystem:82,safety:80,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:72,intelligence:80,value:72,ecosystem:82,safety:80,design:76}},
{slug:"kuka-visiontec-qc",name:"KUKA VisionTec Quality Cell",mfr:"kuka",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Pre-engineered robotic quality inspection cell with KUKA robot, 3D scanner, and turntable. Scans parts from all angles for dimensional and surface quality verification. Delivers inspection reports automatically. From $180K.",specs:{type:"Pre-engineered inspection cell",components:"KUKA robot + 3D scanner + turntable",coverage:"360-degree all-angle",output:"Automated inspection reports",dimensional:"CAD comparison",surface:"Defect detection",cell_price:180000},score:cs({performance:84,reliability:84,ease_of_use:76,intelligence:78,value:74,ecosystem:80,safety:82,design:76}),breakdown:{performance:84,reliability:84,ease_of_use:76,intelligence:78,value:74,ecosystem:80,safety:82,design:76}},
{slug:"keyence-ai-explorer",name:"Keyence AI Image Analysis Explorer",mfr:"keyence",cat:"software",price:null,year:2025,status:"active",desc:"Standalone AI software for building custom inspection models from Keyence camera images. No-code interface with guided model training and one-click deployment to Keyence vision hardware. From $8K license.",specs:{type:"No-code AI model builder",workflow:"Guided train + deploy",target:"Keyence camera ecosystem",skill_level:"No ML expertise needed",deployment:"One-click to Keyence hardware",models:"Classification, detection, segmentation",license_from:8000},score:cs({performance:80,reliability:84,ease_of_use:88,intelligence:82,value:78,ecosystem:82,safety:78,design:78}),breakdown:{performance:80,reliability:84,ease_of_use:88,intelligence:82,value:78,ecosystem:82,safety:78,design:78}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 16 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 16 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
