/**
 * Robotomated — Wave 6 Robot Import: 50 Robots
 * 25 Industrial/Manufacturing + 25 Warehouse/Logistics
 *
 * Run: npx tsx scripts/import-robots-wave6.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  manufacturing: [
    "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop",
  ],
  warehouse: [
    "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop",
  ],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.manufacturing;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers for Wave 6 ──
const newMfrs = [
  { slug: "kassow-robots", name: "Kassow Robots", country: "DK", founded_year: 2014, website: "https://kassowrobots.com" },
  { slug: "neura-robotics", name: "Neura Robotics", country: "DE", founded_year: 2019, website: "https://neura-robotics.com" },
  { slug: "staubli", name: "Staubli", country: "CH", founded_year: 1892, website: "https://staubli.com" },
  { slug: "mitsubishi-electric", name: "Mitsubishi Electric", country: "JP", founded_year: 1921, website: "https://mitsubishielectric.com" },
  { slug: "nachi-fujikoshi", name: "Nachi-Fujikoshi", country: "JP", founded_year: 1928, website: "https://nachi-fujikoshi.co.jp" },
  { slug: "yamaha-robotics", name: "Yamaha Robotics", country: "JP", founded_year: 1955, website: "https://yamaha-motor.com" },
  { slug: "flexiv", name: "Flexiv", country: "CN", founded_year: 2016, website: "https://flexiv.com" },
  { slug: "realman-robotics", name: "Realman Robotics", country: "CN", founded_year: 2021, website: "https://realman-robotics.com" },
  { slug: "jaka-robotics", name: "JAKA Robotics", country: "CN", founded_year: 2014, website: "https://jakarobotics.com" },
  { slug: "aubo-robotics", name: "AUBO Robotics", country: "CN", founded_year: 2015, website: "https://aubo-robotics.com" },
  { slug: "precise-automation", name: "Precise Automation (Brooks)", country: "US", founded_year: 2004, website: "https://preciseautomation.com" },
  { slug: "berkshire-grey", name: "Berkshire Grey", country: "US", founded_year: 2013, website: "https://berkshiregrey.com" },
  { slug: "dexterity-inc", name: "Dexterity Inc", country: "US", founded_year: 2020, website: "https://dexterity.ai" },
  { slug: "righthand-robotics", name: "RightHand Robotics", country: "US", founded_year: 2014, website: "https://righthandrobotics.com" },
  { slug: "covariant", name: "Covariant", country: "US", founded_year: 2017, website: "https://covariant.ai" },
  { slug: "fizyr", name: "Fizyr", country: "NL", founded_year: 2014, website: "https://fizyr.com" },
  { slug: "opex-corp", name: "OPEX Corporation", country: "US", founded_year: 1973, website: "https://opex.com" },
  { slug: "autostore", name: "AutoStore", country: "NO", founded_year: 1996, website: "https://autostoresystem.com" },
  { slug: "ocado-technology", name: "Ocado Technology", country: "GB", founded_year: 2001, website: "https://ocadogroup.com" },
  { slug: "swisslog", name: "Swisslog (KUKA)", country: "CH", founded_year: 1900, website: "https://swisslog.com" },
  { slug: "knapp", name: "KNAPP", country: "AT", founded_year: 1952, website: "https://knapp.com" },
  { slug: "vanderlande", name: "Vanderlande", country: "NL", founded_year: 1949, website: "https://vanderlande.com" },
  { slug: "tgw-logistics", name: "TGW Logistics", country: "AT", founded_year: 1969, website: "https://tgw-group.com" },
  { slug: "honeywell-intelligrated", name: "Honeywell Intelligrated", country: "US", founded_year: 2001, website: "https://intelligrated.com" },
  { slug: "formic", name: "Formic", country: "US", founded_year: 2020, website: "https://formic.co" },
  { slug: "pkl-robot", name: "Pkl Robot Co", country: "US", founded_year: 2018, website: "https://pklrobot.com" },
  { slug: "six-river-systems", name: "6 River Systems (Shopify)", country: "US", founded_year: 2015, website: "https://6river.com" },
];

const robots: R[] = [

  // ═══ INDUSTRIAL/MANUFACTURING (25) ═══
  {slug:"kassow-kr1205",name:"Kassow KR1205",mfr:"kassow-robots",cat:"manufacturing",price:35000,year:2023,status:"active",desc:"7-axis collaborative robot with 1200mm reach and 5kg payload. The 7th axis enables human-like flexibility to reach around obstacles. Ideal for machine tending and assembly in tight spaces. Part of Bosch Rexroth ecosystem.",specs:{payload_kg:5,reach_mm:1200,dof:7,repeatability_mm:0.05,weight_kg:25,max_speed_ms:2.1,ip_rating:"IP54"},score:cs({performance:80,reliability:80,ease_of_use:82,intelligence:78,value:80,ecosystem:72,safety:84,design:78}),breakdown:{performance:80,reliability:80,ease_of_use:82,intelligence:78,value:80,ecosystem:72,safety:84,design:78}},
  {slug:"doosan-h2515",name:"Doosan H2515",mfr:"doosan-robotics",cat:"manufacturing",price:42000,year:2023,status:"active",desc:"Heavy-payload collaborative robot with 25kg capacity and 1500mm reach. 6 torque sensors for precise force control. SafeMove 2.0 certified safety. Direct teaching by hand guidance.",specs:{payload_kg:25,reach_mm:1500,dof:6,repeatability_mm:0.05,weight_kg:72,torque_sensors:6,safety:"SafeMove 2.0"},score:cs({performance:84,reliability:82,ease_of_use:82,intelligence:78,value:78,ecosystem:72,safety:86,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:82,intelligence:78,value:78,ecosystem:72,safety:86,design:76}},
  {slug:"neura-maira",name:"Neura MAiRA",mfr:"neura-robotics",cat:"manufacturing",price:null,year:2024,status:"active",desc:"World's first cognitive robot with integrated AI perception. Built-in 3D vision, voice control, and person detection. No external sensors needed. Self-learning capabilities through demonstration. German engineering with cognitive AI stack.",specs:{payload_kg:20,reach_mm:1800,dof:6,repeatability_mm:0.05,vision:"Built-in 3D + RGB",voice_control:true,person_detection:true,ai:"Cognitive self-learning"},score:cs({performance:84,reliability:78,ease_of_use:88,intelligence:90,value:78,ecosystem:68,safety:86,design:82}),breakdown:{performance:84,reliability:78,ease_of_use:88,intelligence:90,value:78,ecosystem:68,safety:86,design:82}},
  {slug:"omron-tm14",name:"Omron TM14",mfr:"omron",cat:"manufacturing",price:38000,year:2023,status:"active",desc:"Collaborative robot with built-in vision and 14kg payload. Landmark-based vision system for flexible positioning. TMflow visual programming environment. Integrates with Omron mobile robots for mobile manipulation.",specs:{payload_kg:14,reach_mm:1100,dof:6,repeatability_mm:0.05,vision:"Built-in 5MP smart camera",programming:"TMflow visual",mobile_integration:"Omron AMR compatible"},score:cs({performance:82,reliability:82,ease_of_use:86,intelligence:82,value:80,ecosystem:78,safety:84,design:76}),breakdown:{performance:82,reliability:82,ease_of_use:86,intelligence:82,value:80,ecosystem:78,safety:84,design:76}},
  {slug:"epson-vt6",name:"Epson VT6",mfr:"epson-robots",cat:"manufacturing",price:18000,year:2023,status:"active",desc:"Compact 6-axis robot optimized for small parts assembly and dispensing. Built-in force sensing for delicate operations. QMEMS sensor technology for vibration control. Cleanroom compatible.",specs:{payload_kg:6,reach_mm:920,dof:6,repeatability_mm:0.02,weight_kg:29,force_sensing:true,cleanroom:"ISO Class 5 compatible"},score:cs({performance:80,reliability:84,ease_of_use:78,intelligence:72,value:86,ecosystem:72,safety:82,design:74}),breakdown:{performance:80,reliability:84,ease_of_use:78,intelligence:72,value:86,ecosystem:72,safety:82,design:74}},
  {slug:"staubli-tx2-90",name:"Staubli TX2-90",mfr:"staubli",cat:"manufacturing",price:55000,year:2022,status:"active",desc:"High-performance 6-axis robot for demanding industrial applications. Exceptional path accuracy and speed. JCS safety controller for human-robot collaboration. IP65/67 protection for harsh environments.",specs:{payload_kg:20,reach_mm:1000,dof:6,repeatability_mm:0.03,speed_ms:8.7,ip_rating:"IP65/67",safety:"JCS safe controller"},score:cs({performance:88,reliability:88,ease_of_use:72,intelligence:74,value:74,ecosystem:78,safety:86,design:78}),breakdown:{performance:88,reliability:88,ease_of_use:72,intelligence:74,value:74,ecosystem:78,safety:86,design:78}},
  {slug:"mitsubishi-melfa-rv-fr",name:"Mitsubishi MELFA RV-FR",mfr:"mitsubishi-electric",cat:"manufacturing",price:32000,year:2023,status:"active",desc:"Next-gen industrial robot with AI-assisted servo tuning. 7kg payload, enhanced vibration suppression. MELFA Smart Plus predictive maintenance. RT VisualBox for easy vision setup.",specs:{payload_kg:7,reach_mm:911,dof:6,repeatability_mm:0.02,ai:"AI servo tuning",predictive_maintenance:"MELFA Smart Plus",vision:"RT VisualBox"},score:cs({performance:84,reliability:86,ease_of_use:78,intelligence:78,value:80,ecosystem:80,safety:84,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:78,intelligence:78,value:80,ecosystem:80,safety:84,design:76}},
  {slug:"nachi-mz07",name:"Nachi MZ07",mfr:"nachi-fujikoshi",cat:"manufacturing",price:25000,year:2022,status:"active",desc:"Ultra-compact high-speed robot with 7kg payload. Slim arm design fits in tight spaces. 0.37s cycle time. Built-in air and signal lines through the arm. Ideal for high-density production cells.",specs:{payload_kg:7,reach_mm:723,dof:6,repeatability_mm:0.02,cycle_time_s:0.37,weight_kg:28,internal_routing:true},score:cs({performance:84,reliability:84,ease_of_use:74,intelligence:72,value:84,ecosystem:70,safety:82,design:74}),breakdown:{performance:84,reliability:84,ease_of_use:74,intelligence:72,value:84,ecosystem:70,safety:82,design:74}},
  {slug:"yamaha-yk-xg",name:"Yamaha YK-XG",mfr:"yamaha-robotics",cat:"manufacturing",price:15000,year:2023,status:"active",desc:"High-speed SCARA robot for pick-and-place and assembly. 0.29s cycle time. RCX340 controller supports up to 4 robots simultaneously. Vision-guided picking with iVY2+ system.",specs:{payload_kg:4,reach_mm:500,dof:4,repeatability_mm:0.01,cycle_time_s:0.29,type:"SCARA",controller:"RCX340 (4 robots)"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:72,value:88,ecosystem:72,safety:82,design:72}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:72,value:88,ecosystem:72,safety:82,design:72}},
  {slug:"comau-nj4",name:"Comau NJ4",mfr:"comau",cat:"manufacturing",price:65000,year:2022,status:"active",desc:"Heavy-duty industrial robot designed for automotive welding and material handling. 170kg payload. Hollow wrist for cable routing. TP5 teaching pendant with graphical programming.",specs:{payload_kg:170,reach_mm:2700,dof:6,repeatability_mm:0.05,weight_kg:1100,wrist:"Hollow for cable routing",ip_rating:"IP65"},score:cs({performance:88,reliability:86,ease_of_use:72,intelligence:72,value:76,ecosystem:72,safety:84,design:72}),breakdown:{performance:88,reliability:86,ease_of_use:72,intelligence:72,value:76,ecosystem:72,safety:84,design:72}},
  {slug:"kuka-lbr-iisy",name:"KUKA LBR iisy",mfr:"kuka",cat:"manufacturing",price:30000,year:2023,status:"active",desc:"KUKA's most user-friendly cobot. 3-15kg payload range. iiQKA.OS operating system with app-based programming. Hand-guided teach mode. Designed for small and medium enterprises new to robotics.",specs:{payload_kg:15,reach_mm:930,dof:6,repeatability_mm:0.05,os:"iiQKA.OS",programming:"App-based + hand-guided",weight_kg:28},score:cs({performance:80,reliability:84,ease_of_use:90,intelligence:78,value:82,ecosystem:85,safety:86,design:82}),breakdown:{performance:80,reliability:84,ease_of_use:90,intelligence:78,value:82,ecosystem:85,safety:86,design:82}},
  {slug:"franka-production-3",name:"Franka Production 3",mfr:"han-robot",cat:"manufacturing",price:25000,year:2024,status:"active",desc:"Third-generation Franka Emika platform (now under Han's Robot). Torque sensors in all 7 joints for sensitive manipulation. Franka World app ecosystem. Research and production variants available.",specs:{payload_kg:3,reach_mm:855,dof:7,repeatability_mm:0.1,torque_sensors:7,programming:"Franka World apps",sensitivity:"Sub-Newton force control"},score:cs({performance:78,reliability:78,ease_of_use:86,intelligence:82,value:80,ecosystem:78,safety:88,design:82}),breakdown:{performance:78,reliability:78,ease_of_use:86,intelligence:82,value:80,ecosystem:78,safety:88,design:82}},
  {slug:"abb-yumi-irb14050",name:"ABB YuMi IRB 14050",mfr:"abb-robotics",cat:"manufacturing",price:40000,year:2023,status:"active",desc:"Single-arm collaborative robot derived from the iconic dual-arm YuMi. 0.5kg payload for small parts assembly. Inherently safe padded design. Lead-through programming. Electronics assembly specialist.",specs:{payload_kg:0.5,reach_mm:559,dof:7,repeatability_mm:0.02,weight_kg:9.5,programming:"Lead-through + Wizard Easy",safety:"Inherently safe padded arm"},score:cs({performance:74,reliability:82,ease_of_use:88,intelligence:76,value:72,ecosystem:85,safety:92,design:84}),breakdown:{performance:74,reliability:82,ease_of_use:88,intelligence:76,value:72,ecosystem:85,safety:92,design:84}},
  {slug:"fanuc-crx-25ia",name:"Fanuc CRX-25iA",mfr:"fanuc",cat:"manufacturing",price:50000,year:2023,status:"active",desc:"Largest Fanuc collaborative robot with 25kg payload and 1889mm reach. Tablet-based drag-and-drop programming. Contact-stop safety with no pinch points. IP67 protection. Backed by Fanuc's global service network.",specs:{payload_kg:25,reach_mm:1889,dof:6,repeatability_mm:0.04,ip_rating:"IP67",programming:"Tablet drag-and-drop",safety:"Contact-stop, no pinch points"},score:cs({performance:86,reliability:88,ease_of_use:86,intelligence:78,value:78,ecosystem:90,safety:88,design:78}),breakdown:{performance:86,reliability:88,ease_of_use:86,intelligence:78,value:78,ecosystem:90,safety:88,design:78}},
  {slug:"ur30",name:"Universal Robots UR30",mfr:"universal-robots",cat:"manufacturing",price:55000,year:2023,status:"active",desc:"Heavy-payload cobot with 30kg capacity in a compact footprint. Same base diameter as UR10e. Ideal for machine tending, palletizing, and heavy assembly. UR+ ecosystem with 400+ certified peripherals.",specs:{payload_kg:30,reach_mm:1300,dof:6,repeatability_mm:0.05,weight_kg:63.5,ecosystem:"UR+ 400+ peripherals",programming:"PolyScope + URScript"},score:cs({performance:86,reliability:86,ease_of_use:88,intelligence:78,value:80,ecosystem:92,safety:86,design:78}),breakdown:{performance:86,reliability:86,ease_of_use:88,intelligence:78,value:80,ecosystem:92,safety:86,design:78}},
  {slug:"ur20",name:"Universal Robots UR20",mfr:"universal-robots",cat:"manufacturing",price:52000,year:2023,status:"active",desc:"Long-reach cobot with 1750mm reach and 20kg payload. New joint design provides 65% faster cycle times. Revolutionized palletizing with cobots. Over 75,000 UR cobots deployed globally.",specs:{payload_kg:20,reach_mm:1750,dof:6,repeatability_mm:0.05,weight_kg:64,cycle_improvement:"65% faster",global_fleet:"75,000+ UR cobots"},score:cs({performance:86,reliability:86,ease_of_use:88,intelligence:78,value:82,ecosystem:92,safety:86,design:78}),breakdown:{performance:86,reliability:86,ease_of_use:88,intelligence:78,value:82,ecosystem:92,safety:86,design:78}},
  {slug:"ur7e",name:"Universal Robots UR7e",mfr:"universal-robots",cat:"manufacturing",price:28000,year:2025,status:"active",desc:"New-generation compact cobot replacing UR5e. 7kg payload with faster speeds and improved repeatability. New PolyScope X software platform. AI-ready compute module. Most affordable UR to date.",specs:{payload_kg:7,reach_mm:850,dof:6,repeatability_mm:0.03,weight_kg:22,software:"PolyScope X",ai_ready:true},score:cs({performance:82,reliability:84,ease_of_use:90,intelligence:82,value:88,ecosystem:92,safety:86,design:80}),breakdown:{performance:82,reliability:84,ease_of_use:90,intelligence:82,value:88,ecosystem:92,safety:86,design:80}},
  {slug:"techman-tm25s",name:"Techman TM25S",mfr:"techman-robot",cat:"manufacturing",price:48000,year:2024,status:"active",desc:"Heavy-payload cobot with 25kg capacity and built-in smart vision. TMvision AI-powered defect detection. 1900mm reach for palletizing applications. Omron partnership for mobile manipulation.",specs:{payload_kg:25,reach_mm:1900,dof:6,repeatability_mm:0.05,vision:"TMvision AI defect detection",programming:"TMflow visual",partner:"Omron mobile robots"},score:cs({performance:84,reliability:82,ease_of_use:86,intelligence:84,value:78,ecosystem:78,safety:84,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:86,intelligence:84,value:78,ecosystem:78,safety:84,design:76}},
  {slug:"dobot-cr10",name:"Dobot CR10",mfr:"dobot",cat:"manufacturing",price:22000,year:2023,status:"active",desc:"Affordable 10kg payload cobot from Dobot. SafeSkin collision detection system. Hand-guided teaching and graphical programming. Popular in education and small manufacturing. 1300mm reach.",specs:{payload_kg:10,reach_mm:1300,dof:6,repeatability_mm:0.05,weight_kg:33,safety:"SafeSkin collision detection",programming:"Graphical + hand-guided"},score:cs({performance:78,reliability:78,ease_of_use:84,intelligence:74,value:88,ecosystem:68,safety:82,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:84,intelligence:74,value:88,ecosystem:68,safety:82,design:76}},
  {slug:"flexiv-rizon-4s",name:"Flexiv Rizon 4s",mfr:"flexiv",cat:"manufacturing",price:35000,year:2024,status:"active",desc:"Adaptive robot with force control resolution under 0.1N. Handles contact-rich tasks like polishing, insertion, and assembly with human-level dexterity. AI-powered Flexiv Elements software for complex task programming.",specs:{payload_kg:4,reach_mm:700,dof:7,repeatability_mm:0.05,force_resolution_n:0.1,ai:"Flexiv Elements",adaptive_force:true},score:cs({performance:84,reliability:80,ease_of_use:82,intelligence:86,value:78,ecosystem:65,safety:86,design:80}),breakdown:{performance:84,reliability:80,ease_of_use:82,intelligence:86,value:78,ecosystem:65,safety:86,design:80}},
  {slug:"realman-rm75",name:"Realman RM-75",mfr:"realman-robotics",cat:"manufacturing",price:8000,year:2024,status:"active",desc:"Ultra-lightweight 7-DOF cobot at disruptive price point. Only 7.2kg arm weight. Harmonic drive joints with torque sensors. Designed for mobile manipulation and research. Rapidly growing in Chinese market.",specs:{payload_kg:5,reach_mm:750,dof:7,repeatability_mm:0.05,weight_kg:7.2,torque_sensors:7,price_class:"Ultra-affordable"},score:cs({performance:74,reliability:72,ease_of_use:80,intelligence:74,value:96,ecosystem:55,safety:80,design:76}),breakdown:{performance:74,reliability:72,ease_of_use:80,intelligence:74,value:96,ecosystem:55,safety:80,design:76}},
  {slug:"jaka-zu-12",name:"JAKA Zu 12",mfr:"jaka-robotics",cat:"manufacturing",price:20000,year:2023,status:"active",desc:"12kg payload cobot with wireless programming via tablet. No teach pendant required. All-in-one joint design. IP68 dustproof and waterproof. Strong value proposition for SME manufacturing.",specs:{payload_kg:12,reach_mm:1327,dof:6,repeatability_mm:0.03,ip_rating:"IP68",programming:"Wireless tablet",weight_kg:35},score:cs({performance:80,reliability:80,ease_of_use:86,intelligence:76,value:88,ecosystem:62,safety:84,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:86,intelligence:76,value:88,ecosystem:62,safety:84,design:76}},
  {slug:"elite-robots-ec66",name:"Elite Robots EC66",mfr:"elite-robots",cat:"manufacturing",price:18000,year:2023,status:"active",desc:"6kg payload cobot with built-in force/torque sensor. Elite Studio graphical programming. Growing global presence with 10,000+ units deployed. Competitive alternative to UR cobots at lower price point.",specs:{payload_kg:6,reach_mm:914,dof:6,repeatability_mm:0.03,force_torque:true,programming:"Elite Studio graphical",deployments:"10,000+"},score:cs({performance:78,reliability:78,ease_of_use:84,intelligence:76,value:90,ecosystem:62,safety:84,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:84,intelligence:76,value:90,ecosystem:62,safety:84,design:76}},
  {slug:"aubo-i10",name:"AUBO i10",mfr:"aubo-robotics",cat:"manufacturing",price:22000,year:2023,status:"active",desc:"10kg payload collaborative robot with modular joint design. Each joint can be replaced in 15 minutes. ROS2 native support for research applications. Growing international presence from Chinese manufacturer.",specs:{payload_kg:10,reach_mm:1350,dof:6,repeatability_mm:0.05,modular_joints:true,joint_swap_min:15,ros2:true},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:76,value:86,ecosystem:64,safety:82,design:74}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:76,value:86,ecosystem:64,safety:82,design:74}},
  {slug:"precise-automation-pf3400",name:"Precise Automation PF3400",mfr:"precise-automation",cat:"manufacturing",price:35000,year:2022,status:"active",desc:"Collaborative SCARA robot for high-speed precision assembly. 3kg payload. Direct-drive motors for zero-backlash positioning. Cleanroom compatible for semiconductor and medical device manufacturing.",specs:{payload_kg:3,reach_mm:400,dof:4,repeatability_mm:0.005,type:"SCARA collaborative",drive:"Direct-drive zero-backlash",cleanroom:"ISO Class 4"},score:cs({performance:84,reliability:86,ease_of_use:78,intelligence:72,value:76,ecosystem:68,safety:86,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:78,intelligence:72,value:76,ecosystem:68,safety:86,design:74}},

  // ═══ WAREHOUSE/LOGISTICS (25) ═══
  {slug:"berkshire-grey-rpp",name:"Berkshire Grey RPP",mfr:"berkshire-grey",cat:"warehouse",price:null,year:2024,status:"active",desc:"Robotic Pick & Pack system using AI-powered vision and grasping. Handles mixed SKU picking at 300+ picks/hour. Deployed in major retail fulfillment centers. Reduces labor costs by 50%+ in pick operations.",specs:{picks_per_hour:300,sku_types:"Mixed SKU",vision:"AI 3D vision",grasping:"Multi-modal gripper",labor_reduction:"50%+"},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:86,value:76,ecosystem:72,safety:82,design:74}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:86,value:76,ecosystem:72,safety:82,design:74}},
  {slug:"dexterity-dexd",name:"Dexterity DexD",mfr:"dexterity-inc",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered depalletizing robot using large language models for task understanding. Full-layer depalletizing at 1000+ cases/hour. Handles 10,000+ SKUs without pre-programming. Sim-to-real AI training pipeline.",specs:{cases_per_hour:1000,skus:"10,000+ without programming",ai:"LLM + sim-to-real",type:"Depalletizing",vision:"3D perception"},score:cs({performance:86,reliability:78,ease_of_use:82,intelligence:90,value:76,ecosystem:68,safety:82,design:76}),breakdown:{performance:86,reliability:78,ease_of_use:82,intelligence:90,value:76,ecosystem:68,safety:82,design:76}},
  {slug:"righthand-rightpick-3",name:"RightHand RightPick 3",mfr:"righthand-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Piece-picking robot with intelligent suction gripper for e-commerce fulfillment. Handles 99.5% of items in a typical warehouse. RightPick AI learns from every pick across fleet. Cloud-connected intelligence.",specs:{pick_success:"99.5%",picks_per_hour:600,gripper:"Intelligent suction",ai:"Fleet-learning cloud AI",items:"Most e-commerce SKUs"},score:cs({performance:84,reliability:82,ease_of_use:80,intelligence:88,value:78,ecosystem:72,safety:82,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:80,intelligence:88,value:78,ecosystem:72,safety:82,design:76}},
  {slug:"covariant-brain",name:"Covariant Brain",mfr:"covariant",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI platform for warehouse robot manipulation. Foundation model trained on millions of real-world grasps. Enables any robot arm to handle virtually any object. Powers picking, packing, and sorting across major 3PLs.",specs:{type:"AI manipulation platform",training:"Millions of real grasps",compatibility:"Any robot arm",applications:"Pick, pack, sort, induct",partners:"ABB, KNAPP"},score:cs({performance:86,reliability:80,ease_of_use:78,intelligence:94,value:74,ecosystem:75,safety:82,design:72}),breakdown:{performance:86,reliability:80,ease_of_use:78,intelligence:94,value:74,ecosystem:75,safety:82,design:72}},
  {slug:"mujin-truckbot",name:"Mujin TruckBot",mfr:"mujin",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous truck unloading robot using real-time motion planning. No teach programming needed. MujinController computes collision-free paths in real-time. Handles mixed-case palletizing and depalletizing.",specs:{type:"Truck unloading",cases_per_hour:800,ai:"Real-time motion planning",controller:"MujinController",programming:"Zero-teach"},score:cs({performance:86,reliability:80,ease_of_use:84,intelligence:88,value:74,ecosystem:70,safety:84,design:74}),breakdown:{performance:86,reliability:80,ease_of_use:84,intelligence:88,value:74,ecosystem:70,safety:84,design:74}},
  {slug:"fizyr-vision",name:"Fizyr Vision System",mfr:"fizyr",cat:"warehouse",price:null,year:2024,status:"active",desc:"Deep learning vision system for logistics picking and depalletizing. Identifies and segments objects in cluttered bins and pallets. Hardware-agnostic, works with any robot arm. Over 99% detection rate on unknown objects.",specs:{type:"AI vision system",detection_rate:"99%+",compatibility:"Any robot arm",objects:"Unknown object detection",applications:"Bin picking, depalletizing"},score:cs({performance:82,reliability:80,ease_of_use:80,intelligence:90,value:78,ecosystem:72,safety:80,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:80,intelligence:90,value:78,ecosystem:72,safety:80,design:72}},
  {slug:"greyorange-ranger-gtp",name:"GreyOrange Ranger GTP",mfr:"greyorange",cat:"warehouse",price:null,year:2024,status:"active",desc:"Goods-to-person autonomous mobile robot with AI-powered orchestration. GreyOrange Fulfillment OS dynamically prioritizes orders. 600kg payload capacity. Used by IKEA, H&M, and major 3PLs globally.",specs:{payload_kg:600,speed_ms:2.0,battery_hrs:8,nav:"LiDAR + camera fusion",software:"GreyOrange Fulfillment OS",clients:"IKEA, H&M, 3PLs"},score:cs({performance:82,reliability:82,ease_of_use:80,intelligence:84,value:76,ecosystem:78,safety:82,design:76}),breakdown:{performance:82,reliability:82,ease_of_use:80,intelligence:84,value:76,ecosystem:78,safety:82,design:76}},
  {slug:"6river-chuck-2",name:"6 River Chuck 2.0",mfr:"six-river-systems",cat:"warehouse",price:null,year:2024,status:"active",desc:"Collaborative mobile robot for warehouse picking. Guides workers through optimal pick paths, increasing productivity 2-3x. Shopify-owned. Used by XPO, DHL, and Lockheed Martin. Easy deployment in 2-4 weeks.",specs:{type:"Collaborative mobile robot",productivity:"2-3x improvement",deployment_weeks:"2-4",battery_hrs:10,nav:"LiDAR SLAM",clients:"XPO, DHL, Lockheed Martin"},score:cs({performance:80,reliability:82,ease_of_use:88,intelligence:80,value:80,ecosystem:76,safety:84,design:76}),breakdown:{performance:80,reliability:82,ease_of_use:88,intelligence:80,value:80,ecosystem:76,safety:84,design:76}},
  {slug:"fetch-freight-150",name:"Fetch Freight 150",mfr:"fetch-robotics",cat:"warehouse",price:null,year:2023,status:"active",desc:"Heavy-payload autonomous mobile robot for warehouse material transport. 150kg payload. Zebra FetchCore cloud management. Fleet coordination across large warehouses. On-demand transport between zones.",specs:{payload_kg:150,speed_ms:2.0,battery_hrs:9,nav:"LiDAR SLAM",software:"Zebra FetchCore cloud",fleet:"Multi-robot coordination"},score:cs({performance:80,reliability:82,ease_of_use:80,intelligence:78,value:76,ecosystem:76,safety:84,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:80,intelligence:78,value:76,ecosystem:76,safety:84,design:72}},
  {slug:"locus-origin-2-warehouse",name:"Locus Robotics Origin 2.0",mfr:"locus-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Next-gen collaborative warehouse AMR. 3 billion+ units picked across the fleet. Enhanced multi-bot coordination through LocusHub AI. Used by DHL, GEODIS, and Boots.",specs:{payload_kg:36,battery_hrs:12,fleet_picks:"3B+ lifetime",nav:"LiDAR SLAM + camera",software:"LocusHub AI",clients:"DHL, GEODIS, Boots"},score:cs({performance:84,reliability:84,ease_of_use:86,intelligence:84,value:80,ecosystem:82,safety:84,design:78}),breakdown:{performance:84,reliability:84,ease_of_use:86,intelligence:84,value:80,ecosystem:82,safety:84,design:78}},
  {slug:"symbotic-bot",name:"Symbotic Bot",mfr:"symbotic",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered autonomous warehouse robot operating in dense storage cube systems. Partner of Walmart and Albertsons for distribution center automation. Bots navigate 3D grid structure to store and retrieve cases.",specs:{type:"Cube storage bot",nav:"3D grid navigation",ai:"SymBot AI",clients:"Walmart, Albertsons, C&S",speed_ms:5.0,automation:"End-to-end DC"},score:cs({performance:88,reliability:82,ease_of_use:76,intelligence:86,value:74,ecosystem:72,safety:84,design:76}),breakdown:{performance:88,reliability:82,ease_of_use:76,intelligence:86,value:74,ecosystem:72,safety:84,design:76}},
  {slug:"geek-plus-p800",name:"Geek+ P800",mfr:"geek-plus",cat:"warehouse",price:null,year:2024,status:"active",desc:"Heavy-payload goods-to-person robot lifting shelving units up to 1000kg. Deployed in 30+ countries with 30,000+ robots shipped. AI-optimized slotting and picking paths. Largest AMR fleet in Asia.",specs:{payload_kg:1000,speed_ms:2.0,battery_hrs:8,fleet:"30,000+ shipped",nav:"QR code + LiDAR",countries:"30+"},score:cs({performance:84,reliability:82,ease_of_use:78,intelligence:82,value:82,ecosystem:78,safety:82,design:74}),breakdown:{performance:84,reliability:82,ease_of_use:78,intelligence:82,value:82,ecosystem:78,safety:82,design:74}},
  {slug:"hai-robotics-a42t",name:"HAI Robotics A42T",mfr:"hai-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous Case-handling Robot with telescoping mast reaching up to 10m high racking. Retrieves individual tote bins without moving entire shelves. Deployed in 1000+ warehouses globally.",specs:{max_height_m:10,payload_kg:50,speed_ms:1.5,mast:"Telescoping",deployments:"1000+ warehouses",countries:"30+"},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:75,safety:82,design:74}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:75,safety:82,design:74}},
  {slug:"quicktron-m100c",name:"Quicktron M100C",mfr:"quicktron",cat:"warehouse",price:null,year:2024,status:"active",desc:"Compact sorting robot operating on elevated grid tracks. Sorts parcels at 2000+ per hour in dense configurations. Alibaba-backed. Powers Cainiao smart logistics globally.",specs:{sorts_per_hour:2000,payload_kg:8,type:"Grid sorting robot",backer:"Alibaba",speed_ms:2.5,clients:"Cainiao global"},score:cs({performance:82,reliability:80,ease_of_use:78,intelligence:78,value:82,ecosystem:72,safety:80,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:78,intelligence:78,value:82,ecosystem:72,safety:80,design:72}},
  {slug:"opex-sure-sort-2",name:"OPEX Sure Sort 2",mfr:"opex-corp",cat:"warehouse",price:null,year:2024,status:"active",desc:"Automated item sortation system using vision AI for e-commerce returns and fulfillment. Identifies items by shape, barcode, or image recognition. 2400+ sorts/hour. Handles returns processing without pre-scanning.",specs:{sorts_per_hour:2400,vision:"AI item recognition",applications:"Returns, fulfillment, sortation",items:"Mixed SKU without pre-scan",footprint:"Compact modular"},score:cs({performance:82,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:68,safety:82,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:68,safety:82,design:74}},
  {slug:"exotec-skypod",name:"Exotec Skypod",mfr:"exotec",cat:"warehouse",price:null,year:2024,status:"active",desc:"Goods-to-person robot that climbs vertical racking up to 12m. Combines horizontal travel with vertical climbing. Used by Uniqlo, Decathlon, and Carrefour. 5x storage density vs traditional systems.",specs:{max_height_m:12,payload_kg:30,speed_ms:4.0,climbing:true,storage_density:"5x traditional",clients:"Uniqlo, Decathlon, Carrefour"},score:cs({performance:88,reliability:82,ease_of_use:78,intelligence:82,value:76,ecosystem:72,safety:84,design:82}),breakdown:{performance:88,reliability:82,ease_of_use:78,intelligence:82,value:76,ecosystem:72,safety:84,design:82}},
  {slug:"autostore-r5-plus",name:"AutoStore R5+",mfr:"autostore",cat:"warehouse",price:null,year:2024,status:"active",desc:"Grid-based storage and retrieval robot operating on top of a cubic bin grid. 1100+ installations worldwide. Robots traverse an aluminum grid to retrieve bins from below. 4x storage density.",specs:{type:"Cube storage robot",bins_per_hour:25,grid:"Aluminum top-grid",installations:"1100+",storage_density:"4x traditional",bin_depth:"Up to 24 deep"},score:cs({performance:82,reliability:88,ease_of_use:80,intelligence:76,value:78,ecosystem:80,safety:86,design:74}),breakdown:{performance:82,reliability:88,ease_of_use:80,intelligence:76,value:78,ecosystem:80,safety:86,design:74}},
  {slug:"ocado-600-series",name:"Ocado 600 Series Bot",mfr:"ocado-technology",cat:"warehouse",price:null,year:2024,status:"active",desc:"Next-gen grocery fulfillment bot 40% lighter than predecessor. Operates on Ocado Smart Platform grid. 3500+ bots per facility process 220,000 orders/week. Licensed to Kroger, Sobeys, and Casino.",specs:{type:"Grid grocery bot",weight_reduction:"40% lighter",orders_per_week:220000,bots_per_facility:3500,clients:"Kroger, Sobeys, Casino"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:78,safety:84,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:78,safety:84,design:76}},
  {slug:"swisslog-automover",name:"Swisslog AutoMover",mfr:"swisslog",cat:"warehouse",price:null,year:2023,status:"active",desc:"Autonomous intelligent vehicle for pallet transport in warehouses and manufacturing. 1000kg payload. Natural feature navigation without infrastructure. Integrates with Swisslog SynQ warehouse management system.",specs:{payload_kg:1000,type:"Autonomous pallet transport",nav:"Natural feature navigation",software:"SynQ WMS integration",speed_ms:1.5},score:cs({performance:80,reliability:84,ease_of_use:78,intelligence:78,value:76,ecosystem:78,safety:84,design:72}),breakdown:{performance:80,reliability:84,ease_of_use:78,intelligence:78,value:76,ecosystem:78,safety:84,design:72}},
  {slug:"knapp-open-shuttle",name:"KNAPP Open Shuttle",mfr:"knapp",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous mobile robot for flexible goods transport in warehouses. Fleet intelligence with swarm coordination. Carries bins, cartons, and trays. Integrates with KNAPP shuttle systems for hybrid automation.",specs:{payload_kg:50,speed_ms:2.0,nav:"LiDAR SLAM",fleet:"Swarm coordination",integration:"KNAPP shuttle systems",battery_hrs:8},score:cs({performance:80,reliability:82,ease_of_use:78,intelligence:80,value:76,ecosystem:78,safety:84,design:74}),breakdown:{performance:80,reliability:82,ease_of_use:78,intelligence:80,value:76,ecosystem:78,safety:84,design:74}},
  {slug:"vanderlande-fleet",name:"Vanderlande FLEET",mfr:"vanderlande",cat:"warehouse",price:null,year:2024,status:"active",desc:"Fleet of autonomous mobile robots for airport baggage handling and warehouse logistics. Modular system scales from 10 to 1000+ bots. Each bot carries individual items along dynamic routes.",specs:{type:"AMR fleet system",scale:"10 to 1000+ bots",applications:"Airport baggage, warehouse",payload_kg:35,speed_ms:2.5,routing:"Dynamic path planning"},score:cs({performance:82,reliability:84,ease_of_use:78,intelligence:82,value:74,ecosystem:76,safety:84,design:76}),breakdown:{performance:82,reliability:84,ease_of_use:78,intelligence:82,value:74,ecosystem:76,safety:84,design:76}},
  {slug:"tgw-rovolution",name:"TGW Rovolution",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Shuttle-based goods-to-person system with autonomous mobile robots. Combines shuttle storage with AMR delivery to workstations. FlashPick and OmniPick modules for multi-channel fulfillment.",specs:{type:"Shuttle + AMR hybrid",modules:"FlashPick, OmniPick",fulfillment:"Multi-channel",speed_ms:4.0,throughput:"10,000+ picks/hour"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:82,value:74,ecosystem:76,safety:84,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:82,value:74,ecosystem:76,safety:84,design:76}},
  {slug:"honeywell-intelligrated-asrs",name:"Honeywell Intelligrated ASRS",mfr:"honeywell-intelligrated",cat:"warehouse",price:null,year:2024,status:"active",desc:"Automated storage and retrieval system with robotic shuttles. High-density storage for pallets, cases, and mini-loads. Momentum warehouse execution system for orchestration. Deployed in distribution centers worldwide.",specs:{type:"ASRS with shuttles",storage:"Pallet, case, mini-load",software:"Momentum WES",density:"High-density automated",applications:"Distribution centers"},score:cs({performance:84,reliability:86,ease_of_use:74,intelligence:78,value:74,ecosystem:78,safety:86,design:72}),breakdown:{performance:84,reliability:86,ease_of_use:74,intelligence:78,value:74,ecosystem:78,safety:86,design:72}},
  {slug:"formic-cobot-palletizer",name:"Formic Cobot Palletizer",mfr:"formic",cat:"warehouse",price:null,year:2024,status:"active",desc:"Robots-as-a-service palletizing solution with no upfront cost. Customers pay per pallet handled. Cobot-based system handles mixed SKU palletizing. Lowers entry barrier for small/mid manufacturers.",specs:{type:"Cobot palletizer RaaS",pricing:"Per-pallet, no upfront",cases_per_hour:600,skus:"Mixed SKU",model:"Robots-as-a-Service"},score:cs({performance:78,reliability:78,ease_of_use:86,intelligence:76,value:88,ecosystem:65,safety:84,design:72}),breakdown:{performance:78,reliability:78,ease_of_use:86,intelligence:76,value:88,ecosystem:65,safety:84,design:72}},
  {slug:"pkl-unload-bot",name:"Pkl Robot Unload Bot",mfr:"pkl-robot",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered truck unloading robot that handles the hardest warehouse job. Unloads floor-loaded trailers at 500+ cases/hour. Computer vision identifies and picks boxes of varying sizes. Deployed at major retailers.",specs:{type:"Truck unloading",cases_per_hour:500,vision:"AI box identification",boxes:"Variable size floor-loaded",applications:"Retail distribution centers"},score:cs({performance:82,reliability:76,ease_of_use:80,intelligence:84,value:78,ecosystem:62,safety:82,design:72}),breakdown:{performance:82,reliability:76,ease_of_use:80,intelligence:84,value:78,ecosystem:62,safety:82,design:72}},
];

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 6 Import: 50 New Robots");
  console.log("  25 Manufacturing + 25 Warehouse/Logistics");
  console.log("═══════════════════════════════════════════════════\n");

  const { data: cats } = await sb.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`Categories: ${catMap.size}\n`);

  const { data: existingMfrs } = await sb.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await sb.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await sb.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await sb.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await sb.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"=".repeat(50)}`);
  console.log(`Wave 6 Import Summary`);
  console.log(`${"=".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"=".repeat(50)}`);
}

main().catch(console.error);
