/**
 * Robotomated — Wave 7 Robot Import: 50 Robots
 * 20 Medical/Surgical + 20 Agricultural + 10 Construction
 *
 * Run: npx tsx scripts/import-robots-wave7.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  medical: [
    "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop",
  ],
  agricultural: [
    "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=400&fit=crop",
  ],
  construction: [
    "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop",
  ],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.medical;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

const newMfrs = [
  // Medical
  { slug: "medtronic", name: "Medtronic", country: "IE", founded_year: 1949, website: "https://medtronic.com" },
  { slug: "jnj-ottava", name: "Johnson & Johnson (Ottava)", country: "US", founded_year: 1886, website: "https://jnj.com" },
  { slug: "corindus", name: "Corindus (Siemens Healthineers)", country: "US", founded_year: 2002, website: "https://corindus.com" },
  { slug: "accuray", name: "Accuray", country: "US", founded_year: 1990, website: "https://accuray.com" },
  { slug: "stryker", name: "Stryker", country: "US", founded_year: 1941, website: "https://stryker.com" },
  { slug: "globus-medical", name: "Globus Medical", country: "US", founded_year: 2003, website: "https://globusmedical.com" },
  { slug: "brainlab", name: "Brainlab", country: "DE", founded_year: 1989, website: "https://brainlab.com" },
  { slug: "synaptive", name: "Synaptive Medical", country: "CA", founded_year: 2012, website: "https://synaptivemedical.com" },
  { slug: "riken", name: "RIKEN", country: "JP", founded_year: 1917, website: "https://riken.jp" },
  { slug: "diligent-robotics", name: "Diligent Robotics", country: "US", founded_year: 2017, website: "https://diligentrobots.com" },
  { slug: "aethon", name: "Aethon (ST Engineering)", country: "US", founded_year: 2001, website: "https://aethon.com" },
  { slug: "xenex", name: "Xenex Disinfection Services", country: "US", founded_year: 2009, website: "https://xenex.com" },
  { slug: "omnicell", name: "Omnicell", country: "US", founded_year: 1992, website: "https://omnicell.com" },
  { slug: "intouch-health", name: "InTouch Health (Teladoc)", country: "US", founded_year: 2002, website: "https://intouchhealth.com" },
  // Agricultural
  { slug: "small-robot-company", name: "Small Robot Company", country: "GB", founded_year: 2017, website: "https://smallrobotcompany.com" },
  { slug: "naio-technologies", name: "Naio Technologies", country: "FR", founded_year: 2011, website: "https://naio-technologies.com" },
  { slug: "farmdroid", name: "FarmDroid", country: "DK", founded_year: 2018, website: "https://farmdroid.dk" },
  { slug: "agrobot", name: "Agrobot", country: "ES", founded_year: 2009, website: "https://agrobot.com" },
  { slug: "root-ai", name: "Root AI (AppHarvest)", country: "US", founded_year: 2018, website: "https://root-ai.com" },
  { slug: "iron-ox", name: "Iron Ox", country: "US", founded_year: 2015, website: "https://ironox.com" },
  { slug: "saga-robotics", name: "Saga Robotics", country: "NO", founded_year: 2016, website: "https://sagarobotics.com" },
  { slug: "harvest-croo", name: "Harvest CROO Robotics", country: "US", founded_year: 2013, website: "https://harvestcroo.com" },
  { slug: "ffrobotics", name: "FFRobotics", country: "IL", founded_year: 2014, website: "https://ffrobotics.com" },
  { slug: "dogtooth-technologies", name: "Dogtooth Technologies", country: "GB", founded_year: 2016, website: "https://dogtooth.tech" },
  { slug: "ripe-robotics", name: "Ripe Robotics", country: "AU", founded_year: 2017, website: "https://riperobotics.com" },
  { slug: "carbon-robotics", name: "Carbon Robotics", country: "US", founded_year: 2018, website: "https://carbonrobotics.com" },
  { slug: "monarch-tractor", name: "Monarch Tractor", country: "US", founded_year: 2018, website: "https://monarchtractor.com" },
  { slug: "earthsense", name: "EarthSense", country: "US", founded_year: 2016, website: "https://earthsense.co" },
  { slug: "verdant-robotics", name: "Verdant Robotics", country: "US", founded_year: 2018, website: "https://verdantrobotics.com" },
  // Construction
  { slug: "dusty-robotics", name: "Dusty Robotics", country: "US", founded_year: 2018, website: "https://dustyrobotics.com" },
  { slug: "canvas-construction", name: "Canvas Construction", country: "US", founded_year: 2017, website: "https://canvas.build" },
  { slug: "brokk", name: "Brokk", country: "SE", founded_year: 1976, website: "https://brokk.com" },
  { slug: "husqvarna-construction", name: "Husqvarna Construction", country: "SE", founded_year: 1689, website: "https://husqvarnacp.com" },
  { slug: "icon-build", name: "ICON", country: "US", founded_year: 2017, website: "https://iconbuild.com" },
  { slug: "apis-cor", name: "Apis Cor", country: "US", founded_year: 2014, website: "https://apis-cor.com" },
  { slug: "sarcos-robotics", name: "Sarcos Robotics", country: "US", founded_year: 1983, website: "https://sarcos.com" },
  { slug: "cognibotics", name: "Cognibotics", country: "SE", founded_year: 2010, website: "https://cognibotics.com" },
  { slug: "formant-robotics", name: "Formant", country: "US", founded_year: 2017, website: "https://formant.io" },
];

const robots: R[] = [

  // ═══ MEDICAL/SURGICAL (20) ═══
  {slug:"medtronic-hugo-ras",name:"Medtronic Hugo RAS",mfr:"medtronic",cat:"medical",price:null,year:2023,status:"active",desc:"Modular robotic-assisted surgery system with individual arm carts for flexible OR setup. Open console design. Touch Surgery AI analytics. CE Mark in Europe, expanding globally. Competes directly with da Vinci.",specs:{arms:4,type:"Robotic-assisted surgery",console:"Open design",ai:"Touch Surgery analytics",instruments:"Wristed, fully articulating",clearance:"CE Mark"},score:cs({performance:86,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:72,safety:90,design:80}),breakdown:{performance:86,reliability:82,ease_of_use:80,intelligence:82,value:78,ecosystem:72,safety:90,design:80}},
  {slug:"cmr-versius",name:"CMR Versius",mfr:"cmr-surgical",cat:"medical",price:null,year:2022,status:"active",desc:"Portable surgical robot with individual arm units that can be wheeled between ORs. Small footprint designed for hospital economics. Used in general surgery, gynecology, urology, and thoracic procedures across Europe and Asia.",specs:{arms:4,type:"Modular surgical robot",portability:"Individual arm carts",procedures:"General, gyn, urology, thoracic",clearance:"CE Mark, multiple markets"},score:cs({performance:84,reliability:80,ease_of_use:82,intelligence:80,value:82,ecosystem:68,safety:88,design:82}),breakdown:{performance:84,reliability:80,ease_of_use:82,intelligence:80,value:82,ecosystem:68,safety:88,design:82}},
  {slug:"jnj-ottava",name:"J&J Ottava",mfr:"jnj-ottava",cat:"medical",price:null,year:2026,status:"coming_soon",desc:"Johnson & Johnson's next-gen surgical robot integrating Ethicon instruments, Auris endoscopy, and Verb Surgical AI. Single-port design. Aims to democratize robotic surgery with lower cost of ownership. Expected launch 2026.",specs:{type:"Surgical robot",design:"Single-port",ai:"Verb Surgical AI",instruments:"Ethicon integrated",endoscopy:"Auris platform"},score:cs({performance:80,reliability:72,ease_of_use:78,intelligence:84,value:75,ecosystem:78,safety:85,design:80}),breakdown:{performance:80,reliability:72,ease_of_use:78,intelligence:84,value:75,ecosystem:78,safety:85,design:80}},
  {slug:"corindus-corpath-grx",name:"Corindus CorPath GRX",mfr:"corindus",cat:"medical",price:null,year:2021,status:"active",desc:"Robotic-assisted system for coronary and peripheral vascular interventions. Enables precision stent placement with sub-millimeter accuracy. Reduces radiation exposure to physician by up to 95%. Siemens Healthineers integration.",specs:{type:"Vascular interventional robot",precision:"Sub-millimeter",radiation_reduction:"95%",procedures:"Coronary PCI, peripheral",partner:"Siemens Healthineers"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:80,value:72,ecosystem:72,safety:90,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:80,value:72,ecosystem:72,safety:90,design:76}},
  {slug:"accuray-cyberknife-m6",name:"Accuray CyberKnife M6",mfr:"accuray",cat:"medical",price:null,year:2022,status:"active",desc:"Robotic radiosurgery system for non-invasive tumor treatment. 6-DOF robotic arm delivers radiation beams from thousands of angles. Real-time tumor tracking compensates for patient movement. Treats brain, spine, lung, prostate, and liver tumors.",specs:{type:"Robotic radiosurgery",dof:6,tracking:"Real-time tumor tracking",beams:"1000+ angles",tumors:"Brain, spine, lung, prostate, liver"},score:cs({performance:90,reliability:88,ease_of_use:72,intelligence:86,value:68,ecosystem:70,safety:92,design:78}),breakdown:{performance:90,reliability:88,ease_of_use:72,intelligence:86,value:68,ecosystem:70,safety:92,design:78}},
  {slug:"stryker-mako-totalhip",name:"Stryker Mako TotalHip",mfr:"stryker",cat:"medical",price:null,year:2022,status:"active",desc:"Robotic-arm assisted total hip replacement system. CT-based 3D planning creates patient-specific surgical plan. AccuStop haptic technology prevents cutting beyond planned boundaries. 2000+ installations worldwide.",specs:{type:"Robotic joint replacement",planning:"CT-based 3D patient-specific",haptics:"AccuStop boundaries",joints:"Total hip",installations:"2000+"},score:cs({performance:88,reliability:86,ease_of_use:78,intelligence:84,value:74,ecosystem:80,safety:92,design:78}),breakdown:{performance:88,reliability:86,ease_of_use:78,intelligence:84,value:74,ecosystem:80,safety:92,design:78}},
  {slug:"zimmer-biomet-rosa-knee",name:"Zimmer Biomet ROSA Knee",mfr:"zimmer-biomet",cat:"medical",price:null,year:2022,status:"active",desc:"Robotic surgical assistant for total and partial knee replacement. Combines pre-operative imaging with intraoperative data for real-time adjustments. Gap balancing and bone assessment tools.",specs:{type:"Robotic knee replacement",planning:"Pre-op + intraoperative",tools:"Gap balancing, bone assessment",joints:"Total and partial knee"},score:cs({performance:86,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:76,safety:90,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:76,safety:90,design:76}},
  {slug:"smith-nephew-navio",name:"Smith+Nephew NAVIO",mfr:"smith-nephew",cat:"medical",price:null,year:2021,status:"active",desc:"Handheld robotics-assisted surgical system for knee replacement. No pre-operative CT required. Surgeon maintains direct control of handpiece with robotic speed and depth control. Image-free option reduces workflow.",specs:{type:"Handheld surgical robot",ct_required:false,control:"Surgeon-held handpiece",joints:"Partial and total knee",approach:"Image-free option"},score:cs({performance:82,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:74,safety:88,design:76}),breakdown:{performance:82,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:74,safety:88,design:76}},
  {slug:"globus-excelsiusgps",name:"Globus ExcelsiusGPS",mfr:"globus-medical",cat:"medical",price:null,year:2022,status:"active",desc:"Robotic navigation platform for spine surgery. GPS-like guidance for pedicle screw placement. Full navigation with intraoperative imaging. 98.9% accuracy rate. Used in 1000+ hospitals.",specs:{type:"Robotic spine surgery",accuracy:"98.9%",guidance:"GPS-like navigation",imaging:"Intraoperative",hospitals:"1000+"},score:cs({performance:88,reliability:86,ease_of_use:76,intelligence:84,value:76,ecosystem:74,safety:92,design:76}),breakdown:{performance:88,reliability:86,ease_of_use:76,intelligence:84,value:76,ecosystem:74,safety:92,design:76}},
  {slug:"medtronic-mazor-x-stealth",name:"Medtronic Mazor X Stealth",mfr:"medtronic",cat:"medical",price:null,year:2022,status:"active",desc:"Robotic guidance system for spine surgery combining Mazor robotics with Stealth navigation. Predictive algorithms for optimal screw trajectories. Intraoperative 3D imaging with O-arm. 350,000+ screws placed.",specs:{type:"Robotic spine guidance",navigation:"Stealth 3D",imaging:"O-arm intraoperative",screws_placed:"350,000+",ai:"Predictive trajectory planning"},score:cs({performance:88,reliability:86,ease_of_use:78,intelligence:86,value:74,ecosystem:80,safety:92,design:76}),breakdown:{performance:88,reliability:86,ease_of_use:78,intelligence:86,value:74,ecosystem:80,safety:92,design:76}},
  {slug:"brainlab-cirq",name:"Brainlab Cirq",mfr:"brainlab",cat:"medical",price:null,year:2022,status:"active",desc:"Compact robotic arm that mounts directly on the OR table for cranial and spinal procedures. Lightweight design integrates with Brainlab navigation. Aligns instruments along planned trajectories. Minimal OR footprint.",specs:{type:"Cranial/spinal robotic arm",mount:"OR table-mounted",weight_kg:8,navigation:"Brainlab surgical navigation",footprint:"Minimal compact"},score:cs({performance:82,reliability:84,ease_of_use:82,intelligence:80,value:78,ecosystem:76,safety:88,design:80}),breakdown:{performance:82,reliability:84,ease_of_use:82,intelligence:80,value:78,ecosystem:76,safety:88,design:80}},
  {slug:"synaptive-modus-v",name:"Synaptive Modus V",mfr:"synaptive",cat:"medical",price:null,year:2022,status:"active",desc:"Digital robotic arm for automated positioning of exoscope in neurosurgery. AI-driven hands-free scope positioning follows surgical instruments. Eliminates need for manual microscope adjustment during brain and spine surgery.",specs:{type:"Robotic exoscope",ai:"Hands-free instrument tracking",surgery:"Neurosurgery",automation:"Automated scope positioning"},score:cs({performance:82,reliability:80,ease_of_use:84,intelligence:84,value:74,ecosystem:66,safety:86,design:80}),breakdown:{performance:82,reliability:80,ease_of_use:84,intelligence:84,value:74,ecosystem:66,safety:86,design:80}},
  {slug:"riken-robear",name:"RIKEN Robear",mfr:"riken",cat:"medical",price:null,year:2015,status:"active",desc:"Patient transfer robot shaped like a bear for elderly care. Lifts and transfers patients between beds and wheelchairs. Soft contact surfaces and force sensors ensure gentle handling. Addresses Japan's caregiver shortage.",specs:{type:"Patient transfer robot",payload_kg:80,design:"Bear-shaped friendly",sensors:"Force sensors for gentle handling",application:"Elderly care, hospital transfer"},score:cs({performance:72,reliability:74,ease_of_use:78,intelligence:70,value:60,ecosystem:50,safety:88,design:85}),breakdown:{performance:72,reliability:74,ease_of_use:78,intelligence:70,value:60,ecosystem:50,safety:88,design:85}},
  {slug:"diligent-moxi-2",name:"Diligent Moxi 2",mfr:"diligent-robotics",cat:"medical",price:null,year:2024,status:"active",desc:"Hospital service robot for non-patient-facing logistics. Delivers supplies, lab samples, and medications. Mobile manipulator with arm for pressing elevator buttons and opening doors. Deployed in 10+ hospitals.",specs:{type:"Hospital logistics robot",tasks:"Supply delivery, lab samples, medications",arm_dof:7,nav:"Hospital-trained AI navigation",deployments:"10+ hospitals"},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:80,value:74,ecosystem:65,safety:84,design:78}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:80,value:74,ecosystem:65,safety:84,design:78}},
  {slug:"aethon-tug-t3",name:"Aethon TUG T3",mfr:"aethon",cat:"medical",price:null,year:2023,status:"active",desc:"Autonomous mobile delivery robot for hospitals. Delivers medications, meals, linens, and lab specimens. 1400+ hospitals worldwide. Self-driving through hallways and elevators. Encrypted cabinets for secure medication transport.",specs:{type:"Hospital delivery robot",payload_kg:600,nav:"LiDAR + sensor fusion",elevator:true,security:"Encrypted cabinets",hospitals:"1400+"},score:cs({performance:82,reliability:84,ease_of_use:82,intelligence:78,value:78,ecosystem:76,safety:86,design:74}),breakdown:{performance:82,reliability:84,ease_of_use:82,intelligence:78,value:78,ecosystem:76,safety:86,design:74}},
  {slug:"xenex-lightstrike",name:"Xenex LightStrike",mfr:"xenex",cat:"medical",price:null,year:2022,status:"active",desc:"Pulsed xenon UV disinfection robot for hospital rooms. Kills C. diff, MRSA, and other HAIs in 5-10 minutes. Used in 500+ hospitals. Proven 50-70% reduction in hospital-acquired infections. No mercury, no residue.",specs:{type:"UV disinfection robot",uv_type:"Pulsed xenon",cycle_min:"5-10",pathogens:"C. diff, MRSA, HAIs",infection_reduction:"50-70%",hospitals:"500+"},score:cs({performance:84,reliability:86,ease_of_use:88,intelligence:72,value:82,ecosystem:68,safety:90,design:72}),breakdown:{performance:84,reliability:86,ease_of_use:88,intelligence:72,value:82,ecosystem:68,safety:90,design:72}},
  {slug:"omnicell-xt-automation",name:"Omnicell XT Automation",mfr:"omnicell",cat:"medical",price:null,year:2023,status:"active",desc:"Automated medication dispensing and management system with robotic pick-and-place. Central pharmacy automation for high-volume hospitals. Bar code verification ensures right medication to right patient.",specs:{type:"Pharmacy automation",verification:"Bar code scanning",volume:"High-volume hospital pharmacy",accuracy:"99.9%+ dispensing accuracy",system:"Central pharmacy robot"},score:cs({performance:86,reliability:88,ease_of_use:80,intelligence:78,value:78,ecosystem:76,safety:92,design:70}),breakdown:{performance:86,reliability:88,ease_of_use:80,intelligence:78,value:78,ecosystem:76,safety:92,design:70}},
  {slug:"omnicell-central-pharmacy",name:"Omnicell Central Pharmacy",mfr:"omnicell",cat:"medical",price:null,year:2023,status:"active",desc:"Fully automated central pharmacy dispensing robot. Robotic arm picks, packs, and labels medications for unit dose distribution. Integrates with EHR systems. Handles 60-80% of pharmacy dispensing volume.",specs:{type:"Central pharmacy robot",arm:"Robotic pick-pack-label",ehr_integration:true,dispensing_volume:"60-80%",output:"Unit dose packaging"},score:cs({performance:84,reliability:86,ease_of_use:78,intelligence:76,value:76,ecosystem:78,safety:90,design:70}),breakdown:{performance:84,reliability:86,ease_of_use:78,intelligence:76,value:76,ecosystem:78,safety:90,design:70}},
  {slug:"swisslog-transcar",name:"Swisslog TransCar",mfr:"swisslog",cat:"medical",price:null,year:2023,status:"active",desc:"Autonomous transport robot for hospital logistics. Delivers supplies, meals, medications, and waste via hospital corridors. Integrates with pneumatic tube systems and automated pharmacy. Multi-floor elevator operation.",specs:{type:"Hospital transport robot",payload_kg:300,nav:"LiDAR SLAM",elevator:true,integration:"Pharmacy, pneumatic tube",deliveries:"Supplies, meals, meds, waste"},score:cs({performance:80,reliability:84,ease_of_use:80,intelligence:78,value:76,ecosystem:78,safety:84,design:72}),breakdown:{performance:80,reliability:84,ease_of_use:80,intelligence:78,value:76,ecosystem:78,safety:84,design:72}},
  {slug:"intouch-vita",name:"InTouch Vita",mfr:"intouch-health",cat:"medical",price:null,year:2022,status:"active",desc:"Telepresence robot enabling remote physician consultation. HD camera, dual monitors, and integrated medical devices (stethoscope, otoscope). Used for stroke assessment, ICU rounding, and specialist consults. Teladoc Health platform.",specs:{type:"Medical telepresence",camera:"HD + zoom",devices:"Stethoscope, otoscope",display:"Dual monitors",platform:"Teladoc Health",applications:"Stroke, ICU, specialist consult"},score:cs({performance:78,reliability:82,ease_of_use:84,intelligence:76,value:76,ecosystem:72,safety:82,design:76}),breakdown:{performance:78,reliability:82,ease_of_use:84,intelligence:76,value:76,ecosystem:72,safety:82,design:76}},

  // ═══ AGRICULTURAL (20) ═══
  {slug:"small-robot-tom-v4",name:"Small Robot Company Tom V4",mfr:"small-robot-company",cat:"agricultural",price:null,year:2024,status:"active",desc:"Per-plant farming robot that maps and monitors individual plants. Lightweight design eliminates soil compaction. AI identifies weeds, diseases, and nutrient deficiencies at plant level. UK-based sustainable agriculture pioneer.",specs:{type:"Per-plant monitoring",weight_kg:30,ai:"Per-plant AI analysis",functions:"Mapping, monitoring, weed ID",sustainability:"Zero soil compaction"},score:cs({performance:74,reliability:72,ease_of_use:76,intelligence:82,value:70,ecosystem:58,safety:78,design:74}),breakdown:{performance:74,reliability:72,ease_of_use:76,intelligence:82,value:70,ecosystem:58,safety:78,design:74}},
  {slug:"naio-dino-v2",name:"Naio Dino V2",mfr:"naio-technologies",cat:"agricultural",price:null,year:2024,status:"active",desc:"Large-scale autonomous weeding robot for row crops. Handles beds up to 3m wide. Mechanical and electric weeding tools. RTK GPS navigation with centimeter accuracy. Used across French and European vegetable farms.",specs:{width_m:3,weight_kg:800,nav:"RTK GPS centimeter",weeding:"Mechanical + electric",crops:"Row vegetables",battery_hrs:8},score:cs({performance:80,reliability:78,ease_of_use:76,intelligence:78,value:74,ecosystem:68,safety:80,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:76,intelligence:78,value:74,ecosystem:68,safety:80,design:72}},
  {slug:"farmdroid-fd20",name:"FarmDroid FD20",mfr:"farmdroid",cat:"agricultural",price:60000,year:2024,status:"active",desc:"Solar-powered autonomous seeding and weeding robot from Denmark. Seeds with GPS precision, then returns to weed exactly between seeds without cameras. 100% solar, zero emissions. Covers 20+ hectares.",specs:{power:"100% solar",functions:"Seeding + precision weeding",coverage_ha:20,nav:"RTK GPS seed memory",emissions:"Zero",weight_kg:900},score:cs({performance:78,reliability:80,ease_of_use:82,intelligence:76,value:82,ecosystem:62,safety:82,design:76}),breakdown:{performance:78,reliability:80,ease_of_use:82,intelligence:76,value:82,ecosystem:62,safety:82,design:76}},
  {slug:"agrobot-e-series",name:"Agrobot E-Series",mfr:"agrobot",cat:"agricultural",price:null,year:2023,status:"active",desc:"Autonomous strawberry harvesting robot from Spain. 24 picking arms with machine vision for ripeness detection. Gentle gripping to avoid bruising. Harvests at night using LED lighting for consistent quality assessment.",specs:{arms:24,crop:"Strawberries",vision:"Ripeness detection",harvesting:"Night LED operation",gripping:"Gentle bruise-free"},score:cs({performance:78,reliability:72,ease_of_use:74,intelligence:80,value:68,ecosystem:55,safety:78,design:72}),breakdown:{performance:78,reliability:72,ease_of_use:74,intelligence:80,value:68,ecosystem:55,safety:78,design:72}},
  {slug:"root-ai-virgo",name:"Root AI Virgo",mfr:"root-ai",cat:"agricultural",price:null,year:2022,status:"active",desc:"Indoor greenhouse harvesting robot for tomatoes and peppers. Computer vision identifies ripe produce. Gentle suction gripping prevents damage. Navigates greenhouse rows autonomously. Now part of AppHarvest ecosystem.",specs:{type:"Greenhouse harvester",crops:"Tomatoes, peppers",vision:"Ripeness CV detection",gripping:"Suction gentle-pick",environment:"Indoor greenhouse"},score:cs({performance:74,reliability:72,ease_of_use:76,intelligence:80,value:68,ecosystem:58,safety:78,design:72}),breakdown:{performance:74,reliability:72,ease_of_use:76,intelligence:80,value:68,ecosystem:58,safety:78,design:72}},
  {slug:"iron-ox-grover",name:"Iron Ox Grover",mfr:"iron-ox",cat:"agricultural",price:null,year:2023,status:"active",desc:"Autonomous mobile robot for indoor farming operations. Moves 1000+ lb grow modules around the greenhouse. Part of Iron Ox fully autonomous growing system. AI-controlled nutrient management and environment.",specs:{type:"Indoor farm logistics",payload_kg:450,nav:"Autonomous greenhouse",ai:"Growth optimization AI",system:"Full autonomous grow system"},score:cs({performance:78,reliability:76,ease_of_use:78,intelligence:84,value:68,ecosystem:62,safety:80,design:74}),breakdown:{performance:78,reliability:76,ease_of_use:78,intelligence:84,value:68,ecosystem:62,safety:80,design:74}},
  {slug:"saga-thorvald-v3",name:"Saga Thorvald V3",mfr:"saga-robotics",cat:"agricultural",price:null,year:2024,status:"active",desc:"Modular agricultural robot platform from Norway. UV-C treatment for strawberry mildew. Autonomous phenotyping and crop monitoring. Modular tool system swaps between tasks. Operating in commercial UK and European farms.",specs:{type:"Modular farm platform",tools:"UV-C treatment, monitoring, phenotyping",modular:true,nav:"RTK GPS + LiDAR",commercial:"UK and EU farms"},score:cs({performance:76,reliability:78,ease_of_use:76,intelligence:78,value:72,ecosystem:62,safety:80,design:74}),breakdown:{performance:76,reliability:78,ease_of_use:76,intelligence:78,value:72,ecosystem:62,safety:80,design:74}},
  {slug:"harvest-croo-harvester",name:"Harvest CROO Harvester",mfr:"harvest-croo",cat:"agricultural",price:null,year:2024,status:"active",desc:"Large-scale autonomous strawberry harvester. 16 picking robots work simultaneously on an overhead gantry. Covers 8 acres per day. Machine vision and soft robotics for gentle berry picking.",specs:{pickers:16,type:"Overhead gantry harvester",crop:"Strawberries",coverage_acres_day:8,picking:"Soft robotics gentle"},score:cs({performance:80,reliability:74,ease_of_use:72,intelligence:78,value:72,ecosystem:55,safety:78,design:70}),breakdown:{performance:80,reliability:74,ease_of_use:72,intelligence:78,value:72,ecosystem:55,safety:78,design:70}},
  {slug:"ffrobotics-harvester",name:"FFRobotics Harvester",mfr:"ffrobotics",cat:"agricultural",price:null,year:2023,status:"active",desc:"Multi-arm fruit harvesting robot for apples and stone fruit. 12 robotic arms with 3-finger grippers. AI-based ripeness and size classification. Each arm picks independently using coordinated motion planning.",specs:{arms:12,type:"Multi-arm fruit harvester",crops:"Apples, stone fruit",vision:"Ripeness + size classification",gripper:"3-finger soft grip"},score:cs({performance:76,reliability:72,ease_of_use:72,intelligence:80,value:68,ecosystem:52,safety:78,design:70}),breakdown:{performance:76,reliability:72,ease_of_use:72,intelligence:80,value:68,ecosystem:52,safety:78,design:70}},
  {slug:"dogtooth-berry-pick",name:"Dogtooth Berry Picker",mfr:"dogtooth-technologies",cat:"agricultural",price:null,year:2024,status:"active",desc:"Autonomous strawberry picking robot using 3D vision and AI. Identifies and picks ripe berries while leaving unripe ones. Operates in standard polytunnel environments. Cambridge University spinout with commercial deployments.",specs:{type:"Berry picker",crop:"Strawberries",vision:"3D AI ripeness",environment:"Standard polytunnels",origin:"Cambridge spinout"},score:cs({performance:76,reliability:74,ease_of_use:76,intelligence:82,value:70,ecosystem:55,safety:80,design:72}),breakdown:{performance:76,reliability:74,ease_of_use:76,intelligence:82,value:70,ecosystem:55,safety:80,design:72}},
  {slug:"ripe-robotics-eve",name:"Ripe Robotics Eve",mfr:"ripe-robotics",cat:"agricultural",price:null,year:2024,status:"active",desc:"Australian apple and fruit picking robot. Vacuum-based picking with computer vision. Operates day and night. Modular platform adaptable to different orchard configurations and fruit types.",specs:{type:"Fruit picker",method:"Vacuum-based",crops:"Apples, stone fruit",operation:"Day and night",vision:"Computer vision ripeness"},score:cs({performance:74,reliability:72,ease_of_use:76,intelligence:78,value:72,ecosystem:52,safety:78,design:70}),breakdown:{performance:74,reliability:72,ease_of_use:76,intelligence:78,value:72,ecosystem:52,safety:78,design:70}},
  {slug:"carbon-laserweeder-2",name:"Carbon LaserWeeder 2",mfr:"carbon-robotics",cat:"agricultural",price:null,year:2024,status:"active",desc:"Tractor-pulled autonomous weeding system using high-power lasers to eliminate weeds. AI identifies and destroys 200,000 weeds per hour without herbicides. 30 CO2 lasers with millimeter precision. Chemical-free weed control.",specs:{lasers:30,weeds_per_hour:200000,type:"Laser weeding",precision:"Millimeter",chemical_free:true,ai:"Real-time weed identification"},score:cs({performance:88,reliability:80,ease_of_use:78,intelligence:90,value:78,ecosystem:62,safety:82,design:76}),breakdown:{performance:88,reliability:80,ease_of_use:78,intelligence:90,value:78,ecosystem:62,safety:82,design:76}},
  {slug:"burro-grande-ag",name:"Burro Grande",mfr:"burro",cat:"agricultural",price:null,year:2024,status:"active",desc:"Autonomous farm cart that follows workers through fields. AI learns farm layout over time. 225kg payload. Used in berry, grape, and nursery operations. Eliminates repetitive carrying tasks for harvest workers.",specs:{payload_kg:225,battery_hrs:10,autonomy:"Follow-me + waypoint",terrain:"Off-road, rows, hills",ai:"Self-improving navigation"},score:cs({performance:76,reliability:78,ease_of_use:86,intelligence:80,value:82,ecosystem:65,safety:80,design:72}),breakdown:{performance:76,reliability:78,ease_of_use:86,intelligence:80,value:82,ecosystem:65,safety:80,design:72}},
  {slug:"monarch-mk-v",name:"Monarch MK-V",mfr:"monarch-tractor",cat:"agricultural",price:78000,year:2024,status:"active",desc:"Electric smart tractor with autonomous and driver-optional operation. 70 HP equivalent. Implements standard 3-point hitch. AI-powered vision for autonomous mowing, spraying, and tilling. Carbon-negative farming.",specs:{power_hp:70,type:"Electric smart tractor",autonomy:"Driver-optional",hitch:"Standard 3-point",battery_hrs:10,ai:"Vision autonomous operation"},score:cs({performance:82,reliability:78,ease_of_use:80,intelligence:84,value:76,ecosystem:68,safety:82,design:80}),breakdown:{performance:82,reliability:78,ease_of_use:80,intelligence:84,value:76,ecosystem:68,safety:82,design:80}},
  {slug:"swarmfarm-robot-2",name:"SwarmFarm Robot 2",mfr:"swarmfarm",cat:"agricultural",price:null,year:2024,status:"active",desc:"Next-gen autonomous swarm farming platform from Australia. Multiple lightweight units work as coordinated swarm for broad-acre operations. Spot spraying, weed management, and data collection. Reduced chemical usage by 90%+.",specs:{weight_kg:900,swarm_capable:true,spray_width_m:6,nav:"RTK GPS",speed_kmh:15,chemical_reduction:"90%+"},score:cs({performance:80,reliability:78,ease_of_use:74,intelligence:82,value:76,ecosystem:60,safety:80,design:70}),breakdown:{performance:80,reliability:78,ease_of_use:74,intelligence:82,value:76,ecosystem:60,safety:80,design:70}},
  {slug:"earthsense-terrasentia",name:"EarthSense TerraSentia",mfr:"earthsense",cat:"agricultural",price:15000,year:2024,status:"active",desc:"Under-canopy crop phenotyping robot. Drives between crop rows measuring plant height, stem diameter, leaf area, and disease indicators. Used by seed companies and research universities for high-throughput field trials.",specs:{type:"Crop phenotyping",weight_kg:7,measurements:"Height, stem, leaf, disease",environment:"Under-canopy row crops",users:"Seed companies, universities"},score:cs({performance:78,reliability:76,ease_of_use:80,intelligence:82,value:80,ecosystem:62,safety:82,design:72}),breakdown:{performance:78,reliability:76,ease_of_use:80,intelligence:82,value:80,ecosystem:62,safety:82,design:72}},
  {slug:"verdant-v4000",name:"Verdant V4000",mfr:"verdant-robotics",cat:"agricultural",price:null,year:2024,status:"active",desc:"Multi-action precision agriculture robot. Combines AI weed identification with targeted micro-spraying, laser weeding, and fertilizer application in a single pass. Processes 500,000 plants per hour. 95% reduction in herbicide use.",specs:{plants_per_hour:500000,actions:"Spray, laser, fertilize",herbicide_reduction:"95%",ai:"Real-time weed classification",type:"Multi-action precision ag"},score:cs({performance:86,reliability:78,ease_of_use:76,intelligence:90,value:78,ecosystem:60,safety:82,design:76}),breakdown:{performance:86,reliability:78,ease_of_use:76,intelligence:90,value:78,ecosystem:60,safety:82,design:76}},
  {slug:"blue-river-see-spray-ag",name:"Blue River See & Spray",mfr:"john-deere",cat:"agricultural",price:null,year:2024,status:"active",desc:"John Deere precision spraying system using computer vision to distinguish crops from weeds. Applies herbicide only to weeds, reducing chemical use by 77%. 36 cameras across 120-foot boom. 12 mph operation speed.",specs:{cameras:36,spray_width_ft:120,speed_mph:12,herbicide_reduction:"77%",ai:"Deep learning weed detection"},score:cs({performance:88,reliability:82,ease_of_use:78,intelligence:92,value:80,ecosystem:78,safety:80,design:72}),breakdown:{performance:88,reliability:82,ease_of_use:78,intelligence:92,value:80,ecosystem:78,safety:80,design:72}},
  {slug:"naio-oz-v4",name:"Naio Oz V4",mfr:"naio-technologies",cat:"agricultural",price:30000,year:2024,status:"active",desc:"Compact autonomous weeding robot for market gardens and small farms. Handles 3 rows simultaneously. Electric drive with 8-hour battery. Interchangeable weeding tools. Most deployed autonomous weeding robot globally.",specs:{rows:3,weight_kg:130,battery_hrs:8,nav:"RTK GPS + LiDAR",tools:"Interchangeable weeding",type:"Compact autonomous weeder"},score:cs({performance:76,reliability:78,ease_of_use:82,intelligence:76,value:80,ecosystem:68,safety:82,design:74}),breakdown:{performance:76,reliability:78,ease_of_use:82,intelligence:76,value:80,ecosystem:68,safety:82,design:74}},
  {slug:"ecorobotix-ara-ii",name:"Ecorobotix ARA II",mfr:"ecorobotix",cat:"agricultural",price:null,year:2025,status:"active",desc:"Second-generation ultra-high precision spot spraying system from Switzerland. Camera-based AI detects and sprays individual weeds with 95% less herbicide. Improved speed and field coverage over ARA I. Tractor-mounted operation.",specs:{cameras:8,spray_reduction:"95%",resolution_cm:4,speed_kmh:14,mount:"Tractor 3-point hitch",generation:"Second gen"},score:cs({performance:86,reliability:80,ease_of_use:80,intelligence:90,value:82,ecosystem:65,safety:82,design:74}),breakdown:{performance:86,reliability:80,ease_of_use:80,intelligence:90,value:82,ecosystem:65,safety:82,design:74}},

  // ═══ CONSTRUCTION (10) ═══
  {slug:"hilti-jaibot-v2",name:"Hilti Jaibot V2",mfr:"hilti-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Semi-autonomous ceiling drilling robot for MEP installations. Reads BIM data to drill holes precisely according to architectural plans. Reduces ceiling layout and drilling time by 50%. Second generation with improved speed and accuracy.",specs:{type:"Ceiling drilling robot",source:"BIM data driven",time_reduction:"50%",application:"MEP installations",generation:"V2 improved"},score:cs({performance:80,reliability:80,ease_of_use:82,intelligence:78,value:78,ecosystem:72,safety:84,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:82,intelligence:78,value:78,ecosystem:72,safety:84,design:76}},
  {slug:"dusty-fieldprinter",name:"Dusty FieldPrinter",mfr:"dusty-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous BIM-to-field layout robot that prints construction plans directly on floors. Replaces manual chalk line layout. Sub-1/16-inch accuracy. Reduces layout time by 10x. Used by top ENR contractors.",specs:{type:"Floor layout printer",accuracy:"Sub-1/16 inch",speed:"10x faster than manual",source:"BIM data",users:"Top ENR contractors"},score:cs({performance:86,reliability:82,ease_of_use:84,intelligence:80,value:82,ecosystem:72,safety:82,design:78}),breakdown:{performance:86,reliability:82,ease_of_use:84,intelligence:80,value:82,ecosystem:72,safety:82,design:78}},
  {slug:"canvas-drywall-robot",name:"Canvas Construction Robot",mfr:"canvas-construction",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous drywall finishing robot. Applies joint compound, sands, and finishes drywall surfaces. 3D scanning maps wall surfaces. Addresses severe labor shortage in drywall finishing trade. 5x productivity improvement.",specs:{type:"Drywall finishing",scanning:"3D surface mapping",productivity:"5x improvement",tasks:"Compound, sand, finish",labor:"Addresses trade shortage"},score:cs({performance:80,reliability:76,ease_of_use:78,intelligence:80,value:78,ecosystem:58,safety:82,design:74}),breakdown:{performance:80,reliability:76,ease_of_use:78,intelligence:80,value:78,ecosystem:58,safety:82,design:74}},
  {slug:"brokk-170",name:"Brokk 170",mfr:"brokk",cat:"construction",price:90000,year:2023,status:"active",desc:"Remote-controlled demolition robot. 1.7-ton class with 210kg tool carrying capacity. Three-arm system for stability during breaking. Fits through standard doorways. Used in demolition, tunneling, and nuclear decommissioning.",specs:{weight_kg:1700,tool_capacity_kg:210,type:"Demolition robot",arms:3,fits:"Standard doorways",applications:"Demolition, tunneling, nuclear"},score:cs({performance:86,reliability:88,ease_of_use:72,intelligence:65,value:78,ecosystem:70,safety:85,design:70}),breakdown:{performance:86,reliability:88,ease_of_use:72,intelligence:65,value:78,ecosystem:70,safety:85,design:70}},
  {slug:"husqvarna-dxr-140",name:"Husqvarna DXR 140",mfr:"husqvarna-construction",cat:"construction",price:50000,year:2023,status:"active",desc:"Remote-controlled demolition robot from Husqvarna. 1.4-ton class. Interchangeable tools for breaking, crushing, and drilling. Electric-powered for indoor use. Low vibration transmission to operator.",specs:{weight_kg:1400,type:"Demolition robot",power:"Electric",tools:"Breaking, crushing, drilling",indoor:true,vibration:"Low operator exposure"},score:cs({performance:82,reliability:86,ease_of_use:74,intelligence:62,value:78,ecosystem:68,safety:84,design:72}),breakdown:{performance:82,reliability:86,ease_of_use:74,intelligence:62,value:78,ecosystem:68,safety:84,design:72}},
  {slug:"icon-vulcan-ii",name:"ICON Vulcan II",mfr:"icon-build",cat:"construction",price:null,year:2024,status:"active",desc:"Large-scale 3D construction printer for homes and buildings. Prints concrete walls up to 3 stories. Built 100+ homes in Austin TX. NASA partnership for lunar habitat printing. Reduces construction waste by 60%.",specs:{type:"3D construction printer",height_stories:3,material:"Concrete lavacrete",homes_built:"100+",waste_reduction:"60%",partner:"NASA lunar habitat"},score:cs({performance:84,reliability:78,ease_of_use:72,intelligence:78,value:82,ecosystem:62,safety:80,design:80}),breakdown:{performance:84,reliability:78,ease_of_use:72,intelligence:78,value:82,ecosystem:62,safety:80,design:80}},
  {slug:"apis-cor-printer",name:"Apis Cor 3D Printer",mfr:"apis-cor",cat:"construction",price:null,year:2023,status:"active",desc:"Mobile 3D construction printer that can print a house shell in 24 hours. Compact design fits on a flatbed truck. Prints circular and complex geometries. Used in affordable housing and military construction.",specs:{type:"Mobile 3D house printer",print_time_hrs:24,transport:"Flatbed truck",geometries:"Circular and complex",applications:"Affordable housing, military"},score:cs({performance:76,reliability:72,ease_of_use:70,intelligence:74,value:80,ecosystem:52,safety:78,design:74}),breakdown:{performance:76,reliability:72,ease_of_use:70,intelligence:74,value:80,ecosystem:52,safety:78,design:74}},
  {slug:"sarcos-guardian-xo",name:"Sarcos Guardian XO",mfr:"sarcos-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Full-body powered exoskeleton for construction and industrial work. Amplifies human strength by 20x. Lifts up to 200 lbs repeatedly without fatigue. Battery-powered for 2 hours. Reduces workplace injuries.",specs:{type:"Powered exoskeleton",force_amplification:"20x",max_lift_lbs:200,battery_hrs:2,weight_kg:100,injury_reduction:"Significant"},score:cs({performance:80,reliability:74,ease_of_use:72,intelligence:70,value:62,ecosystem:55,safety:82,design:80}),breakdown:{performance:80,reliability:74,ease_of_use:72,intelligence:70,value:62,ecosystem:55,safety:82,design:80}},
  {slug:"cognibotics-auto-calibration",name:"Cognibotics Auto Calibration",mfr:"cognibotics",cat:"construction",price:null,year:2023,status:"active",desc:"Robotic auto-calibration system for large-scale industrial robots. Improves robot accuracy from millimeters to sub-millimeter without manual intervention. Software-based correction uses physics models. Used in aerospace and automotive.",specs:{type:"Robot calibration system",improvement:"mm to sub-mm accuracy",method:"Physics model software",applications:"Aerospace, automotive",intervention:"No manual calibration"},score:cs({performance:82,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:62,safety:80,design:70}),breakdown:{performance:82,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:62,safety:80,design:70}},
  {slug:"formant-field-bot",name:"Formant Field Bot",mfr:"formant-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Cloud-managed field robot platform for construction site monitoring and inspection. Autonomous patrol and data collection. Integrates with Formant fleet management platform. Monitors progress, safety compliance, and site conditions.",specs:{type:"Site monitoring robot",functions:"Patrol, inspect, monitor",cloud:"Formant fleet management",monitoring:"Progress, safety, conditions",autonomy:"Scheduled patrol routes"},score:cs({performance:74,reliability:76,ease_of_use:80,intelligence:76,value:74,ecosystem:68,safety:78,design:72}),breakdown:{performance:74,reliability:76,ease_of_use:80,intelligence:76,value:74,ecosystem:68,safety:78,design:72}},
];

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 7 Import: 50 New Robots");
  console.log("  20 Medical + 20 Agricultural + 10 Construction");
  console.log("═══════════════════════════════════════════════════\n");

  const { data: cats } = await sb.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`Categories: ${catMap.size}\n`);

  const { data: existingMfrs } = await sb.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await sb.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await sb.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await sb.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await sb.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"=".repeat(50)}`);
  console.log(`Wave 7 Import Summary`);
  console.log(`${"=".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"=".repeat(50)}`);
}

main().catch(console.error);
