/**
 * Robotomated — Wave 5 Robot Import: 50 Robots
 * 20 Humanoid + 15 Security & Surveillance + 15 Hospitality & Service
 *
 * Run: npx tsx scripts/import-robots-wave5.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  humanoid: [
    "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop",
  ],
  security: [
    "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&h=400&fit=crop",
  ],
  hospitality: [
    "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop",
    "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop",
  ],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.humanoid;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers for Wave 5 ──
const newMfrs = [
  { slug: "hanson-robotics", name: "Hanson Robotics", country: "HK", founded_year: 2013, website: "https://hansonrobotics.com" },
  { slug: "astribot", name: "Astribot", country: "CN", founded_year: 2022, website: "https://astribot.com" },
  { slug: "mentee-robotics", name: "Mentee Robotics", country: "IL", founded_year: 2022, website: "https://menteerobotics.com" },
  { slug: "kepler-robot", name: "Kepler Robot", country: "CN", founded_year: 2023, website: "https://kepler-robot.com" },
  { slug: "clone-robotics", name: "Clone Robotics", country: "PL", founded_year: 2021, website: "https://clonerobotics.com" },
  { slug: "smp-robotics", name: "SMP Robotics", country: "US", founded_year: 2014, website: "https://smprobotics.com" },
  { slug: "gamma-2-robotics", name: "Gamma 2 Robotics", country: "US", founded_year: 2013, website: "https://intouchhealth.com" },
  { slug: "superdroid-robots", name: "SuperDroid Robots", country: "US", founded_year: 2001, website: "https://superdroidrobots.com" },
  { slug: "telerob", name: "Telerob (Cobham)", country: "DE", founded_year: 1992, website: "https://telerob.com" },
  { slug: "endeavor-robotics", name: "Endeavor Robotics (FLIR)", country: "US", founded_year: 2016, website: "https://flir.com" },
  { slug: "qinetiq", name: "QinetiQ", country: "GB", founded_year: 2001, website: "https://qinetiq.com" },
  { slug: "percepto", name: "Percepto", country: "IL", founded_year: 2014, website: "https://percepto.co" },
  { slug: "airobotics", name: "Airobotics", country: "IL", founded_year: 2014, website: "https://airoboticsdrones.com" },
  { slug: "nightingale-security", name: "Nightingale Security", country: "US", founded_year: 2013, website: "https://nightingalesecurity.com" },
  { slug: "sharp-robotics", name: "Sharp (Robotics)", country: "JP", founded_year: 1912, website: "https://sharp.co.jp" },
  { slug: "bear-robotics", name: "Bear Robotics", country: "US", founded_year: 2017, website: "https://bearrobotics.ai" },
  { slug: "pudu-robotics", name: "Pudu Robotics", country: "CN", founded_year: 2016, website: "https://pudutech.com" },
  { slug: "richtech-robotics", name: "Richtech Robotics", country: "US", founded_year: 2016, website: "https://richtechrobotics.com" },
  { slug: "savioke", name: "Savioke", country: "US", founded_year: 2013, website: "https://savioke.com" },
  { slug: "softbank-robotics", name: "SoftBank Robotics", country: "JP", founded_year: 2014, website: "https://softbankrobotics.com" },
  { slug: "avidbots", name: "Avidbots", country: "CA", founded_year: 2014, website: "https://avidbots.com" },
  { slug: "brain-corp", name: "Brain Corp", country: "US", founded_year: 2009, website: "https://braincorp.com" },
  { slug: "gaussian-robotics", name: "Gaussian Robotics", country: "CN", founded_year: 2013, website: "https://gaussianrobotics.com" },
  { slug: "keenon-robotics", name: "Keenon Robotics", country: "CN", founded_year: 2010, website: "https://keenon.com" },
  { slug: "orion-star", name: "Orion Star", country: "CN", founded_year: 2016, website: "https://orionstar.com" },
];

// ═══════════════════════════════════════════════════════════════
// ALL ROBOTS — 50 entries
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

  // ═══ HUMANOID ROBOTS (20) ═══
  {slug:"figure-01",name:"Figure 01",mfr:"figure-ai",cat:"humanoid",price:null,year:2023,status:"discontinued",desc:"Figure AI's first-generation humanoid robot. Full-size bipedal platform that demonstrated autonomous coffee-making and complex object manipulation. Served as the development platform for Figure 02 and 03. Partnered with OpenAI for conversational AI integration.",specs:{height_cm:168,weight_kg:60,payload_kg:20,dof:42,battery_hrs:5,max_speed_ms:1.2,compute:"Custom neural engine"},score:cs({performance:75,reliability:68,ease_of_use:72,intelligence:80,value:60,ecosystem:55,safety:70,design:82}),breakdown:{performance:75,reliability:68,ease_of_use:72,intelligence:80,value:60,ecosystem:55,safety:70,design:82}},
  {slug:"figure-02-humanoid",name:"Figure 02",mfr:"figure-ai",cat:"humanoid",price:130000,year:2024,status:"active",desc:"Second-generation humanoid robot deployed at BMW Spartanburg for 11 months. Loaded 90,000+ parts autonomously. Features 4th-gen hands with 16 DOF each. Helix VLA foundation model enables end-to-end learned behaviors from vision to action.",specs:{height_cm:168,weight_kg:70,payload_kg:25,dof:40,battery_hrs:5,max_speed_ms:1.2,compute:"Helix VLA onboard",hands_dof:16},score:cs({performance:85,reliability:78,ease_of_use:80,intelligence:88,value:72,ecosystem:70,safety:80,design:85}),breakdown:{performance:85,reliability:78,ease_of_use:80,intelligence:88,value:72,ecosystem:70,safety:80,design:85}},
  {slug:"apptronik-apollo-humanoid",name:"Apptronik Apollo",mfr:"apptronik",cat:"humanoid",price:null,year:2024,status:"active",desc:"NASA-heritage general-purpose humanoid designed for logistics and manufacturing. Swappable 4-hour battery packs for continuous operation. Partnerships with Amazon, Mercedes-Benz, and GXO for warehouse deployment. 55 lb payload capacity per arm.",specs:{height_cm:173,weight_kg:73,payload_kg:25,dof:36,battery_hrs:4,max_speed_ms:1.4,compute:"Custom AI stack",partners:"Amazon, Mercedes-Benz, GXO"},score:cs({performance:80,reliability:76,ease_of_use:78,intelligence:80,value:72,ecosystem:72,safety:78,design:82}),breakdown:{performance:80,reliability:76,ease_of_use:78,intelligence:80,value:72,ecosystem:72,safety:78,design:82}},
  {slug:"agility-digit-5",name:"Agility Digit 5",mfr:"agility-robotics",cat:"humanoid",price:null,year:2025,status:"coming_soon",desc:"Fifth-generation bipedal humanoid robot purpose-built for warehouse logistics. Improved from Digit deployed at Amazon and GXO warehouses. Updated hands for box manipulation, longer battery life, and enhanced navigation in dynamic environments.",specs:{height_cm:175,weight_kg:65,payload_kg:16,dof:30,battery_hrs:4,max_speed_ms:1.5,compute:"Custom perception stack"},score:cs({performance:82,reliability:78,ease_of_use:80,intelligence:82,value:70,ecosystem:74,safety:80,design:80}),breakdown:{performance:82,reliability:78,ease_of_use:80,intelligence:82,value:70,ecosystem:74,safety:80,design:80}},
  {slug:"1x-neo-humanoid",name:"1X NEO",mfr:"1x-technologies",cat:"humanoid",price:25000,year:2025,status:"coming_soon",desc:"First humanoid designed specifically for home use. OpenAI-backed. In-home trials with selected families. Only 30 kg weight makes it safe for domestic environments. Neural network-driven locomotion and manipulation learned from human demonstrations.",specs:{height_cm:167,weight_kg:30,payload_kg:10,dof:32,battery_hrs:2,max_speed_ms:1.0,compute:"OpenAI models"},score:cs({performance:72,reliability:68,ease_of_use:82,intelligence:82,value:80,ecosystem:65,safety:75,design:80}),breakdown:{performance:72,reliability:68,ease_of_use:82,intelligence:82,value:80,ecosystem:65,safety:75,design:80}},
  {slug:"1x-eve-humanoid",name:"1X EVE",mfr:"1x-technologies",cat:"humanoid",price:null,year:2022,status:"active",desc:"Wheeled upper-body humanoid for security and logistics. Dual-arm manipulation on mobile wheeled base. Deployed in commercial security patrols. Vision-language model integration for natural interaction.",specs:{height_cm:180,weight_kg:86,payload_kg:15,dof:24,battery_hrs:6,max_speed_ms:2.0,compute:"OpenAI models",locomotion:"Wheeled base"},score:cs({performance:72,reliability:74,ease_of_use:76,intelligence:78,value:68,ecosystem:62,safety:72,design:74}),breakdown:{performance:72,reliability:74,ease_of_use:76,intelligence:78,value:68,ecosystem:62,safety:72,design:74}},
  {slug:"sanctuary-phoenix-humanoid",name:"Sanctuary AI Phoenix",mfr:"sanctuary-ai",cat:"humanoid",price:null,year:2024,status:"active",desc:"World's most dexterous humanoid hands with 20+ DOF per hand. Carbon AI general-purpose AI system learns new tasks in 24 hours. 7th generation robot deployed at Magna International for automotive parts handling. Teleoperation for rapid skill transfer.",specs:{height_cm:170,weight_kg:70,payload_kg:25,dof:64,battery_hrs:4,max_speed_ms:1.0,compute:"Carbon AI system",hand_dof:20},score:cs({performance:82,reliability:75,ease_of_use:80,intelligence:88,value:68,ecosystem:65,safety:76,design:82}),breakdown:{performance:82,reliability:75,ease_of_use:80,intelligence:88,value:68,ecosystem:65,safety:76,design:82}},
  {slug:"fourier-gr1",name:"Fourier GR-1",mfr:"fourier-intelligence",cat:"humanoid",price:90000,year:2023,status:"active",desc:"First mass-produced full-size humanoid robot at $90K price point. 40 DOF with force-controlled joints. Originally designed for rehabilitation but pivoting to general purpose. 50 kg payload, walks at 5 km/h. Open SDK for research.",specs:{height_cm:165,weight_kg:55,payload_kg:50,dof:40,battery_hrs:2,max_speed_ms:1.4,compute:"Custom + ROS2"},score:cs({performance:78,reliability:74,ease_of_use:76,intelligence:72,value:82,ecosystem:70,safety:76,design:76}),breakdown:{performance:78,reliability:74,ease_of_use:76,intelligence:72,value:82,ecosystem:70,safety:76,design:76}},
  {slug:"unitree-h1-humanoid",name:"Unitree H1",mfr:"unitree-robotics",cat:"humanoid",price:90000,year:2023,status:"active",desc:"Full-size humanoid that set the world record for bipedal running at 3.3 m/s. 360 N.m max joint torque. Built for enterprise deployment in logistics and inspection. Reinforcement learning for dynamic locomotion.",specs:{height_cm:180,weight_kg:47,payload_kg:10,dof:26,battery_hrs:2,max_speed_ms:3.3,max_torque_nm:360,compute:"NVIDIA Orin"},score:cs({performance:90,reliability:78,ease_of_use:78,intelligence:82,value:82,ecosystem:75,safety:72,design:85}),breakdown:{performance:90,reliability:78,ease_of_use:78,intelligence:82,value:82,ecosystem:75,safety:72,design:85}},
  {slug:"unitree-g1-humanoid",name:"Unitree G1",mfr:"unitree-robotics",cat:"humanoid",price:16000,year:2024,status:"active",desc:"Most affordable production humanoid robot at $16K base price. 23+ DOF with force-sensing joints. Sim-to-real reinforcement learning for locomotion. Compact 127 cm height. Ships globally with developer SDK.",specs:{height_cm:127,weight_kg:35,payload_kg:3,dof:23,battery_hrs:2,max_speed_ms:2.0,compute:"NVIDIA Jetson Orin"},score:cs({performance:76,reliability:72,ease_of_use:82,intelligence:78,value:95,ecosystem:72,safety:68,design:78}),breakdown:{performance:76,reliability:72,ease_of_use:82,intelligence:78,value:95,ecosystem:72,safety:68,design:78}},
  {slug:"tesla-optimus-gen2-humanoid",name:"Tesla Optimus Gen 2",mfr:"tesla",cat:"humanoid",price:null,year:2024,status:"coming_soon",desc:"Second-generation Tesla humanoid deployed internally at Tesla factories for battery cell handling and parts sorting. 11 DOF hands with tactile sensing. End-to-end neural network control derived from FSD technology. Target price under $20K at scale.",specs:{height_cm:173,weight_kg:57,payload_kg:20,dof:28,battery_hrs:8,max_speed_ms:1.0,compute:"Tesla FSD chip / Dojo",hands_dof:11},score:cs({performance:74,reliability:68,ease_of_use:70,intelligence:78,value:75,ecosystem:65,safety:68,design:78}),breakdown:{performance:74,reliability:68,ease_of_use:70,intelligence:78,value:75,ecosystem:65,safety:68,design:78}},
  {slug:"boston-dynamics-atlas-electric-humanoid",name:"Boston Dynamics Atlas (Electric)",mfr:"boston-dynamics",cat:"humanoid",price:null,year:2024,status:"coming_soon",desc:"All-electric commercial redesign of the legendary Atlas platform. Unprecedented range of motion exceeds human flexibility. Designed for real-world manufacturing with Hyundai. Gripper-based manipulation system replaces hydraulics entirely.",specs:{height_cm:150,weight_kg:89,payload_kg:25,dof:28,battery_hrs:4,max_speed_ms:2.5,compute:"Custom perception AI"},score:cs({performance:95,reliability:82,ease_of_use:75,intelligence:90,value:60,ecosystem:80,safety:85,design:95}),breakdown:{performance:95,reliability:82,ease_of_use:75,intelligence:90,value:60,ecosystem:80,safety:85,design:95}},
  {slug:"engineered-arts-ameca-humanoid",name:"Engineered Arts Ameca",mfr:"engineered-arts",cat:"humanoid",price:150000,year:2021,status:"active",desc:"Most realistic facial expressions in robotics with 52 DOF face. GPT-4o integrated for natural conversation. Used globally for research, entertainment, and human-robot interaction studies. Modular Mesmer technology for lifelike expressions.",specs:{height_cm:180,weight_kg:50,dof:52,compute:"GPT-4o cloud + onboard",face_actuators:17,expressions:"Unlimited blended"},score:cs({performance:70,reliability:74,ease_of_use:80,intelligence:82,value:58,ecosystem:60,safety:75,design:95}),breakdown:{performance:70,reliability:74,ease_of_use:80,intelligence:82,value:58,ecosystem:60,safety:75,design:95}},
  {slug:"pal-robotics-talos",name:"PAL Robotics TALOS",mfr:"pal-robotics",cat:"humanoid",price:null,year:2020,status:"active",desc:"Full-size torque-controlled humanoid for research and industrial applications. 32 DOF with 6-axis force/torque sensors in all joints. ROS-based open platform. Used by DARPA, NASA, and EU research programs.",specs:{height_cm:175,weight_kg:95,payload_kg:6,dof:32,battery_hrs:3,max_speed_ms:1.0,compute:"ROS2 + custom",sensors:"6-axis F/T all joints"},score:cs({performance:80,reliability:78,ease_of_use:70,intelligence:76,value:60,ecosystem:78,safety:80,design:75}),breakdown:{performance:80,reliability:78,ease_of_use:70,intelligence:76,value:60,ecosystem:78,safety:80,design:75}},
  {slug:"ubtech-walker-x",name:"UBTECH Walker X",mfr:"ubtech-robotics",cat:"humanoid",price:null,year:2024,status:"active",desc:"Latest industrial humanoid from UBTECH, the first publicly traded humanoid company. 41 DOF. Deployed in NIO EV factories for quality inspection and parts handling. Upgraded vision and manipulation over Walker S.",specs:{height_cm:145,weight_kg:63,payload_kg:10,dof:41,battery_hrs:3,max_speed_ms:1.0,compute:"Custom UBTECH AI"},score:cs({performance:78,reliability:74,ease_of_use:76,intelligence:78,value:70,ecosystem:68,safety:74,design:78}),breakdown:{performance:78,reliability:74,ease_of_use:76,intelligence:78,value:70,ecosystem:68,safety:74,design:78}},
  {slug:"hanson-robotics-sophia",name:"Hanson Robotics Sophia",mfr:"hanson-robotics",cat:"humanoid",price:null,year:2016,status:"active",desc:"World's most famous social humanoid robot. First robot to receive citizenship (Saudi Arabia). Lifelike facial expressions using patented Frubber material. Primarily a research and PR platform for human-robot interaction.",specs:{height_cm:165,weight_kg:20,dof:62,compute:"SingularityNET + GPT",face_material:"Frubber",expressions:"62+ facial expressions"},score:cs({performance:55,reliability:65,ease_of_use:78,intelligence:75,value:50,ecosystem:55,safety:70,design:90}),breakdown:{performance:55,reliability:65,ease_of_use:78,intelligence:75,value:50,ecosystem:55,safety:70,design:90}},
  {slug:"astribot-s1",name:"Astribot S1",mfr:"astribot",cat:"humanoid",price:null,year:2024,status:"coming_soon",desc:"Chinese humanoid with exceptional speed and dexterity. Demonstrated pouring liquids, calligraphy, and cooking without teleoperation. Upper-body humanoid on wheeled base. Trained using imitation learning from human demonstration.",specs:{height_cm:170,weight_kg:60,payload_kg:10,dof:38,max_speed_ms:1.5,compute:"Custom VLA model",learning:"Imitation learning"},score:cs({performance:82,reliability:70,ease_of_use:75,intelligence:85,value:72,ecosystem:55,safety:72,design:80}),breakdown:{performance:82,reliability:70,ease_of_use:75,intelligence:85,value:72,ecosystem:55,safety:72,design:80}},
  {slug:"mentee-robotics-me2",name:"Mentee Robotics ME-2",mfr:"mentee-robotics",cat:"humanoid",price:null,year:2025,status:"coming_soon",desc:"Israeli humanoid robot founded by Prof. Amnon Shashua (Mobileye creator). Full-body bipedal with advanced vision-language-action model. Designed for real-world adaptability in unstructured environments. Lightweight carbon fiber construction.",specs:{height_cm:170,weight_kg:45,payload_kg:15,dof:34,battery_hrs:4,max_speed_ms:1.2,compute:"Proprietary VLA",material:"Carbon fiber"},score:cs({performance:76,reliability:70,ease_of_use:74,intelligence:84,value:68,ecosystem:50,safety:74,design:82}),breakdown:{performance:76,reliability:70,ease_of_use:74,intelligence:84,value:68,ecosystem:50,safety:74,design:82}},
  {slug:"kepler-discover",name:"Kepler Discover",mfr:"kepler-robot",cat:"humanoid",price:30000,year:2025,status:"coming_soon",desc:"Chinese humanoid targeting mass production at $30K price point. 40 DOF with dexterous 12-DOF hands. Built for industrial and commercial service applications. Strong emphasis on affordability and scalability.",specs:{height_cm:178,weight_kg:85,payload_kg:15,dof:40,battery_hrs:5,max_speed_ms:1.2,compute:"Custom AI chip",hand_dof:12},score:cs({performance:76,reliability:70,ease_of_use:76,intelligence:76,value:85,ecosystem:55,safety:72,design:76}),breakdown:{performance:76,reliability:70,ease_of_use:76,intelligence:76,value:85,ecosystem:55,safety:72,design:76}},
  {slug:"clone-alpha",name:"Clone Alpha",mfr:"clone-robotics",cat:"humanoid",price:null,year:2025,status:"coming_soon",desc:"Biomimetic humanoid using artificial muscles instead of electric motors. Replicates human musculoskeletal system with synthetic tendons and muscles. 1000+ actuators. Aims to be the most human-like movement system ever built.",specs:{height_cm:175,weight_kg:70,actuators:1000,actuation:"Artificial muscles",compute:"Custom neural control",biomimetic:true},score:cs({performance:72,reliability:60,ease_of_use:65,intelligence:70,value:55,ecosystem:40,safety:65,design:90}),breakdown:{performance:72,reliability:60,ease_of_use:65,intelligence:70,value:55,ecosystem:40,safety:65,design:90}},

  // ═══ SECURITY & SURVEILLANCE (15) ═══
  {slug:"cobalt-robotics-guard",name:"Cobalt Robotics Guard",mfr:"cobalt-robotics",cat:"security",price:null,year:2022,status:"active",desc:"Indoor security patrol robot combining autonomous navigation with remote human security specialists. 360-degree cameras, thermal imaging, and badge reader. Deployed in Fortune 500 offices, data centers, and warehouses.",specs:{height_cm:120,weight_kg:55,battery_hrs:8,cameras:"360-degree HD + thermal",sensors:"Badge reader, air quality, motion",nav:"LiDAR SLAM",monitoring:"24/7 remote specialists"},score:cs({performance:80,reliability:82,ease_of_use:84,intelligence:78,value:72,ecosystem:70,safety:85,design:78}),breakdown:{performance:80,reliability:82,ease_of_use:84,intelligence:78,value:72,ecosystem:70,safety:85,design:78}},
  {slug:"knightscope-k5-security",name:"Knightscope K5",mfr:"knightscope",cat:"security",price:null,year:2015,status:"active",desc:"Outdoor autonomous security robot with 24-hour patrol capability. 360-degree video, thermal cameras, LiDAR, and license plate recognition. $400/month lease model. 400+ units deployed across corporate campuses and parking lots.",specs:{height_cm:152,weight_kg:181,battery_hrs:24,cameras:"360° video + thermal",sensors:"LiDAR, ALPR, environmental",ip_rating:"IP55",lease_monthly:400},score:cs({performance:68,reliability:72,ease_of_use:74,intelligence:70,value:72,ecosystem:60,safety:74,design:62}),breakdown:{performance:68,reliability:72,ease_of_use:74,intelligence:70,value:72,ecosystem:60,safety:74,design:62}},
  {slug:"knightscope-k7",name:"Knightscope K7",mfr:"knightscope",cat:"security",price:null,year:2023,status:"active",desc:"Multi-terrain security robot designed for rough outdoor environments. Handles grass, gravel, and uneven surfaces. Enhanced AI threat detection. GPS-guided patrol routes with geofencing.",specs:{height_cm:100,weight_kg:340,battery_hrs:20,terrain:"Multi-terrain all-weather",cameras:"4K + thermal",sensors:"LiDAR, radar, GPS",ip_rating:"IP65"},score:cs({performance:72,reliability:74,ease_of_use:72,intelligence:72,value:68,ecosystem:62,safety:76,design:65}),breakdown:{performance:72,reliability:74,ease_of_use:72,intelligence:72,value:68,ecosystem:62,safety:76,design:65}},
  {slug:"boston-dynamics-spot-security",name:"Boston Dynamics Spot Security",mfr:"boston-dynamics",cat:"security",price:74500,year:2023,status:"active",desc:"Spot quadruped configured for security and surveillance. Autonomous patrol routes through complex environments including stairs. Thermal anomaly detection, gas leak detection, and intrusion alerts. Scout integration for remote monitoring.",specs:{height_cm:84,weight_kg:32,battery_hrs:1.5,cameras:"360° + thermal",nav:"Visual + LiDAR SLAM",terrain:"Stairs, rough terrain",ip_rating:"IP54",software:"Scout remote monitoring"},score:cs({performance:88,reliability:88,ease_of_use:80,intelligence:86,value:68,ecosystem:88,safety:90,design:90}),breakdown:{performance:88,reliability:88,ease_of_use:80,intelligence:86,value:68,ecosystem:88,safety:90,design:90}},
  {slug:"smp-robotics-s52",name:"SMP Robotics S5.2",mfr:"smp-robotics",cat:"security",price:25000,year:2023,status:"active",desc:"Outdoor autonomous patrol robot with 24/7 operation capability. LiDAR, thermal cameras, and 360-degree optical cameras. Solar-assisted charging. GPS waypoint navigation with obstacle avoidance.",specs:{height_cm:80,weight_kg:80,battery_hrs:22,cameras:"360° optical + thermal",nav:"GPS waypoint + LiDAR",solar_assist:true,ip_rating:"IP65"},score:cs({performance:72,reliability:76,ease_of_use:74,intelligence:70,value:78,ecosystem:58,safety:76,design:68}),breakdown:{performance:72,reliability:76,ease_of_use:74,intelligence:70,value:78,ecosystem:58,safety:76,design:68}},
  {slug:"ramsee-gamma2",name:"RAMSEE by Gamma 2",mfr:"gamma-2-robotics",cat:"security",price:null,year:2020,status:"active",desc:"Autonomous indoor security patrol robot with AI-based anomaly detection. Detects unauthorized persons, unusual sounds, environmental hazards, and security breaches. Integrates with existing security systems.",specs:{height_cm:150,weight_kg:68,battery_hrs:10,cameras:"HD + infrared",sensors:"Audio anomaly, PIR, environmental",nav:"LiDAR SLAM indoor"},score:cs({performance:70,reliability:72,ease_of_use:76,intelligence:72,value:70,ecosystem:58,safety:78,design:65}),breakdown:{performance:70,reliability:72,ease_of_use:76,intelligence:72,value:70,ecosystem:58,safety:78,design:65}},
  {slug:"superdroid-surveillance-robot",name:"SuperDroid Surveillance Robot",mfr:"superdroid-robots",cat:"security",price:15000,year:2022,status:"active",desc:"Rugged tracked surveillance robot for hazardous environments. Military-grade construction. Pan-tilt-zoom camera, night vision, and two-way audio. Remote-controlled with autonomous patrol modes.",specs:{weight_kg:45,cameras:"PTZ + night vision",tracks:"All-terrain tracked",battery_hrs:6,control:"Remote + autonomous patrol",two_way_audio:true},score:cs({performance:74,reliability:78,ease_of_use:68,intelligence:62,value:74,ecosystem:52,safety:80,design:62}),breakdown:{performance:74,reliability:78,ease_of_use:68,intelligence:62,value:74,ecosystem:52,safety:80,design:62}},
  {slug:"telerob-telemax",name:"Telerob Telemax",mfr:"telerob",cat:"security",price:250000,year:2021,status:"active",desc:"Heavy-duty EOD and CBRN reconnaissance robot. Used by military and law enforcement for bomb disposal, hazmat response, and tactical reconnaissance. Manipulator arm with 7 DOF. Stair-climbing tracked platform.",specs:{weight_kg:180,arm_dof:7,payload_kg:50,cameras:"HD + thermal + zoom",tracks:"Stair-climbing",battery_hrs:4,applications:"EOD, CBRN, tactical"},score:cs({performance:85,reliability:88,ease_of_use:65,intelligence:72,value:55,ecosystem:62,safety:92,design:68}),breakdown:{performance:85,reliability:88,ease_of_use:65,intelligence:72,value:55,ecosystem:62,safety:92,design:68}},
  {slug:"endeavor-packbot",name:"Endeavor PackBot",mfr:"endeavor-robotics",cat:"security",price:200000,year:2018,status:"active",desc:"Battle-proven tactical robot used in Iraq and Afghanistan. 5,000+ units deployed globally by military and law enforcement. IED disposal, reconnaissance, and hazmat detection. Multi-mission payloads.",specs:{weight_kg:13,cameras:"HD + infrared zoom",tracks:"Articulated flippers",battery_hrs:4,payload_kg:9,arm_reach_mm:500,deployments:"5000+"},score:cs({performance:82,reliability:90,ease_of_use:72,intelligence:68,value:60,ecosystem:72,safety:90,design:65}),breakdown:{performance:82,reliability:90,ease_of_use:72,intelligence:68,value:60,ecosystem:72,safety:90,design:65}},
  {slug:"qinetiq-talon",name:"QinetiQ TALON",mfr:"qinetiq",cat:"security",price:175000,year:2019,status:"active",desc:"Multi-mission military robot with 4,000+ units deployed. EOD, CBRN reconnaissance, and SWAT operations. Tracked platform climbs stairs and traverses rough terrain. Modular payload system.",specs:{weight_kg:52,cameras:"Day/night + thermal",tracks:"6-wheel heavy-duty",battery_hrs:8,speed_mph:5.2,payload_kg:45,deployments:"4000+"},score:cs({performance:84,reliability:90,ease_of_use:70,intelligence:68,value:62,ecosystem:70,safety:92,design:65}),breakdown:{performance:84,reliability:90,ease_of_use:70,intelligence:68,value:62,ecosystem:70,safety:92,design:65}},
  {slug:"percepto-sparrow",name:"Percepto Sparrow",mfr:"percepto",cat:"security",price:null,year:2024,status:"active",desc:"Autonomous drone-in-a-box system for industrial site security and inspection. Launches, flies missions, and returns to base autonomously. AI-powered anomaly detection. Deployed at power plants, oil refineries, and solar farms.",specs:{type:"Drone-in-a-box",flight_time_min:40,range_km:7,cameras:"Dual RGB + thermal",ai:"Anomaly detection",autonomous_landing:true,ip_rating:"IP55"},score:cs({performance:84,reliability:80,ease_of_use:82,intelligence:84,value:72,ecosystem:68,safety:82,design:78}),breakdown:{performance:84,reliability:80,ease_of_use:82,intelligence:84,value:72,ecosystem:68,safety:82,design:78}},
  {slug:"airobotics-optimus-drone",name:"Airobotics Optimus",mfr:"airobotics",cat:"security",price:null,year:2023,status:"active",desc:"Fully automated industrial drone platform. Self-launching, self-charging, self-managing. FAA BVLOS approval. Used for security patrols, emergency response, and infrastructure inspection at industrial sites.",specs:{type:"Automated drone platform",flight_time_min:35,cameras:"4K + thermal + LiDAR",charging:"Automated base station",faa:"BVLOS approved",range_km:5},score:cs({performance:82,reliability:78,ease_of_use:84,intelligence:82,value:68,ecosystem:65,safety:80,design:78}),breakdown:{performance:82,reliability:78,ease_of_use:84,intelligence:82,value:68,ecosystem:65,safety:80,design:78}},
  {slug:"nightingale-blackbird",name:"Nightingale Blackbird",mfr:"nightingale-security",cat:"security",price:null,year:2023,status:"active",desc:"Autonomous drone security system for large properties and campuses. Responds to alarms by automatically deploying drone to investigate. Real-time streaming to security operations center. Weatherproof base station.",specs:{type:"Drone response system",flight_time_min:30,cameras:"4K + night vision",response_time_sec:60,base_station:"Weatherproof",monitoring:"SOC integration"},score:cs({performance:78,reliability:76,ease_of_use:80,intelligence:80,value:70,ecosystem:60,safety:78,design:75}),breakdown:{performance:78,reliability:76,ease_of_use:80,intelligence:80,value:70,ecosystem:60,safety:78,design:75}},
  {slug:"sharp-intellos",name:"Sharp INTELLOS",mfr:"sharp-robotics",cat:"security",price:null,year:2022,status:"active",desc:"Autonomous outdoor security patrol robot by Sharp. Patrols perimeters with thermal and optical cameras. AI-powered intruder detection with automatic alert system. Self-docking for charging.",specs:{height_cm:90,weight_kg:60,battery_hrs:10,cameras:"HD + thermal",nav:"GPS + LiDAR",ai:"Intruder detection",ip_rating:"IP55",self_charging:true},score:cs({performance:74,reliability:78,ease_of_use:78,intelligence:74,value:72,ecosystem:62,safety:80,design:70}),breakdown:{performance:74,reliability:78,ease_of_use:78,intelligence:74,value:72,ecosystem:62,safety:80,design:70}},
  {slug:"pal-robotics-tiago-security",name:"PAL Robotics TIAGo Security",mfr:"pal-robotics",cat:"security",price:null,year:2023,status:"active",desc:"Configurable mobile service robot adapted for indoor security patrol. ROS-based platform with modular sensors. Face recognition, anomaly detection, and telepresence. Originally a research platform adapted for commercial security.",specs:{height_cm:145,weight_kg:70,battery_hrs:8,cameras:"RGB-D + 360° LiDAR",arm_dof:7,nav:"ROS2 SLAM",ai:"Face recognition, anomaly detection"},score:cs({performance:76,reliability:78,ease_of_use:72,intelligence:78,value:65,ecosystem:75,safety:80,design:72}),breakdown:{performance:76,reliability:78,ease_of_use:72,intelligence:78,value:65,ecosystem:75,safety:80,design:72}},

  // ═══ HOSPITALITY & SERVICE (15) ═══
  {slug:"bear-robotics-servi",name:"Bear Robotics Servi",mfr:"bear-robotics",cat:"hospitality",price:null,year:2023,status:"active",desc:"Restaurant food delivery robot founded by a former Google engineer. Autonomous navigation between kitchen and tables. Multi-tray design carries 4 trays simultaneously. Used in 2000+ restaurants including Denny's and Chili's.",specs:{height_cm:105,weight_kg:40,trays:4,payload_kg:40,battery_hrs:12,nav:"3D LiDAR SLAM",deployments:"2000+ restaurants"},score:cs({performance:82,reliability:82,ease_of_use:88,intelligence:78,value:80,ecosystem:72,safety:82,design:78}),breakdown:{performance:82,reliability:82,ease_of_use:88,intelligence:78,value:80,ecosystem:72,safety:82,design:78}},
  {slug:"pudu-bellabot",name:"Pudu BellaBot",mfr:"pudu-robotics",cat:"hospitality",price:15000,year:2022,status:"active",desc:"Cat-themed food delivery robot beloved by diners worldwide. Expressive LED cat face reacts to touch and interaction. Multi-modal navigation in crowded restaurants. 40kg payload across 4 trays. 600,000+ units shipped globally.",specs:{height_cm:100,weight_kg:36,trays:4,payload_kg:40,battery_hrs:10,nav:"LiDAR + depth camera",units_shipped:"600K+",face:"Expressive LED cat face"},score:cs({performance:80,reliability:80,ease_of_use:90,intelligence:76,value:85,ecosystem:75,safety:82,design:88}),breakdown:{performance:80,reliability:80,ease_of_use:90,intelligence:76,value:85,ecosystem:75,safety:82,design:88}},
  {slug:"pudu-kettybot",name:"Pudu KettyBot",mfr:"pudu-robotics",cat:"hospitality",price:20000,year:2023,status:"active",desc:"Premium service robot with 18.5-inch advertising display. Combines food delivery with digital signage and customer interaction. Greeting, delivery, and promotional functions. Multi-floor capability via elevator integration.",specs:{height_cm:120,weight_kg:45,trays:2,display_inch:18.5,payload_kg:30,battery_hrs:8,nav:"PUDU SLAM 2.0",elevator_integration:true},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:78,value:78,ecosystem:72,safety:82,design:85}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:78,value:78,ecosystem:72,safety:82,design:85}},
  {slug:"richtech-adam",name:"Richtech Adam",mfr:"richtech-robotics",cat:"hospitality",price:null,year:2024,status:"active",desc:"Dual-arm barista and bartender robot. Makes coffee, cocktails, and boba tea autonomously. Two 6-DOF arms with grippers handle cups, bottles, and dispensers. Deployed in hotels, airports, and convention centers.",specs:{arms:2,arm_dof:6,drinks:"Coffee, cocktails, boba",prep_time_min:2,height_cm:160,weight_kg:120,deployments:"Hotels, airports, events"},score:cs({performance:82,reliability:76,ease_of_use:80,intelligence:78,value:72,ecosystem:60,safety:80,design:85}),breakdown:{performance:82,reliability:76,ease_of_use:80,intelligence:78,value:72,ecosystem:60,safety:80,design:85}},
  {slug:"relay-savioke",name:"Relay by Savioke",mfr:"savioke",cat:"hospitality",price:null,year:2019,status:"active",desc:"Hotel delivery robot that autonomously navigates to guest rooms. Delivers amenities, snacks, and toiletries. Integrates with hotel PMS and elevator systems. Used in 1000+ hotels worldwide including Marriott and Hilton.",specs:{height_cm:91,weight_kg:45,compartment_l:25,battery_hrs:12,nav:"LiDAR SLAM",elevator:"Automatic integration",deployments:"1000+ hotels"},score:cs({performance:78,reliability:82,ease_of_use:88,intelligence:76,value:76,ecosystem:70,safety:84,design:78}),breakdown:{performance:78,reliability:82,ease_of_use:88,intelligence:76,value:76,ecosystem:70,safety:84,design:78}},
  {slug:"lg-cloi-servebot",name:"LG CLOi ServeBot",mfr:"lg-electronics",cat:"hospitality",price:null,year:2023,status:"active",desc:"LG's commercial service robot for restaurants and hotels. Three-tier tray system for food delivery. LG ThinQ ecosystem integration. Voice guidance and customizable LED display.",specs:{height_cm:105,weight_kg:50,trays:3,payload_kg:30,battery_hrs:10,nav:"LiDAR + 3D camera",ecosystem:"LG ThinQ"},score:cs({performance:78,reliability:80,ease_of_use:84,intelligence:76,value:74,ecosystem:78,safety:82,design:80}),breakdown:{performance:78,reliability:80,ease_of_use:84,intelligence:76,value:74,ecosystem:78,safety:82,design:80}},
  {slug:"softbank-pepper-2024",name:"SoftBank Pepper (2024)",mfr:"softbank-robotics",cat:"hospitality",price:null,year:2024,status:"active",desc:"Updated version of the iconic social robot. Enhanced AI with LLM integration for natural conversation. Deployed in retail, hospitality, and healthcare for customer interaction, wayfinding, and information services.",specs:{height_cm:121,weight_kg:28,dof:20,battery_hrs:12,display_inch:10.1,ai:"LLM-powered conversation",applications:"Retail, hospitality, healthcare"},score:cs({performance:68,reliability:72,ease_of_use:85,intelligence:80,value:65,ecosystem:70,safety:80,design:82}),breakdown:{performance:68,reliability:72,ease_of_use:85,intelligence:80,value:65,ecosystem:70,safety:80,design:82}},
  {slug:"softbank-whiz",name:"SoftBank Whiz",mfr:"softbank-robotics",cat:"hospitality",price:null,year:2021,status:"active",desc:"Commercial vacuum cleaning robot for offices, hotels, and retail. Brain Corp AI navigation. Learns cleaning routes from a single manual demonstration. Covers up to 15,000 sq ft per charge.",specs:{coverage_sqft:15000,battery_hrs:3,nav:"Brain Corp BrainOS",learning:"Single-pass route learning",dustbin_l:5,noise_db:62},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:76,value:74,ecosystem:72,safety:82,design:72}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:76,value:74,ecosystem:72,safety:82,design:72}},
  {slug:"avidbots-neo-2",name:"Avidbots Neo 2",mfr:"avidbots",cat:"hospitality",price:null,year:2024,status:"active",desc:"Autonomous commercial floor scrubbing robot. AI-powered navigation handles complex environments. Cleans up to 30,000 sq ft per hour. Used in airports, malls, hospitals, and warehouses. Real-time performance dashboard.",specs:{coverage_sqft_hr:30000,battery_hrs:6,nav:"AI + LiDAR SLAM",cleaning:"Scrub + vacuum + dry",width_cm:75,water_tank_l:110},score:cs({performance:84,reliability:82,ease_of_use:84,intelligence:80,value:76,ecosystem:72,safety:82,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:84,intelligence:80,value:76,ecosystem:72,safety:82,design:76}},
  {slug:"brain-corp-fleet",name:"Brain Corp Fleet (BrainOS)",mfr:"brain-corp",cat:"hospitality",price:null,year:2024,status:"active",desc:"AI platform powering 30,000+ autonomous commercial cleaning robots worldwide. BrainOS provides navigation, fleet management, and analytics to OEM cleaning machines. Used in Walmart, Kroger, and airports globally.",specs:{fleet_size:"30,000+ robots",partners:"Walmart, Kroger, airports",platform:"BrainOS AI",capabilities:"Navigation, fleet management, analytics",oem_partners:"ICE, Tennant, Nilfisk"},score:cs({performance:82,reliability:84,ease_of_use:82,intelligence:82,value:78,ecosystem:85,safety:82,design:70}),breakdown:{performance:82,reliability:84,ease_of_use:82,intelligence:82,value:78,ecosystem:85,safety:82,design:70}},
  {slug:"gaussian-robotics-scrubber",name:"Gaussian Robotics Scrubber 50",mfr:"gaussian-robotics",cat:"hospitality",price:25000,year:2023,status:"active",desc:"Autonomous commercial floor scrubbing robot from leading Chinese cleaning robotics company. Used in 2000+ locations across 30 countries. AI navigation with dynamic obstacle avoidance. Auto-fill and auto-drain water systems.",specs:{coverage_sqm_hr:2500,battery_hrs:5,nav:"AI SLAM + depth camera",cleaning:"Scrub + squeegee + vacuum",water_auto:true,deployments:"2000+ locations"},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:78,value:82,ecosystem:68,safety:80,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:78,value:82,ecosystem:68,safety:80,design:72}},
  {slug:"keenon-t8",name:"Keenon T8",mfr:"keenon-robotics",cat:"hospitality",price:12000,year:2023,status:"active",desc:"Multi-purpose service robot for hotels and restaurants. Food delivery, room service, and lobby concierge. Elevator integration for multi-floor service. Compact design navigates narrow corridors.",specs:{height_cm:130,weight_kg:48,compartments:4,payload_kg:40,battery_hrs:12,nav:"SLAM + depth camera",elevator:true},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:76,value:84,ecosystem:70,safety:82,design:76}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:76,value:84,ecosystem:70,safety:82,design:76}},
  {slug:"keenon-dinerbot-t10",name:"Keenon Dinerbot T10",mfr:"keenon-robotics",cat:"hospitality",price:18000,year:2024,status:"active",desc:"Premium restaurant delivery robot with AI-powered face and voice interaction. 10.1-inch display for promotions and menus. Enhanced perception for crowded dining environments. Supports table-to-table delivery patterns.",specs:{height_cm:132,weight_kg:52,trays:4,display_inch:10.1,payload_kg:40,battery_hrs:10,nav:"SLAM + 3D vision",ai_interaction:"Voice + face recognition"},score:cs({performance:80,reliability:80,ease_of_use:86,intelligence:80,value:80,ecosystem:72,safety:82,design:82}),breakdown:{performance:80,reliability:80,ease_of_use:86,intelligence:80,value:80,ecosystem:72,safety:82,design:82}},
  {slug:"ubtech-aimbot",name:"UBTECH Aimbot",mfr:"ubtech-robotics",cat:"hospitality",price:null,year:2023,status:"active",desc:"Smart disinfection and service robot. UV-C disinfection, temperature screening, and mask detection. Deployed in schools, hospitals, and government buildings across Asia. Multi-function platform.",specs:{height_cm:140,weight_kg:60,uv_c:true,temp_screening:true,mask_detection:true,battery_hrs:8,nav:"LiDAR SLAM"},score:cs({performance:74,reliability:78,ease_of_use:80,intelligence:76,value:72,ecosystem:68,safety:84,design:74}),breakdown:{performance:74,reliability:78,ease_of_use:80,intelligence:76,value:72,ecosystem:68,safety:84,design:74}},
  {slug:"orion-star-mini",name:"Orion Star Mini",mfr:"orion-star",cat:"hospitality",price:8000,year:2023,status:"active",desc:"Compact service robot for restaurants and cafes. Built by Cheetah Mobile subsidiary. Affordable entry point for small restaurants. Multi-tray delivery with simple tablet-based management.",specs:{height_cm:95,weight_kg:30,trays:3,payload_kg:30,battery_hrs:8,nav:"LiDAR",management:"Tablet-based"},score:cs({performance:72,reliability:74,ease_of_use:86,intelligence:70,value:88,ecosystem:58,safety:78,design:72}),breakdown:{performance:72,reliability:74,ease_of_use:86,intelligence:70,value:88,ecosystem:58,safety:78,design:72}},
];

// ═══════════════════════════════════════════════════════════════

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 5 Import: 50 New Robots");
  console.log("  20 Humanoid + 15 Security + 15 Hospitality");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await sb.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await sb.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await sb.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await sb.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await sb.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await sb.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"=".repeat(50)}`);
  console.log(`Wave 5 Import Summary`);
  console.log(`${"=".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"=".repeat(50)}`);
}

main().catch(console.error);
