/**
 * Robotomated — Wave 12 Robot Import: 50 New Robots
 * Focus: CONSTRUCTION, AGRICULTURAL, DELIVERY gap-filling.
 *
 * Run: npx tsx scripts/import-robots-wave12.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  // Construction
  { slug: "built-robotics", name: "Built Robotics", country: "US", founded_year: 2016, website: "https://builtrobotics.com" },
  { slug: "canvas-construction", name: "Canvas Construction", country: "US", founded_year: 2017, website: "https://canvas.build" },
  { slug: "dusty-robotics", name: "Dusty Robotics", country: "US", founded_year: 2018, website: "https://dustyrobotics.com" },
  { slug: "hilti", name: "Hilti", country: "LI", founded_year: 1941, website: "https://hilti.com" },
  { slug: "advanced-construction-robotics", name: "Advanced Construction Robotics", country: "US", founded_year: 2016, website: "https://constructionrobots.com" },
  { slug: "scaled-robotics", name: "Scaled Robotics", country: "ES", founded_year: 2018, website: "https://scaledrobotics.com" },
  // Agricultural
  { slug: "naio-technologies", name: "Na\u00efo Technologies", country: "FR", founded_year: 2011, website: "https://naio-technologies.com" },
  { slug: "monarch-tractor", name: "Monarch Tractor", country: "US", founded_year: 2018, website: "https://monarchtractor.com" },
  { slug: "carbon-robotics", name: "Carbon Robotics", country: "US", founded_year: 2018, website: "https://carbonrobotics.com" },
  { slug: "farmwise", name: "FarmWise", country: "US", founded_year: 2016, website: "https://farmwise.io" },
  // Delivery
  { slug: "tortoise", name: "Tortoise", country: "US", founded_year: 2019, website: "https://tortoise.dev" },
  { slug: "ottonomy", name: "Ottonomy", country: "US", founded_year: 2020, website: "https://ottonomy.io" },
  { slug: "coco-delivery", name: "Coco", country: "US", founded_year: 2020, website: "https://cocodelivery.com" },
  { slug: "kiwibot", name: "Kiwibot", country: "CO", founded_year: 2017, website: "https://kiwibot.com" },
  { slug: "serve-robotics", name: "Serve Robotics", country: "US", founded_year: 2021, website: "https://serverobotics.com" },
];

// ═══════════════════════════════════════════════════════════════
// ROBOTS — 50 total (20 construction, 15 agricultural, 15 delivery)
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

// ═══ CONSTRUCTION (20) ═══
{slug:"built-excavator",name:"Built Robotics Autonomous Excavator",mfr:"built-robotics",cat:"construction",price:350000,year:2024,status:"active",desc:"Fully autonomous excavator retrofit by Built Robotics. Uses GPS, LiDAR, and IMU to execute dig plans without a human operator. Handles mass excavation, trenching, and backfill on commercial sites.",specs:{type:"Autonomous excavator retrofit",nav:"RTK GPS + LiDAR + IMU",tasks:"Mass excavation, trenching, backfill",autonomy:"Fully autonomous dig cycles",safety:"Geo-fenced exclusion zones",operating_weight_tons:20},score:cs({performance:82,reliability:78,ease_of_use:70,intelligence:84,value:68,ecosystem:60,safety:80,design:70}),breakdown:{performance:82,reliability:78,ease_of_use:70,intelligence:84,value:68,ecosystem:60,safety:80,design:70}},
{slug:"built-dozer",name:"Built Robotics Autonomous Dozer",mfr:"built-robotics",cat:"construction",price:400000,year:2024,status:"active",desc:"Autonomous bulldozer system from Built Robotics. Converts standard dozers to autonomous grading machines. Achieves finish-grade accuracy within 2cm using GPS-guided blade control.",specs:{type:"Autonomous dozer retrofit",accuracy_cm:2,nav:"RTK GPS + blade control",tasks:"Rough grading, finish grading, spreading",autonomy:"Fully autonomous grading cycles",operating_weight_tons:25},score:cs({performance:80,reliability:76,ease_of_use:68,intelligence:82,value:66,ecosystem:60,safety:78,design:68}),breakdown:{performance:80,reliability:76,ease_of_use:68,intelligence:82,value:66,ecosystem:60,safety:78,design:68}},
{slug:"built-compact-loader",name:"Built Robotics Compact Track Loader",mfr:"built-robotics",cat:"construction",price:280000,year:2024,status:"active",desc:"Autonomous compact track loader from Built Robotics. Handles material loading, site clearing, and grading tasks. Smaller form factor for tight residential and commercial job sites.",specs:{type:"Autonomous compact track loader",nav:"RTK GPS + LiDAR",tasks:"Loading, clearing, grading",form_factor:"Compact — tight site access",operating_weight_tons:5,autonomy:"Supervised autonomy"},score:cs({performance:76,reliability:74,ease_of_use:72,intelligence:78,value:70,ecosystem:58,safety:78,design:70}),breakdown:{performance:76,reliability:74,ease_of_use:72,intelligence:78,value:70,ecosystem:58,safety:78,design:70}},
{slug:"canvas-drywall",name:"Canvas Drywall Robot",mfr:"canvas-construction",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous drywall finishing robot. Applies joint compound and skim coats to drywall surfaces with consistent quality. Reduces drywall finishing labor by 50% while improving consistency. Available as $150K/yr lease.",specs:{application:"Drywall taping and finishing",method:"Robotic arm + compound applicator",coverage_sqft_hr:800,finish_quality:"Level 4-5 finish",lease_annual:150000,consistency:"Sub-millimeter uniformity"},score:cs({performance:78,reliability:76,ease_of_use:74,intelligence:76,value:72,ecosystem:55,safety:80,design:72}),breakdown:{performance:78,reliability:76,ease_of_use:74,intelligence:76,value:72,ecosystem:55,safety:80,design:72}},
{slug:"dusty-fieldprinter",name:"Dusty Robotics FieldPrinter",mfr:"dusty-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous BIM-to-field layout robot. Prints full-scale floor plans directly onto concrete from BIM models. Replaces manual chalk-line layout, reducing layout time by 10x. Monthly subscription at $5,000/mo.",specs:{application:"BIM layout printing",accuracy_mm:1.5,speed:"10x manual layout",input:"BIM/Revit models",output:"Printed floor plans on concrete",subscription_monthly:5000},score:cs({performance:86,reliability:82,ease_of_use:84,intelligence:82,value:78,ecosystem:72,safety:85,design:78}),breakdown:{performance:86,reliability:82,ease_of_use:84,intelligence:82,value:78,ecosystem:72,safety:85,design:78}},
{slug:"dusty-fieldprinter-2",name:"Dusty Robotics FieldPrinter 2.0",mfr:"dusty-robotics",cat:"construction",price:null,year:2025,status:"active",desc:"Second-generation BIM layout robot with enhanced speed and multi-color printing. Prints different trade layouts in distinct colors. Improved battery life and outdoor capability. $6,000/mo subscription.",specs:{application:"Multi-color BIM layout",accuracy_mm:1.0,speed:"15x manual layout",colors:"Multi-color trade differentiation",battery_hrs:10,outdoor_capable:true,subscription_monthly:6000},score:cs({performance:88,reliability:84,ease_of_use:86,intelligence:84,value:76,ecosystem:74,safety:86,design:80}),breakdown:{performance:88,reliability:84,ease_of_use:86,intelligence:84,value:76,ecosystem:74,safety:86,design:80}},
{slug:"hilti-jaibot-w12",name:"Hilti Jaibot",mfr:"hilti",cat:"construction",price:75000,year:2023,status:"active",desc:"Semi-autonomous ceiling drilling robot from Hilti. Drills holes for MEP installations from BIM coordinates. Reduces overhead drilling labor by 4x and eliminates repetitive strain injuries for workers.",specs:{application:"Ceiling drilling for MEP",accuracy_mm:5,bim_integration:true,drills_per_charge:500,productivity:"4x manual labor",ergonomic:"Eliminates overhead strain"},score:cs({performance:80,reliability:82,ease_of_use:76,intelligence:80,value:74,ecosystem:70,safety:84,design:74}),breakdown:{performance:80,reliability:82,ease_of_use:76,intelligence:80,value:74,ecosystem:70,safety:84,design:74}},
{slug:"hilti-buildbot",name:"Hilti BIM-guided Layout Bot",mfr:"hilti",cat:"construction",price:50000,year:2024,status:"active",desc:"BIM-guided construction layout robot from Hilti. Projects and marks reference points on floors and walls directly from BIM models. Integrates with Hilti ON!Track asset management.",specs:{application:"BIM construction layout",accuracy_mm:2,projection:"Laser + ink marking",bim:"Direct Revit/IFC import",integration:"Hilti ON!Track",marking:"Floor and wall"},score:cs({performance:78,reliability:80,ease_of_use:80,intelligence:78,value:76,ecosystem:72,safety:82,design:76}),breakdown:{performance:78,reliability:80,ease_of_use:80,intelligence:78,value:76,ecosystem:72,safety:82,design:76}},
{slug:"acr-ironbot",name:"ACR IronBot",mfr:"advanced-construction-robotics",cat:"construction",price:120000,year:2024,status:"active",desc:"Autonomous rebar tying robot for slab-on-grade construction. Navigates rebar grids and ties intersections automatically. Reduces rebar tying labor by 5x while improving worker safety.",specs:{application:"Slab rebar tying",speed:"5x manual tying",nav:"GPS + rebar grid detection",ties_per_hour:1100,safety:"Eliminates worker bending",terrain:"Rebar grid traversal"},score:cs({performance:82,reliability:78,ease_of_use:74,intelligence:76,value:78,ecosystem:56,safety:84,design:68}),breakdown:{performance:82,reliability:78,ease_of_use:74,intelligence:76,value:78,ecosystem:56,safety:84,design:68}},
{slug:"acr-tybot",name:"ACR TyBot",mfr:"advanced-construction-robotics",cat:"construction",price:200000,year:2023,status:"active",desc:"Autonomous rebar tying robot for bridge decks. Suspended from a gantry system, TyBot traverses bridge deck rebar and ties intersections. Deployed on 100+ bridge projects across the US.",specs:{application:"Bridge deck rebar tying",method:"Gantry-suspended autonomous",ties_per_hour:1000,projects_completed:100,span:"Full bridge deck width",safety:"Zero worker exposure on deck"},score:cs({performance:84,reliability:80,ease_of_use:72,intelligence:78,value:74,ecosystem:58,safety:88,design:70}),breakdown:{performance:84,reliability:80,ease_of_use:72,intelligence:78,value:74,ecosystem:58,safety:88,design:70}},
{slug:"scaled-scout",name:"Scaled Robotics Scout",mfr:"scaled-robotics",cat:"construction",price:45000,year:2024,status:"active",desc:"Autonomous construction quality scanning robot. Navigates job sites and creates 3D as-built scans compared against BIM. Detects deviations, missing elements, and quality issues automatically.",specs:{application:"Construction quality scanning",scanning:"3D LiDAR + photogrammetry",comparison:"BIM vs as-built",detection:"Deviation + defect",nav:"Autonomous site navigation",accuracy_mm:3},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:84,value:80,ecosystem:64,safety:80,design:76}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:84,value:80,ecosystem:64,safety:80,design:76}},
{slug:"okibo-plaster",name:"Okibo Plastering Robot",mfr:"okibo",cat:"construction",price:85000,year:2024,status:"active",desc:"Autonomous wall plastering robot from Israel. Scans wall surfaces with LiDAR, calculates optimal plaster thickness, and applies plaster uniformly. 5x faster than manual plastering.",specs:{application:"Wall plastering",speed:"5x manual",scanning:"LiDAR surface scan",plaster_type:"Standard + gypsum",coverage_sqm_hr:60,uniformity:"Sub-millimeter thickness control"},score:cs({performance:76,reliability:74,ease_of_use:76,intelligence:76,value:76,ecosystem:52,safety:78,design:72}),breakdown:{performance:76,reliability:74,ease_of_use:76,intelligence:76,value:76,ecosystem:52,safety:78,design:72}},
{slug:"baubot-main",name:"Baubot",mfr:"baubot",cat:"construction",price:200000,year:2023,status:"active",desc:"Multi-function mobile construction robot from Austria. Modular platform handles drilling, 3D printing, welding, and material handling. Tracked base navigates rough construction terrain.",specs:{application:"Multi-function construction",functions:"Drilling, 3D printing, welding, handling",base:"Tracked mobile platform",reach_m:3,payload_kg:50,programming:"Tablet interface"},score:cs({performance:78,reliability:72,ease_of_use:70,intelligence:74,value:68,ecosystem:54,safety:76,design:72}),breakdown:{performance:78,reliability:72,ease_of_use:70,intelligence:74,value:68,ecosystem:54,safety:76,design:72}},
{slug:"shimizu-robo-carrier",name:"Shimizu Robo-Carrier",mfr:"shimizu",cat:"construction",price:180000,year:2023,status:"active",desc:"Autonomous heavy material transport robot by Shimizu Corporation. Navigates multi-floor construction sites via elevators. Carries steel beams, drywall stacks, and mechanical equipment to installation points.",specs:{application:"Heavy material transport",payload_kg:500,nav:"Autonomous multi-floor",elevator:"Autonomous elevator use",materials:"Steel, drywall, mechanical",speed_kmh:3},score:cs({performance:76,reliability:74,ease_of_use:68,intelligence:74,value:66,ecosystem:56,safety:80,design:66}),breakdown:{performance:76,reliability:74,ease_of_use:68,intelligence:74,value:66,ecosystem:56,safety:80,design:66}},
{slug:"fbr-hadrian-x",name:"FBR Hadrian X",mfr:"fbr",cat:"construction",price:500000,year:2024,status:"active",desc:"Autonomous bricklaying robot from Australian company FBR. 30m telescopic boom places blocks at up to 200 blocks/hour. Handles cutting, routing, and adhesive application. Wind compensation system.",specs:{application:"Autonomous bricklaying",speed:"200 blocks/hour",boom_m:30,adhesive:"Automated application",cutting:"Integrated block cutting",wind_compensation:true},score:cs({performance:82,reliability:74,ease_of_use:66,intelligence:80,value:62,ecosystem:52,safety:78,design:74}),breakdown:{performance:82,reliability:74,ease_of_use:66,intelligence:80,value:62,ecosystem:52,safety:78,design:74}},
{slug:"printstones-bam",name:"Printstones BAM",mfr:"printstones",cat:"construction",price:350000,year:2024,status:"active",desc:"Autonomous bricklaying mobile robot. Uses a robotic arm on a tracked mobile base to lay bricks with mortar autonomously. Computer vision ensures precise placement and alignment.",specs:{application:"Mobile autonomous bricklaying",method:"Robotic arm on tracked base",vision:"Computer vision alignment",mortar:"Automated application",speed:"100 bricks/hour",mobility:"Self-propelled tracked"},score:cs({performance:74,reliability:70,ease_of_use:68,intelligence:76,value:66,ecosystem:50,safety:76,design:70}),breakdown:{performance:74,reliability:70,ease_of_use:68,intelligence:76,value:66,ecosystem:50,safety:76,design:70}},
{slug:"apis-cor-3d",name:"Apis Cor 3D Printer",mfr:"apis-cor",cat:"construction",price:300000,year:2023,status:"active",desc:"Mobile construction 3D printer. Prints building structures on-site using specialized concrete mixture. Printed a 400 sq ft house in under 24 hours. Suitable for walls, foundations, and custom architectural shapes.",specs:{application:"Construction 3D printing",material:"Specialized concrete mix",print_speed_sqft_day:400,structure:"Walls, foundations, shapes",setup_time_hrs:2,portability:"Crane-deployable mobile"},score:cs({performance:74,reliability:70,ease_of_use:64,intelligence:72,value:70,ecosystem:50,safety:74,design:76}),breakdown:{performance:74,reliability:70,ease_of_use:64,intelligence:72,value:70,ecosystem:50,safety:74,design:76}},
{slug:"icon-vulcan",name:"ICON Vulcan",mfr:"icon",cat:"construction",price:800000,year:2024,status:"active",desc:"Large-scale construction 3D printer from ICON. Prints entire homes using Lavacrete material. Partnered with NASA for lunar construction. Printed 100+ homes in community developments.",specs:{application:"Large-scale 3D home printing",material:"Lavacrete proprietary concrete",print_area_sqft:3000,homes_printed:100,partners:"NASA, Lennar, BIG",speed:"Walls of a home in days"},score:cs({performance:86,reliability:78,ease_of_use:62,intelligence:82,value:64,ecosystem:66,safety:78,design:82}),breakdown:{performance:86,reliability:78,ease_of_use:62,intelligence:82,value:64,ecosystem:66,safety:78,design:82}},
{slug:"tiger-stone-paver",name:"Tiger Stone Paver",mfr:"tiger-stone",cat:"construction",price:120000,year:2023,status:"active",desc:"Road brick paving machine from the Netherlands. Workers feed bricks into the top, and the machine lays them in pattern on the road surface as it slowly advances. Lays 400 sqm/day.",specs:{application:"Road brick laying",method:"Gravity-fed pattern laying",speed_sqm_day:400,patterns:"Herringbone, stretcher, basket",crew_needed:3,road_width_m:6},score:cs({performance:78,reliability:82,ease_of_use:78,intelligence:58,value:80,ecosystem:52,safety:80,design:72}),breakdown:{performance:78,reliability:82,ease_of_use:78,intelligence:58,value:80,ecosystem:52,safety:80,design:72}},
{slug:"robovent-hvac",name:"RoboVent HVAC Install",mfr:"robovent",cat:"construction",price:95000,year:2024,status:"active",desc:"Robotic ductwork installation assistant. Lifts, positions, and holds HVAC ductwork sections for connection. Reduces the need for scissor lifts and multiple workers for overhead duct installation.",specs:{application:"HVAC ductwork installation",lift_capacity_kg:80,reach_m:4,positioning:"Laser-guided alignment",method:"Lift, hold, and position",safety:"Eliminates overhead manual lifting"},score:cs({performance:72,reliability:74,ease_of_use:72,intelligence:68,value:74,ecosystem:50,safety:82,design:66}),breakdown:{performance:72,reliability:74,ease_of_use:72,intelligence:68,value:74,ecosystem:50,safety:82,design:66}},

// ═══ AGRICULTURAL (15) ═══
{slug:"naio-oz",name:"Na\u00efo Oz",mfr:"naio-technologies",cat:"agricultural",price:35000,year:2023,status:"active",desc:"Compact autonomous weeding robot from Na\u00efo Technologies. Designed for market gardens and small-scale vegetable farms. Mechanical weeding between crop rows using RTK GPS guidance.",specs:{application:"Market garden weeding",method:"Mechanical inter-row weeding",nav:"RTK GPS + camera",row_spacing_cm:"50-80",battery_hrs:8,weight_kg:150,area_ha_day:1},score:cs({performance:72,reliability:76,ease_of_use:80,intelligence:72,value:82,ecosystem:62,safety:82,design:76}),breakdown:{performance:72,reliability:76,ease_of_use:80,intelligence:72,value:82,ecosystem:62,safety:82,design:76}},
{slug:"naio-dino",name:"Na\u00efo Dino",mfr:"naio-technologies",cat:"agricultural",price:85000,year:2024,status:"active",desc:"Large-scale autonomous weeding robot for open-field vegetable farming. Straddle design allows weeding across wide beds. Handles lettuce, onion, carrot, and other row crops at scale.",specs:{application:"Large-scale vegetable weeding",method:"Mechanical + camera-guided intra-row",width_m:2.5,crops:"Lettuce, onion, carrot, beet",nav:"RTK GPS + AI vision",area_ha_day:5,weight_kg:800},score:cs({performance:80,reliability:78,ease_of_use:76,intelligence:80,value:76,ecosystem:64,safety:82,design:74}),breakdown:{performance:80,reliability:78,ease_of_use:76,intelligence:80,value:76,ecosystem:64,safety:82,design:74}},
{slug:"naio-ted",name:"Na\u00efo Ted",mfr:"naio-technologies",cat:"agricultural",price:65000,year:2023,status:"active",desc:"Autonomous vineyard robot from Na\u00efo Technologies. Straddles vine rows for mechanical weeding, mowing, and soil work. GPS-guided autonomous operation in structured vineyard environments.",specs:{application:"Vineyard weeding and mowing",method:"Mechanical under-vine weeding",nav:"RTK GPS + row following",row_spacing_m:"1.5-2.5",battery_hrs:8,terrain:"Vineyard slopes up to 15%"},score:cs({performance:76,reliability:76,ease_of_use:78,intelligence:74,value:78,ecosystem:62,safety:80,design:76}),breakdown:{performance:76,reliability:76,ease_of_use:78,intelligence:74,value:78,ecosystem:62,safety:80,design:76}},
{slug:"monarch-mk-v",name:"Monarch MK-V",mfr:"monarch-tractor",cat:"agricultural",price:78000,year:2024,status:"active",desc:"Fully electric autonomous tractor from Monarch Tractor. 70hp equivalent with driver-optional autonomy. Collects crop and implement data during operation. Compatible with standard PTO implements.",specs:{power_hp:70,drivetrain:"Fully electric",autonomy:"Driver-optional",implements:"Standard 3-point hitch + PTO",data:"Crop intelligence collection",battery_hrs:10,weight_kg:3200},score:cs({performance:80,reliability:76,ease_of_use:82,intelligence:84,value:76,ecosystem:68,safety:82,design:80}),breakdown:{performance:80,reliability:76,ease_of_use:82,intelligence:84,value:76,ecosystem:68,safety:82,design:80}},
{slug:"monarch-mk-v-plus",name:"Monarch MK-V+",mfr:"monarch-tractor",cat:"agricultural",price:95000,year:2025,status:"active",desc:"Premium version of Monarch's electric autonomous tractor. Enhanced battery capacity for all-day operation. Advanced perception suite with thermal imaging for livestock and wildlife detection.",specs:{power_hp:70,drivetrain:"Fully electric",autonomy:"Full autonomous",battery_hrs:14,perception:"Thermal + RGB + LiDAR",implements:"Standard 3-point hitch + PTO",data:"Enhanced crop analytics"},score:cs({performance:84,reliability:78,ease_of_use:84,intelligence:86,value:72,ecosystem:70,safety:84,design:82}),breakdown:{performance:84,reliability:78,ease_of_use:84,intelligence:86,value:72,ecosystem:70,safety:84,design:82}},
{slug:"carbon-laserweeder",name:"Carbon Robotics LaserWeeder",mfr:"carbon-robotics",cat:"agricultural",price:185000,year:2024,status:"active",desc:"AI-powered laser weeding machine from Carbon Robotics. Uses 30 high-power CO2 lasers and deep learning to identify and eliminate weeds without chemicals. Processes 15-20 acres per day.",specs:{application:"Laser weeding",lasers:30,laser_type:"CO2 thermal",vision:"Deep learning weed ID",accuracy:"Sub-inch targeting",acres_per_day:20,chemical_free:true},score:cs({performance:86,reliability:78,ease_of_use:74,intelligence:88,value:74,ecosystem:60,safety:76,design:78}),breakdown:{performance:86,reliability:78,ease_of_use:74,intelligence:88,value:74,ecosystem:60,safety:76,design:78}},
{slug:"carbon-laserweeder-mini",name:"Carbon Robotics LaserWeeder Mini",mfr:"carbon-robotics",cat:"agricultural",price:120000,year:2025,status:"active",desc:"Compact version of the LaserWeeder for smaller farms and specialty crops. 12 laser units optimized for bed-width vegetable operations. Lower price point makes laser weeding accessible to mid-size farms.",specs:{application:"Compact laser weeding",lasers:12,laser_type:"CO2 thermal",vision:"Deep learning weed ID",width_m:1.8,acres_per_day:8,chemical_free:true},score:cs({performance:80,reliability:76,ease_of_use:76,intelligence:86,value:78,ecosystem:58,safety:76,design:76}),breakdown:{performance:80,reliability:76,ease_of_use:76,intelligence:86,value:78,ecosystem:58,safety:76,design:76}},
{slug:"farmwise-vulcan",name:"FarmWise Vulcan",mfr:"farmwise",cat:"agricultural",price:250000,year:2024,status:"active",desc:"Autonomous precision weeding machine from FarmWise. Uses AI vision to distinguish crops from weeds and removes weeds mechanically with micro-precision blades. Zero chemical residue.",specs:{application:"Precision mechanical weeding",method:"AI-guided micro blades",vision:"Deep learning crop/weed classification",rows:12,speed_mph:5,chemical_free:true,acres_per_day:25},score:cs({performance:84,reliability:76,ease_of_use:72,intelligence:86,value:68,ecosystem:58,safety:78,design:74}),breakdown:{performance:84,reliability:76,ease_of_use:72,intelligence:86,value:68,ecosystem:58,safety:78,design:74}},
{slug:"aigen-model-a",name:"Aigen Model A",mfr:"aigen",cat:"agricultural",price:null,year:2024,status:"active",desc:"Solar-powered autonomous weeding robot from Aigen. Operates indefinitely on solar power for continuous field coverage. AI vision identifies weeds and removes them mechanically. Available at $1,200/mo subscription.",specs:{application:"Solar-powered weeding",power:"100% solar",method:"Mechanical weed removal",vision:"AI weed identification",subscription_monthly:1200,autonomy:"Continuous solar operation",weight_kg:200},score:cs({performance:72,reliability:72,ease_of_use:82,intelligence:78,value:84,ecosystem:54,safety:82,design:78}),breakdown:{performance:72,reliability:72,ease_of_use:82,intelligence:78,value:84,ecosystem:54,safety:82,design:78}},
{slug:"ecorobotix-ara",name:"Ecorobotix ARA",mfr:"ecorobotix",cat:"agricultural",price:130000,year:2024,status:"active",desc:"Ultra-precision spot sprayer from Ecorobotix. AI cameras detect individual weeds and spray micro-doses, reducing herbicide use by 95%. Swiss-engineered for sugar beet, rapeseed, and vegetable crops.",specs:{application:"Ultra-precision spot spraying",reduction:"95% less herbicide",vision:"AI individual weed detection",nozzles:52,width_m:6,speed_kmh:7,crops:"Sugar beet, rapeseed, vegetables"},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:86,value:80,ecosystem:62,safety:84,design:78}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:86,value:80,ecosystem:62,safety:84,design:78}},
{slug:"swarmfarm-sb4",name:"SwarmFarm SB4",mfr:"swarmfarm",cat:"agricultural",price:95000,year:2024,status:"active",desc:"Autonomous swarm farming robot from Australia. Multiple small robots replace single large tractors for broadacre farming. Each unit handles spraying, weeding, or seeding with precision.",specs:{application:"Swarm broadacre farming",tasks:"Spraying, weeding, seeding",swarm:"Multi-robot coordination",weight_kg:600,width_m:6,nav:"RTK GPS + AI",power:"Diesel-electric hybrid"},score:cs({performance:78,reliability:74,ease_of_use:70,intelligence:80,value:76,ecosystem:58,safety:78,design:72}),breakdown:{performance:78,reliability:74,ease_of_use:70,intelligence:80,value:76,ecosystem:58,safety:78,design:72}},
{slug:"agerris-digital-farmhand",name:"Agerris Digital Farmhand",mfr:"agerris",cat:"agricultural",price:110000,year:2024,status:"active",desc:"Multi-task autonomous farm robot from Australian company Agerris. Handles weeding, spraying, crop scouting, and data collection. Modular implement system for different farm tasks.",specs:{application:"Multi-task farming",tasks:"Weeding, spraying, scouting, data",nav:"RTK GPS + stereo vision",implements:"Modular quick-swap",weight_kg:500,battery_hrs:12,crops:"Broadacre + horticulture"},score:cs({performance:76,reliability:74,ease_of_use:74,intelligence:78,value:74,ecosystem:56,safety:80,design:72}),breakdown:{performance:76,reliability:74,ease_of_use:74,intelligence:78,value:74,ecosystem:56,safety:80,design:72}},
{slug:"burro-grande",name:"Burro Grande",mfr:"burro",cat:"agricultural",price:30000,year:2024,status:"active",desc:"Autonomous farm hauling robot from Burro. Follows workers through fields, carrying harvested produce. Person-following and autonomous return-to-base modes. Popular in table grape and berry operations.",specs:{application:"Autonomous farm hauling",payload_kg:270,following:"Person-following mode",return:"Autonomous RTB",crops:"Table grapes, berries, nursery",battery_hrs:10,speed_kmh:6},score:cs({performance:72,reliability:76,ease_of_use:88,intelligence:72,value:86,ecosystem:60,safety:84,design:74}),breakdown:{performance:72,reliability:76,ease_of_use:88,intelligence:72,value:86,ecosystem:60,safety:84,design:74}},
{slug:"harvest-croo-berry",name:"Harvest CROO Berry Harvester",mfr:"harvest-croo",cat:"agricultural",price:350000,year:2024,status:"active",desc:"Autonomous strawberry harvesting robot. Uses AI vision to identify ripe berries and gentle robotic pickers to harvest without bruising. Addresses critical labor shortages in berry farming.",specs:{application:"Strawberry harvesting",method:"AI vision + gentle robotic picking",berries_per_hour:8000,bruise_rate:"< 2%",pickers:16,nav:"Row-following autonomous",field_coverage_acres_day:8},score:cs({performance:78,reliability:72,ease_of_use:68,intelligence:82,value:64,ecosystem:52,safety:78,design:70}),breakdown:{performance:78,reliability:72,ease_of_use:68,intelligence:82,value:64,ecosystem:52,safety:78,design:70}},
{slug:"tortuga-berry",name:"Tortuga AgTech Berry Picker",mfr:"tortuga-agtech",cat:"agricultural",price:180000,year:2024,status:"active",desc:"Greenhouse strawberry harvesting robot from Tortuga AgTech. Operates in tabletop growing systems common in modern greenhouses. AI identifies ripeness and picks with soft grippers.",specs:{application:"Greenhouse strawberry picking",environment:"Tabletop greenhouse systems",method:"Soft gripper + AI ripeness detection",berries_per_hour:5000,accuracy:"95% ripe-only picking",nav:"Rail-guided greenhouse"},score:cs({performance:76,reliability:74,ease_of_use:72,intelligence:80,value:68,ecosystem:54,safety:80,design:72}),breakdown:{performance:76,reliability:74,ease_of_use:72,intelligence:80,value:68,ecosystem:54,safety:80,design:72}},

// ═══ DELIVERY (15) ═══
{slug:"tortoise-delivery",name:"Tortoise Delivery Robot",mfr:"tortoise",cat:"delivery",price:null,year:2024,status:"active",desc:"Sidewalk delivery robot with remote human oversight. Combines autonomous navigation with remote operator assistance for edge cases. Delivers food and groceries in residential neighborhoods. $3,500/mo.",specs:{application:"Sidewalk food/grocery delivery",nav:"Autonomous + remote operator backup",speed_kmh:6,payload_kg:20,range_km:5,subscription_monthly:3500,camera:"360-degree + depth"},score:cs({performance:72,reliability:74,ease_of_use:82,intelligence:74,value:72,ecosystem:60,safety:80,design:74}),breakdown:{performance:72,reliability:74,ease_of_use:82,intelligence:74,value:72,ecosystem:60,safety:80,design:74}},
{slug:"tortoise-grocery",name:"Tortoise Grocery Bot",mfr:"tortoise",cat:"delivery",price:null,year:2024,status:"active",desc:"Larger-capacity grocery delivery robot from Tortoise. Insulated compartments for temperature-sensitive items. Serves grocery chains and dark stores for last-mile residential delivery. $4,000/mo.",specs:{application:"Grocery delivery",payload_kg:35,compartments:"Insulated hot/cold",nav:"Autonomous + remote assist",range_km:8,subscription_monthly:4000,speed_kmh:6},score:cs({performance:74,reliability:74,ease_of_use:80,intelligence:74,value:70,ecosystem:60,safety:80,design:72}),breakdown:{performance:74,reliability:74,ease_of_use:80,intelligence:74,value:70,ecosystem:60,safety:80,design:72}},
{slug:"ottonomy-ottie",name:"Ottonomy Ottie",mfr:"ottonomy",cat:"delivery",price:null,year:2024,status:"active",desc:"Indoor/outdoor autonomous delivery robot. Operates in airports, malls, and campuses. UV-C sanitized cargo compartment. Deployed at Cincinnati/NKY and Rome Fiumicino airports. $2,500/mo.",specs:{application:"Indoor/outdoor delivery",environments:"Airports, malls, campuses",payload_kg:15,sanitization:"UV-C compartment",nav:"LiDAR + camera SLAM",subscription_monthly:2500,deployments:"CVG, FCO airports"},score:cs({performance:76,reliability:76,ease_of_use:84,intelligence:76,value:78,ecosystem:62,safety:82,design:78}),breakdown:{performance:76,reliability:76,ease_of_use:84,intelligence:76,value:78,ecosystem:62,safety:82,design:78}},
{slug:"ottonomy-yeti",name:"Ottonomy Yeti",mfr:"ottonomy",cat:"delivery",price:null,year:2024,status:"active",desc:"Last-mile outdoor delivery robot from Ottonomy. Weatherproof design for year-round sidewalk delivery. Larger cargo bay than Ottie for multi-order deliveries. $3,000/mo subscription.",specs:{application:"Last-mile outdoor delivery",payload_kg:25,weather:"All-weather IP65",nav:"LiDAR + GPS + camera",range_km:10,subscription_monthly:3000,speed_kmh:7},score:cs({performance:76,reliability:76,ease_of_use:82,intelligence:76,value:74,ecosystem:62,safety:82,design:76}),breakdown:{performance:76,reliability:76,ease_of_use:82,intelligence:76,value:74,ecosystem:62,safety:82,design:76}},
{slug:"coco-1",name:"Coco Delivery Robot",mfr:"coco-delivery",cat:"delivery",price:null,year:2024,status:"active",desc:"Remote-operated delivery robot for restaurant last-mile delivery in Los Angeles. Human operators provide real-time guidance via cameras. Partnered with 1,000+ restaurants. $2,000/mo.",specs:{application:"Restaurant food delivery",operation:"Remote human-guided",cameras:"Multi-angle live feed",partners:"1000+ LA restaurants",payload_kg:15,range_km:3,subscription_monthly:2000},score:cs({performance:70,reliability:76,ease_of_use:84,intelligence:68,value:78,ecosystem:64,safety:82,design:76}),breakdown:{performance:70,reliability:76,ease_of_use:84,intelligence:68,value:78,ecosystem:64,safety:82,design:76}},
{slug:"coco-2",name:"Coco 2",mfr:"coco-delivery",cat:"delivery",price:null,year:2025,status:"active",desc:"Second-generation Coco delivery robot with enhanced autonomy. Reduced remote operator intervention through improved AI. Expanded delivery radius and faster speeds. $2,500/mo.",specs:{application:"Enhanced food delivery",operation:"Hybrid autonomous + remote",autonomy:"70% autonomous, 30% remote assist",payload_kg:18,range_km:5,speed_kmh:8,subscription_monthly:2500},score:cs({performance:74,reliability:76,ease_of_use:84,intelligence:74,value:76,ecosystem:64,safety:82,design:78}),breakdown:{performance:74,reliability:76,ease_of_use:84,intelligence:74,value:76,ecosystem:64,safety:82,design:78}},
{slug:"kiwibot-s3",name:"Kiwibot S3",mfr:"kiwibot",cat:"delivery",price:null,year:2024,status:"active",desc:"Third-generation campus delivery robot from Colombian-founded Kiwibot. Deployed at 20+ US universities. Semi-autonomous with remote assist. Handles food delivery orders via app integration. $1,800/mo.",specs:{application:"Campus food delivery",deployments:"20+ US universities",nav:"Semi-autonomous + remote",payload_kg:10,speed_kmh:5,app_integration:true,subscription_monthly:1800},score:cs({performance:70,reliability:74,ease_of_use:86,intelligence:70,value:80,ecosystem:66,safety:80,design:78}),breakdown:{performance:70,reliability:74,ease_of_use:86,intelligence:70,value:80,ecosystem:66,safety:80,design:78}},
{slug:"kiwibot-s4",name:"Kiwibot S4",mfr:"kiwibot",cat:"delivery",price:null,year:2025,status:"active",desc:"Fourth-generation Kiwibot with improved autonomy and expanded capacity. Full sidewalk navigation without remote assist in mapped zones. Improved weather resistance. $2,200/mo.",specs:{application:"Sidewalk food delivery",autonomy:"Full autonomous in mapped zones",payload_kg:12,speed_kmh:6,weather:"IP54 rain resistant",nav:"LiDAR + stereo cameras",subscription_monthly:2200},score:cs({performance:74,reliability:76,ease_of_use:86,intelligence:76,value:78,ecosystem:66,safety:82,design:80}),breakdown:{performance:74,reliability:76,ease_of_use:86,intelligence:76,value:78,ecosystem:66,safety:82,design:80}},
{slug:"serve-gen3",name:"Serve Robotics Gen 3",mfr:"serve-robotics",cat:"delivery",price:null,year:2024,status:"active",desc:"Third-generation delivery robot from Serve Robotics, an Uber spin-off. Official Uber Eats delivery partner. Level 4 autonomous navigation on sidewalks. Insulated multi-compartment cargo. $2,000/mo.",specs:{application:"Uber Eats delivery",autonomy:"Level 4 sidewalk",partner:"Uber Eats official",payload_kg:15,compartments:"Insulated multi-compartment",speed_kmh:6,subscription_monthly:2000},score:cs({performance:78,reliability:78,ease_of_use:84,intelligence:80,value:76,ecosystem:72,safety:82,design:80}),breakdown:{performance:78,reliability:78,ease_of_use:84,intelligence:80,value:76,ecosystem:72,safety:82,design:80}},
{slug:"serve-gen3-plus",name:"Serve Robotics Gen 3+",mfr:"serve-robotics",cat:"delivery",price:null,year:2025,status:"active",desc:"Enhanced third-generation Serve robot with extended range and improved autonomy. Higher battery capacity for longer delivery routes. Advanced pedestrian prediction AI. $2,500/mo.",specs:{application:"Extended-range Uber Eats delivery",autonomy:"Level 4+ enhanced",range_km:12,battery_hrs:14,payload_kg:18,pedestrian_ai:"Predictive path planning",subscription_monthly:2500},score:cs({performance:80,reliability:80,ease_of_use:84,intelligence:82,value:74,ecosystem:72,safety:84,design:82}),breakdown:{performance:80,reliability:80,ease_of_use:84,intelligence:82,value:74,ecosystem:72,safety:84,design:82}},
{slug:"dax-delivery",name:"Dax Delivery Robot",mfr:"dax",cat:"delivery",price:null,year:2024,status:"active",desc:"Autonomous last-mile delivery robot designed for suburban neighborhoods. Large cargo compartment for package and grocery delivery. Operates on sidewalks and bike lanes. $3,000/mo.",specs:{application:"Suburban package/grocery delivery",payload_kg:30,nav:"LiDAR + GPS + camera fusion",terrain:"Sidewalks and bike lanes",range_km:15,speed_kmh:8,subscription_monthly:3000},score:cs({performance:74,reliability:74,ease_of_use:80,intelligence:76,value:72,ecosystem:56,safety:80,design:74}),breakdown:{performance:74,reliability:74,ease_of_use:80,intelligence:76,value:72,ecosystem:56,safety:80,design:74}},
{slug:"cartken-model-c",name:"Cartken Model C",mfr:"cartken",cat:"delivery",price:null,year:2024,status:"active",desc:"Compact autonomous delivery robot from Cartken. Deployed at universities and corporate campuses. Modular cargo system for food, packages, or medical supplies. $1,500/mo.",specs:{application:"Campus and corporate delivery",payload_kg:10,nav:"Visual SLAM + LiDAR",modular:"Swappable cargo modules",deployments:"Universities, corporate campuses",speed_kmh:5,subscription_monthly:1500},score:cs({performance:72,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:60,safety:82,design:78}),breakdown:{performance:72,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:60,safety:82,design:78}},
{slug:"tinymill-scout",name:"TinyMile Scout",mfr:"tinymile",cat:"delivery",price:null,year:2023,status:"active",desc:"Neighborhood delivery robot from Canadian startup TinyMile. Lightweight design for residential areas. Remote-operated with growing autonomous capabilities. Friendly LED face display. $1,200/mo.",specs:{application:"Neighborhood delivery",operation:"Remote + semi-autonomous",payload_kg:8,weight_kg:35,display:"LED face expressions",range_km:4,subscription_monthly:1200},score:cs({performance:66,reliability:70,ease_of_use:84,intelligence:66,value:82,ecosystem:54,safety:80,design:82}),breakdown:{performance:66,reliability:70,ease_of_use:84,intelligence:66,value:82,ecosystem:54,safety:80,design:82}},
{slug:"neubility-neubie",name:"Neubility Neubie",mfr:"neubility",cat:"delivery",price:null,year:2024,status:"active",desc:"South Korean autonomous delivery robot deployed across Seoul and other Korean cities. Approved for public sidewalk operation in South Korea. Partners with major Korean food delivery platforms. $2,000/mo.",specs:{application:"Urban food delivery (Korea)",nav:"Autonomous sidewalk L4",regulatory:"Korean sidewalk approved",partners:"Korean food delivery platforms",payload_kg:15,speed_kmh:6,subscription_monthly:2000},score:cs({performance:76,reliability:76,ease_of_use:82,intelligence:78,value:76,ecosystem:64,safety:84,design:78}),breakdown:{performance:76,reliability:76,ease_of_use:82,intelligence:78,value:76,ecosystem:64,safety:84,design:78}},
{slug:"lmdelivery-loomo",name:"Segway Loomo Delivery",mfr:"segway",cat:"delivery",price:5000,year:2023,status:"active",desc:"Indoor courier robot based on Segway's self-balancing platform. Delivers packages, documents, and meals within office buildings and hotels. Two-wheel self-balancing with autonomous navigation.",specs:{application:"Indoor office/hotel courier",platform:"Self-balancing two-wheel",payload_kg:8,nav:"Visual SLAM indoor",environments:"Offices, hotels, hospitals",speed_kmh:8,battery_hrs:8},score:cs({performance:68,reliability:72,ease_of_use:82,intelligence:70,value:80,ecosystem:62,safety:78,design:82}),breakdown:{performance:68,reliability:72,ease_of_use:82,intelligence:70,value:80,ecosystem:62,safety:78,design:82}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 12 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 12 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
