/**
 * Robotomated — Wave 4 Robot Import: 80+ New Robots
 * Scale database from ~228 to 300+ robots.
 * Covers: agricultural, warehouse/logistics, consumer/home, manufacturing,
 *   delivery, drones, medical, security.
 *
 * Run: npx tsx scripts/import-robots-wave4.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  // Agricultural
  { slug: "abundant-robotics", name: "Abundant Robotics", country: "US", founded_year: 2016, website: "https://abundantrobotics.com" },
  { slug: "raven-industries", name: "Raven Industries (CNH)", country: "US", founded_year: 1956, website: "https://ravenind.com" },
  { slug: "agbot", name: "AgBot", country: "AU", founded_year: 2015, website: "https://agbot.com.au" },
  { slug: "burro", name: "Burro", country: "US", founded_year: 2017, website: "https://burro.ai" },
  { slug: "swarmfarm", name: "SwarmFarm Robotics", country: "AU", founded_year: 2012, website: "https://swarmfarm.com" },
  { slug: "ecorobotix", name: "Ecorobotix", country: "CH", founded_year: 2014, website: "https://ecorobotix.com" },
  // Warehouse/Logistics
  { slug: "greyorange", name: "GreyOrange", country: "US", founded_year: 2011, website: "https://greyorange.com" },
  { slug: "magazino", name: "Magazino (Jungheinrich)", country: "DE", founded_year: 2014, website: "https://magazino.eu" },
  { slug: "hai-robotics", name: "HAI Robotics", country: "CN", founded_year: 2016, website: "https://hairobotics.com" },
  { slug: "quicktron", name: "Quicktron", country: "CN", founded_year: 2014, website: "https://quicktron.com" },
  { slug: "forwardx", name: "ForwardX Robotics", country: "CN", founded_year: 2016, website: "https://forwardx.com" },
  { slug: "tompkins-robotics", name: "Tompkins Robotics", country: "US", founded_year: 2017, website: "https://tompkinsrobotics.com" },
  { slug: "matthews-automation", name: "Matthews Automation", country: "US", founded_year: 1927, website: "https://matthewsautomation.com" },
  { slug: "crown-equipment", name: "Crown Equipment", country: "US", founded_year: 1945, website: "https://crown.com" },
  { slug: "raymond-corp", name: "The Raymond Corporation", country: "US", founded_year: 1922, website: "https://raymondcorp.com" },
  // Consumer/Home
  { slug: "aeolus-robotics", name: "Aeolus Robotics", country: "US", founded_year: 2015, website: "https://aeolusbot.com" },
  { slug: "narwal", name: "Narwal", country: "CN", founded_year: 2016, website: "https://narwal.com" },
  { slug: "ilife", name: "ILIFE", country: "CN", founded_year: 2010, website: "https://iliferobot.com" },
  { slug: "neato-robotics", name: "Neato Robotics", country: "US", founded_year: 2005, website: "https://neatorobotics.com" },
  { slug: "shark-robot", name: "Shark (SharkNinja)", country: "US", founded_year: 2003, website: "https://sharkclean.com" },
  // Delivery
  { slug: "wing-alphabet", name: "Wing (Alphabet)", country: "US", founded_year: 2012, website: "https://wing.com" },
  { slug: "amazon-scout", name: "Amazon Scout", country: "US", founded_year: 2019, website: "https://amazon.com" },
  { slug: "fedex-robotics", name: "FedEx Robotics", country: "US", founded_year: 2019, website: "https://fedex.com" },
  { slug: "refraction-ai", name: "Refraction AI", country: "US", founded_year: 2019, website: "https://refraction.ai" },
  { slug: "manna-aero", name: "Manna Aero", country: "IE", founded_year: 2018, website: "https://manna.aero" },
  // Drones
  { slug: "joby-aviation", name: "Joby Aviation", country: "US", founded_year: 2009, website: "https://jobyaviation.com" },
  { slug: "archer-aviation", name: "Archer Aviation", country: "US", founded_year: 2018, website: "https://archer.com" },
  // Medical
  { slug: "verb-surgical", name: "Verb Surgical (J&J/Verily)", country: "US", founded_year: 2015, website: "https://jnj.com" },
  { slug: "cmr-surgical", name: "CMR Surgical", country: "GB", founded_year: 2014, website: "https://cmrsurgical.com" },
  { slug: "zimmer-biomet", name: "Zimmer Biomet", country: "US", founded_year: 1927, website: "https://zimmerbiomet.com" },
  { slug: "smith-nephew", name: "Smith+Nephew", country: "GB", founded_year: 1856, website: "https://smith-nephew.com" },
  { slug: "procept-biorobotics", name: "Procept BioRobotics", country: "US", founded_year: 2009, website: "https://procept-biorobotics.com" },
  // Security
  { slug: "cobalt-robotics", name: "Cobalt Robotics", country: "US", founded_year: 2016, website: "https://cobaltrobotics.com" },
  { slug: "pal-robotics", name: "PAL Robotics", country: "ES", founded_year: 2004, website: "https://pal-robotics.com" },
  { slug: "ascento", name: "Ascento", country: "CH", founded_year: 2018, website: "https://ascento.ai" },
  { slug: "otsaw", name: "OTSAW Digital", country: "SG", founded_year: 2015, website: "https://otsaw.com" },
  // Manufacturing (new ones not already in DB)
  { slug: "comau", name: "Comau", country: "IT", founded_year: 1973, website: "https://comau.com" },
  { slug: "epson-robots", name: "Epson Robots", country: "JP", founded_year: 1942, website: "https://epson.com/robots" },
  // Additional warehouse
  { slug: "geek-plus", name: "Geek+", country: "CN", founded_year: 2015, website: "https://geekplus.com" },
  { slug: "mujin", name: "Mujin", country: "JP", founded_year: 2011, website: "https://mujin.co.jp" },
  { slug: "symbotic", name: "Symbotic", country: "US", founded_year: 2007, website: "https://symbotic.com" },
  { slug: "exotec", name: "Exotec", country: "FR", founded_year: 2015, website: "https://exotec.com" },
  // Additional consumer
  { slug: "eufy", name: "Eufy (Anker)", country: "CN", founded_year: 2016, website: "https://eufy.com" },
  { slug: "switchbot", name: "SwitchBot", country: "CN", founded_year: 2015, website: "https://switch-bot.com" },
  { slug: "yeedi", name: "Yeedi (Ecovacs)", country: "CN", founded_year: 2019, website: "https://yeedi.com" },
  // Additional construction
  { slug: "hilti-robotics", name: "Hilti (Robotics)", country: "LI", founded_year: 1941, website: "https://hilti.com" },
  { slug: "okibo", name: "Okibo", country: "IL", founded_year: 2018, website: "https://okibo.com" },
  // Additional manufacturing
  { slug: "elite-robots", name: "Elite Robots", country: "CN", founded_year: 2016, website: "https://eliterobot.com" },
  { slug: "han-robot", name: "Han's Robot (Franka)", country: "CN", founded_year: 2017, website: "https://hansrobot.net" },
  // (medtronic already exists in DB from wave 1)
  // (skydio already exists in DB from wave 1)
];

// ═══════════════════════════════════════════════════════════════
// ALL ROBOTS — 80 new entries
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

  // ═══ AGRICULTURAL (8) ═══
  {slug:"blue-river-see-spray",name:"Blue River See & Spray Ultimate",mfr:"john-deere",cat:"agricultural",price:null,year:2024,status:"active",desc:"Precision spraying system by Blue River (John Deere). Uses computer vision to distinguish crops from weeds and applies herbicide only where needed, reducing chemical use by up to 77%.",specs:{cameras:36,spray_width_ft:120,speed_mph:12,herbicide_reduction:"77%",ai:"Deep learning weed detection"},score:cs({performance:88,reliability:82,ease_of_use:78,intelligence:92,value:80,ecosystem:75,safety:80,design:72}),breakdown:{performance:88,reliability:82,ease_of_use:78,intelligence:92,value:80,ecosystem:75,safety:80,design:72}},
  {slug:"abundant-robotics-apple-picker",name:"Abundant Robotics Apple Harvester",mfr:"abundant-robotics",cat:"agricultural",price:null,year:2021,status:"discontinued",desc:"Autonomous apple harvesting robot using vacuum-based picking. Could identify and pick ripe apples without bruising. Company ceased operations in 2021 but pioneered robotic fruit harvesting.",specs:{method:"Vacuum pick",target:"Apples",vision:"Computer vision ripeness detection",speed:"One apple per second"},score:cs({performance:72,reliability:65,ease_of_use:70,intelligence:78,value:55,ecosystem:40,safety:78,design:68}),breakdown:{performance:72,reliability:65,ease_of_use:70,intelligence:78,value:55,ecosystem:40,safety:78,design:68}},
  {slug:"raven-autonomy-omnipower",name:"Raven Autonomy OmniPower",mfr:"raven-industries",cat:"agricultural",price:null,year:2023,status:"active",desc:"Autonomous power platform by Raven (acquired by CNH Industrial). Provides autonomous capability to existing farm implements. Driverless field operations including tillage and spraying.",specs:{autonomy:"Level 4 driverless",implements:"Universal hitch compatible",connectivity:"4G LTE + GPS RTK",safety:"360-degree obstacle detection"},score:cs({performance:82,reliability:78,ease_of_use:75,intelligence:85,value:72,ecosystem:70,safety:82,design:70}),breakdown:{performance:82,reliability:78,ease_of_use:75,intelligence:85,value:72,ecosystem:70,safety:82,design:70}},
  {slug:"agbot-ii",name:"AgBot II",mfr:"agbot",cat:"agricultural",price:null,year:2022,status:"active",desc:"Australian multi-purpose agricultural robot for weed detection, soil sampling, and crop monitoring. Lightweight design minimizes soil compaction. Solar-assisted battery.",specs:{weight_kg:350,solar_assist:true,functions:"Weed detection, soil sampling, monitoring",nav:"RTK GPS + LiDAR"},score:cs({performance:72,reliability:74,ease_of_use:70,intelligence:76,value:68,ecosystem:55,safety:78,design:68}),breakdown:{performance:72,reliability:74,ease_of_use:70,intelligence:76,value:68,ecosystem:55,safety:78,design:68}},
  {slug:"burro-grande",name:"Burro Grande",mfr:"burro",cat:"agricultural",price:null,year:2024,status:"active",desc:"Autonomous cart for farm labor assistance. Follows workers through fields, carrying harvested produce. AI learns farm layout over time. Used in berry, grape, and nursery operations.",specs:{payload_kg:225,battery_hrs:10,autonomy:"Follow-me + waypoint",terrain:"Off-road, rows, hills",ai:"Self-improving navigation"},score:cs({performance:76,reliability:78,ease_of_use:85,intelligence:80,value:82,ecosystem:65,safety:80,design:72}),breakdown:{performance:76,reliability:78,ease_of_use:85,intelligence:80,value:82,ecosystem:65,safety:80,design:72}},
  {slug:"swarmfarm-robot",name:"SwarmFarm SwarmBot",mfr:"swarmfarm",cat:"agricultural",price:null,year:2023,status:"active",desc:"Australian autonomous swarm farming robot. Multiple lightweight units work together to cover large fields. Designed for broad-acre cropping with spot spraying and weed management.",specs:{weight_kg:800,swarm_capable:true,spray_width_m:6,nav:"RTK GPS",speed_kmh:15},score:cs({performance:78,reliability:76,ease_of_use:72,intelligence:80,value:74,ecosystem:58,safety:78,design:68}),breakdown:{performance:78,reliability:76,ease_of_use:72,intelligence:80,value:74,ecosystem:58,safety:78,design:68}},
  {slug:"naio-orio",name:"Naio Orio",mfr:"naio-technologies",cat:"agricultural",price:null,year:2024,status:"active",desc:"Large-scale autonomous vineyard and orchard robot by Naio Technologies. Handles mowing, weeding, and spraying between rows. Fully electric with all-day battery life.",specs:{weight_kg:500,battery_hrs:8,functions:"Mowing, weeding, spraying",terrain:"Vineyard rows, orchards",width_cm:80},score:cs({performance:76,reliability:78,ease_of_use:76,intelligence:78,value:72,ecosystem:68,safety:80,design:72}),breakdown:{performance:76,reliability:78,ease_of_use:76,intelligence:78,value:72,ecosystem:68,safety:80,design:72}},
  {slug:"ecorobotix-ara",name:"Ecorobotix ARA",mfr:"ecorobotix",cat:"agricultural",price:null,year:2024,status:"active",desc:"Ultra-high precision spot spraying system from Switzerland. Camera-based weed detection applies micro-doses of herbicide with 95% reduction in chemical use. Tractor-mounted.",specs:{cameras:8,spray_reduction:"95%",resolution_cm:6,speed_kmh:12,mount:"Tractor 3-point hitch"},score:cs({performance:85,reliability:80,ease_of_use:78,intelligence:90,value:82,ecosystem:65,safety:82,design:72}),breakdown:{performance:85,reliability:80,ease_of_use:78,intelligence:90,value:82,ecosystem:65,safety:82,design:72}},

  // ═══ WAREHOUSE/LOGISTICS (10) ═══
  {slug:"greyorange-ranger-moveit",name:"GreyOrange Ranger MoveIt",mfr:"greyorange",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered goods-to-person AMR for warehouse fulfillment. GreyOrange Fulfillment OS orchestrates fleet. Used by IKEA, H&M, and major 3PLs. Up to 600kg payload.",specs:{payload_kg:600,speed_ms:2.0,battery_hrs:8,nav:"LiDAR + camera fusion",fleet_software:"GreyOrange Fulfillment OS"},score:cs({performance:82,reliability:80,ease_of_use:78,intelligence:84,value:76,ecosystem:78,safety:82,design:75}),breakdown:{performance:82,reliability:80,ease_of_use:78,intelligence:84,value:76,ecosystem:78,safety:82,design:75}},
  {slug:"magazino-toru",name:"Magazino TORU",mfr:"magazino",cat:"warehouse",price:null,year:2023,status:"active",desc:"Piece-picking robot by Magazino (acquired by Jungheinrich). Uses 3D vision to identify and pick individual items from shelves. Handles shoes, books, and small goods in e-commerce fulfillment.",specs:{picking:"Individual piece-picking",vision:"3D object recognition",height_cm:190,payload_kg:16,items:"Shoes, books, small goods"},score:cs({performance:78,reliability:76,ease_of_use:74,intelligence:85,value:70,ecosystem:68,safety:80,design:74}),breakdown:{performance:78,reliability:76,ease_of_use:74,intelligence:85,value:70,ecosystem:68,safety:80,design:74}},
  {slug:"hai-robotics-acr-a42t",name:"HAI Robotics ACR A42T",mfr:"hai-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous Case-handling Robot (ACR) that retrieves individual tote bins from racking up to 10m high. Telescoping lift mast. Deployed in 1000+ warehouses in 30+ countries.",specs:{max_height_m:10,payload_kg:50,speed_ms:1.5,telescoping_mast:true,deployments:1000},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:75,safety:82,design:74}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:75,safety:82,design:74}},
  {slug:"quicktron-qmp-350",name:"Quicktron QMP-350",mfr:"quicktron",cat:"warehouse",price:null,year:2023,status:"active",desc:"High-speed goods-to-person AMR from Alibaba-backed Quicktron. 350kg payload, operates in fleets of 1000+. Powers Cainiao Smart Logistics and global 3PL operations.",specs:{payload_kg:350,speed_ms:2.0,battery_hrs:8,fleet_size:"1000+",partners:"Alibaba Cainiao"},score:cs({performance:82,reliability:80,ease_of_use:76,intelligence:80,value:82,ecosystem:72,safety:80,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:76,intelligence:80,value:82,ecosystem:72,safety:80,design:72}},
  {slug:"forwardx-flex-300",name:"ForwardX Flex 300",mfr:"forwardx",cat:"warehouse",price:null,year:2024,status:"active",desc:"Vision-based AMR for warehouse fulfillment. No infrastructure modifications needed. AI-powered navigation works in dynamic environments with humans and other equipment.",specs:{payload_kg:300,speed_ms:1.8,battery_hrs:10,nav:"Vision AI + LiDAR",infrastructure:"Zero modification"},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:82,value:78,ecosystem:68,safety:80,design:74}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:82,value:78,ecosystem:68,safety:80,design:74}},
  {slug:"locus-origin-2",name:"Locus Robotics Origin 2.0",mfr:"locus-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Next-gen collaborative warehouse AMR with larger payload capacity and improved AI. 3 billion units picked to date across the Locus fleet. Enhanced multi-bot coordination.",specs:{payload_kg:36,battery_hrs:12,units_picked:"3B+ lifetime fleet",nav:"LiDAR SLAM + camera",fleet_coordination:"LocusHub AI"},score:cs({performance:84,reliability:84,ease_of_use:86,intelligence:84,value:80,ecosystem:82,safety:84,design:78}),breakdown:{performance:84,reliability:84,ease_of_use:86,intelligence:84,value:80,ecosystem:82,safety:84,design:78}},
  {slug:"tompkins-tsort-3d",name:"Tompkins Robotics t-Sort 3D",mfr:"tompkins-robotics",cat:"warehouse",price:null,year:2023,status:"active",desc:"Robotic sortation system using swarm of small robots on an elevated track. Each robot carries one parcel to its destination chute. 2500+ sorts/hour. Compact footprint.",specs:{sorts_per_hour:2500,payload_kg:15,type:"Robotic sortation",track:"Elevated grid",footprint:"Compact modular"},score:cs({performance:80,reliability:82,ease_of_use:76,intelligence:78,value:78,ecosystem:65,safety:82,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:76,intelligence:78,value:78,ecosystem:65,safety:82,design:72}},
  {slug:"matthews-adams-bot",name:"Matthews ADAMS Bot",mfr:"matthews-automation",cat:"warehouse",price:null,year:2023,status:"active",desc:"Autonomous Delivery and Material Sorting bot for distribution centers. Mid-level parcel sortation with flexible routing. Integrates with Matthews warehouse control system.",specs:{payload_kg:30,speed_ms:1.5,sorting:"Dynamic route assignment",integration:"Matthews WCS"},score:cs({performance:74,reliability:78,ease_of_use:76,intelligence:74,value:74,ecosystem:62,safety:80,design:70}),breakdown:{performance:74,reliability:78,ease_of_use:76,intelligence:74,value:74,ecosystem:62,safety:80,design:70}},
  {slug:"crown-autonomous-reach",name:"Crown Autonomous Reach Truck",mfr:"crown-equipment",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous reach truck from Crown Equipment. Handles high-bay pallet storage and retrieval up to 10m. Integrates with existing warehouse management systems. Hybrid manual/autonomous operation.",specs:{lift_height_m:10,payload_kg:1500,type:"Autonomous reach truck",mode:"Hybrid manual/auto",nav:"Natural feature navigation"},score:cs({performance:80,reliability:82,ease_of_use:75,intelligence:78,value:72,ecosystem:72,safety:85,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:75,intelligence:78,value:72,ecosystem:72,safety:85,design:72}},
  {slug:"raymond-courier-3030",name:"Raymond Courier 3030",mfr:"raymond-corp",cat:"warehouse",price:null,year:2024,status:"active",desc:"Automated pallet truck from The Raymond Corporation. Natural feature navigation requires no infrastructure changes. Handles horizontal transport in warehouses and manufacturing.",specs:{payload_kg:1360,type:"Automated pallet truck",nav:"Natural feature iWAREHOUSE",integration:"iWAREHOUSE Gateway"},score:cs({performance:78,reliability:82,ease_of_use:78,intelligence:76,value:76,ecosystem:72,safety:84,design:70}),breakdown:{performance:78,reliability:82,ease_of_use:78,intelligence:76,value:76,ecosystem:72,safety:84,design:70}},

  // ═══ CONSUMER/HOME (10) ═══
  {slug:"samsung-ballie",name:"Samsung Ballie",mfr:"samsung",cat:"consumer",price:null,year:2025,status:"coming_soon",desc:"Samsung's rolling home AI companion robot with built-in projector. Acts as a smart home hub, pet monitor, fitness assistant, and entertainment device. Projects content onto any surface.",specs:{shape:"Spherical rolling",projector:"Built-in HD",ai:"On-device + cloud",functions:"Smart home, pet care, fitness, entertainment"},score:cs({performance:70,reliability:65,ease_of_use:80,intelligence:82,value:62,ecosystem:75,safety:75,design:90}),breakdown:{performance:70,reliability:65,ease_of_use:80,intelligence:82,value:62,ecosystem:75,safety:75,design:90}},
  {slug:"aeolus-aeo-2",name:"Aeolus Aeo 2",mfr:"aeolus-robotics",cat:"consumer",price:null,year:2024,status:"active",desc:"Commercial service and disinfection robot. UV-C disinfection, telepresence, security patrol, and autonomous delivery in hotels and healthcare. Multi-function platform.",specs:{height_cm:160,uv_c:true,telepresence:true,battery_hrs:8,functions:"Disinfection, patrol, delivery, telepresence"},score:cs({performance:72,reliability:74,ease_of_use:76,intelligence:74,value:68,ecosystem:60,safety:80,design:74}),breakdown:{performance:72,reliability:74,ease_of_use:76,intelligence:74,value:68,ecosystem:60,safety:80,design:74}},
  {slug:"lg-cloi-uv-c",name:"LG CLOi UV-C Robot",mfr:"lg-electronics",cat:"consumer",price:null,year:2022,status:"active",desc:"Autonomous UV-C disinfection robot for commercial spaces. Delivers UV-C irradiation to high-touch surfaces while navigating autonomously. Used in hospitals, hotels, and schools.",specs:{uv_c_wavelength_nm:254,coverage_sqm:160,battery_hrs:4,nav:"LiDAR SLAM",safety:"PIR motion sensor auto-shutoff"},score:cs({performance:74,reliability:80,ease_of_use:82,intelligence:72,value:68,ecosystem:70,safety:88,design:74}),breakdown:{performance:74,reliability:80,ease_of_use:82,intelligence:72,value:68,ecosystem:70,safety:88,design:74}},
  {slug:"narwal-freo-x-ultra",name:"Narwal Freo X Ultra",mfr:"narwal",cat:"consumer",price:1400,year:2024,status:"active",desc:"Premium robot vacuum and mop with auto-mop washing, drying, and detergent dispensing. Zero-tangling DirtSense technology. Edge-to-edge mopping with side-extending mop.",specs:{suction_pa:8200,mop:"Auto-wash, dry, detergent",nav:"LiDAR + 3D structured light",dustbin:"Self-empty 4L",edge_mopping:true},score:cs({performance:86,reliability:82,ease_of_use:88,intelligence:84,value:80,ecosystem:72,safety:80,design:82}),breakdown:{performance:86,reliability:82,ease_of_use:88,intelligence:84,value:80,ecosystem:72,safety:80,design:82}},
  {slug:"dreame-x30-ultra",name:"Dreame X30 Ultra",mfr:"dreame",cat:"consumer",price:1600,year:2024,status:"active",desc:"Flagship robot vacuum with extending and lifting side mop, 12,000Pa suction, and OmniDirt Detect. Hot water mop washing at 70C. ProLeap stair-avoidance technology.",specs:{suction_pa:12000,mop:"Extending side mop, hot wash 70C",nav:"3D structured light + LiDAR",dustbin:"Self-empty 3.2L",obstacle_avoidance:"AI RGB + 3D ToF"},score:cs({performance:90,reliability:82,ease_of_use:86,intelligence:88,value:78,ecosystem:74,safety:80,design:84}),breakdown:{performance:90,reliability:82,ease_of_use:86,intelligence:88,value:78,ecosystem:74,safety:80,design:84}},
  {slug:"ecovacs-deebot-t30-pro",name:"Ecovacs DEEBOT T30 Pro Omni",mfr:"ecovacs",cat:"consumer",price:1200,year:2024,status:"active",desc:"Robot vacuum and mop with TruEdge adaptive edge mopping. 11,000Pa suction. Zero-tangle anti-hair brush. YIKO 2.0 voice assistant with natural language control.",specs:{suction_pa:11000,mop:"TruEdge adaptive edge",nav:"TrueMapping 3.0 LiDAR",voice:"YIKO 2.0 NLP",dustbin:"Self-empty"},score:cs({performance:86,reliability:82,ease_of_use:86,intelligence:84,value:82,ecosystem:76,safety:80,design:80}),breakdown:{performance:86,reliability:82,ease_of_use:86,intelligence:84,value:82,ecosystem:76,safety:80,design:80}},
  {slug:"roborock-q8-max-plus",name:"Roborock Q8 Max+",mfr:"roborock",cat:"consumer",price:530,year:2024,status:"active",desc:"Mid-range robot vacuum and mop with 5500Pa suction. DuoRoller brush system. Auto-empty dock included. Reactive Tech obstacle avoidance. Strong value proposition.",specs:{suction_pa:5500,brush:"DuoRoller anti-tangle",nav:"LiDAR PreciSense",dustbin:"Self-empty 2.5L",obstacle:"Reactive Tech 2.0"},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:76,value:90,ecosystem:78,safety:80,design:78}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:76,value:90,ecosystem:78,safety:80,design:78}},
  {slug:"ilife-a20",name:"ILIFE A20",mfr:"ilife",cat:"consumer",price:300,year:2024,status:"active",desc:"Budget-friendly robot vacuum with LiDAR navigation and 5000Pa suction. Self-empty base station included. Multi-floor mapping. Strong value for entry-level buyers.",specs:{suction_pa:5000,nav:"LiDAR SLAM",dustbin:"Self-empty base",mapping:"Multi-floor",runtime_min:120},score:cs({performance:70,reliability:72,ease_of_use:82,intelligence:70,value:92,ecosystem:58,safety:78,design:72}),breakdown:{performance:70,reliability:72,ease_of_use:82,intelligence:70,value:92,ecosystem:58,safety:78,design:72}},
  {slug:"neato-d10",name:"Neato D10",mfr:"neato-robotics",cat:"consumer",price:750,year:2022,status:"active",desc:"D-shape robot vacuum optimized for corner and edge cleaning. LaserSmart SLAM navigation. True HEPA filtration. Large dustbin. Zone cleaning with no-go lines.",specs:{suction_pa:4000,shape:"D-shape edge cleaning",nav:"LaserSmart LiDAR SLAM",filter:"True HEPA",dustbin_ml:700},score:cs({performance:76,reliability:76,ease_of_use:80,intelligence:74,value:72,ecosystem:68,safety:78,design:76}),breakdown:{performance:76,reliability:76,ease_of_use:80,intelligence:74,value:72,ecosystem:68,safety:78,design:76}},
  {slug:"shark-ai-ultra-2in1",name:"Shark AI Ultra 2-in-1",mfr:"shark-robot",cat:"consumer",price:600,year:2024,status:"active",desc:"Robot vacuum and mop combo with Matrix Clean navigation for systematic row-by-row coverage. Self-empty base. 360-degree LiDAR. Strong suction on carpets.",specs:{suction_pa:5000,nav:"360 LiDAR Matrix Clean",mop:"Sonic mopping",dustbin:"Self-empty XL base",carpet_detection:true},score:cs({performance:78,reliability:78,ease_of_use:84,intelligence:76,value:82,ecosystem:72,safety:78,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:84,intelligence:76,value:82,ecosystem:72,safety:78,design:76}},

  // ═══ MANUFACTURING (10) ═══
  {slug:"techman-tm5-900",name:"Techman TM5-900",mfr:"techman-robot",cat:"manufacturing",price:28000,year:2023,status:"active",desc:"Compact collaborative robot with built-in smart vision. 4kg payload, 900mm reach. Ideal for machine tending, assembly, and inspection. TM Flow visual programming.",specs:{payload_kg:4,reach_mm:900,dof:6,repeatability_mm:0.05,vision:"Built-in 5MP smart camera",programming:"TMflow visual"},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:82,value:85,ecosystem:75,safety:82,design:78}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:82,value:85,ecosystem:75,safety:82,design:78}},
  {slug:"abb-irb-6700",name:"ABB IRB 6700",mfr:"abb-robotics",cat:"manufacturing",price:80000,year:2023,status:"active",desc:"ABB workhorse industrial robot. 150-300kg payload range. Built for spot welding, material handling, and machine tending. 7th gen TrueMove and QuickMove motion control.",specs:{payload_kg:300,reach_mm:3200,dof:6,repeatability_mm:0.05,ip_rating:"IP67",motion:"TrueMove QuickMove"},score:cs({performance:90,reliability:90,ease_of_use:72,intelligence:76,value:78,ecosystem:88,safety:85,design:75}),breakdown:{performance:90,reliability:90,ease_of_use:72,intelligence:76,value:78,ecosystem:88,safety:85,design:75}},
  {slug:"kuka-kr-cybertech-nano",name:"KUKA KR CYBERTECH nano",mfr:"kuka",cat:"manufacturing",price:35000,year:2023,status:"active",desc:"Compact industrial robot for handling, assembly, and arc welding. 6-10kg payload. Slim design fits tight production cells. KR C5 controller with KUKA.SystemSoftware 8.",specs:{payload_kg:10,reach_mm:1420,dof:6,repeatability_mm:0.04,weight_kg:54,controller:"KR C5"},score:cs({performance:82,reliability:86,ease_of_use:78,intelligence:76,value:82,ecosystem:85,safety:84,design:78}),breakdown:{performance:82,reliability:86,ease_of_use:78,intelligence:76,value:82,ecosystem:85,safety:84,design:78}},
  {slug:"yaskawa-gp7",name:"Yaskawa GP7",mfr:"yaskawa",cat:"manufacturing",price:32000,year:2023,status:"active",desc:"High-speed handling robot with 7kg payload. Fastest in class with 0.32s cycle time. Compact design for material handling, packaging, and assembly applications.",specs:{payload_kg:7,reach_mm:927,dof:6,repeatability_mm:0.01,cycle_time_s:0.32,controller:"YRC1000"},score:cs({performance:86,reliability:86,ease_of_use:76,intelligence:74,value:82,ecosystem:82,safety:84,design:74}),breakdown:{performance:86,reliability:86,ease_of_use:76,intelligence:74,value:82,ecosystem:82,safety:84,design:74}},
  {slug:"comau-racer-5",name:"Comau Racer-5 0.80",mfr:"comau",cat:"manufacturing",price:28000,year:2023,status:"active",desc:"Ultra-fast 6-axis industrial robot from Italian manufacturer Comau. 5kg payload, 809mm reach. Designed for high-speed assembly, pick-and-place, and machine tending.",specs:{payload_kg:5,reach_mm:809,dof:6,repeatability_mm:0.03,speed:"Industry-leading",ip_rating:"IP65"},score:cs({performance:84,reliability:82,ease_of_use:74,intelligence:72,value:80,ecosystem:70,safety:82,design:74}),breakdown:{performance:84,reliability:82,ease_of_use:74,intelligence:72,value:80,ecosystem:70,safety:82,design:74}},
  {slug:"kawasaki-rs007l",name:"Kawasaki RS007L",mfr:"kawasaki-robotics",cat:"manufacturing",price:30000,year:2023,status:"active",desc:"Compact high-speed industrial robot with 7kg payload and extended 930mm reach. Ideal for assembly, machine tending, and dispensing. Cubic-S safety technology.",specs:{payload_kg:7,reach_mm:930,dof:6,repeatability_mm:0.02,safety:"Cubic-S",controller:"E02"},score:cs({performance:84,reliability:84,ease_of_use:76,intelligence:74,value:80,ecosystem:76,safety:84,design:74}),breakdown:{performance:84,reliability:84,ease_of_use:76,intelligence:74,value:80,ecosystem:76,safety:84,design:74}},
  {slug:"staubli-ts2-60",name:"Staubli TS2-60",mfr:"staubli",cat:"manufacturing",price:25000,year:2023,status:"active",desc:"4-axis SCARA robot with fully enclosed arm for cleanroom and food applications. Unique JCS drive technology eliminates external cabling. IP65 standard, IP67 HE model.",specs:{payload_kg:8.4,reach_mm:620,dof:4,repeatability_mm:0.01,type:"SCARA",ip_rating:"IP65/IP67 HE",cabling:"Fully enclosed JCS"},score:cs({performance:82,reliability:86,ease_of_use:78,intelligence:72,value:78,ecosystem:74,safety:86,design:80}),breakdown:{performance:82,reliability:86,ease_of_use:78,intelligence:72,value:78,ecosystem:74,safety:86,design:80}},
  {slug:"epson-t6-scara",name:"Epson T6",mfr:"epson-robots",cat:"manufacturing",price:18000,year:2023,status:"active",desc:"Compact SCARA robot for precision assembly and handling. 6kg payload, 600mm reach. Built-in controller saves space. Epson RC+ development environment. Ideal for electronics assembly.",specs:{payload_kg:6,reach_mm:600,dof:4,repeatability_mm:0.01,type:"SCARA",controller:"Built-in",programming:"Epson RC+"},score:cs({performance:80,reliability:84,ease_of_use:82,intelligence:70,value:88,ecosystem:72,safety:82,design:76}),breakdown:{performance:80,reliability:84,ease_of_use:82,intelligence:70,value:88,ecosystem:72,safety:82,design:76}},
  {slug:"doosan-e-series-e0509",name:"Doosan E Series E0509",mfr:"doosan-robotics",cat:"manufacturing",price:22000,year:2024,status:"active",desc:"Economy collaborative robot from Doosan. 5kg payload, 900mm reach. 6 torque sensors for safe human collaboration. Simplified programming with Dart-Studio.",specs:{payload_kg:5,reach_mm:900,dof:6,repeatability_mm:0.03,torque_sensors:6,programming:"Dart-Studio"},score:cs({performance:76,reliability:78,ease_of_use:84,intelligence:76,value:88,ecosystem:70,safety:82,design:76}),breakdown:{performance:76,reliability:78,ease_of_use:84,intelligence:76,value:88,ecosystem:70,safety:82,design:76}},
  {slug:"fanuc-cr-7ia",name:"FANUC CR-7iA",mfr:"fanuc",cat:"manufacturing",price:38000,year:2023,status:"active",desc:"FANUC collaborative robot with 7kg payload. Green soft-cover exterior with contact-stop safety. Full FANUC reliability and ecosystem. Identical programming to industrial FANUC robots.",specs:{payload_kg:7,reach_mm:717,dof:6,repeatability_mm:0.01,safety:"Contact-stop + DCS",ip_rating:"IP67",controller:"R-30iB Plus"},score:cs({performance:82,reliability:90,ease_of_use:76,intelligence:76,value:76,ecosystem:90,safety:88,design:72}),breakdown:{performance:82,reliability:90,ease_of_use:76,intelligence:76,value:76,ecosystem:90,safety:88,design:72}},

  // ═══ DELIVERY (5) ═══
  {slug:"wing-delivery-drone",name:"Wing Delivery Drone",mfr:"wing-alphabet",cat:"delivery",price:null,year:2024,status:"active",desc:"Alphabet's autonomous drone delivery service. Hovers and lowers packages via tether. Operates in US, Australia, and Finland. 350,000+ deliveries completed. FAA Part 135 certified.",specs:{payload_kg:1.2,range_km:10,speed_kmh:113,delivery_method:"Hover + tether lower",deliveries:"350K+",faa:"Part 135 certified"},score:cs({performance:82,reliability:80,ease_of_use:85,intelligence:86,value:78,ecosystem:72,safety:84,design:78}),breakdown:{performance:82,reliability:80,ease_of_use:85,intelligence:86,value:78,ecosystem:72,safety:84,design:78}},
  {slug:"amazon-scout-bot",name:"Amazon Scout",mfr:"amazon",cat:"delivery",price:null,year:2022,status:"discontinued",desc:"Amazon's six-wheeled sidewalk delivery robot. Cooler-sized autonomous robot tested in Snohomish County, WA. Program paused in 2022 as Amazon shifted focus to drone delivery.",specs:{wheels:6,size:"Cooler-sized",autonomy:"Sidewalk L4",status:"Program paused 2022"},score:cs({performance:68,reliability:70,ease_of_use:78,intelligence:74,value:60,ecosystem:70,safety:78,design:72}),breakdown:{performance:68,reliability:70,ease_of_use:78,intelligence:74,value:60,ecosystem:70,safety:78,design:72}},
  {slug:"fedex-roxo",name:"FedEx Roxo SameDay Bot",mfr:"fedex-robotics",cat:"delivery",price:null,year:2023,status:"active",desc:"FedEx autonomous delivery robot for same-day and last-mile deliveries. Navigates sidewalks, roads, and curbs. Multi-terrain wheels. Developed with DEKA (Dean Kamen's company).",specs:{payload_kg:45,wheels:"Multi-terrain iBot",autonomy:"Sidewalk + road",partner:"DEKA Research",range_km:32},score:cs({performance:74,reliability:74,ease_of_use:78,intelligence:76,value:68,ecosystem:72,safety:80,design:74}),breakdown:{performance:74,reliability:74,ease_of_use:78,intelligence:76,value:68,ecosystem:72,safety:80,design:74}},
  {slug:"refraction-ai-rev-1",name:"Refraction AI REV-1",mfr:"refraction-ai",cat:"delivery",price:null,year:2023,status:"active",desc:"Lightweight autonomous delivery robot that rides in bike lanes. 3-wheeled design. 50 lbs payload. Operates at bike speeds for food and grocery delivery in Ann Arbor and Austin.",specs:{wheels:3,payload_kg:23,max_speed_mph:15,lane:"Bike lane",cities:"Ann Arbor, Austin"},score:cs({performance:72,reliability:72,ease_of_use:80,intelligence:76,value:78,ecosystem:58,safety:78,design:76}),breakdown:{performance:72,reliability:72,ease_of_use:80,intelligence:76,value:78,ecosystem:58,safety:78,design:76}},
  {slug:"manna-aero-delivery",name:"Manna Aero Delivery Drone",mfr:"manna-aero",cat:"delivery",price:null,year:2024,status:"active",desc:"Irish drone delivery company operating residential deliveries in Ireland, US, and EU. Average 3-minute delivery time. Biodegradable packaging drop. Samsung and Tesco partnerships.",specs:{payload_kg:3,delivery_time_min:3,altitude_m:80,partners:"Samsung, Tesco",drop_method:"Biodegradable string lower"},score:cs({performance:80,reliability:78,ease_of_use:86,intelligence:82,value:76,ecosystem:68,safety:82,design:76}),breakdown:{performance:80,reliability:78,ease_of_use:86,intelligence:82,value:76,ecosystem:68,safety:82,design:76}},

  // ═══ DRONES (5) ═══
  {slug:"dji-mavic-4-pro",name:"DJI Mavic 4 Pro",mfr:"dji",cat:"drone",price:2200,year:2025,status:"active",desc:"DJI flagship consumer/prosumer drone. Hasselblad camera with 1-inch CMOS. Omnidirectional obstacle sensing. 45-min flight time. ActiveTrack 6.0. 4K/120fps video.",specs:{camera:"Hasselblad 1-inch CMOS",video:"4K/120fps",flight_time_min:45,range_km:20,obstacle_sensing:"Omnidirectional",weight_g:900},score:cs({performance:92,reliability:88,ease_of_use:90,intelligence:88,value:82,ecosystem:90,safety:85,design:90}),breakdown:{performance:92,reliability:88,ease_of_use:90,intelligence:88,value:82,ecosystem:90,safety:85,design:90}},
  {slug:"autel-evo-ii-pro-v3",name:"Autel EVO II Pro V3",mfr:"autel-robotics",cat:"drone",price:1950,year:2024,status:"active",desc:"Professional drone with 1-inch Sony CMOS sensor. 6K video. 42-min flight time. Moonlight algorithm for low-light performance. SkyLink 2.0 transmission.",specs:{camera:"1-inch Sony CMOS",video:"6K/30fps",flight_time_min:42,range_km:15,transmission:"SkyLink 2.0",weight_g:1190},score:cs({performance:88,reliability:84,ease_of_use:84,intelligence:84,value:84,ecosystem:78,safety:82,design:82}),breakdown:{performance:88,reliability:84,ease_of_use:84,intelligence:84,value:84,ecosystem:78,safety:82,design:82}},
  {slug:"parrot-anafi-usa",name:"Parrot ANAFI USA",mfr:"parrot",cat:"drone",price:7000,year:2022,status:"active",desc:"US-made enterprise drone for public safety and defense. Dual visual + thermal cameras. 32x zoom. NDAA compliant (no Chinese components). Used by US Army and first responders.",specs:{cameras:"Dual visual + FLIR thermal",zoom:"32x",flight_time_min:32,range_km:4,compliance:"NDAA, TAA",weight_g:500},score:cs({performance:80,reliability:82,ease_of_use:82,intelligence:78,value:72,ecosystem:70,safety:82,design:78}),breakdown:{performance:80,reliability:82,ease_of_use:82,intelligence:78,value:72,ecosystem:70,safety:82,design:78}},
  {slug:"joby-aviation-evtol",name:"Joby Aviation S4 eVTOL",mfr:"joby-aviation",cat:"drone",price:null,year:2025,status:"coming_soon",desc:"Electric vertical takeoff and landing air taxi. 5 passengers, 150+ mph, 100+ mile range. FAA certification expected 2025. Toyota-backed. First commercial urban air mobility vehicle.",specs:{passengers:5,speed_mph:200,range_miles:100,propellers:6,noise_dba:45,certification:"FAA Type Certificate pending"},score:cs({performance:88,reliability:72,ease_of_use:70,intelligence:82,value:60,ecosystem:55,safety:78,design:88}),breakdown:{performance:88,reliability:72,ease_of_use:70,intelligence:82,value:60,ecosystem:55,safety:78,design:88}},
  {slug:"archer-midnight-evtol",name:"Archer Midnight eVTOL",mfr:"archer-aviation",cat:"drone",price:null,year:2025,status:"coming_soon",desc:"Electric air taxi designed for urban air mobility. 4 passengers + pilot. 60-mile range. 150 mph cruise. United Airlines partnership for airport-to-city routes. Tilting propeller design.",specs:{passengers:4,speed_mph:150,range_miles:60,propellers:12,partner:"United Airlines",certification:"FAA in progress"},score:cs({performance:82,reliability:68,ease_of_use:68,intelligence:78,value:58,ecosystem:58,safety:75,design:85}),breakdown:{performance:82,reliability:68,ease_of_use:68,intelligence:78,value:58,ecosystem:58,safety:75,design:85}},

  // ═══ MEDICAL (5) ═══
  {slug:"verb-surgical-ottava",name:"Verb Surgical OTTAVA",mfr:"verb-surgical",cat:"medical",price:null,year:2025,status:"coming_soon",desc:"Johnson & Johnson's next-gen surgical robot co-developed with Verily (Alphabet). Multi-port flexible robotic system aiming to challenge Intuitive Surgical's da Vinci dominance.",specs:{arms:6,type:"Multi-port robotic surgery",developer:"J&J + Verily (Alphabet)",target:"General surgery"},score:cs({performance:80,reliability:72,ease_of_use:72,intelligence:85,value:62,ecosystem:65,safety:82,design:78}),breakdown:{performance:80,reliability:72,ease_of_use:72,intelligence:85,value:62,ecosystem:65,safety:82,design:78}},
  {slug:"cmr-versius",name:"CMR Surgical Versius",mfr:"cmr-surgical",cat:"medical",price:null,year:2023,status:"active",desc:"Modular surgical robotic system from Cambridge, UK. Individual arm units port-placed around patient. Small footprint. 500+ installations across 20+ countries. Wristed instruments.",specs:{arms:"Modular individual units",instruments:"Fully wristed 5mm",installations:500,countries:20,approach:"Modular port-placed"},score:cs({performance:82,reliability:80,ease_of_use:78,intelligence:80,value:75,ecosystem:72,safety:86,design:80}),breakdown:{performance:82,reliability:80,ease_of_use:78,intelligence:80,value:75,ecosystem:72,safety:86,design:80}},
  {slug:"zimmer-biomet-rosa-knee",name:"Zimmer Biomet ROSA Knee",mfr:"zimmer-biomet",cat:"medical",price:800000,year:2022,status:"active",desc:"Robotic-arm assisted surgery platform for total knee replacement. Integrates with Zimmer's Persona implant system. Bone tracking without pins. 3,500+ installations worldwide.",specs:{application:"Total knee replacement",implant_system:"Persona IQ",tracking:"Pinless bone tracking",installations:3500},score:cs({performance:84,reliability:84,ease_of_use:78,intelligence:82,value:72,ecosystem:78,safety:88,design:75}),breakdown:{performance:84,reliability:84,ease_of_use:78,intelligence:82,value:72,ecosystem:78,safety:88,design:75}},
  {slug:"smith-nephew-cori",name:"Smith+Nephew CORI Surgical System",mfr:"smith-nephew",cat:"medical",price:750000,year:2023,status:"active",desc:"Handheld robotic-assisted surgery platform for knee replacement. Surgeon holds the handpiece while robotic control ensures precision. No large robotic arm required.",specs:{application:"Knee arthroplasty",type:"Handheld robotics",planning:"Real-time 3D bone mapping",size:"Compact console"},score:cs({performance:80,reliability:82,ease_of_use:82,intelligence:80,value:76,ecosystem:72,safety:86,design:78}),breakdown:{performance:80,reliability:82,ease_of_use:82,intelligence:80,value:76,ecosystem:72,safety:86,design:78}},
  {slug:"procept-greenlight",name:"Procept GreenLight Laser + AquaBeam",mfr:"procept-biorobotics",cat:"medical",price:500000,year:2023,status:"active",desc:"Robotic waterjet therapy for BPH (enlarged prostate). AquaBeam uses autonomous heat-free waterjet guided by real-time ultrasound imaging. Minimally invasive with fast recovery.",specs:{application:"BPH prostate treatment",method:"Autonomous waterjet ablation",guidance:"Real-time ultrasound",type:"Heat-free resection"},score:cs({performance:82,reliability:80,ease_of_use:76,intelligence:84,value:74,ecosystem:62,safety:84,design:74}),breakdown:{performance:82,reliability:80,ease_of_use:76,intelligence:84,value:74,ecosystem:62,safety:84,design:74}},

  // ═══ SECURITY (5) — mapped to "consumer" ═══
  {slug:"cobalt-robotics-guard",name:"Cobalt Robotics Security Robot",mfr:"cobalt-robotics",cat:"consumer",price:null,year:2024,status:"active",desc:"Indoor security robot with human-in-the-loop monitoring. Autonomous patrol with 60+ sensors. Live security specialist responds remotely to anomalies. Used in Fortune 500 offices.",specs:{height_cm:120,sensors:"60+ (cameras, thermal, lidar, badge reader)",patrol:"Autonomous + scheduled",monitoring:"24/7 remote specialist",clients:"Fortune 500"},score:cs({performance:78,reliability:80,ease_of_use:82,intelligence:82,value:72,ecosystem:68,safety:85,design:80}),breakdown:{performance:78,reliability:80,ease_of_use:82,intelligence:82,value:72,ecosystem:68,safety:85,design:80}},
  {slug:"pal-robotics-tiago",name:"PAL Robotics TIAGo",mfr:"pal-robotics",cat:"consumer",price:null,year:2023,status:"active",desc:"Versatile mobile manipulation robot from Barcelona. Used in research, retail, healthcare, and hospitality. Optional arm for object manipulation. ROS-based. 200+ units deployed globally.",specs:{height_cm:145,arm:"Optional 7-DOF",nav:"ROS SLAM",payload_kg:3,units_deployed:200,ros:true},score:cs({performance:74,reliability:78,ease_of_use:76,intelligence:78,value:70,ecosystem:75,safety:80,design:76}),breakdown:{performance:74,reliability:78,ease_of_use:76,intelligence:78,value:70,ecosystem:75,safety:80,design:76}},
  {slug:"ascento-guard",name:"Ascento Guard",mfr:"ascento",cat:"consumer",price:null,year:2024,status:"active",desc:"Two-wheeled balancing security robot from Swiss startup. Navigates outdoor terrain including stairs, curbs, and uneven ground. Autonomous perimeter patrol with HD cameras and thermal sensors.",specs:{locomotion:"2-wheel self-balancing",terrain:"Stairs, curbs, outdoor",sensors:"HD camera + thermal",patrol:"Autonomous perimeter",speed_kmh:10},score:cs({performance:76,reliability:74,ease_of_use:78,intelligence:78,value:68,ecosystem:55,safety:80,design:82}),breakdown:{performance:76,reliability:74,ease_of_use:78,intelligence:78,value:68,ecosystem:55,safety:80,design:82}},
  {slug:"otsaw-o-r3",name:"OTSAW O-R3",mfr:"otsaw",cat:"consumer",price:null,year:2023,status:"active",desc:"Autonomous outdoor security robot from Singapore. Patrols outdoor areas with 3D LiDAR, cameras, and facial recognition. Can deploy a surveillance drone from its roof for aerial view.",specs:{nav:"3D LiDAR SLAM",cameras:"360-degree + facial recognition",drone:"Deployable aerial drone",ip_rating:"IP65",speed_kmh:8},score:cs({performance:78,reliability:76,ease_of_use:76,intelligence:82,value:68,ecosystem:58,safety:82,design:78}),breakdown:{performance:78,reliability:76,ease_of_use:76,intelligence:82,value:68,ecosystem:58,safety:82,design:78}},
  {slug:"spot-security-config",name:"Boston Dynamics Spot (Security Config)",mfr:"boston-dynamics",cat:"consumer",price:84500,year:2024,status:"active",desc:"Spot configured for security patrols. Thermal cameras, 360-degree video, audio detection. Autonomous patrol routes with anomaly reporting. Used by data centers, industrial facilities, and campuses.",specs:{cameras:"Thermal + 360 RGB",audio:"Anomaly detection microphones",battery_hrs:1.5,gait:"Quadruped all-terrain",payload:"Spot CAM + thermal kit",patrol:"Autonomous scheduled routes"},score:cs({performance:85,reliability:86,ease_of_use:78,intelligence:84,value:68,ecosystem:85,safety:88,design:90}),breakdown:{performance:85,reliability:86,ease_of_use:78,intelligence:84,value:68,ecosystem:85,safety:88,design:90}},

  // ═══ ADDITIONAL WAREHOUSE (5) ═══
  {slug:"geek-plus-mp1000r",name:"Geek+ MP1000R",mfr:"geek-plus",cat:"warehouse",price:null,year:2024,status:"active",desc:"Heavy-duty goods-to-person AMR from Geek+. 1000kg payload for pallet-level movement. AI fleet management for 1000+ robot fleets. Deployed in Nike, Decathlon warehouses.",specs:{payload_kg:1000,speed_ms:1.5,battery_hrs:8,fleet:"1000+ robot coordination",clients:"Nike, Decathlon"},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:84,value:78,ecosystem:76,safety:82,design:72}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:84,value:78,ecosystem:76,safety:82,design:72}},
  {slug:"mujin-truckbot",name:"Mujin TruckBot",mfr:"mujin",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous truck unloading robot powered by MujinController. Real-time 3D perception picks mixed-SKU cases at 600+ cases/hour. No pre-programming needed per new SKU.",specs:{throughput:"600+ cases/hr",vision:"Real-time 3D perception",programming:"Zero-teach",type:"Truck unloading",payload_kg:30},score:cs({performance:84,reliability:80,ease_of_use:82,intelligence:88,value:74,ecosystem:68,safety:82,design:72}),breakdown:{performance:84,reliability:80,ease_of_use:82,intelligence:88,value:74,ecosystem:68,safety:82,design:72}},
  {slug:"symbotic-bot",name:"Symbotic Bot",mfr:"symbotic",cat:"warehouse",price:null,year:2024,status:"active",desc:"High-density warehouse automation robot that stores and retrieves cases in a dense 3D structure. Walmart's primary warehouse automation partner. AI-optimized storage and retrieval.",specs:{type:"3D grid storage/retrieval",partner:"Walmart",speed_ms:2.5,cases_per_hour:1500,ai:"Storage optimization"},score:cs({performance:88,reliability:82,ease_of_use:72,intelligence:86,value:76,ecosystem:72,safety:82,design:72}),breakdown:{performance:88,reliability:82,ease_of_use:72,intelligence:86,value:76,ecosystem:72,safety:82,design:72}},
  {slug:"exotec-skypod",name:"Exotec Skypod",mfr:"exotec",cat:"warehouse",price:null,year:2024,status:"active",desc:"3D goods-to-person warehouse robot that climbs racks up to 12m high. Combines horizontal movement with vertical climbing. Used by Uniqlo, Carrefour, Decathlon. French-made.",specs:{max_height_m:12,speed_ms:4,payload_kg:30,climbing:true,clients:"Uniqlo, Carrefour, Decathlon"},score:cs({performance:86,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:72,safety:82,design:82}),breakdown:{performance:86,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:72,safety:82,design:82}},
  {slug:"geek-plus-picking-p800",name:"Geek+ Picking Robot P800",mfr:"geek-plus",cat:"warehouse",price:null,year:2024,status:"active",desc:"Piece-picking robot combining AMR mobility with robotic arm. AI vision identifies and picks individual items from totes. 99.9% pick accuracy for e-commerce fulfillment.",specs:{payload_kg:5,picking_accuracy:"99.9%",arm_dof:6,vision:"AI + depth camera",type:"Mobile piece-picking"},score:cs({performance:82,reliability:78,ease_of_use:78,intelligence:86,value:74,ecosystem:74,safety:80,design:74}),breakdown:{performance:82,reliability:78,ease_of_use:78,intelligence:86,value:74,ecosystem:74,safety:80,design:74}},

  // ═══ ADDITIONAL CONSUMER (5) ═══
  {slug:"eufy-x10-pro-omni",name:"Eufy X10 Pro Omni",mfr:"eufy",cat:"consumer",price:800,year:2024,status:"active",desc:"Robot vacuum and mop with 8000Pa suction and auto-clean station. ProDetect 3D obstacle avoidance with AI. MopMaster spinning mop with 1kg pressure. Strong mid-range value.",specs:{suction_pa:8000,mop:"Spinning 1kg pressure",nav:"iPath LiDAR",obstacle:"ProDetect 3D AI",dustbin:"Self-empty + mop wash"},score:cs({performance:82,reliability:80,ease_of_use:86,intelligence:80,value:86,ecosystem:72,safety:80,design:78}),breakdown:{performance:82,reliability:80,ease_of_use:86,intelligence:80,value:86,ecosystem:72,safety:80,design:78}},
  {slug:"switchbot-mini-k10-plus",name:"SwitchBot Mini Robot K10+",mfr:"switchbot",cat:"consumer",price:400,year:2024,status:"active",desc:"Ultra-compact robot vacuum at just 24.8cm diameter. Fits under furniture standard robots cannot reach. Self-empty dock. Quiet operation at 48dB. Ideal for small apartments.",specs:{diameter_cm:24.8,suction_pa:2500,noise_db:48,dustbin:"Self-empty mini dock",nav:"LiDAR SLAM"},score:cs({performance:70,reliability:76,ease_of_use:88,intelligence:72,value:86,ecosystem:70,safety:80,design:84}),breakdown:{performance:70,reliability:76,ease_of_use:88,intelligence:72,value:86,ecosystem:70,safety:80,design:84}},
  {slug:"yeedi-floor-3-plus",name:"Yeedi Floor 3+",mfr:"yeedi",cat:"consumer",price:500,year:2024,status:"active",desc:"Budget-friendly robot vacuum and mop from Ecovacs sub-brand. 5100Pa suction, oscillating mop, self-empty station. ZeroTangle brush. Good value for price-conscious buyers.",specs:{suction_pa:5100,mop:"Oscillating",brush:"ZeroTangle",dustbin:"Self-empty 2.5L",nav:"TrueMapping LiDAR"},score:cs({performance:76,reliability:76,ease_of_use:84,intelligence:74,value:90,ecosystem:68,safety:78,design:74}),breakdown:{performance:76,reliability:76,ease_of_use:84,intelligence:74,value:90,ecosystem:68,safety:78,design:74}},
  {slug:"roborock-s8-maxv-ultra",name:"Roborock S8 MaxV Ultra",mfr:"roborock",cat:"consumer",price:1800,year:2024,status:"active",desc:"Roborock's top-tier flagship. 10,000Pa suction, dual spinning mop with hot water wash. Rocky AI 3.0 obstacle avoidance. FlexiArm extending side mop for edge cleaning.",specs:{suction_pa:10000,mop:"Dual spinning + hot wash 60C",nav:"LiDAR + 3D structured light",obstacle:"Rocky AI 3.0",edge_mop:"FlexiArm extending"},score:cs({performance:90,reliability:84,ease_of_use:86,intelligence:88,value:76,ecosystem:80,safety:80,design:84}),breakdown:{performance:90,reliability:84,ease_of_use:86,intelligence:88,value:76,ecosystem:80,safety:80,design:84}},
  {slug:"dreame-l20-ultra",name:"Dreame L20 Ultra",mfr:"dreame",cat:"consumer",price:1200,year:2024,status:"active",desc:"Premium robot vacuum with extending mop pad that reaches edges and corners. 7000Pa suction. Auto mop lifting on carpets. Dual-line LiDAR for precise mapping.",specs:{suction_pa:7000,mop:"Extending MopExtend",nav:"Dual-line LiDAR",carpet:"Auto mop lift",dustbin:"Self-empty 3.2L"},score:cs({performance:86,reliability:82,ease_of_use:86,intelligence:84,value:80,ecosystem:74,safety:80,design:80}),breakdown:{performance:86,reliability:82,ease_of_use:86,intelligence:84,value:80,ecosystem:74,safety:80,design:80}},

  // ═══ ADDITIONAL CONSTRUCTION (3) ═══
  {slug:"hilti-jaibot",name:"Hilti Jaibot",mfr:"hilti-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous ceiling drilling robot. Drills holes for MEP installations per BIM model. Reduces overhead drilling labor by 400%. Works from BIM coordinates directly.",specs:{application:"Ceiling drilling",accuracy_mm:5,bim_integration:true,drills_per_charge:500,productivity:"4x manual labor"},score:cs({performance:80,reliability:82,ease_of_use:76,intelligence:80,value:74,ecosystem:68,safety:82,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:76,intelligence:80,value:74,ecosystem:68,safety:82,design:72}},
  {slug:"okibo-painting-robot",name:"Okibo Painting Robot",mfr:"okibo",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous interior wall painting robot from Israel. Scans rooms with LiDAR, plans paint paths, and paints walls autonomously. 5x faster than manual painting with consistent quality.",specs:{application:"Interior wall painting",speed:"5x manual",scanning:"LiDAR room scan",paint_type:"Any standard paint",coverage_sqm_hr:100},score:cs({performance:78,reliability:76,ease_of_use:80,intelligence:78,value:76,ecosystem:55,safety:78,design:72}),breakdown:{performance:78,reliability:76,ease_of_use:80,intelligence:78,value:76,ecosystem:55,safety:78,design:72}},
  {slug:"spot-construction",name:"Boston Dynamics Spot (Construction Config)",mfr:"boston-dynamics",cat:"construction",price:78500,year:2024,status:"active",desc:"Spot configured for construction site monitoring. Autonomous progress documentation, BIM comparison, and safety hazard detection. Daily autonomous scans of active job sites.",specs:{cameras:"360 + LiDAR point cloud",bim:"BIM comparison",scanning:"Daily autonomous",reports:"Automated progress",ip_rating:"IP54"},score:cs({performance:86,reliability:86,ease_of_use:78,intelligence:86,value:70,ecosystem:85,safety:85,design:90}),breakdown:{performance:86,reliability:86,ease_of_use:78,intelligence:86,value:70,ecosystem:85,safety:85,design:90}},

  // ═══ ADDITIONAL MANUFACTURING (4) ═══
  {slug:"elite-ec66",name:"Elite Robots EC66",mfr:"elite-robots",cat:"manufacturing",price:20000,year:2024,status:"active",desc:"Chinese collaborative robot with 6kg payload and 914mm reach. Competitive alternative to Universal Robots at lower price point. Growing global dealer network.",specs:{payload_kg:6,reach_mm:914,dof:6,repeatability_mm:0.03,weight_kg:17.5,programming:"EliStudio"},score:cs({performance:76,reliability:76,ease_of_use:80,intelligence:74,value:90,ecosystem:62,safety:80,design:74}),breakdown:{performance:76,reliability:76,ease_of_use:80,intelligence:74,value:90,ecosystem:62,safety:80,design:74}},
  {slug:"hans-elfin-5",name:"Han's Robot Elfin 5",mfr:"han-robot",cat:"manufacturing",price:18000,year:2024,status:"active",desc:"Lightweight collaborative robot from Han's Robot (Franka Emika acquirer). 5kg payload, dual-sensor safety. Drag-and-drop programming. Aggressive pricing for global market expansion.",specs:{payload_kg:5,reach_mm:800,dof:6,repeatability_mm:0.02,weight_kg:15,safety:"Dual torque + current sensors"},score:cs({performance:74,reliability:74,ease_of_use:82,intelligence:72,value:92,ecosystem:58,safety:80,design:74}),breakdown:{performance:74,reliability:74,ease_of_use:82,intelligence:72,value:92,ecosystem:58,safety:80,design:74}},
  {slug:"abb-swifti-crb-1300",name:"ABB SWIFTI CRB 1300",mfr:"abb-robotics",cat:"manufacturing",price:45000,year:2024,status:"active",desc:"ABB high-speed collaborative robot. 11kg payload at industrial speeds with safe collaboration zones. Bridges gap between cobots and industrial robots. SafeMove safety system.",specs:{payload_kg:11,reach_mm:900,dof:6,speed:"5m/s",safety:"SafeMove collaborative zones",ip_rating:"IP67"},score:cs({performance:86,reliability:86,ease_of_use:78,intelligence:78,value:76,ecosystem:88,safety:86,design:78}),breakdown:{performance:86,reliability:86,ease_of_use:78,intelligence:78,value:76,ecosystem:88,safety:86,design:78}},
  {slug:"kuka-lbr-iisy-11",name:"KUKA LBR iisy 11",mfr:"kuka",cat:"manufacturing",price:40000,year:2024,status:"active",desc:"KUKA's latest sensitive collaborative robot. 11kg payload. Intuitive lead-through programming. iiQKA.OS operating system makes setup accessible to non-experts.",specs:{payload_kg:11,reach_mm:1300,dof:6,repeatability_mm:0.02,os:"iiQKA.OS",programming:"Lead-through + iiQKA"},score:cs({performance:84,reliability:84,ease_of_use:84,intelligence:78,value:76,ecosystem:84,safety:86,design:80}),breakdown:{performance:84,reliability:84,ease_of_use:84,intelligence:78,value:76,ecosystem:84,safety:86,design:80}},

  // ═══ ADDITIONAL MEDICAL (3) ═══
  {slug:"medtronic-hugo-ras",name:"Medtronic Hugo RAS",mfr:"medtronic",cat:"medical",price:null,year:2024,status:"active",desc:"Medtronic's modular robotic-assisted surgery system. Individual arm units allow flexible OR setup. Touch Surgery Enterprise for data analytics. Challenging da Vinci in general surgery.",specs:{arms:"Modular individual",instruments:"Fully wristed",analytics:"Touch Surgery Enterprise",application:"General, thoracic, urologic surgery"},score:cs({performance:82,reliability:78,ease_of_use:76,intelligence:82,value:72,ecosystem:72,safety:84,design:78}),breakdown:{performance:82,reliability:78,ease_of_use:76,intelligence:82,value:72,ecosystem:72,safety:84,design:78}},
  {slug:"stryker-mako-hip",name:"Stryker Mako SmartRobotics (Hip)",mfr:"stryker",cat:"medical",price:1200000,year:2024,status:"active",desc:"Robotic-arm assisted hip replacement system. CT-based 3D planning with haptic-guided bone preparation. AccuStop technology prevents cutting outside planned boundaries. 4,000+ systems installed.",specs:{application:"Total hip arthroplasty",planning:"CT-based 3D AccuPlan",guidance:"Haptic AccuStop boundaries",installations:4000},score:cs({performance:88,reliability:86,ease_of_use:78,intelligence:86,value:70,ecosystem:82,safety:90,design:78}),breakdown:{performance:88,reliability:86,ease_of_use:78,intelligence:86,value:70,ecosystem:82,safety:90,design:78}},
  {slug:"zimmer-biomet-rosa-spine",name:"Zimmer Biomet ROSA ONE Spine",mfr:"zimmer-biomet",cat:"medical",price:900000,year:2023,status:"active",desc:"Robotic guidance system for spine surgery. Provides stereotactic guidance for pedicle screw placement. 3D planning with intraoperative imaging integration. Sub-millimeter accuracy.",specs:{application:"Spine pedicle screw placement",accuracy_mm:0.8,planning:"3D CT-based",imaging:"Intraoperative integration",guidance:"Stereotactic robotic arm"},score:cs({performance:84,reliability:84,ease_of_use:76,intelligence:84,value:70,ecosystem:76,safety:88,design:74}),breakdown:{performance:84,reliability:84,ease_of_use:76,intelligence:84,value:70,ecosystem:76,safety:88,design:74}},

  // ═══ ADDITIONAL DRONES (2) ═══
  {slug:"skydio-x10d",name:"Skydio X10D",mfr:"skydio",cat:"drone",price:16000,year:2024,status:"active",desc:"US-made defense and enterprise drone. NDAA compliant. Thermal + visual + night vision cameras. Autonomous Skydio 3D Scan for digital twins. US Department of Defense approved.",specs:{cameras:"Thermal + RGB + NV",flight_time_min:35,range_km:8,autonomy:"Skydio Autonomy Enterprise",compliance:"NDAA, Blue sUAS",scan:"3D Scan digital twin"},score:cs({performance:86,reliability:84,ease_of_use:84,intelligence:90,value:74,ecosystem:78,safety:84,design:80}),breakdown:{performance:86,reliability:84,ease_of_use:84,intelligence:90,value:74,ecosystem:78,safety:84,design:80}},
  {slug:"dji-matrice-350-rtk",name:"DJI Matrice 350 RTK",mfr:"dji",cat:"drone",price:11000,year:2023,status:"active",desc:"DJI flagship enterprise drone platform. Interchangeable payloads including H20T thermal, L2 LiDAR, and P1 photogrammetry. 55-min flight time. RTK centimeter positioning.",specs:{flight_time_min:55,payloads:"H20T, L2 LiDAR, P1",positioning:"RTK centimeter",ip_rating:"IP55",range_km:20,max_payload_kg:2.7},score:cs({performance:90,reliability:88,ease_of_use:82,intelligence:84,value:80,ecosystem:90,safety:84,design:78}),breakdown:{performance:90,reliability:88,ease_of_use:82,intelligence:84,value:80,ecosystem:90,safety:84,design:78}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 4 Import: 80 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 4 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
