/**
 * Robotomated — Wave 18 Robot Import: 50 New Robots
 * Focus: Surgical robots, hospital logistics, pharmacy automation, rehabilitation, disinfection
 * Run: npx tsx scripts/import-robots-wave18.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

const newMfrs = [
  { slug: "medtronic-surgical", name: "Medtronic Surgical", country: "US", founded_year: 1949, website: "https://www.medtronic.com" },
  { slug: "stryker-robotics", name: "Stryker Robotics", country: "US", founded_year: 1941, website: "https://www.stryker.com" },
  { slug: "zimmer-biomet-rosa", name: "Zimmer Biomet", country: "US", founded_year: 1927, website: "https://www.zimmerbiomet.com" },
  { slug: "smith-nephew-robotics", name: "Smith+Nephew Robotics", country: "GB", founded_year: 1856, website: "https://www.smith-nephew.com" },
  { slug: "omnicell", name: "Omnicell", country: "US", founded_year: 1992, website: "https://www.omnicell.com" },
  { slug: "bd-rowa", name: "BD Rowa", country: "DE", founded_year: 1979, website: "https://www.bd.com/rowa" },
  { slug: "diligent-robotics", name: "Diligent Robotics", country: "US", founded_year: 2017, website: "https://www.diligentrobots.com" },
  { slug: "aethon", name: "Aethon", country: "US", founded_year: 2001, website: "https://aethon.com" },
  { slug: "xenex", name: "Xenex Disinfection Services", country: "US", founded_year: 2009, website: "https://www.xenex.com" },
  { slug: "rewalk-robotics", name: "ReWalk Robotics", country: "IL", founded_year: 2001, website: "https://rewalk.com" },
];

const robots: R[] = [
  // Intuitive Surgical — 5 systems (mfr already in DB as "intuitive-surgical")
  (() => { const b = { performance: 95, reliability: 93, ease_of_use: 78, intelligence: 88, value: 60, ecosystem: 90, safety: 94, design: 90 }; return { slug: "intuitive-da-vinci-5", name: "da Vinci 5", mfr: "intuitive-surgical", cat: "medical", price: 2500000, year: 2024, status: "active", desc: "Fifth-generation surgical robot with force feedback, 10,000x digital zoom, and AI-powered tissue analytics for multi-quadrant general surgery.", specs: { arms: 4, instruments: "8mm EndoWrist", degrees_of_freedom: 7, tremor_filtration: "enhanced", vision: "3D 10,000x zoom", force_feedback: true, clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 90, reliability: 92, ease_of_use: 80, intelligence: 85, value: 65, ecosystem: 88, safety: 93, design: 88 }; return { slug: "intuitive-da-vinci-sp", name: "da Vinci SP", mfr: "intuitive-surgical", cat: "medical", price: 1800000, year: 2023, status: "active", desc: "Single-port surgical system delivering three articulating instruments and a camera through a single 25 mm cannula for transoral and urologic procedures.", specs: { arms: 3, port_size: "25 mm single", instruments: "6mm flexible", vision: "3D HD", dof_per_arm: 7, procedures: "transoral, urologic", clearance: "FDA" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 88, reliability: 91, ease_of_use: 82, intelligence: 83, value: 68, ecosystem: 87, safety: 92, design: 86 }; return { slug: "intuitive-da-vinci-xi", name: "da Vinci Xi", mfr: "intuitive-surgical", cat: "medical", price: 2000000, year: 2022, status: "active", desc: "Multi-port platform optimized for complex multi-quadrant procedures with overhead arm architecture enabling access from any position.", specs: { arms: 4, instruments: "8mm EndoWrist", vision: "3D HD fluorescence", dof_per_arm: 7, boom: "overhead rotating", procedures: "general, thoracic, colorectal", clearance: "FDA" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 88, ease_of_use: 85, intelligence: 80, value: 75, ecosystem: 85, safety: 91, design: 84 }; return { slug: "intuitive-ion", name: "Intuitive Ion", mfr: "intuitive-surgical", cat: "medical", price: 800000, year: 2023, status: "active", desc: "Robotic bronchoscopy platform using shape-sensing technology to navigate thin peripheral airways for minimally invasive lung biopsy.", specs: { catheter_od: "3.5 mm", navigation: "shape-sensing fiber optic", reach: "all 18 lung segments", vision: "radial EBUS integration", biopsy_tools: "needle, forceps, brush", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 86, ease_of_use: 88, intelligence: 82, value: 72, ecosystem: 80, safety: 90, design: 82 }; return { slug: "intuitive-simnovus", name: "Intuitive SimNovus", mfr: "intuitive-surgical", cat: "medical", price: 150000, year: 2024, status: "active", desc: "Surgical simulation platform providing haptic-feedback training on da Vinci procedures with AI-scored performance metrics and skill progression tracking.", specs: { haptic_feedback: true, procedures: "30+ simulated", scoring: "AI performance metrics", compatibility: "da Vinci Xi, SP, 5", multiplayer: "dual console", latency: "< 5 ms" }, score: cs(b), breakdown: b }; })(),

  // Medtronic Hugo — 5 surgical robots
  (() => { const b = { performance: 86, reliability: 84, ease_of_use: 80, intelligence: 84, value: 72, ecosystem: 75, safety: 90, design: 83 }; return { slug: "medtronic-hugo-ras", name: "Medtronic Hugo RAS", mfr: "medtronic-surgical", cat: "medical", price: 1500000, year: 2024, status: "active", desc: "Modular robotic-assisted surgery system with independent arm carts that can be positioned around the patient for urologic and gynecologic procedures.", specs: { arms: 4, arm_type: "independent cart-based", instruments: "wristed 8mm", vision: "3D 4K", dof_per_arm: 7, modularity: "independent carts", clearance: "CE Mark" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 82, ease_of_use: 81, intelligence: 83, value: 74, ecosystem: 73, safety: 89, design: 81 }; return { slug: "medtronic-hugo-single-port", name: "Medtronic Hugo SP", mfr: "medtronic-surgical", cat: "medical", price: 1200000, year: 2025, status: "active", desc: "Single-port variant of the Hugo platform with three flexible instruments through a 30 mm incision for reduced scarring cholecystectomy.", specs: { arms: 3, port_size: "30 mm", instruments: "flexible wristed", vision: "3D HD", modularity: "single cart", procedures: "cholecystectomy, hernia", clearance: "CE Mark" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 81, ease_of_use: 84, intelligence: 81, value: 78, ecosystem: 71, safety: 88, design: 80 }; return { slug: "medtronic-hugo-trainer", name: "Medtronic Hugo Trainer", mfr: "medtronic-surgical", cat: "medical", price: 120000, year: 2024, status: "active", desc: "Dedicated Hugo simulation console with curriculum-based training modules and dual-console mentoring capability for proctor-supervised case support.", specs: { training_modules: 25, haptic_feedback: true, dual_console: true, scoring: "automated metrics", vr_integration: true, procedures: "urology, gynecology" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 83, ease_of_use: 79, intelligence: 85, value: 70, ecosystem: 74, safety: 91, design: 82 }; return { slug: "medtronic-hugo-thoracic", name: "Medtronic Hugo Thoracic", mfr: "medtronic-surgical", cat: "medical", price: 1600000, year: 2025, status: "active", desc: "Thoracic-optimized Hugo configuration with slimmer arm profiles and CO2 insufflation management for video-assisted thoracoscopic surgery.", specs: { arms: 4, instruments: "6mm thoracic", vision: "3D 4K + near-infrared", insufflation: "integrated CO2", access: "intercostal optimized", clearance: "CE Mark pending" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 84, ease_of_use: 78, intelligence: 86, value: 68, ecosystem: 76, safety: 90, design: 84 }; return { slug: "medtronic-hugo-colorectal", name: "Medtronic Hugo Colorectal", mfr: "medtronic-surgical", cat: "medical", price: 1550000, year: 2025, status: "active", desc: "Colorectal surgery platform leveraging Hugo modular arms with ICG fluorescence imaging for real-time perfusion assessment during anastomosis.", specs: { arms: 4, instruments: "wristed 8mm + stapler", vision: "3D 4K + ICG fluorescence", imaging: "real-time perfusion", modularity: "multi-quadrant", clearance: "CE Mark" }, score: cs(b), breakdown: b }; })(),

  // Stryker Mako — 5 surgical systems
  (() => { const b = { performance: 90, reliability: 90, ease_of_use: 82, intelligence: 87, value: 66, ecosystem: 82, safety: 93, design: 87 }; return { slug: "stryker-mako-total-knee", name: "Stryker Mako Total Knee", mfr: "stryker-robotics", cat: "medical", price: 1200000, year: 2024, status: "active", desc: "CT-based robotic arm-assisted total knee arthroplasty system with AccuStop haptic boundaries preventing bone cuts beyond the pre-operative plan.", specs: { procedure: "total knee arthroplasty", planning: "CT-based 3D", haptic: "AccuStop boundaries", arm_type: "surgeon-controlled robotic", accuracy: "sub-millimeter", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 89, reliability: 89, ease_of_use: 83, intelligence: 86, value: 67, ecosystem: 81, safety: 92, design: 86 }; return { slug: "stryker-mako-total-hip", name: "Stryker Mako Total Hip", mfr: "stryker-robotics", cat: "medical", price: 1200000, year: 2024, status: "active", desc: "Robotic total hip arthroplasty with 3D CT planning for precise acetabular cup positioning and real-time leg length and offset calculations.", specs: { procedure: "total hip arthroplasty", planning: "CT-based 3D", haptic: "AccuStop boundaries", cup_accuracy: "±1° inclination", leg_length: "real-time calculation", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 87, reliability: 88, ease_of_use: 81, intelligence: 85, value: 68, ecosystem: 80, safety: 91, design: 85 }; return { slug: "stryker-mako-partial-knee", name: "Stryker Mako Partial Knee", mfr: "stryker-robotics", cat: "medical", price: 1100000, year: 2023, status: "active", desc: "Robotic partial knee replacement preserving healthy bone and ligaments with haptic-guided bone preparation for unicompartmental and patellofemoral procedures.", specs: { procedure: "partial knee arthroplasty", compartments: "medial, lateral, patellofemoral", planning: "CT-based 3D", haptic: "AccuStop", bone_preservation: "maximized", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 86, ease_of_use: 80, intelligence: 84, value: 65, ecosystem: 78, safety: 90, design: 84 }; return { slug: "stryker-mako-shoulder", name: "Stryker Mako Shoulder", mfr: "stryker-robotics", cat: "medical", price: 1300000, year: 2025, status: "active", desc: "First robotic-arm assisted total shoulder arthroplasty system with CT-based planning for glenoid preparation and humeral stem alignment.", specs: { procedure: "total shoulder arthroplasty", planning: "CT-based 3D", haptic: "AccuStop boundaries", glenoid_accuracy: "±1.5°", arm_type: "surgeon-controlled", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 87, ease_of_use: 84, intelligence: 83, value: 70, ecosystem: 79, safety: 91, design: 83 }; return { slug: "stryker-mako-spine", name: "Stryker Mako Spine", mfr: "stryker-robotics", cat: "medical", price: 1400000, year: 2025, status: "active", desc: "Robotic-assisted spinal surgery platform for pedicle screw placement with intraoperative CT guidance and real-time instrument tracking.", specs: { procedure: "spinal fusion, pedicle screws", planning: "intraoperative CT", tracking: "real-time 3D", screw_accuracy: "97.5% Gertzbein A/B", navigation: "integrated optical", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),

  // Pharmacy automation — 5 (Omnicell + BD Rowa)
  (() => { const b = { performance: 84, reliability: 87, ease_of_use: 80, intelligence: 78, value: 74, ecosystem: 76, safety: 90, design: 75 }; return { slug: "omnicell-xt-automated-dispensing", name: "Omnicell XT Automated Dispensing Cabinet", mfr: "omnicell", cat: "medical", price: 65000, year: 2024, status: "active", desc: "Point-of-care medication dispensing cabinet with biometric access, barcode verification, and real-time inventory tracking for floor-stock management.", specs: { capacity: "500+ medications", access: "biometric + badge", verification: "barcode scan", inventory: "real-time par levels", integration: "EHR/ADT", dimensions: "150x60x65 cm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 86, reliability: 88, ease_of_use: 77, intelligence: 80, value: 70, ecosystem: 78, safety: 92, design: 76 }; return { slug: "omnicell-central-pharmacy-robot", name: "Omnicell Central Pharmacy Robot", mfr: "omnicell", cat: "medical", price: 450000, year: 2024, status: "active", desc: "Central pharmacy robotic dispensing system picking and packaging unit-dose medications with 99.99% accuracy and barcode-verified labeling.", specs: { throughput: "800 doses/hr", accuracy: "99.99%", capacity: "2,000+ NDCs", labeling: "barcode verified", packaging: "unit-dose", integration: "pharmacy information system" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 89, ease_of_use: 79, intelligence: 79, value: 72, ecosystem: 77, safety: 91, design: 78 }; return { slug: "bd-rowa-vmax", name: "BD Rowa Vmax", mfr: "bd-rowa", cat: "medical", price: 380000, year: 2024, status: "active", desc: "High-speed pharmacy robot storing up to 35,000 packages with pick times under 4 seconds and automatic expiry date management.", specs: { capacity: "35,000 packages", pick_time: "< 4 seconds", throughput: "900 picks/hr", expiry_management: "automatic FEFO", dimensions: "scalable modular", integration: "pharmacy POS" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 86, ease_of_use: 81, intelligence: 77, value: 76, ecosystem: 74, safety: 89, design: 74 }; return { slug: "bd-rowa-smart", name: "BD Rowa Smart", mfr: "bd-rowa", cat: "medical", price: 180000, year: 2025, status: "active", desc: "Compact pharmacy automation for community pharmacies storing 10,000 packages with touchscreen dispensing and patient pickup notification.", specs: { capacity: "10,000 packages", pick_time: "< 5 seconds", footprint: "3x1.5 m", patient_notification: "SMS/app", integration: "pharmacy POS", power: "1.2 kW" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 85, ease_of_use: 83, intelligence: 76, value: 78, ecosystem: 72, safety: 88, design: 73 }; return { slug: "omnicell-iv-compounder", name: "Omnicell IV Compounder", mfr: "omnicell", cat: "medical", price: 320000, year: 2025, status: "active", desc: "Automated IV compounding robot preparing sterile intravenous medications with gravimetric verification and USP 797 compliant workflows.", specs: { throughput: "200 IVs/hr", accuracy: "gravimetric ±1%", compliance: "USP 797", verification: "barcode + gravimetric", environment: "ISO Class 5", drugs: "500+ formulary" }, score: cs(b), breakdown: b }; })(),

  // Hospital logistics — 5 (Diligent Moxi + Aethon TUG)
  (() => { const b = { performance: 79, reliability: 80, ease_of_use: 84, intelligence: 82, value: 73, ecosystem: 71, safety: 86, design: 82 }; return { slug: "diligent-moxi", name: "Diligent Moxi", mfr: "diligent-robotics", cat: "medical", price: null, year: 2024, status: "active", desc: "Hospital service robot with a mobile manipulator arm autonomously delivering lab samples, medications, and supplies to nursing stations 24/7.", specs: { payload: "10 kg", speed: "1.2 m/s", arm_reach: "700 mm", battery: "10 hr runtime", navigation: "LiDAR + elevator integration", tasks: "delivery, fetch, restock" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 82, ease_of_use: 82, intelligence: 80, value: 75, ecosystem: 73, safety: 87, design: 78 }; return { slug: "diligent-moxi-plus", name: "Diligent Moxi Plus", mfr: "diligent-robotics", cat: "medical", price: null, year: 2025, status: "active", desc: "Enhanced Moxi with dual-arm manipulation for handling biohazard containers and sterile supply carts across multi-floor hospital campuses.", specs: { payload: "20 kg", speed: "1.5 m/s", arms: 2, battery: "14 hr runtime", navigation: "LiDAR + 3D vision", elevator: "automatic integration" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 83, ease_of_use: 80, intelligence: 78, value: 74, ecosystem: 75, safety: 85, design: 76 }; return { slug: "aethon-tug-t3", name: "Aethon TUG T3", mfr: "aethon", cat: "medical", price: null, year: 2024, status: "active", desc: "Autonomous mobile robot transporting pharmacy carts, meals, and linens through hospital corridors with cloud-based fleet management for up to 30 robots.", specs: { payload: "600 kg cart tow", speed: "1.0 m/s", battery: "10 hr runtime", fleet_size: "up to 30", navigation: "LiDAR + infrastructure-free", integration: "elevator, door, EHR" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 81, ease_of_use: 83, intelligence: 77, value: 77, ecosystem: 72, safety: 84, design: 75 }; return { slug: "aethon-tug-pharmacy", name: "Aethon TUG Pharmacy", mfr: "aethon", cat: "medical", price: null, year: 2025, status: "active", desc: "Pharmacy-specific TUG variant with locked medication drawers, biometric access, and chain-of-custody tracking for controlled substance delivery.", specs: { payload: "200 kg", drawers: "6 locked", access: "biometric + PIN", tracking: "chain-of-custody", compliance: "DEA Schedule II-V", speed: "1.0 m/s" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 80, ease_of_use: 81, intelligence: 79, value: 76, ecosystem: 70, safety: 85, design: 77 }; return { slug: "aethon-tug-linen", name: "Aethon TUG Linen", mfr: "aethon", cat: "medical", price: null, year: 2024, status: "active", desc: "Dedicated linen and waste transport robot with sealed compartments for infection control, handling 24 cart exchanges per shift autonomously.", specs: { payload: "500 kg cart tow", compartments: "sealed biohazard-rated", exchanges: "24 per shift", battery: "12 hr runtime", navigation: "LiDAR", cleaning: "wipe-down compatible" }, score: cs(b), breakdown: b }; })(),

  // Disinfection robots — 5 (Xenex + UVD)
  (() => { const b = { performance: 83, reliability: 84, ease_of_use: 85, intelligence: 76, value: 75, ecosystem: 68, safety: 88, design: 79 }; return { slug: "xenex-lightstrike-5", name: "Xenex LightStrike 5", mfr: "xenex", cat: "medical", price: 125000, year: 2024, status: "active", desc: "Pulsed xenon UV disinfection robot destroying 99.9% of pathogens including C. diff spores in a full room cycle of under 10 minutes.", specs: { uv_type: "pulsed xenon", cycle_time: "< 10 min full room", efficacy: "99.9% pathogen kill", coverage: "full room 360°", power: "xenon flash lamp", weight: "100 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 85, ease_of_use: 83, intelligence: 78, value: 72, ecosystem: 70, safety: 89, design: 80 }; return { slug: "xenex-lightstrike-5-auto", name: "Xenex LightStrike 5 Auto", mfr: "xenex", cat: "medical", price: 165000, year: 2025, status: "active", desc: "Autonomous variant navigating between patient rooms on a programmed schedule, self-positioning and running disinfection cycles without staff intervention.", specs: { uv_type: "pulsed xenon", cycle_time: "< 10 min", autonomous: true, navigation: "LiDAR + room mapping", scheduling: "cloud-based", rooms_per_charge: 15 }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 83, ease_of_use: 84, intelligence: 75, value: 77, ecosystem: 67, safety: 87, design: 78 }; return { slug: "uvd-robots-model-d", name: "UVD Robot Model D", mfr: "xenex", cat: "medical", price: 98000, year: 2024, status: "active", desc: "UV-C disinfection robot with 8 mercury-free UV-C lamps providing 360-degree coverage and autonomous navigation between treatment areas.", specs: { uv_type: "UV-C LED array", lamps: 8, cycle_time: "15 min standard room", navigation: "autonomous LiDAR", efficacy: "99.99% on surfaces", weight: "140 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 80, ease_of_use: 86, intelligence: 73, value: 80, ecosystem: 65, safety: 86, design: 76 }; return { slug: "xenex-lightstrike-portable", name: "Xenex LightStrike Portable", mfr: "xenex", cat: "medical", price: 55000, year: 2025, status: "active", desc: "Compact portable UV disinfection unit for ambulances, isolation rooms, and field hospitals, completing targeted surface decontamination in 3 minutes.", specs: { uv_type: "pulsed xenon", cycle_time: "3 min targeted", weight: "35 kg", portable: true, coverage: "directional 180°", power: "battery + AC" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 82, ease_of_use: 82, intelligence: 77, value: 74, ecosystem: 69, safety: 90, design: 77 }; return { slug: "xenex-lightstrike-or", name: "Xenex LightStrike OR", mfr: "xenex", cat: "medical", price: 145000, year: 2025, status: "active", desc: "Operating room optimized disinfection robot with accelerated cycle times and equipment-safe UV dosimetry to protect sensitive surgical instruments.", specs: { uv_type: "pulsed xenon", cycle_time: "5 min OR cycle", dosimetry: "equipment-safe adaptive", coverage: "360° elevated", integration: "OR scheduling system", clearance: "FDA listed" }, score: cs(b), breakdown: b }; })(),

  // Rehabilitation robots — 5 (ReWalk + Ekso)
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 72, intelligence: 75, value: 60, ecosystem: 70, safety: 90, design: 82 }; return { slug: "rewalk-personal-6", name: "ReWalk Personal 6.0", mfr: "rewalk-robotics", cat: "medical", price: 85000, year: 2024, status: "active", desc: "Wearable robotic exoskeleton enabling paraplegic individuals to stand and walk independently with tilt-sensor initiated stepping and crutch-assisted balance.", specs: { user_height: "160-190 cm", user_weight: "up to 100 kg", speed: "0.5 m/s", battery: "4 hr walking", weight: "23 kg", dof: "hip + knee bilateral", clearance: "FDA personal use" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 83, ease_of_use: 75, intelligence: 78, value: 58, ecosystem: 72, safety: 91, design: 83 }; return { slug: "rewalk-restore", name: "ReWalk ReStore", mfr: "rewalk-robotics", cat: "medical", price: 45000, year: 2024, status: "active", desc: "Soft robotic exo-suit for stroke rehabilitation providing powered ankle dorsiflexion and plantarflexion assistance during gait training.", specs: { target: "stroke rehabilitation", assistance: "ankle dorsi/plantarflexion", design: "soft exo-suit", weight: "5 kg", battery: "6 hr", sensors: "IMU + force", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 84, ease_of_use: 74, intelligence: 79, value: 56, ecosystem: 73, safety: 92, design: 84 }; return { slug: "rewalk-ekso-nv", name: "Ekso NR", mfr: "rewalk-robotics", cat: "medical", price: 120000, year: 2025, status: "active", desc: "Clinical exoskeleton for neurorehabilitation with variable assistance algorithms that adapt in real-time to patient effort during over-ground walking.", specs: { user_height: "155-193 cm", user_weight: "up to 100 kg", assistance: "variable adaptive", speed: "adjustable to 0.7 m/s", battery: "4 hr", weight: "25 kg", clearance: "FDA clinical" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 81, ease_of_use: 78, intelligence: 76, value: 65, ecosystem: 68, safety: 89, design: 80 }; return { slug: "rewalk-hand-rehab", name: "ReWalk Hand Rehab", mfr: "rewalk-robotics", cat: "medical", price: 28000, year: 2025, status: "active", desc: "Robotic hand rehabilitation glove with individual finger actuation for post-stroke motor recovery, featuring gamified therapy exercises.", specs: { fingers: "5 individually actuated", assistance: "flexion + extension", therapy: "gamified exercises", sensors: "force + position per finger", weight: "0.6 kg", battery: "3 hr", sessions: "clinic + home" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 82, ease_of_use: 76, intelligence: 77, value: 62, ecosystem: 71, safety: 91, design: 81 }; return { slug: "rewalk-pediatric-exo", name: "ReWalk Pediatric Exo", mfr: "rewalk-robotics", cat: "medical", price: 95000, year: 2025, status: "active", desc: "Size-adjustable pediatric exoskeleton for children ages 4-14 with spinal cord injuries, growing with the child through modular limb segments.", specs: { age_range: "4-14 years", height_range: "100-165 cm", weight_range: "15-50 kg", adjustability: "modular limb segments", battery: "3 hr", weight: "12 kg", clearance: "CE Mark" }, score: cs(b), breakdown: b }; })(),

  // Zimmer Biomet ROSA — 5 surgical
  (() => { const b = { performance: 86, reliability: 86, ease_of_use: 81, intelligence: 84, value: 69, ecosystem: 78, safety: 91, design: 83 }; return { slug: "zimmer-rosa-knee", name: "Zimmer Biomet ROSA Knee", mfr: "zimmer-biomet-rosa", cat: "medical", price: 950000, year: 2024, status: "active", desc: "Robotic surgical assistant for total knee arthroplasty with predictive bone modeling that eliminates the need for pre-operative CT scans.", specs: { procedure: "total knee arthroplasty", planning: "CT-free predictive modeling", guidance: "robotic arm-assisted", accuracy: "sub-millimeter", sensors: "intraoperative bone mapping", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 85, ease_of_use: 80, intelligence: 83, value: 70, ecosystem: 77, safety: 90, design: 82 }; return { slug: "zimmer-rosa-hip", name: "Zimmer Biomet ROSA Hip", mfr: "zimmer-biomet-rosa", cat: "medical", price: 950000, year: 2024, status: "active", desc: "Hip arthroplasty robotic system with fluoroscopy-integrated planning for precise cup placement and real-time leg length equalization.", specs: { procedure: "total hip arthroplasty", planning: "fluoroscopy + 3D", guidance: "robotic positioning", accuracy: "±1° cup placement", leg_length: "real-time equalization", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 87, reliability: 87, ease_of_use: 78, intelligence: 86, value: 67, ecosystem: 79, safety: 92, design: 84 }; return { slug: "zimmer-rosa-spine", name: "Zimmer Biomet ROSA Spine", mfr: "zimmer-biomet-rosa", cat: "medical", price: 1100000, year: 2024, status: "active", desc: "Spinal surgery robot providing stereotactic guidance for pedicle screw, interbody cage, and electrode placement with 98% accuracy in Grade A screws.", specs: { procedure: "spinal fusion, neuro", guidance: "stereotactic robotic arm", accuracy: "98% Gertzbein A", planning: "intraoperative 3D", tracking: "optical + robotic", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 84, ease_of_use: 79, intelligence: 82, value: 71, ecosystem: 76, safety: 90, design: 81 }; return { slug: "zimmer-rosa-partial-knee", name: "Zimmer Biomet ROSA Partial Knee", mfr: "zimmer-biomet-rosa", cat: "medical", price: 900000, year: 2025, status: "active", desc: "Unicompartmental knee replacement robotic platform with dynamic ligament balancing that adjusts implant positioning based on intraoperative flexion data.", specs: { procedure: "partial knee arthroplasty", planning: "CT-free + dynamic", balancing: "real-time ligament", guidance: "robotic arm", accuracy: "sub-degree alignment", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 85, ease_of_use: 82, intelligence: 85, value: 68, ecosystem: 77, safety: 91, design: 82 }; return { slug: "zimmer-rosa-one-brain", name: "Zimmer Biomet ROSA One Brain", mfr: "zimmer-biomet-rosa", cat: "medical", price: 750000, year: 2024, status: "active", desc: "Neurosurgical robotic platform for stereoelectroencephalography electrode placement and deep brain stimulation with sub-millimeter trajectory accuracy.", specs: { procedure: "SEEG, DBS, biopsy", accuracy: "< 1 mm trajectory", planning: "MRI/CT fusion", arms: 1, registration: "laser + frameless", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),

  // Smith+Nephew — 5 surgical robots
  (() => { const b = { performance: 84, reliability: 83, ease_of_use: 82, intelligence: 83, value: 71, ecosystem: 74, safety: 89, design: 82 }; return { slug: "smith-nephew-cori", name: "Smith+Nephew CORI", mfr: "smith-nephew-robotics", cat: "medical", price: 850000, year: 2024, status: "active", desc: "Handheld robotic sculpting system for knee arthroplasty that the surgeon wields directly, with haptic boundary control confining bone removal to the plan.", specs: { procedure: "total + partial knee", type: "handheld robotic", haptic: "active boundary control", planning: "image-free intraop", sculpting: "burr-based", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 82, ease_of_use: 84, intelligence: 81, value: 73, ecosystem: 72, safety: 88, design: 80 }; return { slug: "smith-nephew-cori-hip", name: "Smith+Nephew CORI Hip", mfr: "smith-nephew-robotics", cat: "medical", price: 850000, year: 2025, status: "active", desc: "Hip arthroplasty extension of the CORI platform with acetabular reaming guidance and real-time component orientation feedback.", specs: { procedure: "total hip arthroplasty", type: "handheld robotic", haptic: "guided reaming", planning: "intraoperative mapping", accuracy: "±1.5° cup", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 81, ease_of_use: 83, intelligence: 80, value: 75, ecosystem: 71, safety: 87, design: 79 }; return { slug: "smith-nephew-cori-revision", name: "Smith+Nephew CORI Revision", mfr: "smith-nephew-robotics", cat: "medical", price: 900000, year: 2025, status: "active", desc: "Revision knee surgery module for CORI handling bone defect mapping and augment planning for complex re-do knee arthroplasty cases.", specs: { procedure: "revision knee arthroplasty", defect_mapping: "3D intraoperative", augment_planning: "AI-assisted", bone_removal: "precision burr", compatibility: "CORI platform", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 80, ease_of_use: 80, intelligence: 82, value: 72, ecosystem: 70, safety: 88, design: 81 }; return { slug: "smith-nephew-navio-sports", name: "Smith+Nephew NAVIO Sports Med", mfr: "smith-nephew-robotics", cat: "medical", price: 650000, year: 2024, status: "active", desc: "Robotic-assisted platform for sports medicine osteotomy procedures with image-free planning and real-time cut guidance for high tibial corrections.", specs: { procedure: "high tibial osteotomy", planning: "image-free", guidance: "robotic saw control", accuracy: "±1° correction", tracking: "optical markers", clearance: "FDA 510(k)" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 82, ease_of_use: 81, intelligence: 84, value: 69, ecosystem: 73, safety: 89, design: 83 }; return { slug: "smith-nephew-cori-shoulder", name: "Smith+Nephew CORI Shoulder", mfr: "smith-nephew-robotics", cat: "medical", price: 920000, year: 2025, status: "active", desc: "Shoulder arthroplasty module with glenoid baseplate positioning guidance and 3D bone stock assessment for reverse and anatomic implant planning.", specs: { procedure: "total shoulder arthroplasty", type: "handheld robotic", glenoid: "baseplate guidance", planning: "3D bone stock assessment", implants: "anatomic + reverse", clearance: "CE Mark" }, score: cs(b), breakdown: b }; })(),

  // Other medical robots — 5 (telepresence, lab automation)
  (() => { const b = { performance: 76, reliability: 79, ease_of_use: 85, intelligence: 78, value: 77, ecosystem: 72, safety: 83, design: 80 }; return { slug: "ava-telepresence-500", name: "Ava Telepresence 500", mfr: "aethon", cat: "medical", price: 35000, year: 2024, status: "active", desc: "Medical telepresence robot enabling remote physician consultations with 4K video, directional audio, and autonomous navigation to patient bedsides.", specs: { video: "4K pan-tilt-zoom", audio: "directional array", speed: "1.5 m/s", battery: "8 hr", navigation: "autonomous LiDAR", screen: "10.1 inch", weight: "35 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 85, ease_of_use: 78, intelligence: 80, value: 73, ecosystem: 76, safety: 87, design: 75 }; return { slug: "bd-kiestra-total-lab", name: "BD Kiestra TotalLab Automation", mfr: "bd-rowa", cat: "medical", price: 800000, year: 2024, status: "active", desc: "Full microbiology lab automation system with robotic specimen processing, plate inoculation, incubation, and AI-assisted colony morphology reading.", specs: { throughput: "400 specimens/hr", processes: "inoculate, streak, incubate, image", imaging: "AI colony morphology", capacity: "10,000 plates", integration: "LIS bidirectional", footprint: "15x4 m" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 82, ease_of_use: 80, intelligence: 77, value: 75, ecosystem: 71, safety: 85, design: 74 }; return { slug: "omnicell-xr2-counting", name: "Omnicell XR2 Counting System", mfr: "omnicell", cat: "medical", price: 95000, year: 2025, status: "active", desc: "Automated pill counting and bottle-filling robot for outpatient pharmacy with image-verified dispensing and real-time inventory reconciliation.", specs: { throughput: "150 Rx/hr", capacity: "256 drug cells", verification: "image-based counting", accuracy: "99.97%", integration: "pharmacy system", dimensions: "90x60x180 cm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 80, ease_of_use: 82, intelligence: 76, value: 79, ecosystem: 69, safety: 84, design: 77 }; return { slug: "diligent-moxi-lab", name: "Diligent Moxi Lab Runner", mfr: "diligent-robotics", cat: "medical", price: null, year: 2025, status: "active", desc: "Moxi variant optimized for clinical lab specimen transport with temperature-controlled compartments and pneumatic tube bypass for stat samples.", specs: { payload: "8 kg", compartments: "2 temperature-controlled", temps: "ambient + 2-8°C", speed: "1.2 m/s", battery: "10 hr", stat_priority: "auto-escalation" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 75, reliability: 78, ease_of_use: 84, intelligence: 74, value: 80, ecosystem: 67, safety: 83, design: 76 }; return { slug: "aethon-tug-meals", name: "Aethon TUG MealBot", mfr: "aethon", cat: "medical", price: null, year: 2025, status: "active", desc: "Dietary-service TUG variant with insulated heated and chilled compartments delivering patient meals on schedule with dietary restriction verification.", specs: { payload: "300 kg cart", compartments: "heated + chilled", meals_per_trip: 20, verification: "barcode + room match", speed: "1.0 m/s", battery: "10 hr" }, score: cs(b), breakdown: b }; })(),
];

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 18 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 18 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
