/**
 * Robotomated — Wave 13 Robot Import: 50 New Robots
 * Focus: Traditional industrial robots, welding robots, painting robots, assembly robots
 * Run: npx tsx scripts/import-robots-wave13.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  { slug: "daifuku", name: "Daifuku", country: "JP", founded_year: 1937, website: "https://daifuku.com" },
  { slug: "dematic", name: "Dematic", country: "US", founded_year: 1819, website: "https://dematic.com" },
  { slug: "honeywell-robotics", name: "Honeywell Robotics", country: "US", founded_year: 1906, website: "https://honeywell.com" },
  { slug: "swisslog", name: "Swisslog", country: "CH", founded_year: 1900, website: "https://swisslog.com" },
];

// ═══════════════════════════════════════════════════════════════
// ROBOTS — 50 total (10 FANUC, 8 ABB, 8 KUKA, 8 Yaskawa, 6 Daifuku, 5 Dematic, 5 Swisslog)
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

// ═══ FANUC Industrial Robots (10) ═══
{slug:"fanuc-m-20id-35",name:"FANUC M-20iD/35",mfr:"fanuc",cat:"manufacturing",price:65000,year:2024,status:"active",desc:"Compact 6-axis industrial robot with 35 kg payload and 1831 mm reach. Optimized for high-speed material handling and machine tending in tight cell layouts. Integrated cable routing reduces interference.",specs:{axes:6,payload_kg:35,reach_mm:1831,repeatability_mm:0.04,weight_kg:250,controller:"R-30iB Plus",protection:"IP67 wrist",mounting:"Floor, ceiling, wall"},score:cs({performance:84,reliability:88,ease_of_use:76,intelligence:72,value:78,ecosystem:85,safety:80,design:74}),breakdown:{performance:84,reliability:88,ease_of_use:76,intelligence:72,value:78,ecosystem:85,safety:80,design:74}},
{slug:"fanuc-m-900ib-700",name:"FANUC M-900iB/700",mfr:"fanuc",cat:"manufacturing",price:280000,year:2023,status:"active",desc:"Heavy-payload industrial robot with 700 kg capacity and 2832 mm reach. Designed for automotive body shop transfers and heavy part palletizing. Rigid arm structure minimizes deflection under load.",specs:{axes:6,payload_kg:700,reach_mm:2832,repeatability_mm:0.1,weight_kg:2780,controller:"R-30iB Plus",application:"Heavy handling, automotive",mounting:"Floor"},score:cs({performance:88,reliability:90,ease_of_use:68,intelligence:68,value:72,ecosystem:86,safety:82,design:70}),breakdown:{performance:88,reliability:90,ease_of_use:68,intelligence:68,value:72,ecosystem:86,safety:82,design:70}},
{slug:"fanuc-arc-mate-120id",name:"FANUC ARC Mate 120iD",mfr:"fanuc",cat:"manufacturing",price:75000,year:2024,status:"active",desc:"Dedicated arc welding robot with 25 kg payload and 1831 mm reach. Hollow wrist design routes torch cable internally for smooth motion. Compatible with all major welding power sources including Lincoln and Fronius.",specs:{axes:6,payload_kg:25,reach_mm:1831,repeatability_mm:0.03,application:"MIG/MAG, TIG welding",wrist:"Hollow — internal cable routing",welding_sources:"Lincoln, Fronius, Miller",controller:"R-30iB Plus"},score:cs({performance:86,reliability:88,ease_of_use:74,intelligence:74,value:76,ecosystem:84,safety:82,design:72}),breakdown:{performance:86,reliability:88,ease_of_use:74,intelligence:74,value:76,ecosystem:84,safety:82,design:72}},
{slug:"fanuc-p-250ib",name:"FANUC P-250iB",mfr:"fanuc",cat:"manufacturing",price:120000,year:2023,status:"active",desc:"Purpose-built paint robot with intrinsically safe design for hazardous spray booth environments. 3 m reach with hollow arm for internal paint hose routing. Explosion-proof rating for solvent-based paints.",specs:{axes:6,payload_kg:15,reach_mm:3000,repeatability_mm:0.3,application:"Automotive/industrial painting",protection:"Explosion-proof",arm:"Hollow — internal paint routing",controller:"R-30iB Paint"},score:cs({performance:84,reliability:86,ease_of_use:70,intelligence:72,value:74,ecosystem:82,safety:88,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:70,intelligence:72,value:74,ecosystem:82,safety:88,design:74}},
{slug:"fanuc-lr-mate-200id-7l",name:"FANUC LR Mate 200iD/7L",mfr:"fanuc",cat:"manufacturing",price:32000,year:2024,status:"active",desc:"Compact tabletop robot with 7 kg payload and 911 mm reach. Ideal for small parts assembly, testing, and inspection. One of the most widely deployed mini-industrial robots globally with 100,000+ units in service.",specs:{axes:6,payload_kg:7,reach_mm:911,repeatability_mm:0.01,weight_kg:29,application:"Assembly, inspection, testing",units_deployed:"100,000+",controller:"R-30iB Mate Plus"},score:cs({performance:80,reliability:90,ease_of_use:82,intelligence:70,value:86,ecosystem:88,safety:78,design:76}),breakdown:{performance:80,reliability:90,ease_of_use:82,intelligence:70,value:86,ecosystem:88,safety:78,design:76}},
{slug:"fanuc-m-410ib-700",name:"FANUC M-410iB/700",mfr:"fanuc",cat:"manufacturing",price:160000,year:2023,status:"active",desc:"4-axis palletizing robot with 700 kg payload. Purpose-built for high-speed palletizing of heavy bags, cases, and pails. Parallel-link wrist maintains carton orientation through the full motion cycle.",specs:{axes:4,payload_kg:700,reach_mm:3143,repeatability_mm:0.5,application:"High-speed palletizing",wrist:"Parallel-link orientation hold",cycles_per_hour:1300,controller:"R-30iB Plus"},score:cs({performance:86,reliability:88,ease_of_use:78,intelligence:66,value:76,ecosystem:84,safety:80,design:68}),breakdown:{performance:86,reliability:88,ease_of_use:78,intelligence:66,value:76,ecosystem:84,safety:80,design:68}},
{slug:"fanuc-r-2000id-210f",name:"FANUC R-2000iD/210F",mfr:"fanuc",cat:"manufacturing",price:95000,year:2024,status:"active",desc:"Workhorse spot welding robot with 210 kg payload and 2606 mm reach. The R-2000 series is the most deployed industrial robot family in automotive body-in-white welding with 100,000+ units worldwide.",specs:{axes:6,payload_kg:210,reach_mm:2606,repeatability_mm:0.05,application:"Spot welding, handling",units_deployed:"100,000+ (series)",industry:"Automotive body-in-white",controller:"R-30iB Plus"},score:cs({performance:88,reliability:92,ease_of_use:74,intelligence:70,value:80,ecosystem:88,safety:84,design:72}),breakdown:{performance:88,reliability:92,ease_of_use:74,intelligence:70,value:80,ecosystem:88,safety:84,design:72}},
{slug:"fanuc-m-10id-12",name:"FANUC M-10iD/12",mfr:"fanuc",cat:"manufacturing",price:45000,year:2024,status:"active",desc:"Mid-range 6-axis robot with 12 kg payload and 1441 mm reach. Slim arm profile allows close installation to workpieces and adjacent robots. Popular for machine tending and light assembly in automotive tier suppliers.",specs:{axes:6,payload_kg:12,reach_mm:1441,repeatability_mm:0.03,weight_kg:155,application:"Machine tending, light assembly",arm:"Slim profile for dense layouts",controller:"R-30iB Plus"},score:cs({performance:82,reliability:88,ease_of_use:78,intelligence:72,value:82,ecosystem:86,safety:80,design:74}),breakdown:{performance:82,reliability:88,ease_of_use:78,intelligence:72,value:82,ecosystem:86,safety:80,design:74}},
{slug:"fanuc-sr-3ia",name:"FANUC SR-3iA",mfr:"fanuc",cat:"manufacturing",price:28000,year:2024,status:"active",desc:"Delta-style high-speed picking robot with 3 kg payload. Achieves 150 picks per minute for food, pharma, and electronics sorting. Compact ceiling-mount design with IP65 washdown option.",specs:{axes:4,payload_kg:3,reach_mm:400,repeatability_mm:0.01,picks_per_min:150,application:"High-speed picking/sorting",mounting:"Ceiling",protection:"IP65 washdown option"},score:cs({performance:86,reliability:86,ease_of_use:76,intelligence:72,value:80,ecosystem:84,safety:78,design:76}),breakdown:{performance:86,reliability:86,ease_of_use:76,intelligence:72,value:80,ecosystem:84,safety:78,design:76}},
{slug:"fanuc-m-800ia-60",name:"FANUC M-800iA/60",mfr:"fanuc",cat:"manufacturing",price:82000,year:2024,status:"active",desc:"High-precision industrial robot with 60 kg payload and 2040 mm reach. Achieves 0.015 mm repeatability for precision machining, laser cutting, and waterjet applications. Rigid J2/J3 arm design reduces vibration.",specs:{axes:6,payload_kg:60,reach_mm:2040,repeatability_mm:0.015,application:"Precision machining, laser cutting",rigidity:"Enhanced J2/J3 structure",vibration:"Low-vibration design",controller:"R-30iB Plus"},score:cs({performance:88,reliability:88,ease_of_use:72,intelligence:74,value:76,ecosystem:84,safety:80,design:76}),breakdown:{performance:88,reliability:88,ease_of_use:72,intelligence:74,value:76,ecosystem:84,safety:80,design:76}},

// ═══ ABB Robots (8) ═══
{slug:"abb-irb-2600-20",name:"ABB IRB 2600-20/1.65",mfr:"abb-robotics",cat:"manufacturing",price:55000,year:2024,status:"active",desc:"Versatile 6-axis robot with 20 kg payload and 1650 mm reach. Strong in arc welding, material handling, and machine tending. LeanID cable management reduces dress pack wear by 50%.",specs:{axes:6,payload_kg:20,reach_mm:1650,repeatability_mm:0.04,weight_kg:272,cable_mgmt:"LeanID integrated",application:"Welding, handling, tending",controller:"OmniCore"},score:cs({performance:82,reliability:86,ease_of_use:78,intelligence:74,value:80,ecosystem:82,safety:80,design:76}),breakdown:{performance:82,reliability:86,ease_of_use:78,intelligence:74,value:80,ecosystem:82,safety:80,design:76}},
{slug:"abb-irb-6700-235",name:"ABB IRB 6700-235/2.65",mfr:"abb-robotics",cat:"manufacturing",price:130000,year:2023,status:"active",desc:"Heavy-duty 6-axis robot with 235 kg payload and 2650 mm reach. 7th generation with 15% lower energy consumption than predecessor. Primary applications in spot welding and heavy material handling.",specs:{axes:6,payload_kg:235,reach_mm:2650,repeatability_mm:0.05,weight_kg:1305,generation:"7th",energy_savings:"15% vs IRB 6640",application:"Spot welding, heavy handling",controller:"OmniCore"},score:cs({performance:86,reliability:88,ease_of_use:74,intelligence:72,value:76,ecosystem:84,safety:82,design:74}),breakdown:{performance:86,reliability:88,ease_of_use:74,intelligence:72,value:76,ecosystem:84,safety:82,design:74}},
{slug:"abb-irb-5710",name:"ABB IRB 5710",mfr:"abb-robotics",cat:"manufacturing",price:85000,year:2024,status:"active",desc:"High-performance robot with 70-110 kg payload variants and up to 2300 mm reach. Built for press tending, machine loading, and general handling. OmniCore controller delivers 25% faster cycle times.",specs:{axes:6,payload_kg:110,reach_mm:2300,repeatability_mm:0.04,variants:"70/80/90/110 kg",cycle_improvement:"25% faster with OmniCore",application:"Press tending, machine loading",controller:"OmniCore"},score:cs({performance:84,reliability:86,ease_of_use:76,intelligence:74,value:78,ecosystem:84,safety:80,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:76,intelligence:74,value:78,ecosystem:84,safety:80,design:76}},
{slug:"abb-irb-1660id",name:"ABB IRB 1660ID",mfr:"abb-robotics",cat:"manufacturing",price:48000,year:2024,status:"active",desc:"Integrated Dressing arc welding robot with fully internal cable routing. 6 kg payload and 1550 mm reach. Eliminates external cable wear and collision risk, reducing maintenance costs by 50%.",specs:{axes:6,payload_kg:6,reach_mm:1550,repeatability_mm:0.02,cable_routing:"Fully integrated internal",maintenance_savings:"50%",application:"Arc welding",controller:"OmniCore"},score:cs({performance:84,reliability:86,ease_of_use:80,intelligence:74,value:82,ecosystem:82,safety:82,design:78}),breakdown:{performance:84,reliability:86,ease_of_use:80,intelligence:74,value:82,ecosystem:82,safety:82,design:78}},
{slug:"abb-irb-5500-paint",name:"ABB IRB 5500 FlexPainter",mfr:"abb-robotics",cat:"manufacturing",price:140000,year:2023,status:"active",desc:"7-axis paint robot with 3.58 m reach for automotive painting. Shelf-mounted design saves 30% floor space. EX-rated for solvent atmospheres with integrated paint hose routing through hollow arm.",specs:{axes:7,payload_kg:13,reach_mm:3580,application:"Automotive painting",mounting:"Shelf/wall",floor_savings:"30%",protection:"EX rated for solvents",arm:"Hollow — paint hose routing"},score:cs({performance:86,reliability:86,ease_of_use:70,intelligence:74,value:72,ecosystem:82,safety:88,design:78}),breakdown:{performance:86,reliability:86,ease_of_use:70,intelligence:74,value:72,ecosystem:82,safety:88,design:78}},
{slug:"abb-irb-910inv",name:"ABB IRB 910INV",mfr:"abb-robotics",cat:"manufacturing",price:22000,year:2024,status:"active",desc:"Ceiling-mounted SCARA robot with 6 kg payload for high-speed pick-and-place. Inverted mount maximizes work area utilization. 200 picks per minute in electronics and small parts assembly.",specs:{axes:4,payload_kg:6,reach_mm:650,repeatability_mm:0.01,picks_per_min:200,mounting:"Ceiling inverted",application:"Electronics pick-and-place",controller:"OmniCore"},score:cs({performance:84,reliability:84,ease_of_use:78,intelligence:70,value:84,ecosystem:82,safety:78,design:78}),breakdown:{performance:84,reliability:84,ease_of_use:78,intelligence:70,value:84,ecosystem:82,safety:78,design:78}},
{slug:"abb-irb-760",name:"ABB IRB 760",mfr:"abb-robotics",cat:"manufacturing",price:110000,year:2023,status:"active",desc:"4-axis palletizing robot with 450 kg payload and 3180 mm reach. Parallel linkage design ensures stable pallet loads. Handles mixed-case palletizing at 20 cycles per minute.",specs:{axes:4,payload_kg:450,reach_mm:3180,repeatability_mm:0.1,application:"High-speed palletizing",cycles_per_min:20,wrist:"Parallel linkage",controller:"OmniCore"},score:cs({performance:84,reliability:86,ease_of_use:76,intelligence:68,value:78,ecosystem:82,safety:80,design:72}),breakdown:{performance:84,reliability:86,ease_of_use:76,intelligence:68,value:78,ecosystem:82,safety:80,design:72}},
{slug:"abb-irb-390",name:"ABB IRB 390 FlexPacker",mfr:"abb-robotics",cat:"manufacturing",price:35000,year:2024,status:"active",desc:"Delta robot for secondary food packaging at 450 picks per minute. NSF-certified food-safe design with washdown capability. Handles flow-wrapping, case packing, and reorientation.",specs:{axes:4,payload_kg:1.5,reach_mm:800,picks_per_min:450,certification:"NSF food-safe",application:"Food packaging",protection:"Washdown IP69K",controller:"OmniCore"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:72,value:80,ecosystem:82,safety:82,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:72,value:80,ecosystem:82,safety:82,design:76}},

// ═══ KUKA Robots (8) ═══
{slug:"kuka-kr-120-r2700-2",name:"KUKA KR 120 R2700-2",mfr:"kuka",cat:"manufacturing",price:72000,year:2024,status:"active",desc:"6-axis industrial robot with 120 kg payload and 2701 mm reach. KR QUANTEC series workhorse for automotive welding and handling. KUKA.SafeOperation provides TUV-certified safe monitoring.",specs:{axes:6,payload_kg:120,reach_mm:2701,repeatability_mm:0.05,series:"KR QUANTEC",safety:"KUKA.SafeOperation TUV",application:"Automotive welding, handling",controller:"KR C5"},score:cs({performance:84,reliability:86,ease_of_use:74,intelligence:74,value:76,ecosystem:80,safety:84,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:74,intelligence:74,value:76,ecosystem:80,safety:84,design:74}},
{slug:"kuka-kr-1000-titan",name:"KUKA KR 1000 TITAN",mfr:"kuka",cat:"manufacturing",price:350000,year:2023,status:"active",desc:"Ultra-heavy-payload robot with 1000 kg capacity and 3601 mm reach. One of the highest-payload 6-axis robots in production. Used in aerospace, heavy machinery, and foundry applications.",specs:{axes:6,payload_kg:1000,reach_mm:3601,repeatability_mm:0.1,weight_kg:4690,application:"Aerospace, foundry, heavy machinery",distinction:"Highest payload 6-axis class",controller:"KR C5"},score:cs({performance:90,reliability:86,ease_of_use:64,intelligence:68,value:68,ecosystem:78,safety:82,design:70}),breakdown:{performance:90,reliability:86,ease_of_use:64,intelligence:68,value:68,ecosystem:78,safety:82,design:70}},
{slug:"kuka-kr-6-r900-sixx",name:"KUKA KR 6 R900 sixx",mfr:"kuka",cat:"manufacturing",price:30000,year:2024,status:"active",desc:"Compact 6-axis robot with 6 kg payload and 901 mm reach. KR AGILUS series optimized for electronics, small parts assembly, and lab automation. Cycle times under 0.4 seconds for pick-and-place.",specs:{axes:6,payload_kg:6,reach_mm:901,repeatability_mm:0.02,series:"KR AGILUS",cycle_time_s:0.4,application:"Electronics, lab automation",controller:"KR C5 micro"},score:cs({performance:84,reliability:84,ease_of_use:80,intelligence:72,value:84,ecosystem:80,safety:78,design:78}),breakdown:{performance:84,reliability:84,ease_of_use:80,intelligence:72,value:84,ecosystem:80,safety:78,design:78}},
{slug:"kuka-kr-360-r2830",name:"KUKA KR 360 R2830",mfr:"kuka",cat:"manufacturing",price:145000,year:2023,status:"active",desc:"Heavy-duty 6-axis robot with 360 kg payload and 2826 mm reach. Foundry variant available with enhanced sealing for harsh metal casting environments. Strong in automotive underbody and heavy assembly.",specs:{axes:6,payload_kg:360,reach_mm:2826,repeatability_mm:0.06,variants:"Standard, Foundry, Press",application:"Heavy assembly, foundry",protection:"Foundry IP67 variant",controller:"KR C5"},score:cs({performance:86,reliability:88,ease_of_use:72,intelligence:70,value:74,ecosystem:80,safety:84,design:72}),breakdown:{performance:86,reliability:88,ease_of_use:72,intelligence:70,value:74,ecosystem:80,safety:84,design:72}},
{slug:"kuka-kr-16-arc-hw",name:"KUKA KR 16 ARC HW",mfr:"kuka",cat:"manufacturing",price:55000,year:2024,status:"active",desc:"Dedicated arc welding robot with 16 kg payload and hollow wrist for internal torch cable routing. Reach of 1636 mm covers standard welding cell requirements. Integrated with KUKA.ArcTech welding software.",specs:{axes:6,payload_kg:16,reach_mm:1636,repeatability_mm:0.04,wrist:"Hollow for torch cable",software:"KUKA.ArcTech",application:"MIG/MAG arc welding",controller:"KR C5"},score:cs({performance:82,reliability:86,ease_of_use:76,intelligence:74,value:78,ecosystem:80,safety:82,design:74}),breakdown:{performance:82,reliability:86,ease_of_use:76,intelligence:74,value:78,ecosystem:80,safety:82,design:74}},
{slug:"kuka-kr-240-r3100-paint",name:"KUKA KR 240 R3100 Paint",mfr:"kuka",cat:"manufacturing",price:130000,year:2023,status:"active",desc:"Explosion-proof paint robot with 3100 mm reach for automotive and general industrial coating. EX-rated for Zone 1 environments. Hollow arm routes paint supply lines internally.",specs:{axes:6,payload_kg:30,reach_mm:3100,application:"Automotive painting, coating",protection:"ATEX Zone 1 EX-rated",arm:"Hollow paint line routing",mounting:"Floor, ceiling, rail",controller:"KR C5"},score:cs({performance:84,reliability:86,ease_of_use:70,intelligence:72,value:72,ecosystem:80,safety:88,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:70,intelligence:72,value:72,ecosystem:80,safety:88,design:74}},
{slug:"kuka-kr-scara",name:"KUKA KR SCARA",mfr:"kuka",cat:"manufacturing",price:25000,year:2024,status:"active",desc:"4-axis SCARA robot with 6 kg payload and 700 mm reach. Designed for high-speed assembly, testing, and packaging in electronics manufacturing. Cycle time of 0.32 seconds.",specs:{axes:4,payload_kg:6,reach_mm:700,repeatability_mm:0.01,cycle_time_s:0.32,application:"Assembly, testing, packaging",industry:"Electronics",controller:"KR C5 micro"},score:cs({performance:82,reliability:84,ease_of_use:80,intelligence:68,value:84,ecosystem:78,safety:78,design:76}),breakdown:{performance:82,reliability:84,ease_of_use:80,intelligence:68,value:84,ecosystem:78,safety:78,design:76}},
{slug:"kuka-kr-470-2-pa",name:"KUKA KR 470-2 PA",mfr:"kuka",cat:"manufacturing",price:125000,year:2024,status:"active",desc:"4-axis palletizing robot with 470 kg payload and 3150 mm reach. KR QUANTEC PA series handles full-layer palletizing of heavy bags and cases at up to 2190 cycles per hour.",specs:{axes:4,payload_kg:470,reach_mm:3150,repeatability_mm:0.08,series:"KR QUANTEC PA",cycles_per_hour:2190,application:"High-speed palletizing",controller:"KR C5"},score:cs({performance:86,reliability:86,ease_of_use:76,intelligence:68,value:76,ecosystem:80,safety:80,design:70}),breakdown:{performance:86,reliability:86,ease_of_use:76,intelligence:68,value:76,ecosystem:80,safety:80,design:70}},

// ═══ Yaskawa Motoman Robots (8) ═══
{slug:"yaskawa-gp25-12",name:"Yaskawa Motoman GP25-12",mfr:"yaskawa",cat:"manufacturing",price:48000,year:2024,status:"active",desc:"6-axis handling robot with 25 kg payload and 1730 mm reach. GP series delivers class-leading speed with 0.03 mm repeatability. Slim arm and small footprint suit dense manufacturing cell layouts.",specs:{axes:6,payload_kg:25,reach_mm:1730,repeatability_mm:0.03,weight_kg:250,series:"GP",application:"Handling, machine tending",controller:"YRC1000"},score:cs({performance:84,reliability:86,ease_of_use:76,intelligence:72,value:80,ecosystem:78,safety:80,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:76,intelligence:72,value:80,ecosystem:78,safety:80,design:74}},
{slug:"yaskawa-ar1730",name:"Yaskawa Motoman AR1730",mfr:"yaskawa",cat:"manufacturing",price:58000,year:2024,status:"active",desc:"Arc welding robot with 7 kg payload and 1730 mm reach. Thru-arm cable routing eliminates external torch cable snagging. Integrated with Yaskawa ComArc welding management for adaptive seam tracking.",specs:{axes:6,payload_kg:7,reach_mm:1730,repeatability_mm:0.03,cable:"Thru-arm routing",software:"ComArc welding management",application:"Arc welding",controller:"YRC1000"},score:cs({performance:84,reliability:86,ease_of_use:78,intelligence:76,value:78,ecosystem:78,safety:82,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:78,intelligence:76,value:78,ecosystem:78,safety:82,design:76}},
{slug:"yaskawa-gp180-120",name:"Yaskawa Motoman GP180-120",mfr:"yaskawa",cat:"manufacturing",price:95000,year:2023,status:"active",desc:"Heavy-duty 6-axis robot with 180 kg payload and 2702 mm reach. Extended-reach variant of the GP180 for large-envelope spot welding and material handling in automotive body shops.",specs:{axes:6,payload_kg:180,reach_mm:2702,repeatability_mm:0.05,weight_kg:1060,application:"Spot welding, heavy handling",industry:"Automotive body shop",controller:"YRC1000"},score:cs({performance:86,reliability:86,ease_of_use:72,intelligence:70,value:76,ecosystem:78,safety:82,design:72}),breakdown:{performance:86,reliability:86,ease_of_use:72,intelligence:70,value:76,ecosystem:78,safety:82,design:72}},
{slug:"yaskawa-mpl80ii",name:"Yaskawa Motoman MPL80II",mfr:"yaskawa",cat:"manufacturing",price:78000,year:2024,status:"active",desc:"4-axis palletizing robot with 80 kg payload and 2061 mm reach. Compact base footprint of 520 mm allows near-wall installation. Handles 1800 cycles per hour in mixed palletizing applications.",specs:{axes:4,payload_kg:80,reach_mm:2061,repeatability_mm:0.05,footprint_mm:520,cycles_per_hour:1800,application:"Palletizing",controller:"YRC1000"},score:cs({performance:82,reliability:86,ease_of_use:78,intelligence:68,value:80,ecosystem:78,safety:80,design:74}),breakdown:{performance:82,reliability:86,ease_of_use:78,intelligence:68,value:80,ecosystem:78,safety:80,design:74}},
{slug:"yaskawa-sp100b",name:"Yaskawa Motoman SP100B",mfr:"yaskawa",cat:"manufacturing",price:72000,year:2023,status:"active",desc:"Dedicated spot welding robot with 100 kg payload and 2236 mm reach. Designed for medium-duty spot welding of car bodies and BIW sub-assemblies. Compact wrist handles standard servo spot welding guns.",specs:{axes:6,payload_kg:100,reach_mm:2236,repeatability_mm:0.05,application:"Spot welding BIW",wrist:"Compact spot gun compatible",industry:"Automotive",controller:"YRC1000"},score:cs({performance:84,reliability:86,ease_of_use:74,intelligence:70,value:78,ecosystem:76,safety:82,design:72}),breakdown:{performance:84,reliability:86,ease_of_use:74,intelligence:70,value:78,ecosystem:76,safety:82,design:72}},
{slug:"yaskawa-epx2900",name:"Yaskawa Motoman EPX2900",mfr:"yaskawa",cat:"manufacturing",price:115000,year:2024,status:"active",desc:"Explosion-proof paint robot with 15 kg payload and 2900 mm reach. ATEX/IECEx rated for hazardous painting environments. Integrated flow control for bell cup and airless spray applications.",specs:{axes:6,payload_kg:15,reach_mm:2900,application:"Industrial painting",protection:"ATEX/IECEx explosion-proof",spray:"Bell cup, airless",flow:"Integrated flow control",controller:"YRC1000"},score:cs({performance:84,reliability:84,ease_of_use:72,intelligence:72,value:74,ecosystem:76,safety:88,design:74}),breakdown:{performance:84,reliability:84,ease_of_use:72,intelligence:72,value:74,ecosystem:76,safety:88,design:74}},
{slug:"yaskawa-sg650fm",name:"Yaskawa Motoman SG650FM",mfr:"yaskawa",cat:"manufacturing",price:26000,year:2024,status:"active",desc:"SCARA robot with 20 kg payload and 650 mm reach for high-speed assembly. Floor-mount design with fast 0.29 second cycle time. Strong in electronics board handling and precision component insertion.",specs:{axes:4,payload_kg:20,reach_mm:650,repeatability_mm:0.01,cycle_time_s:0.29,application:"Assembly, component insertion",industry:"Electronics",controller:"YRC1000micro"},score:cs({performance:84,reliability:84,ease_of_use:80,intelligence:68,value:84,ecosystem:76,safety:78,design:76}),breakdown:{performance:84,reliability:84,ease_of_use:80,intelligence:68,value:84,ecosystem:76,safety:78,design:76}},
{slug:"yaskawa-gp400",name:"Yaskawa Motoman GP400",mfr:"yaskawa",cat:"manufacturing",price:180000,year:2023,status:"active",desc:"Heavy-payload 6-axis robot with 400 kg capacity and 2942 mm reach. One of the heaviest payloads in Yaskawa's GP lineup. Deployed in engine block transfer, heavy press tending, and aerospace part handling.",specs:{axes:6,payload_kg:400,reach_mm:2942,repeatability_mm:0.05,weight_kg:1800,application:"Engine transfer, press tending, aerospace",series:"GP",controller:"YRC1000"},score:cs({performance:88,reliability:86,ease_of_use:70,intelligence:68,value:72,ecosystem:78,safety:82,design:70}),breakdown:{performance:88,reliability:86,ease_of_use:70,intelligence:68,value:72,ecosystem:78,safety:82,design:70}},

// ═══ Daifuku Material Handling Systems (6) ═══
{slug:"daifuku-sfa",name:"Daifuku SFA Sorting Transfer Vehicle",mfr:"daifuku",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Automated sorting and transfer vehicle for automotive body-in-white production lines. Rail-guided, high-speed transfer of car bodies between welding stations at up to 90 m/min. Lease-based at $8,000/mo.",specs:{type:"Sorting Transfer Vehicle",application:"Automotive BIW transfer",speed_m_min:90,guidance:"Rail-guided",payload_kg:1500,integration:"PLC + MES",subscription_monthly:8000},score:cs({performance:84,reliability:88,ease_of_use:68,intelligence:66,value:72,ecosystem:76,safety:84,design:68}),breakdown:{performance:84,reliability:88,ease_of_use:68,intelligence:66,value:72,ecosystem:76,safety:84,design:68}},
{slug:"daifuku-cleanway",name:"Daifuku Cleanway OHT",mfr:"daifuku",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Overhead Hoist Transport system for semiconductor fabs. Moves FOUP carriers between process tools at up to 250 m/min on ceiling-mounted rail. Cleanroom Class 1 compatible. System pricing from $500K+.",specs:{type:"Overhead Hoist Transport",application:"Semiconductor FOUP transport",speed_m_min:250,cleanroom:"Class 1",guidance:"Rail-guided overhead",throughput:"20,000+ moves/day",system_price_min:500000},score:cs({performance:90,reliability:92,ease_of_use:66,intelligence:72,value:68,ecosystem:80,safety:86,design:72}),breakdown:{performance:90,reliability:92,ease_of_use:66,intelligence:72,value:68,ecosystem:80,safety:86,design:72}},
{slug:"daifuku-agv-fac",name:"Daifuku FAC AGV",mfr:"daifuku",cat:"manufacturing",price:85000,year:2023,status:"active",desc:"Factory Automation Car — AGV for automotive assembly line delivery. Magnetic or optical guidance for just-in-time parts delivery to assembly stations. 1500 kg payload with tugger or platform configurations.",specs:{type:"Factory AGV",payload_kg:1500,guidance:"Magnetic/optical",application:"Assembly line JIT delivery",configurations:"Tugger, platform, custom",speed_m_min:60,battery:"Opportunity charging"},score:cs({performance:80,reliability:86,ease_of_use:72,intelligence:68,value:76,ecosystem:78,safety:82,design:68}),breakdown:{performance:80,reliability:86,ease_of_use:72,intelligence:68,value:76,ecosystem:78,safety:82,design:68}},
{slug:"daifuku-shuttle-rack-m",name:"Daifuku Shuttle Rack M",mfr:"daifuku",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Mini-load automated storage and retrieval system for totes and cartons. Shuttle-based design processes 400+ totes per hour per aisle. Suited for parts buffering in manufacturing and e-commerce fulfillment. From $1.2M installed.",specs:{type:"Shuttle AS/RS",throughput:"400+ totes/hr/aisle",storage:"Totes and cartons",weight_per_tote_kg:50,aisles:"Scalable multi-aisle",integration:"WMS/WCS",system_price_min:1200000},score:cs({performance:84,reliability:86,ease_of_use:68,intelligence:70,value:70,ecosystem:78,safety:84,design:70}),breakdown:{performance:84,reliability:86,ease_of_use:68,intelligence:70,value:70,ecosystem:78,safety:84,design:70}},
{slug:"daifuku-aisle-sorter",name:"Daifuku Surfing Sorter",mfr:"daifuku",cat:"manufacturing",price:null,year:2024,status:"active",desc:"High-speed tilt-tray sortation system processing up to 15,000 items per hour. Widely deployed in e-commerce and parcel distribution centers. Handles items from 50g to 30 kg. System from $800K.",specs:{type:"Tilt-tray sorter",throughput:"15,000 items/hr",weight_range:"50g - 30 kg",application:"E-commerce, parcel sorting",destinations:"200+ chutes",accuracy:"99.99%",system_price_min:800000},score:cs({performance:88,reliability:88,ease_of_use:70,intelligence:68,value:72,ecosystem:78,safety:82,design:70}),breakdown:{performance:88,reliability:88,ease_of_use:70,intelligence:68,value:72,ecosystem:78,safety:82,design:70}},
{slug:"daifuku-contec",name:"Daifuku Contec Conveyor",mfr:"daifuku",cat:"manufacturing",price:null,year:2023,status:"active",desc:"Modular belt and roller conveyor system for manufacturing and distribution. Available in 200+ configurations for transport, accumulation, merge, and divert. Handles loads from 1 to 500 kg per meter.",specs:{type:"Modular conveyor",configurations:"200+",load_per_meter_kg:500,types:"Belt, roller, chain",functions:"Transport, accumulate, merge, divert",application:"Manufacturing, distribution",customization:"Fully modular"},score:cs({performance:80,reliability:88,ease_of_use:74,intelligence:58,value:78,ecosystem:78,safety:80,design:66}),breakdown:{performance:80,reliability:88,ease_of_use:74,intelligence:58,value:78,ecosystem:78,safety:80,design:66}},

// ═══ Dematic Sortation/Conveyor Systems (5) ═══
{slug:"dematic-multishuttle-2",name:"Dematic Multishuttle",mfr:"dematic",cat:"manufacturing",price:null,year:2024,status:"active",desc:"High-density shuttle-based AS/RS for goods-to-person order fulfillment. Each shuttle handles 300+ totes per hour. Scalable from 10 to 100+ aisles with 50,000+ storage locations. System from $2M.",specs:{type:"Shuttle AS/RS",throughput:"300+ totes/hr/shuttle",storage_locations:"50,000+",scalability:"10-100+ aisles",application:"Goods-to-person fulfillment",integration:"Dematic iQ WCS",system_price_min:2000000},score:cs({performance:86,reliability:86,ease_of_use:70,intelligence:74,value:70,ecosystem:80,safety:84,design:72}),breakdown:{performance:86,reliability:86,ease_of_use:70,intelligence:74,value:70,ecosystem:80,safety:84,design:72}},
{slug:"dematic-cross-belt-sorter",name:"Dematic Cross-Belt Sorter",mfr:"dematic",cat:"manufacturing",price:null,year:2024,status:"active",desc:"High-speed cross-belt sortation system processing 20,000+ items per hour. Each carrier has independent belt drive for gentle, accurate sortation. Dominant in parcel, postal, and airport baggage. From $1.5M.",specs:{type:"Cross-belt sorter",throughput:"20,000+ items/hr",accuracy:"99.99%",gentle:"Independent belt per carrier",application:"Parcel, postal, airport baggage",destinations:"300+",system_price_min:1500000},score:cs({performance:90,reliability:88,ease_of_use:68,intelligence:70,value:70,ecosystem:80,safety:84,design:72}),breakdown:{performance:90,reliability:88,ease_of_use:68,intelligence:70,value:70,ecosystem:80,safety:84,design:72}},
{slug:"dematic-pouch-sorter",name:"Dematic Pouch Sorter",mfr:"dematic",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Overhead pouch sorting system where items ride in individual pouches on a suspended rail network. Ideal for apparel and small-item e-commerce fulfillment. Sorts 10,000 items/hr with buffer storage. From $1M.",specs:{type:"Pouch sorter",throughput:"10,000 items/hr",application:"Apparel, small-item e-commerce",method:"Overhead rail-suspended pouches",buffer_storage:true,item_weight_max_kg:5,system_price_min:1000000},score:cs({performance:82,reliability:84,ease_of_use:72,intelligence:72,value:74,ecosystem:78,safety:82,design:76}),breakdown:{performance:82,reliability:84,ease_of_use:72,intelligence:72,value:74,ecosystem:78,safety:82,design:76}},
{slug:"dematic-amr-piece-pick",name:"Dematic AMR Piece Picking",mfr:"dematic",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AMR-based robotic piece picking station combining mobile robots with 6-axis picking arms. Vision-guided picking at 600+ picks per hour per station. Handles mixed SKU e-commerce fulfillment. From $350K/station.",specs:{type:"AMR + robotic arm picking",picks_per_hour:600,vision:"3D vision guided",skus:"Mixed SKU capable",integration:"Dematic iQ WMS",application:"E-commerce piece picking",station_price:350000},score:cs({performance:80,reliability:80,ease_of_use:74,intelligence:82,value:72,ecosystem:80,safety:80,design:74}),breakdown:{performance:80,reliability:80,ease_of_use:74,intelligence:82,value:72,ecosystem:80,safety:80,design:74}},
{slug:"dematic-conveyor-aiv",name:"Dematic AIV Conveyor Bot",mfr:"dematic",cat:"manufacturing",price:65000,year:2024,status:"active",desc:"Autonomous Intelligent Vehicle that replaces fixed conveyor runs. Navigates autonomously to move totes and cases between process areas. Eliminates rigid conveyor infrastructure, enabling flexible facility layouts.",specs:{type:"Autonomous conveyor replacement",payload_kg:120,nav:"SLAM autonomous",speed_m_s:2,battery_hrs:8,application:"Flexible material transport",advantage:"Replaces fixed conveyor"},score:cs({performance:78,reliability:78,ease_of_use:80,intelligence:78,value:76,ecosystem:78,safety:80,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:80,intelligence:78,value:76,ecosystem:78,safety:80,design:76}},

// ═══ Swisslog Warehouse Automation Systems (5) ═══
{slug:"swisslog-autostore-grid",name:"Swisslog AutoStore Integration",mfr:"swisslog",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Swisslog-integrated AutoStore grid system for goods-to-person fulfillment. Combines AutoStore cube storage with Swisslog SynQ software for optimized picking. 250+ installations globally. System from $1.5M.",specs:{type:"AutoStore grid integration",storage:"Cube-based bins",software:"Swisslog SynQ",installations:"250+",throughput:"Varies by grid size",application:"Goods-to-person fulfillment",system_price_min:1500000},score:cs({performance:84,reliability:86,ease_of_use:76,intelligence:76,value:74,ecosystem:82,safety:84,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:76,intelligence:76,value:74,ecosystem:82,safety:84,design:74}},
{slug:"swisslog-cyclonecarrier",name:"Swisslog CycloneCarrier",mfr:"swisslog",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Pallet shuttle AS/RS for deep-lane pallet storage. Single-deep to 20-deep channel storage with autonomous shuttle transport. 99.9% availability with redundant shuttles. System from $2M.",specs:{type:"Pallet shuttle AS/RS",depth:"1-20 deep channels",availability:"99.9%",redundancy:"Multi-shuttle per level",payload_kg:1500,application:"Deep-lane pallet storage",system_price_min:2000000},score:cs({performance:84,reliability:88,ease_of_use:70,intelligence:72,value:72,ecosystem:80,safety:84,design:70}),breakdown:{performance:84,reliability:88,ease_of_use:70,intelligence:72,value:72,ecosystem:80,safety:84,design:70}},
{slug:"swisslog-acapick",name:"Swisslog ACPaQ Mixed Palletizer",mfr:"swisslog",cat:"manufacturing",price:null,year:2024,status:"active",desc:"Robotic mixed-case palletizing system that builds store-ready pallets from mixed SKUs. AI algorithms optimize pallet stability and cube utilization. Processes 1,000+ cases per hour. From $800K.",specs:{type:"Robotic mixed-case palletizer",throughput:"1,000+ cases/hr",ai:"Pallet stability optimization",cube_utilization:"95%+",skus:"Mixed SKU store-ready",application:"Grocery, retail DC",system_price_min:800000},score:cs({performance:84,reliability:84,ease_of_use:72,intelligence:82,value:72,ecosystem:80,safety:82,design:74}),breakdown:{performance:84,reliability:84,ease_of_use:72,intelligence:82,value:72,ecosystem:80,safety:82,design:74}},
{slug:"swisslog-itempiiq",name:"Swisslog ItemPiQ",mfr:"swisslog",cat:"manufacturing",price:null,year:2024,status:"active",desc:"AI-powered robotic piece-picking arm for goods-to-person workstations. Machine learning enables picking of 95% of typical e-commerce SKUs without manual teaching. 1,200 picks per hour. From $250K/station.",specs:{type:"Robotic piece picker",picks_per_hour:1200,sku_coverage:"95% untrained",vision:"AI + 3D vision",grippers:"Multi-gripper auto-swap",application:"E-commerce order picking",station_price:250000},score:cs({performance:82,reliability:80,ease_of_use:78,intelligence:84,value:74,ecosystem:80,safety:80,design:76}),breakdown:{performance:82,reliability:80,ease_of_use:78,intelligence:84,value:74,ecosystem:80,safety:80,design:76}},
{slug:"swisslog-vectura",name:"Swisslog Vectura Stacker Crane",mfr:"swisslog",cat:"manufacturing",price:null,year:2023,status:"active",desc:"High-bay stacker crane AS/RS for pallet and tote storage up to 45 m high. Single or double-deep storage with 60+ pallets per hour throughput. Energy regeneration braking reduces power consumption 20%.",specs:{type:"Stacker crane AS/RS",height_m:45,throughput:"60+ pallets/hr",storage:"Single/double deep",energy:"20% regenerative savings",application:"High-bay warehouse",availability:"99.5%"},score:cs({performance:82,reliability:88,ease_of_use:66,intelligence:66,value:74,ecosystem:80,safety:84,design:68}),breakdown:{performance:82,reliability:88,ease_of_use:66,intelligence:66,value:74,ecosystem:80,safety:84,design:68}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 13 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 13 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
