/**
 * Robotomated — Wave 19 Robot Import: 50 New Robots
 * Focus: Lawn mowers, pool cleaners, personal assistants, educational robots, entertainment
 * Run: npx tsx scripts/import-robots-wave19.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

const newMfrs = [
  { slug: "husqvarna", name: "Husqvarna", country: "SE", founded_year: 1689, website: "https://www.husqvarna.com" },
  { slug: "worx", name: "Worx", country: "US", founded_year: 2004, website: "https://www.worx.com" },
  { slug: "ecovacs", name: "Ecovacs", country: "CN", founded_year: 1998, website: "https://www.ecovacs.com" },
  { slug: "samsung-robotics", name: "Samsung Robotics", country: "KR", founded_year: 1969, website: "https://www.samsung.com" },
  { slug: "lg-robotics", name: "LG Robotics", country: "KR", founded_year: 1958, website: "https://www.lg.com" },
  { slug: "anki-ddl", name: "Digital Dream Labs", country: "US", founded_year: 2018, website: "https://www.digitaldreamlabs.com" },
  { slug: "sphero", name: "Sphero", country: "US", founded_year: 2010, website: "https://sphero.com" },
  { slug: "makeblock", name: "Makeblock", country: "CN", founded_year: 2013, website: "https://www.makeblock.com" },
  { slug: "misty-robotics", name: "Misty Robotics", country: "US", founded_year: 2017, website: "https://www.mistyrobotics.com" },
];

const robots: R[] = [
  // Robotic lawn mowers — 8 (Husqvarna Automower + Worx Landroid)
  (() => { const b = { performance: 85, reliability: 86, ease_of_use: 88, intelligence: 82, value: 72, ecosystem: 80, safety: 84, design: 86 }; return { slug: "husqvarna-automower-450x-nera", name: "Husqvarna Automower 450X NERA", mfr: "husqvarna", cat: "consumer", price: 3499, year: 2024, status: "active", desc: "Wire-free robotic mower using satellite navigation and virtual boundaries to maintain lawns up to 5,000 sqm with systematic mowing patterns.", specs: { area: "5,000 sqm", navigation: "EPOS satellite", boundary: "virtual (wire-free)", cutting_height: "20-60 mm", battery: "270 min runtime", weight: "13.9 kg", connectivity: "4G + Bluetooth" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 85, ease_of_use: 87, intelligence: 79, value: 78, ecosystem: 78, safety: 83, design: 84 }; return { slug: "husqvarna-automower-415x", name: "Husqvarna Automower 415X", mfr: "husqvarna", cat: "consumer", price: 1999, year: 2024, status: "active", desc: "Mid-range robotic mower for lawns up to 1,500 sqm with boundary wire, weather timer, and app-based scheduling for quiet overnight mowing.", specs: { area: "1,500 sqm", navigation: "GPS-assisted random", boundary: "guide wire", cutting_height: "20-50 mm", battery: "75 min runtime", weight: "9.7 kg", noise: "58 dB" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 84, ease_of_use: 89, intelligence: 76, value: 82, ecosystem: 76, safety: 82, design: 82 }; return { slug: "husqvarna-automower-310e-nera", name: "Husqvarna Automower 310E NERA", mfr: "husqvarna", cat: "consumer", price: 1299, year: 2025, status: "active", desc: "Entry-level wire-free Automower with EPOS reference station for lawns up to 1,000 sqm, eliminating boundary wire installation entirely.", specs: { area: "1,000 sqm", navigation: "EPOS satellite", boundary: "virtual", cutting_height: "20-50 mm", battery: "70 min runtime", weight: "9.2 kg", slope: "up to 22°" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 88, reliability: 87, ease_of_use: 86, intelligence: 85, value: 68, ecosystem: 82, safety: 85, design: 88 }; return { slug: "husqvarna-automower-550-epos", name: "Husqvarna Automower 550 EPOS", mfr: "husqvarna", cat: "consumer", price: 5999, year: 2024, status: "active", desc: "Professional-grade robotic mower for properties up to 10,000 sqm with centimeter-precise EPOS positioning and fleet management capability.", specs: { area: "10,000 sqm", navigation: "EPOS centimeter-precise", boundary: "virtual", cutting_height: "25-65 mm", battery: "360 min runtime", weight: "15.2 kg", fleet: "multi-robot management" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 82, ease_of_use: 90, intelligence: 77, value: 85, ecosystem: 74, safety: 82, design: 80 }; return { slug: "worx-landroid-m500-plus", name: "Worx Landroid M500 Plus", mfr: "worx", cat: "consumer", price: 799, year: 2024, status: "active", desc: "Budget-friendly robotic mower for lawns up to 500 sqm with AI-assisted cut-to-edge technology and optional RTK GPS module.", specs: { area: "500 sqm", navigation: "random + AI assist", boundary: "wire", cutting_height: "20-60 mm", battery: "60 min runtime", weight: "8.6 kg", modular: "RTK GPS optional" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 83, ease_of_use: 88, intelligence: 80, value: 80, ecosystem: 76, safety: 83, design: 81 }; return { slug: "worx-landroid-l1000", name: "Worx Landroid L1000", mfr: "worx", cat: "consumer", price: 1199, year: 2024, status: "active", desc: "Robotic mower for medium lawns up to 1,000 sqm with multi-zone scheduling and off-road capability for navigating garden paths.", specs: { area: "1,000 sqm", navigation: "AIA intelligent", boundary: "wire", cutting_height: "20-60 mm", battery: "90 min runtime", weight: "10.5 kg", zones: "4 programmable" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 84, ease_of_use: 87, intelligence: 82, value: 76, ecosystem: 77, safety: 84, design: 83 }; return { slug: "worx-landroid-vision-l1600", name: "Worx Landroid Vision L1600", mfr: "worx", cat: "consumer", price: 1999, year: 2025, status: "active", desc: "Wire-free Landroid using onboard HDR camera and AI to recognize lawn boundaries, obstacles, and garden features without any perimeter installation.", specs: { area: "1,600 sqm", navigation: "vision AI (wire-free)", boundary: "camera-based", cutting_height: "20-60 mm", battery: "120 min runtime", weight: "12.8 kg", camera: "HDR AI vision" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 81, ease_of_use: 91, intelligence: 74, value: 88, ecosystem: 72, safety: 81, design: 79 }; return { slug: "worx-landroid-s300", name: "Worx Landroid S300", mfr: "worx", cat: "consumer", price: 549, year: 2025, status: "active", desc: "Ultra-compact robotic mower for small urban gardens up to 300 sqm with one-touch setup and smartphone scheduling via the Worx app.", specs: { area: "300 sqm", navigation: "random", boundary: "wire", cutting_height: "20-50 mm", battery: "45 min runtime", weight: "7.4 kg", noise: "55 dB" }, score: cs(b), breakdown: b }; })(),

  // Robot vacuums/mops — 8 (Ecovacs Deebot + Roborock)
  (() => { const b = { performance: 86, reliability: 84, ease_of_use: 87, intelligence: 88, value: 74, ecosystem: 82, safety: 80, design: 86 }; return { slug: "ecovacs-deebot-x5-omni", name: "Ecovacs Deebot X5 Omni", mfr: "ecovacs", cat: "consumer", price: 1599, year: 2025, status: "active", desc: "Flagship robot vacuum-mop with 12,800 Pa suction, adaptive edge-mopping, and auto-empty/auto-wash all-in-one station.", specs: { suction: "12,800 Pa", mopping: "OZMO Turbo 2.0 rotating", navigation: "TrueMapping 3.0 LiDAR", station: "auto-empty + auto-wash + hot dry", battery: "200 min", noise: "67 dB" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 83, ease_of_use: 86, intelligence: 85, value: 78, ecosystem: 80, safety: 79, design: 84 }; return { slug: "ecovacs-deebot-t30-omni", name: "Ecovacs Deebot T30 Omni", mfr: "ecovacs", cat: "consumer", price: 999, year: 2024, status: "active", desc: "Mid-range robot vacuum-mop delivering 11,000 Pa suction with TrueEdge adaptive mopping that reaches within 1 mm of baseboards.", specs: { suction: "11,000 Pa", mopping: "TrueEdge rotating pads", navigation: "TrueDetect 3D + LiDAR", station: "auto-empty + auto-wash", battery: "180 min", noise: "65 dB" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 88, intelligence: 82, value: 82, ecosystem: 78, safety: 78, design: 82 }; return { slug: "ecovacs-deebot-n30-omni", name: "Ecovacs Deebot N30 Omni", mfr: "ecovacs", cat: "consumer", price: 599, year: 2025, status: "active", desc: "Value-focused robot vacuum-mop with 10,000 Pa suction, auto-empty station, and AI obstacle avoidance for clutter-heavy homes.", specs: { suction: "10,000 Pa", mopping: "pressure mop pads", navigation: "dToF LiDAR", station: "auto-empty", battery: "170 min", obstacle_avoidance: "AI 3D" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 84, ease_of_use: 85, intelligence: 86, value: 76, ecosystem: 81, safety: 79, design: 85 }; return { slug: "ecovacs-deebot-x2-omni", name: "Ecovacs Deebot X2 Omni", mfr: "ecovacs", cat: "consumer", price: 1199, year: 2024, status: "active", desc: "Square-profile robot vacuum covering 99% of room corners with dual spinning mop pads and AI-powered YIKO voice assistant.", specs: { suction: "8,000 Pa", shape: "square D-profile", mopping: "dual rotating mop", navigation: "TrueMapping 2.0", station: "auto-empty + wash + hot dry", voice: "YIKO AI assistant" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 87, reliability: 85, ease_of_use: 86, intelligence: 89, value: 73, ecosystem: 83, safety: 80, design: 87 }; return { slug: "roborock-s9-maxv-ultra", name: "Roborock S9 MaxV Ultra", mfr: "roborock", cat: "consumer", price: 1799, year: 2025, status: "active", desc: "Top-tier robot vacuum with 10,000 Pa HyperForce suction, dual vibrating mop with auto-lift, and FlexiArm extending mop reaching edges.", specs: { suction: "10,000 Pa HyperForce", mopping: "dual VibraRise 3.0 + FlexiArm", navigation: "Reactive 3D + LiDAR", station: "auto-empty + wash + refill + dry", battery: "215 min", noise: "67 dB" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 84, ease_of_use: 87, intelligence: 86, value: 79, ecosystem: 82, safety: 80, design: 85 }; return { slug: "roborock-q-revo-maxv", name: "Roborock Q Revo MaxV", mfr: "roborock", cat: "consumer", price: 899, year: 2024, status: "active", desc: "Dual rotating mop robot vacuum with 7,000 Pa suction, auto-mop-lift for carpets, and all-in-one dock with hot water washing.", specs: { suction: "7,000 Pa", mopping: "dual rotating + auto-lift", navigation: "Reactive AI + LiDAR", station: "hot water wash + dry + empty", battery: "180 min", carpet: "auto mop lift" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 83, ease_of_use: 89, intelligence: 83, value: 84, ecosystem: 80, safety: 79, design: 83 }; return { slug: "roborock-q5-max-plus", name: "Roborock Q5 Max Plus", mfr: "roborock", cat: "consumer", price: 499, year: 2025, status: "active", desc: "Budget LiDAR vacuum with 5,500 Pa suction and auto-empty dock, offering Roborock navigation quality at an accessible price point.", specs: { suction: "5,500 Pa", navigation: "PreciSense LiDAR", station: "auto-empty", battery: "240 min", noise: "62 dB", dust_bin: "770 ml" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 84, ease_of_use: 85, intelligence: 87, value: 75, ecosystem: 81, safety: 80, design: 86 }; return { slug: "roborock-s8-maxv-ultra", name: "Roborock S8 MaxV Ultra", mfr: "roborock", cat: "consumer", price: 1399, year: 2024, status: "active", desc: "Dual-brush robot vacuum with 6,000 Pa suction, VibraRise 2.0 sonic mopping, and ReactiveAI 2.0 obstacle avoidance with video streaming.", specs: { suction: "6,000 Pa", mopping: "VibraRise 2.0 sonic", brushes: "DuoRoller dual rubber", navigation: "ReactiveAI 2.0 + LiDAR", station: "RockDock Ultra", camera: "RGB + structured light" }, score: cs(b), breakdown: b }; })(),

  // Pool cleaning robots — 6
  (() => { const b = { performance: 82, reliability: 81, ease_of_use: 85, intelligence: 75, value: 78, ecosystem: 68, safety: 80, design: 80 }; return { slug: "dolphin-nautilus-cc-supreme", name: "Dolphin Nautilus CC Supreme", mfr: "ecovacs", cat: "consumer", price: 1299, year: 2024, status: "active", desc: "WiFi-connected robotic pool cleaner with CleverClean mapping that scrubs floors, walls, and waterline in pools up to 50 feet.", specs: { pool_size: "up to 50 ft", cleaning: "floor + walls + waterline", cycle_time: "2.5 hours", filtration: "top-load ultra-fine", connectivity: "WiFi + app", cable: "60 ft swivel" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 80, ease_of_use: 87, intelligence: 72, value: 82, ecosystem: 65, safety: 79, design: 78 }; return { slug: "dolphin-nautilus-cc-plus", name: "Dolphin Nautilus CC Plus", mfr: "ecovacs", cat: "consumer", price: 799, year: 2024, status: "active", desc: "Bestselling robotic pool cleaner with dual scrubbing brushes and weekly scheduling, handling pools up to 33 feet with wall-climbing capability.", specs: { pool_size: "up to 33 ft", cleaning: "floor + walls", cycle_time: "2 hours", filtration: "top-load fine + ultra-fine", scheduling: "weekly timer", cable: "50 ft swivel" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 83, ease_of_use: 84, intelligence: 80, value: 70, ecosystem: 72, safety: 81, design: 83 }; return { slug: "aiper-surfer-s1", name: "Aiper Surfer S1", mfr: "ecovacs", cat: "consumer", price: 1499, year: 2025, status: "active", desc: "Cordless solar-powered robotic pool surface skimmer with ultrasonic sensors that autonomously collects debris, leaves, and pollen from the water surface.", specs: { pool_size: "up to 1,600 sqft surface", type: "surface skimmer", power: "solar + battery", runtime: "6 hours", navigation: "ultrasonic path planning", weight: "6 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 82, ease_of_use: 83, intelligence: 78, value: 74, ecosystem: 70, safety: 80, design: 82 }; return { slug: "beatbot-aquasense-pro", name: "BeatBot AquaSense Pro", mfr: "ecovacs", cat: "consumer", price: 1999, year: 2025, status: "active", desc: "5-in-1 cordless pool cleaning robot handling surface skimming, floor vacuuming, wall scrubbing, water testing, and chemical dosing recommendations.", specs: { pool_size: "up to 2,000 sqft", cleaning: "surface + floor + walls", battery: "4.5 hr runtime", water_testing: "pH, chlorine, ORP", navigation: "sonar + camera AI", weight: "12 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 79, ease_of_use: 88, intelligence: 70, value: 85, ecosystem: 63, safety: 78, design: 77 }; return { slug: "wybot-osprey-700", name: "Wybot Osprey 700", mfr: "ecovacs", cat: "consumer", price: 499, year: 2024, status: "active", desc: "Ultra-affordable cordless robotic pool cleaner with self-parking, quad-motor drive for floor and wall cleaning in above-ground and in-ground pools.", specs: { pool_size: "up to 40 ft", cleaning: "floor + walls", battery: "2.5 hr runtime", motors: 4, cordless: true, weight: "7.5 kg", filter: "top-access fine mesh" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 81, ease_of_use: 82, intelligence: 77, value: 72, ecosystem: 69, safety: 80, design: 81 }; return { slug: "polaris-epic-8642", name: "Polaris Epic 8642", mfr: "ecovacs", cat: "consumer", price: 1699, year: 2025, status: "active", desc: "Connected robotic pool cleaner with 4WD traction system for aggressive wall climbing and a 5-stage filtration capturing particles down to 2 microns.", specs: { pool_size: "up to 60 ft", cleaning: "floor + walls + waterline", traction: "4WD", filtration: "5-stage 2-micron", connectivity: "WiFi + iAquaLink", cable: "70 ft" }, score: cs(b), breakdown: b }; })(),

  // Educational/STEM robots — 6 (Sphero + Makeblock)
  (() => { const b = { performance: 74, reliability: 78, ease_of_use: 90, intelligence: 72, value: 82, ecosystem: 80, safety: 85, design: 88 }; return { slug: "sphero-bolt-plus", name: "Sphero BOLT+", mfr: "sphero", cat: "consumer", price: 199, year: 2024, status: "active", desc: "Programmable robot ball with 8x8 LED matrix, infrared communication for multi-robot activities, and support for Scratch, JavaScript, and Swift.", specs: { diameter: "73 mm", led: "8x8 RGB matrix", sensors: "accelerometer, gyroscope, IR, light", programming: "Scratch, JavaScript, Swift", battery: "2 hr runtime", connectivity: "Bluetooth 5.0", water_resistant: "IP67" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 79, ease_of_use: 88, intelligence: 74, value: 80, ecosystem: 82, safety: 86, design: 86 }; return { slug: "sphero-rvr-plus", name: "Sphero RVR+", mfr: "sphero", cat: "consumer", price: 299, year: 2025, status: "active", desc: "Programmable all-terrain robot with expansion port for Raspberry Pi and Arduino, designed for advanced STEM courses and robotics competitions.", specs: { speed: "1.4 m/s", sensors: "color, light, IR, gyro, accelerometer", expansion: "UART + GPIO", programming: "Python, Scratch, JavaScript", battery: "2 hr runtime", terrain: "indoor + outdoor", payload: "0.5 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 75, reliability: 77, ease_of_use: 89, intelligence: 73, value: 84, ecosystem: 78, safety: 87, design: 84 }; return { slug: "makeblock-mbot-neo", name: "Makeblock mBot Neo", mfr: "makeblock", cat: "consumer", price: 149, year: 2024, status: "active", desc: "Classroom-ready STEM robot with CyberPi microcontroller, ultrasonic sensor, and line-following capability programmable via Scratch and Python.", specs: { controller: "CyberPi ESP32", sensors: "ultrasonic, line follower, color, gyro", programming: "mBlock (Scratch + Python)", connectivity: "WiFi + Bluetooth", battery: "1.5 hr", age: "8+", build_time: "15 min" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 78, ease_of_use: 86, intelligence: 76, value: 79, ecosystem: 80, safety: 85, design: 85 }; return { slug: "makeblock-mbot-mega", name: "Makeblock mBot Mega", mfr: "makeblock", cat: "consumer", price: 399, year: 2025, status: "active", desc: "Advanced STEM robot platform with Mecanum wheels for omnidirectional movement, robotic arm attachment, and AI camera for vision-based projects.", specs: { wheels: "Mecanum omnidirectional", controller: "CyberPi + add-on board", ai_camera: "object/face recognition", arm: "optional 3-DOF", programming: "Python, Scratch, C++", battery: "3 hr", sensors: "10+ included" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 72, reliability: 76, ease_of_use: 92, intelligence: 70, value: 86, ecosystem: 76, safety: 88, design: 82 }; return { slug: "sphero-mini-activity-kit", name: "Sphero Mini Activity Kit", mfr: "sphero", cat: "consumer", price: 79, year: 2024, status: "active", desc: "Ping-pong-ball-sized programmable robot with face-drive mode using phone camera, ideal for introducing coding to children ages 5 and up.", specs: { diameter: "42 mm", led: "RGB", sensors: "gyroscope, accelerometer", programming: "Sphero Edu (Scratch)", battery: "45 min", connectivity: "Bluetooth", accessories: "cones, pins, cards" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 78, ease_of_use: 85, intelligence: 75, value: 78, ecosystem: 79, safety: 86, design: 87 }; return { slug: "makeblock-codey-rocky-2", name: "Makeblock Codey Rocky 2", mfr: "makeblock", cat: "consumer", price: 179, year: 2025, status: "active", desc: "Split-design STEM robot with detachable brain (Codey) and body (Rocky), featuring AI and IoT capabilities through built-in WiFi and cloud services.", specs: { controller: "ESP32 dual-core", display: "LED dot matrix", sensors: "color, light, sound, gyro, IR", programming: "Scratch, Python", connectivity: "WiFi + Bluetooth", battery: "2 hr", ai: "speech + image recognition" }, score: cs(b), breakdown: b }; })(),

  // Home security/companion robots — 6
  (() => { const b = { performance: 75, reliability: 76, ease_of_use: 80, intelligence: 82, value: 68, ecosystem: 73, safety: 80, design: 84 }; return { slug: "samsung-ballie-2025", name: "Samsung Ballie", mfr: "samsung-robotics", cat: "consumer", price: 1299, year: 2025, status: "active", desc: "Spherical AI companion robot with built-in projector, smart home control, and autonomous patrolling that follows you room-to-room adapting to your routines.", specs: { form: "sphere 6-inch", projector: "1080p", navigation: "LiDAR + camera", ai: "on-device LLM", smart_home: "Matter + SmartThings", battery: "4 hr roaming", camera: "privacy shutter" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 73, reliability: 75, ease_of_use: 82, intelligence: 80, value: 70, ecosystem: 71, safety: 79, design: 83 }; return { slug: "lg-cloi-guidebot", name: "LG CLOi GuideBot", mfr: "lg-robotics", cat: "consumer", price: null, year: 2024, status: "active", desc: "Commercial guide robot with autonomous navigation and natural language interaction for retail stores, hotels, and airports.", specs: { height: "130 cm", display: "10.1 inch touchscreen", navigation: "LiDAR + 3D camera", speech: "multilingual NLU", battery: "8 hr", speed: "1.0 m/s", weight: "40 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 72, reliability: 74, ease_of_use: 83, intelligence: 79, value: 72, ecosystem: 68, safety: 78, design: 85 }; return { slug: "misty-ii-home", name: "Misty II Home", mfr: "misty-robotics", cat: "consumer", price: 2499, year: 2024, status: "active", desc: "Programmable home companion robot with facial recognition, home patrol mode, and an open SDK for custom skill development.", specs: { height: "36 cm", sensors: "3D ToF, 4K camera, bump, edge", display: "4-inch LCD face", navigation: "SLAM", programming: "JavaScript, Python, REST API", battery: "3 hr", weight: "3.5 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 71, reliability: 73, ease_of_use: 86, intelligence: 78, value: 74, ecosystem: 67, safety: 77, design: 86 }; return { slug: "ddl-vector-2", name: "Digital Dream Labs Vector 2.0", mfr: "anki-ddl", cat: "consumer", price: 349, year: 2024, status: "active", desc: "Palm-sized AI companion robot with emotional engine, always-on voice assistant, and autonomous exploration of tabletop environments.", specs: { height: "7.6 cm", processor: "Qualcomm APQ8009", camera: "720p wide-angle", sensors: "ToF, cliff, touch, IMU", voice: "wake-word + cloud AI", battery: "45 min", weight: "0.3 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 77, ease_of_use: 81, intelligence: 81, value: 66, ecosystem: 74, safety: 82, design: 82 }; return { slug: "amazon-astro-home", name: "Amazon Astro for Home", mfr: "samsung-robotics", cat: "consumer", price: 1599, year: 2025, status: "active", desc: "Home monitoring robot with periscope camera, Alexa integration, and person recognition that autonomously patrols your home on a customizable schedule.", specs: { height: "42 cm", camera: "periscope + wide-angle", display: "10.1 inch", navigation: "VSLAM + LiDAR", ai: "Alexa + person recognition", battery: "2 hr patrol", speed: "1.5 m/s" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 70, reliability: 74, ease_of_use: 84, intelligence: 77, value: 75, ecosystem: 70, safety: 80, design: 80 }; return { slug: "lg-cloi-servebot-home", name: "LG CLOi ServeBot Home", mfr: "lg-robotics", cat: "consumer", price: 899, year: 2025, status: "active", desc: "Compact serving robot that carries food and drinks between kitchen and living areas with tray-detection and spill-prevention stabilization.", specs: { height: "90 cm", tray_capacity: "5 kg", trays: 2, navigation: "LiDAR + camera", speed: "0.8 m/s", battery: "6 hr", stabilization: "active spill prevention" }, score: cs(b), breakdown: b }; })(),

  // Pet care robots — 6
  (() => { const b = { performance: 72, reliability: 74, ease_of_use: 85, intelligence: 73, value: 78, ecosystem: 65, safety: 82, design: 79 }; return { slug: "litter-robot-4", name: "Litter-Robot 4", mfr: "ecovacs", cat: "consumer", price: 699, year: 2024, status: "active", desc: "Self-cleaning robotic litter box with weight sensor cat detection, odor-trap system, and app notifications for waste drawer fullness.", specs: { cleaning: "automatic sifting", cycle_time: "7 min", cats: "up to 4", sensor: "weight + motion", waste_drawer: "15 lb capacity", connectivity: "WiFi app", dimensions: "62x68x74 cm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 70, reliability: 72, ease_of_use: 86, intelligence: 74, value: 76, ecosystem: 63, safety: 81, design: 78 }; return { slug: "petcube-play-3", name: "Petcube Play 3", mfr: "ecovacs", cat: "consumer", price: 199, year: 2025, status: "active", desc: "Interactive pet camera with AI-powered auto-play laser toy that activates when your pet is detected and you are away from home.", specs: { camera: "1080p 160° wide", laser: "AI auto-play", detection: "pet + person AI", audio: "2-way", storage: "cloud + local", connectivity: "WiFi", treat_dispenser: false }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 68, reliability: 71, ease_of_use: 84, intelligence: 70, value: 80, ecosystem: 60, safety: 80, design: 76 }; return { slug: "furbo-360-dog-cam", name: "Furbo 360 Dog Camera", mfr: "ecovacs", cat: "consumer", price: 179, year: 2024, status: "active", desc: "360-degree rotating pet camera with treat-tossing mechanism, barking alerts, and dog activity reports generated by AI behavioral analysis.", specs: { camera: "1080p 360° rotating", treat_toss: "yes", alerts: "barking, person, dog", ai: "behavioral reports", audio: "2-way", storage: "cloud subscription", night_vision: "infrared" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 74, reliability: 75, ease_of_use: 83, intelligence: 76, value: 72, ecosystem: 66, safety: 83, design: 80 }; return { slug: "ebo-air-pet-companion", name: "Ebo Air Pet Companion", mfr: "ecovacs", cat: "consumer", price: 249, year: 2025, status: "active", desc: "Mobile pet companion robot that rolls around autonomously engaging cats and dogs with laser, feather, and audio stimulation while you are away.", specs: { form: "sphere 9 cm", camera: "1080p", toys: "laser + feather + sounds", navigation: "autonomous roaming", battery: "2 hr", connectivity: "WiFi", scheduling: "app-based play sessions" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 73, reliability: 76, ease_of_use: 82, intelligence: 72, value: 74, ecosystem: 64, safety: 82, design: 77 }; return { slug: "petkit-purobot-ultra", name: "Petkit Purobot Ultra", mfr: "ecovacs", cat: "consumer", price: 599, year: 2025, status: "active", desc: "Fully enclosed self-cleaning robotic litter box with UV sterilization, deodorizer, and health monitoring that tracks cat weight and visit frequency.", specs: { cleaning: "fully enclosed rotation", sterilization: "UV-C", deodorizer: "ozone + carbon", health: "weight + frequency tracking", capacity: "7L waste", connectivity: "WiFi + app", cats: "up to 3" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 71, reliability: 73, ease_of_use: 87, intelligence: 71, value: 79, ecosystem: 62, safety: 81, design: 78 }; return { slug: "wopet-smart-feeder-pro", name: "WOpet Smart Feeder Pro", mfr: "ecovacs", cat: "consumer", price: 89, year: 2024, status: "active", desc: "WiFi-connected automatic pet feeder with portion control, voice recording for meal calls, and dual power backup for feeding schedule reliability.", specs: { capacity: "7L hopper", portions: "1-10 per meal", meals: "up to 6/day", camera: "720p optional", voice: "10-sec recording", power: "AC + battery backup", connectivity: "WiFi" }, score: cs(b), breakdown: b }; })(),

  // Kitchen/cooking robots — 5
  (() => { const b = { performance: 80, reliability: 79, ease_of_use: 82, intelligence: 77, value: 70, ecosystem: 72, safety: 82, design: 83 }; return { slug: "samsung-bot-chef", name: "Samsung Bot Chef", mfr: "samsung-robotics", cat: "consumer", price: 3999, year: 2025, status: "coming_soon", desc: "Dual-arm kitchen robot that mounts above the counter and can chop, stir, season, and plate dishes following video-learned recipes.", specs: { arms: 2, dof_per_arm: 6, reach: "800 mm", recipes: "5,000+ cloud library", learning: "video recipe imitation", safety: "force-limited joints", mounting: "ceiling/cabinet rail" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 80, ease_of_use: 78, intelligence: 79, value: 65, ecosystem: 70, safety: 83, design: 84 }; return { slug: "moley-robotic-kitchen-2", name: "Moley Robotic Kitchen II", mfr: "samsung-robotics", cat: "consumer", price: 35000, year: 2025, status: "active", desc: "Fully automated kitchen system with two robotic arms that replicate chef-recorded recipes, operating the stove, oven, and sink autonomously.", specs: { arms: 2, dof_per_arm: 20, recipes: "7,000+ chef-recorded", appliance_control: "stove, oven, sink, mixer", learning: "motion capture", installation: "full kitchen integrated", safety: "glass safety screen" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 78, ease_of_use: 86, intelligence: 74, value: 80, ecosystem: 68, safety: 84, design: 80 }; return { slug: "thermomix-tm7", name: "Thermomix TM7", mfr: "ecovacs", cat: "consumer", price: 1899, year: 2025, status: "active", desc: "AI-guided cooking robot combining 24 functions including chopping, steaming, and sous vide with a guided cooking screen and auto-temperature adjustment.", specs: { functions: 24, capacity: "2.2L", power: "1,500W", display: "6.8 inch touchscreen", recipes: "100,000+ guided", connectivity: "WiFi", weight: "7 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 74, reliability: 77, ease_of_use: 84, intelligence: 72, value: 78, ecosystem: 66, safety: 83, design: 78 }; return { slug: "rotimatic-flatbread-maker", name: "Rotimatic", mfr: "ecovacs", cat: "consumer", price: 999, year: 2024, status: "active", desc: "Automated flatbread robot that measures, kneads, flattens, and cooks rotis, tortillas, and pizza bases at the touch of a button in 90 seconds each.", specs: { output: "1 flatbread per 90 sec", types: "roti, puri, tortilla, pizza base", capacity: "20 breads per fill", thickness: "adjustable 5 levels", power: "900W", dimensions: "40x30x40 cm", connectivity: "WiFi" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 73, reliability: 76, ease_of_use: 88, intelligence: 71, value: 82, ecosystem: 64, safety: 82, design: 79 }; return { slug: "nymble-cooking-robot", name: "Nymble Julia", mfr: "ecovacs", cat: "consumer", price: 1499, year: 2025, status: "active", desc: "Countertop cooking robot that prepares one-pot meals from pre-loaded ingredient pods, following 500+ recipes with automatic stirring and temperature control.", specs: { capacity: "2 servings", recipes: "500+", cooking: "induction + stirring", pods: "pre-portioned ingredients", time: "15-30 min per meal", power: "1,200W", connectivity: "WiFi + app" }, score: cs(b), breakdown: b }; })(),

  // Window cleaning robots — 5
  (() => { const b = { performance: 76, reliability: 75, ease_of_use: 82, intelligence: 72, value: 77, ecosystem: 63, safety: 80, design: 76 }; return { slug: "ecovacs-winbot-w2-omni", name: "Ecovacs Winbot W2 Omni", mfr: "ecovacs", cat: "consumer", price: 499, year: 2024, status: "active", desc: "Window cleaning robot with dual-pad cross-motion cleaning and edge detection that automatically covers the full pane including corners.", specs: { cleaning: "dual cross-motion pads", suction: "5,500 Pa vacuum hold", detection: "edge + frame sensor", spray: "built-in water spray", safety: "UPS backup + safety rope", weight: "1.8 kg", power: "corded" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 76, ease_of_use: 80, intelligence: 74, value: 75, ecosystem: 65, safety: 81, design: 77 }; return { slug: "hobot-s6-pro", name: "Hobot S6 Pro", mfr: "ecovacs", cat: "consumer", price: 549, year: 2025, status: "active", desc: "Ultrasonic water-spray window robot with AI path planning that maps window dimensions and calculates optimal cleaning routes automatically.", specs: { cleaning: "rotating dual pads", spray: "ultrasonic water mist", suction: "5,800 Pa", path: "AI auto-mapping", safety: "UPS + safety cord", weight: "1.6 kg", remote: "app + included remote" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 74, reliability: 74, ease_of_use: 84, intelligence: 70, value: 80, ecosystem: 62, safety: 79, design: 75 }; return { slug: "mamibot-iglassbot-w200", name: "Mamibot iGlassbot W200", mfr: "ecovacs", cat: "consumer", price: 299, year: 2024, status: "active", desc: "Budget-friendly window cleaning robot with 3,800 Pa suction suitable for glass, tile, and mirror surfaces up to 6 mm thickness.", specs: { cleaning: "microfiber pad", suction: "3,800 Pa", surfaces: "glass, tile, mirror", thickness: "3-6 mm", safety: "UPS + safety rope", weight: "1.3 kg", noise: "65 dB" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 76, ease_of_use: 81, intelligence: 73, value: 74, ecosystem: 64, safety: 82, design: 78 }; return { slug: "ecovacs-winbot-w1-pro", name: "Ecovacs Winbot W1 Pro", mfr: "ecovacs", cat: "consumer", price: 399, year: 2024, status: "active", desc: "Upgraded Winbot with WIN-SLAM 3.0 navigation and cross-motion technology achieving streak-free cleaning on frameless and framed windows.", specs: { cleaning: "cross-motion dual pad", suction: "5,200 Pa", navigation: "WIN-SLAM 3.0", spray: "steady water flow", safety: "UPS backup + cord", weight: "1.7 kg", glass_type: "framed + frameless" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 77, ease_of_use: 79, intelligence: 76, value: 72, ecosystem: 66, safety: 83, design: 79 }; return { slug: "hobot-r3", name: "Hobot R3", mfr: "ecovacs", cat: "consumer", price: 649, year: 2025, status: "active", desc: "Dual-reservoir window robot with separate clean and dirty water tanks, AI edge detection, and automatic drying mode for spot-free results.", specs: { cleaning: "rotating pad + squeegee", reservoirs: "dual clean/dirty", suction: "6,200 Pa", ai: "edge + corner detection", drying: "automatic mode", safety: "triple safety system", weight: "2.0 kg" }, score: cs(b), breakdown: b }; })(),
];

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 19 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 19 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
