/**
 * Robotomated — Wave 20 Robot Import: 50 New Robots
 * Focus: Industrial drones, inspection drones, security patrol, underwater ROVs, space/extreme environment
 * Run: npx tsx scripts/import-robots-wave20.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

const newMfrs = [
  { slug: "skydio", name: "Skydio", country: "US", founded_year: 2014, website: "https://www.skydio.com" },
  { slug: "flyability", name: "Flyability", country: "CH", founded_year: 2014, website: "https://www.flyability.com" },
  { slug: "clearpath-robotics", name: "Clearpath Robotics", country: "CA", founded_year: 2009, website: "https://clearpathrobotics.com" },
  { slug: "ghost-robotics", name: "Ghost Robotics", country: "US", founded_year: 2015, website: "https://www.ghostrobotics.io" },
  { slug: "anybotics", name: "ANYbotics", country: "CH", founded_year: 2016, website: "https://www.anybotics.com" },
  { slug: "blue-ocean-robotics", name: "Blue Ocean Robotics", country: "DK", founded_year: 2013, website: "https://www.blue-ocean-robotics.com" },
  { slug: "smp-robotics", name: "SMP Robotics", country: "US", founded_year: 2016, website: "https://smprobotics.com" },
  { slug: "deep-trekker", name: "Deep Trekker", country: "CA", founded_year: 2010, website: "https://www.deeptrekker.com" },
];

const robots: R[] = [
  // Industrial inspection drones — 8 (Skydio + Flyability)
  (() => { const b = { performance: 87, reliability: 85, ease_of_use: 84, intelligence: 90, value: 72, ecosystem: 80, safety: 86, design: 84 }; return { slug: "skydio-x10", name: "Skydio X10", mfr: "skydio", cat: "drone", price: 14900, year: 2024, status: "active", desc: "Enterprise inspection drone with 6-camera obstacle avoidance, 65-megapixel mapping payload, and 35-minute flight time for infrastructure surveying.", specs: { cameras: "6 navigation + payload", payload_camera: "65 MP mapping", flight_time: "35 min", speed: "15 m/s", obstacle_avoidance: "360° AI", wind_resistance: "45 km/h", weight: "1.9 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 84, ease_of_use: 86, intelligence: 88, value: 74, ecosystem: 78, safety: 85, design: 83 }; return { slug: "skydio-x10d", name: "Skydio X10D", mfr: "skydio", cat: "drone", price: 24900, year: 2024, status: "active", desc: "Defense and public safety variant with thermal imaging, night-vision, and encrypted communications for BVLOS operations in restricted airspace.", specs: { cameras: "6 nav + EO/IR", thermal: "640x512 radiometric", flight_time: "35 min", encryption: "AES-256", range: "6 km", compliance: "NDAA", night_vision: true }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 83, ease_of_use: 85, intelligence: 86, value: 76, ecosystem: 77, safety: 84, design: 82 }; return { slug: "skydio-x2e", name: "Skydio X2E", mfr: "skydio", cat: "drone", price: 10999, year: 2023, status: "active", desc: "Enterprise-grade autonomous drone with 3D Scan and Dock-based persistent monitoring for recurring infrastructure inspections.", specs: { cameras: "6 navigation + 12 MP", thermal: "320x256 optional", flight_time: "27 min", autonomy: "3D Scan + Dock", dock: "remote launch/land", wind_resistance: "40 km/h", weight: "1.4 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 88, reliability: 86, ease_of_use: 82, intelligence: 91, value: 70, ecosystem: 79, safety: 87, design: 85 }; return { slug: "skydio-x10-lidar", name: "Skydio X10 LiDAR", mfr: "skydio", cat: "drone", price: 28000, year: 2025, status: "active", desc: "LiDAR-equipped X10 variant generating survey-grade 3D point clouds at 240,000 points per second for digital twin creation of industrial facilities.", specs: { lidar: "240,000 pts/sec", accuracy: "±2 cm at 100 m", cameras: "6 nav + 65 MP + LiDAR", flight_time: "32 min", output: "3D point cloud + mesh", range: "120 m LiDAR", weight: "2.3 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 84, ease_of_use: 88, intelligence: 84, value: 78, ecosystem: 75, safety: 90, design: 86 }; return { slug: "flyability-elios-3", name: "Flyability Elios 3", mfr: "flyability", cat: "drone", price: 45000, year: 2024, status: "active", desc: "Collision-tolerant cage drone for indoor confined-space inspections in boilers, tanks, and mines where GPS is unavailable and crashes are inevitable.", specs: { cage: "collision-tolerant protective", camera: "4K + LiDAR", flight_time: "12 min", lighting: "10,000 lumen", navigation: "SLAM (GPS-denied)", ip_rating: "dust-tolerant", diameter: "38 cm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 87, intelligence: 82, value: 80, ecosystem: 73, safety: 89, design: 84 }; return { slug: "flyability-elios-3-rag", name: "Flyability Elios 3 RAD", mfr: "flyability", cat: "drone", price: 65000, year: 2025, status: "active", desc: "Radiation-hardened Elios variant for nuclear facility inspections with onboard dosimeter and remote operation from shielded control rooms.", specs: { cage: "collision-tolerant", camera: "4K + thermal", dosimeter: "integrated gamma/beta", radiation_tolerance: "100 Gy total dose", flight_time: "10 min", lighting: "10,000 lumen", tether: "optional 30 m" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 81, ease_of_use: 86, intelligence: 80, value: 82, ecosystem: 72, safety: 88, design: 83 }; return { slug: "flyability-elios-2-ut", name: "Flyability Elios 2 UT", mfr: "flyability", cat: "drone", price: 38000, year: 2024, status: "active", desc: "Ultrasonic thickness measurement drone that lands on metal surfaces and measures wall thickness of pipes, tanks, and vessels in confined spaces.", specs: { cage: "collision-tolerant", ut_probe: "ultrasonic thickness", accuracy: "±0.1 mm", camera: "4K", flight_time: "11 min", surfaces: "metal pipes, tanks, vessels", measurement_range: "1-100 mm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 83, ease_of_use: 83, intelligence: 85, value: 71, ecosystem: 76, safety: 86, design: 82 }; return { slug: "skydio-dock", name: "Skydio Remote Dock", mfr: "skydio", cat: "drone", price: 8500, year: 2024, status: "active", desc: "Weatherproof autonomous docking station enabling scheduled recurring drone flights without on-site pilots for persistent facility monitoring.", specs: { compatibility: "Skydio X10, X2E", weather: "IP55 rated", charging: "80% in 45 min", scheduling: "cloud-based recurring", connectivity: "4G/5G + WiFi", operating_temp: "-20°C to 45°C", dimensions: "60x60x45 cm" }, score: cs(b), breakdown: b }; })(),

  // Agricultural drones — 8 (DJI Agras — DJI already in DB)
  (() => { const b = { performance: 86, reliability: 84, ease_of_use: 80, intelligence: 83, value: 76, ecosystem: 82, safety: 82, design: 80 }; return { slug: "dji-agras-t50", name: "DJI Agras T50", mfr: "dji", cat: "drone", price: 18000, year: 2024, status: "active", desc: "Heavy-lift agricultural drone with 40 kg spray capacity and 50 kg spreading payload for large-scale crop protection and fertilizer application.", specs: { spray_tank: "40 L", spread_capacity: "50 kg", flow_rate: "16 L/min", spray_width: "11 m", flight_time: "18 min loaded", radar: "phased-array + binocular vision", coverage: "21 ha/hr spray" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 83, ease_of_use: 82, intelligence: 81, value: 80, ecosystem: 80, safety: 81, design: 79 }; return { slug: "dji-agras-t25", name: "DJI Agras T25", mfr: "dji", cat: "drone", price: 12500, year: 2024, status: "active", desc: "Mid-size agricultural drone with 20 L spray tank and terrain-following radar for hilly orchards and vineyards with variable rate application.", specs: { spray_tank: "20 L", flow_rate: "12 L/min", spray_width: "7.5 m", flight_time: "15 min loaded", radar: "dual phased-array", terrain_following: "centimeter-level", coverage: "12 ha/hr" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 81, ease_of_use: 84, intelligence: 79, value: 83, ecosystem: 78, safety: 80, design: 78 }; return { slug: "dji-agras-t20p", name: "DJI Agras T20P", mfr: "dji", cat: "drone", price: 9800, year: 2023, status: "active", desc: "Compact agricultural sprayer optimized for smallholder farms with 20 L tank, simple app-based mission planning, and foldable airframe.", specs: { spray_tank: "20 L", flow_rate: "8 L/min", spray_width: "6.5 m", flight_time: "12 min loaded", foldable: true, weight: "22 kg dry", coverage: "8 ha/hr" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 83, ease_of_use: 79, intelligence: 85, value: 72, ecosystem: 81, safety: 83, design: 81 }; return { slug: "dji-mavic-3m", name: "DJI Mavic 3 Multispectral", mfr: "dji", cat: "drone", price: 6388, year: 2024, status: "active", desc: "Compact multispectral survey drone with 4 spectral bands plus RGB for crop health mapping, NDVI analysis, and precision agriculture planning.", specs: { cameras: "20 MP RGB + 4 spectral bands", bands: "green, red, red-edge, near-IR", flight_time: "43 min", accuracy: "centimeter RTK", output: "NDVI, NDRE maps", weight: "951 g", range: "15 km" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 82, ease_of_use: 81, intelligence: 82, value: 75, ecosystem: 79, safety: 81, design: 79 }; return { slug: "dji-agras-t50-mapping", name: "DJI Agras T50 Mapping Kit", mfr: "dji", cat: "drone", price: 22000, year: 2025, status: "active", desc: "T50 equipped with multispectral camera payload for combined spraying and crop monitoring, generating prescription maps that feed back into spray missions.", specs: { spray_tank: "40 L", mapping: "5-band multispectral", workflow: "map → prescription → spray", flight_time: "15 min mapping / 18 min spray", output: "NDVI + variable rate map", integration: "DJI SmartFarm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 80, ease_of_use: 83, intelligence: 78, value: 84, ecosystem: 77, safety: 79, design: 77 }; return { slug: "dji-agras-t10", name: "DJI Agras T10", mfr: "dji", cat: "drone", price: 5500, year: 2023, status: "active", desc: "Entry-level agricultural drone with 8 L spray tank designed for small farms and specialty crops like coffee, tea, and berries.", specs: { spray_tank: "8 L", flow_rate: "4.8 L/min", spray_width: "5 m", flight_time: "10 min loaded", weight: "15 kg dry", foldable: true, coverage: "4 ha/hr" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 82, ease_of_use: 78, intelligence: 84, value: 70, ecosystem: 80, safety: 82, design: 80 }; return { slug: "dji-flycart-30", name: "DJI FlyCart 30", mfr: "dji", cat: "drone", price: 16000, year: 2024, status: "active", desc: "Heavy-lift delivery drone carrying 30 kg payloads up to 16 km for agricultural supply drops, emergency deliveries, and remote area logistics.", specs: { payload: "30 kg", range: "16 km loaded", flight_time: "18 min at 30 kg", speed: "15 m/s", ip_rating: "IP55", weather: "rain + wind 12 m/s", winch: "optional 20 m" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 81, ease_of_use: 80, intelligence: 80, value: 77, ecosystem: 78, safety: 80, design: 78 }; return { slug: "dji-agras-fleet-manager", name: "DJI SmartFarm Platform", mfr: "dji", cat: "drone", price: null, year: 2025, status: "active", desc: "Cloud-based fleet management platform coordinating multiple Agras drones for synchronized spraying operations across large agricultural estates.", specs: { drones: "unlimited fleet", coordination: "multi-drone sync", planning: "prescription maps", analytics: "spray coverage reports", integration: "Agras T10/T20P/T25/T50", connectivity: "4G cloud", pricing: "SaaS subscription" }, score: cs(b), breakdown: b }; })(),

  // Security patrol robots — 6
  (() => { const b = { performance: 78, reliability: 79, ease_of_use: 82, intelligence: 80, value: 70, ecosystem: 72, safety: 84, design: 80 }; return { slug: "cobalt-indoor-patrol", name: "Cobalt Indoor Patrol Robot", mfr: "cobalt-robotics", cat: "warehouse", price: null, year: 2024, status: "active", desc: "Indoor security robot with 360-degree camera array, thermal anomaly detection, and live remote guard intervention for corporate campus patrol.", specs: { height: "120 cm", cameras: "360° array + thermal", speed: "1.5 m/s", battery: "8 hr", detection: "person, thermal anomaly, door ajar", response: "live remote guard", navigation: "LiDAR SLAM" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 77, ease_of_use: 80, intelligence: 78, value: 72, ecosystem: 70, safety: 83, design: 78 }; return { slug: "smp-s5-outdoor-patrol", name: "SMP Robotics S5.2", mfr: "smp-robotics", cat: "warehouse", price: 75000, year: 2024, status: "active", desc: "All-weather outdoor security robot patrolling perimeters autonomously with license plate recognition, thermal imaging, and intrusion alerting.", specs: { speed: "5 km/h", cameras: "PTZ + thermal + LPR", battery: "16 hr", terrain: "paved + gravel + grass", weather: "IP65 all-weather", alerts: "intrusion + LPR + thermal", weight: "60 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 80, ease_of_use: 79, intelligence: 82, value: 68, ecosystem: 74, safety: 85, design: 82 }; return { slug: "anybotics-anymal-d", name: "ANYbotics ANYmal D", mfr: "anybotics", cat: "warehouse", price: 150000, year: 2024, status: "active", desc: "Quadruped inspection robot for industrial facilities that climbs stairs, reads gauges, and detects gas leaks with thermal and acoustic sensors.", specs: { legs: 4, speed: "1.0 m/s", stairs: "yes, standard industrial", sensors: "LiDAR, thermal, acoustic, RGB", battery: "2 hr", ip_rating: "IP67", weight: "55 kg", atex: "Zone 1 optional" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 78, ease_of_use: 78, intelligence: 79, value: 66, ecosystem: 68, safety: 84, design: 83 }; return { slug: "ghost-vision-60", name: "Ghost Robotics Vision 60", mfr: "ghost-robotics", cat: "warehouse", price: 135000, year: 2024, status: "active", desc: "All-terrain quadruped robot for perimeter security and remote inspection in GPS-denied environments with modular sensor payload bay.", specs: { legs: 4, speed: "1.5 m/s", terrain: "sand, rock, stairs, mud", payload_bay: "10 kg modular", battery: "3 hr", ip_rating: "IP66", weight: "45 kg", autonomous: "waypoint patrol" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 81, ease_of_use: 77, intelligence: 83, value: 64, ecosystem: 75, safety: 86, design: 84 }; return { slug: "anybotics-anymal-x", name: "ANYbotics ANYmal X", mfr: "anybotics", cat: "warehouse", price: 200000, year: 2025, status: "active", desc: "ATEX-certified legged robot for explosive atmosphere inspections in oil refineries and chemical plants with integrated gas detection array.", specs: { legs: 4, certification: "ATEX Zone 1", gas_detection: "LEL, H2S, CO, O2", sensors: "LiDAR, thermal, acoustic, RGB", battery: "2.5 hr", speed: "1.0 m/s", weight: "60 kg", docking: "auto-charge station" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 75, reliability: 77, ease_of_use: 81, intelligence: 77, value: 74, ecosystem: 71, safety: 82, design: 79 }; return { slug: "smp-s6-heavy-patrol", name: "SMP Robotics S6", mfr: "smp-robotics", cat: "warehouse", price: 95000, year: 2025, status: "active", desc: "Heavy-duty outdoor patrol robot with tracked drive for rough terrain, 20 km range, and integration with existing VMS and access control systems.", specs: { speed: "8 km/h", drive: "tracked", range: "20 km", cameras: "PTZ 30x zoom + thermal", integration: "VMS, access control", battery: "12 hr", weight: "85 kg", payload: "15 kg sensor bay" }, score: cs(b), breakdown: b }; })(),

  // Underwater ROVs — 6
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 84, intelligence: 74, value: 82, ecosystem: 72, safety: 80, design: 78 }; return { slug: "deep-trekker-dtg3", name: "Deep Trekker DTG3", mfr: "deep-trekker", cat: "manufacturing", price: 15000, year: 2024, status: "active", desc: "Portable observation-class ROV with 200 m depth rating, internal battery (no tether power), and hand-controller for infrastructure and hull inspections.", specs: { depth: "200 m", camera: "4K 330° rotating", battery: "8 hr", thrusters: 4, weight: "7.7 kg in air", tether: "data only (no power)", controller: "handheld integrated" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 83, reliability: 83, ease_of_use: 82, intelligence: 76, value: 78, ecosystem: 74, safety: 81, design: 80 }; return { slug: "deep-trekker-revolution", name: "Deep Trekker Revolution", mfr: "deep-trekker", cat: "manufacturing", price: 25000, year: 2024, status: "active", desc: "Work-class ROV with manipulator arm and 305 m depth rating for underwater construction inspection, debris removal, and sample collection.", specs: { depth: "305 m", camera: "4K + auxiliary", manipulator: "1 DOF grabber arm", thrusters: 6, battery: "6 hr", weight: "14 kg in air", payload: "tool attachments" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 80, ease_of_use: 86, intelligence: 72, value: 85, ecosystem: 70, safety: 79, design: 77 }; return { slug: "deep-trekker-pivot", name: "Deep Trekker Pivot", mfr: "deep-trekker", cat: "manufacturing", price: 8500, year: 2025, status: "active", desc: "Ultra-compact ROV the size of a football for pipe and tank internal inspections in spaces as small as 250 mm diameter.", specs: { depth: "100 m", camera: "1080p 270° tilt", dimensions: "210x210x170 mm", weight: "3.8 kg", battery: "4 hr", thrusters: 4, pipe_size: "250 mm min" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 85, reliability: 84, ease_of_use: 79, intelligence: 78, value: 72, ecosystem: 76, safety: 82, design: 81 }; return { slug: "bluerov-2-heavy", name: "BlueROV2 Heavy", mfr: "deep-trekker", cat: "manufacturing", price: 12000, year: 2024, status: "active", desc: "Open-source heavy-configuration ROV with 8 thrusters for stable underwater work including sonar mapping and photogrammetry to 300 m depth.", specs: { depth: "300 m", thrusters: 8, camera: "1080p low-light", sonar: "Ping360 scanning optional", payload: "10 kg", open_source: "ArduSub firmware", tether: "300 m max" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 81, ease_of_use: 80, intelligence: 77, value: 70, ecosystem: 73, safety: 81, design: 79 }; return { slug: "deep-trekker-dtg3-sonar", name: "Deep Trekker DTG3 Sonar", mfr: "deep-trekker", cat: "manufacturing", price: 28000, year: 2025, status: "active", desc: "DTG3 equipped with multibeam imaging sonar for zero-visibility inspections in turbid water, mapping submerged structures at 5 cm resolution.", specs: { depth: "200 m", camera: "4K + sonar imaging", sonar: "multibeam imaging", resolution: "5 cm", battery: "6 hr", weight: "9.5 kg", visibility: "zero-vis capable" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 86, reliability: 85, ease_of_use: 76, intelligence: 80, value: 65, ecosystem: 77, safety: 83, design: 82 }; return { slug: "deep-trekker-revolution-cp", name: "Deep Trekker Revolution CP", mfr: "deep-trekker", cat: "manufacturing", price: 55000, year: 2025, status: "active", desc: "Cathodic protection inspection ROV with integrated CP measurement probes and hull cleaning brush for ship hull surveys and maintenance.", specs: { depth: "305 m", cp_probes: "integrated Ag/AgCl", brush: "hull cleaning attachment", camera: "4K + close-up", thrusters: 6, battery: "5 hr", weight: "18 kg" }, score: cs(b), breakdown: b }; })(),

  // Space/extreme environment robots — 6
  (() => { const b = { performance: 80, reliability: 86, ease_of_use: 68, intelligence: 82, value: 55, ecosystem: 60, safety: 90, design: 82 }; return { slug: "clearpath-husky-observer", name: "Clearpath Husky Observer", mfr: "clearpath-robotics", cat: "construction", price: 85000, year: 2024, status: "active", desc: "Ruggedized UGV for extreme-environment surveys in volcanic, arctic, and disaster zones with modular sensor payload and IP67 all-weather rating.", specs: { payload: "75 kg", speed: "1.0 m/s", drive: "4x4 skid-steer", battery: "3 hr", ip_rating: "IP67", temp_range: "-40°C to 50°C", weight: "50 kg", ros: "ROS 2 native" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 84, ease_of_use: 70, intelligence: 80, value: 58, ecosystem: 62, safety: 88, design: 80 }; return { slug: "clearpath-warthog", name: "Clearpath Warthog", mfr: "clearpath-robotics", cat: "construction", price: 40000, year: 2024, status: "active", desc: "Amphibious all-terrain UGV with 272 kg payload capacity for mining site mapping, search-and-rescue, and nuclear decommissioning support.", specs: { payload: "272 kg", speed: "4.5 m/s", drive: "differential 4-wheel", battery: "3 hr", amphibious: true, weight: "280 kg", ros: "ROS 2", clearance: "254 mm" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 82, ease_of_use: 72, intelligence: 78, value: 60, ecosystem: 58, safety: 87, design: 78 }; return { slug: "clearpath-jackal-2", name: "Clearpath Jackal 2", mfr: "clearpath-robotics", cat: "construction", price: 28000, year: 2025, status: "active", desc: "Compact weatherproof UGV for outdoor research and inspection with ROS 2 native stack and 20 kg sensor payload for rapid prototyping.", specs: { payload: "20 kg", speed: "2.0 m/s", drive: "4-wheel differential", battery: "4 hr", ip_rating: "IP62", weight: "17 kg", ros: "ROS 2 Humble", sensors: "modular mounting" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 74, reliability: 80, ease_of_use: 74, intelligence: 76, value: 62, ecosystem: 56, safety: 86, design: 76 }; return { slug: "blue-ocean-uv-disinfect-outdoor", name: "Blue Ocean UVD OutdoorBot", mfr: "blue-ocean-robotics", cat: "construction", price: 120000, year: 2025, status: "active", desc: "Outdoor-rated autonomous UV disinfection robot for transit stations, stadiums, and public spaces with 360-degree UV-C array and rain detection.", specs: { uv_type: "UV-C 360° array", coverage: "500 sqm/hr", navigation: "outdoor SLAM", weather: "IP55 rain-detect pause", battery: "8 hr", speed: "1.0 m/s", weight: "120 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 82, reliability: 85, ease_of_use: 66, intelligence: 81, value: 52, ecosystem: 64, safety: 92, design: 84 }; return { slug: "ghost-spirit-40-hazmat", name: "Ghost Robotics Spirit 40 HAZMAT", mfr: "ghost-robotics", cat: "construction", price: 180000, year: 2025, status: "active", desc: "Quadruped robot for CBRN hazmat response with sealed joints, decontamination-compatible exterior, and chemical detection sensor suite.", specs: { legs: 4, speed: "1.2 m/s", sensors: "CBRN detection array", sealing: "IP67 + chemical resistant", battery: "2 hr", weight: "22 kg", decon: "washdown compatible", teleoperation: "1 km range" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 83, ease_of_use: 71, intelligence: 79, value: 56, ecosystem: 61, safety: 89, design: 81 }; return { slug: "clearpath-dingo-d", name: "Clearpath Dingo-D", mfr: "clearpath-robotics", cat: "construction", price: 22000, year: 2025, status: "active", desc: "Ultra-compact indoor/outdoor UGV designed for tight-space inspection in collapsed structures, mines, and confined industrial spaces.", specs: { payload: "20 kg", speed: "1.3 m/s", drive: "omnidirectional", battery: "4 hr", dimensions: "55x42x18 cm", weight: "14 kg", ros: "ROS 2", sensors: "3D LiDAR + camera" }, score: cs(b), breakdown: b }; })(),

  // Mine inspection robots — 6
  (() => { const b = { performance: 81, reliability: 83, ease_of_use: 75, intelligence: 82, value: 68, ecosystem: 70, safety: 90, design: 79 }; return { slug: "anybotics-anymal-mine", name: "ANYbotics ANYmal Mine", mfr: "anybotics", cat: "construction", price: 180000, year: 2025, status: "active", desc: "Mine-certified ANYmal variant with methane and dust explosion-proof housing for autonomous inspection of underground mining operations.", specs: { legs: 4, certification: "IECEx Zone 1", gas_detection: "CH4, CO, NO2, O2", dust: "explosion-proof housing", battery: "2 hr", speed: "0.8 m/s", weight: "65 kg", mapping: "3D LiDAR SLAM" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 77, reliability: 80, ease_of_use: 78, intelligence: 78, value: 74, ecosystem: 67, safety: 88, design: 76 }; return { slug: "clearpath-husky-mine", name: "Clearpath Husky Mine", mfr: "clearpath-robotics", cat: "construction", price: 95000, year: 2024, status: "active", desc: "Mine-rated Husky UGV with integrated gas monitoring and 3D mapping for post-blast inspection and geological survey in underground galleries.", specs: { payload: "50 kg", speed: "0.8 m/s", gas_monitoring: "multi-gas array", mapping: "3D LiDAR", battery: "4 hr", ip_rating: "IP67", weight: "55 kg", explosion_proof: "optional housing" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 81, ease_of_use: 83, intelligence: 77, value: 80, ecosystem: 69, safety: 87, design: 78 }; return { slug: "flyability-elios-3-mine", name: "Flyability Elios 3 Mine", mfr: "flyability", cat: "drone", price: 52000, year: 2025, status: "active", desc: "Mine-configured Elios drone with enhanced dust filtration and 3D cavity mapping for stope inspections and ore body volumetric surveys.", specs: { cage: "collision-tolerant", camera: "4K + LiDAR", dust_protection: "enhanced filtration", mapping: "3D cavity volumetric", flight_time: "11 min", lighting: "12,000 lumen", output: "point cloud + mesh" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 75, reliability: 78, ease_of_use: 80, intelligence: 75, value: 76, ecosystem: 65, safety: 86, design: 75 }; return { slug: "smp-s5-mine-patrol", name: "SMP Robotics Mine Patrol", mfr: "smp-robotics", cat: "construction", price: 85000, year: 2025, status: "active", desc: "Wheeled patrol robot for surface mine perimeter security and tailings dam monitoring with thermal leak detection and seismic sensors.", specs: { speed: "5 km/h", cameras: "PTZ + thermal", sensors: "seismic, gas, thermal", battery: "14 hr", terrain: "mine roads + gravel", weather: "IP65", weight: "65 kg", alerts: "tailings dam + perimeter" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 76, intelligence: 80, value: 70, ecosystem: 68, safety: 89, design: 77 }; return { slug: "ghost-vision-60-mine", name: "Ghost Robotics V60 Mine", mfr: "ghost-robotics", cat: "construction", price: 155000, year: 2025, status: "active", desc: "Mine-adapted quadruped robot traversing rubble, rail tracks, and steep grades for autonomous underground inspection with methane pre-alarm.", specs: { legs: 4, speed: "1.2 m/s", terrain: "rubble, rails, 45° grade", gas: "CH4 pre-alarm at 10% LEL", battery: "2.5 hr", weight: "48 kg", mapping: "SLAM in GPS-denied", teleoperation: "mesh radio" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 79, ease_of_use: 82, intelligence: 76, value: 78, ecosystem: 66, safety: 85, design: 76 }; return { slug: "deep-trekker-mine-rov", name: "Deep Trekker DTG3 Mine Sump", mfr: "deep-trekker", cat: "manufacturing", price: 18000, year: 2025, status: "active", desc: "Mine sump inspection ROV with reinforced tether and silt-agitation-resistant design for inspecting underground water sumps and flooded shafts.", specs: { depth: "200 m", camera: "4K low-light", tether: "reinforced Kevlar 200 m", thrusters: 4, battery: "7 hr", weight: "8 kg", silt_resistant: "protected intakes", lighting: "dual LED 2000 lumen" }, score: cs(b), breakdown: b }; })(),

  // Oil & gas inspection robots — 5
  (() => { const b = { performance: 83, reliability: 85, ease_of_use: 74, intelligence: 83, value: 62, ecosystem: 76, safety: 92, design: 80 }; return { slug: "anybotics-anymal-oil-gas", name: "ANYbotics ANYmal Oil & Gas", mfr: "anybotics", cat: "construction", price: 210000, year: 2024, status: "active", desc: "ATEX Zone 1 legged robot for offshore platform autonomous inspection with acoustic leak detection and thermal hotspot identification.", specs: { legs: 4, certification: "ATEX/IECEx Zone 1", acoustic: "ultrasonic leak detection", thermal: "hotspot identification", battery: "2 hr", speed: "1.0 m/s", weight: "62 kg", marine: "salt-spray resistant" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 81, reliability: 83, ease_of_use: 76, intelligence: 81, value: 66, ecosystem: 73, safety: 91, design: 78 }; return { slug: "clearpath-husky-oil-gas", name: "Clearpath Husky O&G", mfr: "clearpath-robotics", cat: "construction", price: 110000, year: 2025, status: "active", desc: "Explosion-proof UGV for pipeline right-of-way patrol with methane sniffer, thermal camera, and pipeline marker GPS logging.", specs: { payload: "60 kg", speed: "1.0 m/s", gas: "methane sniffer PPB", thermal: "radiometric IR", gps_logging: "pipeline marker", battery: "4 hr", explosion_proof: "Zone 2", weight: "58 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 84, reliability: 84, ease_of_use: 80, intelligence: 84, value: 68, ecosystem: 75, safety: 88, design: 79 }; return { slug: "skydio-x10-flare-stack", name: "Skydio X10 Flare Stack", mfr: "skydio", cat: "drone", price: 32000, year: 2025, status: "active", desc: "Flare stack inspection drone with heat-shielded payload bay and radiometric thermal camera for tip condition assessment during active flaring.", specs: { cameras: "6 nav + radiometric thermal", thermal_range: "-40°C to 2,000°C", heat_shield: "ceramic payload bay", flight_time: "28 min", wind: "50 km/h", standoff: "15 m minimum", weight: "2.1 kg" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 79, reliability: 81, ease_of_use: 82, intelligence: 78, value: 74, ecosystem: 71, safety: 87, design: 77 }; return { slug: "deep-trekker-revolution-subsea", name: "Deep Trekker Revolution Subsea Pipeline", mfr: "deep-trekker", cat: "manufacturing", price: 45000, year: 2025, status: "active", desc: "Subsea pipeline inspection ROV with CP measurement, cathodic anode tracking, and pipeline profile sonar for offshore oil & gas infrastructure.", specs: { depth: "305 m", cp_measurement: "integrated probes", sonar: "pipeline profile", camera: "4K + scaling laser", thrusters: 6, battery: "5 hr", tether: "305 m armored" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 82, ease_of_use: 79, intelligence: 80, value: 70, ecosystem: 72, safety: 90, design: 78 }; return { slug: "flyability-elios-3-refinery", name: "Flyability Elios 3 Refinery", mfr: "flyability", cat: "drone", price: 55000, year: 2025, status: "active", desc: "Refinery-configured Elios drone for column and vessel internal inspection with corrosion mapping and weld seam tracking in hydrocarbon environments.", specs: { cage: "collision-tolerant", camera: "4K + close-up macro", lidar: "3D corrosion mapping", flight_time: "11 min", lighting: "10,000 lumen", environment: "hydrocarbon tolerant", output: "corrosion map + measurements" }, score: cs(b), breakdown: b }; })(),

  // Forestry/environmental robots — 5
  (() => { const b = { performance: 77, reliability: 78, ease_of_use: 79, intelligence: 78, value: 74, ecosystem: 66, safety: 82, design: 77 }; return { slug: "clearpath-husky-forestry", name: "Clearpath Husky Forestry", mfr: "clearpath-robotics", cat: "agricultural", price: 90000, year: 2025, status: "active", desc: "Forestry research UGV with tree diameter measurement LiDAR and biomass estimation for automated forest inventory and carbon stock assessment.", specs: { payload: "60 kg", speed: "0.8 m/s", lidar: "360° tree measurement", biomass: "volume estimation", battery: "4 hr", terrain: "forest floor, trails", weight: "52 kg", ros: "ROS 2" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 80, reliability: 79, ease_of_use: 77, intelligence: 80, value: 70, ecosystem: 68, safety: 81, design: 78 }; return { slug: "dji-mavic-3e-forestry", name: "DJI Mavic 3E Forestry Kit", mfr: "dji", cat: "drone", price: 8500, year: 2024, status: "active", desc: "Enterprise drone with multispectral canopy analysis and tree-crown segmentation AI for wildfire risk mapping and pest infestation detection.", specs: { camera: "56 MP wide + thermal", multispectral: "NDVI canopy health", ai: "tree-crown segmentation", flight_time: "45 min", range: "15 km", output: "wildfire risk + pest maps", weight: "920 g" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 75, reliability: 77, ease_of_use: 81, intelligence: 76, value: 78, ecosystem: 64, safety: 80, design: 76 }; return { slug: "clearpath-jackal-wildlife", name: "Clearpath Jackal Wildlife", mfr: "clearpath-robotics", cat: "agricultural", price: 32000, year: 2025, status: "active", desc: "Whisper-quiet UGV for wildlife monitoring with camera traps, acoustic sensors, and scent-neutral materials to minimize animal disturbance.", specs: { payload: "15 kg", speed: "1.5 m/s", noise: "< 45 dB", sensors: "camera trap + acoustic", battery: "6 hr", weight: "18 kg", materials: "scent-neutral", connectivity: "LoRa + satellite" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 78, reliability: 80, ease_of_use: 76, intelligence: 79, value: 72, ecosystem: 67, safety: 83, design: 79 }; return { slug: "dji-flycart-30-reforest", name: "DJI FlyCart 30 Reforestation", mfr: "dji", cat: "drone", price: 19000, year: 2025, status: "active", desc: "Seed-dispersal drone dropping 30 kg of seed pods per flight across deforested hillsides, planting 40,000 trees per day at 10x the speed of manual planting.", specs: { payload: "30 kg seed pods", dispersal: "precision drop", coverage: "40,000 seeds/day", terrain: "steep hillsides", flight_time: "16 min loaded", speed: "12 m/s", range: "16 km" }, score: cs(b), breakdown: b }; })(),
  (() => { const b = { performance: 76, reliability: 78, ease_of_use: 80, intelligence: 77, value: 76, ecosystem: 65, safety: 81, design: 77 }; return { slug: "clearpath-husky-water", name: "Clearpath Husky Water Quality", mfr: "clearpath-robotics", cat: "agricultural", price: 75000, year: 2025, status: "active", desc: "Autonomous water sampling UGV that traverses riverbanks collecting and analyzing water samples for pH, turbidity, dissolved oxygen, and contaminants.", specs: { payload: "40 kg", speed: "0.8 m/s", sensors: "pH, DO, turbidity, conductivity, nitrates", samples: "24 auto-collection vials", battery: "5 hr", terrain: "riverbank, wetland", gps: "RTK centimeter", weight: "48 kg" }, score: cs(b), breakdown: b }; })(),
];

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 20 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 20 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
