/**
 * Robotomated — Wave 3 Robot Import: 190+ New Robots
 * Scale database from ~117 to 300+ robots.
 * Covers: exoskeletons, logistics/sortation, retail/hospitality,
 *   eldercare, underwater, mining, space, additional humanoids,
 *   more cobots, more drones, more warehouse, more construction.
 *
 * Run: npx tsx scripts/import-robots-wave3.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  // Exoskeletons
  { slug: "rewalk", name: "ReWalk Robotics", country: "IL", founded_year: 2001, website: "https://rewalk.com" },
  { slug: "ottobock", name: "Ottobock", country: "DE", founded_year: 1919, website: "https://ottobock.com" },
  { slug: "suitx", name: "SuitX (US Bionics)", country: "US", founded_year: 2012, website: "https://suitx.com" },
  // Retail/Hospitality
  { slug: "simbe", name: "Simbe Robotics", country: "US", founded_year: 2015, website: "https://simberobotics.com" },
  { slug: "badger-technologies", name: "Badger Technologies", country: "US", founded_year: 2017, website: "https://badger-technologies.com" },
  { slug: "softbank-robotics", name: "SoftBank Robotics", country: "JP", founded_year: 2012, website: "https://softbankrobotics.com" },
  { slug: "bear-robotics", name: "Bear Robotics", country: "US", founded_year: 2017, website: "https://bearrobotics.ai" },
  { slug: "keenon", name: "Keenon Robotics", country: "CN", founded_year: 2010, website: "https://keenon.com" },
  { slug: "lg-electronics", name: "LG Electronics", country: "KR", founded_year: 1958, website: "https://lg.com" },
  { slug: "samsung", name: "Samsung", country: "KR", founded_year: 1938, website: "https://samsung.com" },
  { slug: "pudu-robotics", name: "Pudu Robotics", country: "CN", founded_year: 2016, website: "https://pudutech.com" },
  { slug: "richtech", name: "Richtech Robotics", country: "US", founded_year: 2016, website: "https://richtechrobotics.com" },
  // Logistics/sortation
  { slug: "ocado", name: "Ocado Group", country: "GB", founded_year: 2000, website: "https://ocadogroup.com" },
  { slug: "dematic", name: "Dematic (KION)", country: "US", founded_year: 1819, website: "https://dematic.com" },
  { slug: "autostore", name: "AutoStore", country: "NO", founded_year: 1996, website: "https://autostoresystem.com" },
  { slug: "berkshire-grey", name: "Berkshire Grey", country: "US", founded_year: 2013, website: "https://berkshiregrey.com" },
  { slug: "righthand-robotics", name: "RightHand Robotics", country: "US", founded_year: 2014, website: "https://righthandrobotics.com" },
  { slug: "covariant", name: "Covariant", country: "US", founded_year: 2017, website: "https://covariant.ai" },
  { slug: "plus-one-robotics", name: "Plus One Robotics", country: "US", founded_year: 2016, website: "https://plusonerobotics.com" },
  { slug: "vecna-robotics", name: "Vecna Robotics", country: "US", founded_year: 2018, website: "https://vecnarobotics.com" },
  // Underwater/Marine
  { slug: "saab-seaeye", name: "Saab Seaeye", country: "SE", founded_year: 1986, website: "https://saabseaeye.com" },
  { slug: "ocean-infinity", name: "Ocean Infinity", country: "GB", founded_year: 2017, website: "https://oceaninfinity.com" },
  { slug: "blueye-robotics", name: "Blueye Robotics", country: "NO", founded_year: 2015, website: "https://blueyerobotics.com" },
  { slug: "boxfish-research", name: "Boxfish Research", country: "NZ", founded_year: 2016, website: "https://boxfish.nz" },
  // Space
  { slug: "astrobotic", name: "Astrobotic", country: "US", founded_year: 2007, website: "https://astrobotic.com" },
  { slug: "gitai", name: "GITAI", country: "JP", founded_year: 2016, website: "https://gitai.tech" },
  // Mining
  { slug: "epiroc", name: "Epiroc", country: "SE", founded_year: 2018, website: "https://epiroc.com" },
  { slug: "asi-robotics", name: "Autonomous Solutions Inc", country: "US", founded_year: 2000, website: "https://asirobots.com" },
  { slug: "caterpillar", name: "Caterpillar", country: "US", founded_year: 1925, website: "https://cat.com" },
  // Eldercare/Education
  { slug: "paro-intelligent", name: "PARO Intelligent System", country: "JP", founded_year: 2003, website: "https://parorobots.com" },
  { slug: "embodied", name: "Embodied Inc.", country: "US", founded_year: 2016, website: "https://embodied.com" },
  // Additional cobots/industrial
  { slug: "yaskawa", name: "Yaskawa", country: "JP", founded_year: 1915, website: "https://yaskawa.com" },
  { slug: "omron-robotics", name: "Omron Robotics", country: "JP", founded_year: 1933, website: "https://industrial.omron.com" },
  { slug: "denso-robotics", name: "Denso Robotics", country: "JP", founded_year: 1949, website: "https://densorobotics-europe.com" },
  { slug: "staubli", name: "Stäubli", country: "CH", founded_year: 1892, website: "https://staubli.com" },
  { slug: "kawasaki-robotics", name: "Kawasaki Robotics", country: "JP", founded_year: 1969, website: "https://kawasakirobotics.com" },
  // More drones
  { slug: "parrot", name: "Parrot", country: "FR", founded_year: 1994, website: "https://parrot.com" },
  { slug: "flyability", name: "Flyability", country: "CH", founded_year: 2014, website: "https://flyability.com" },
  // More construction
  { slug: "rugged-robotics", name: "Rugged Robotics", country: "US", founded_year: 2018, website: "https://ruggedrobotics.com" },
  { slug: "trimble", name: "Trimble", country: "US", founded_year: 1978, website: "https://trimble.com" },
  { slug: "canvas-construction", name: "Canvas (Drywall)", country: "US", founded_year: 2017, website: "https://canvas.build" },
  // Cleaning
  { slug: "avidbots", name: "Avidbots", country: "CA", founded_year: 2014, website: "https://avidbots.com" },
  { slug: "brain-corp", name: "Brain Corp", country: "US", founded_year: 2009, website: "https://braincorp.com" },
  { slug: "gaussian-robotics", name: "Gaussian Robotics", country: "CN", founded_year: 2013, website: "https://gaussianrobotics.com" },
];

// ═══════════════════════════════════════════════════════════════
// ALL ROBOTS — 190 new entries
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

  // ═══ EXOSKELETONS (10) — mapped to "medical" ═══
  {slug:"rewalk-personal-6",name:"ReWalk Personal 6.0",mfr:"rewalk",cat:"medical",price:85000,year:2023,status:"active",desc:"FDA-cleared personal exoskeleton for paraplegic users. Enables standing, walking, and stair climbing. Battery: 3-4 hours continuous walking.",specs:{weight_kg:23,battery_hrs:4,max_speed_kmh:2.6,joints:"Hip, knee bilateral",fda_cleared:true},score:cs({performance:72,reliability:80,ease_of_use:68,intelligence:65,value:60,ecosystem:58,safety:88,design:72}),breakdown:{performance:72,reliability:80,ease_of_use:68,intelligence:65,value:60,ecosystem:58,safety:88,design:72}},
  {slug:"rewalk-reStore",name:"ReWalk ReStore",mfr:"rewalk",cat:"medical",price:null,year:2022,status:"active",desc:"Soft exo-suit for stroke rehabilitation. Lightweight fabric-based design assists ankle dorsiflexion during gait training. FDA 510(k) cleared.",specs:{weight_kg:5,type:"Soft exo-suit",target:"Ankle dorsiflexion",fda_cleared:true},score:cs({performance:70,reliability:78,ease_of_use:75,intelligence:62,value:65,ecosystem:55,safety:85,design:78}),breakdown:{performance:70,reliability:78,ease_of_use:75,intelligence:62,value:65,ecosystem:55,safety:85,design:78}},
  {slug:"ottobock-paexo",name:"Ottobock Paexo Back",mfr:"ottobock",cat:"medical",price:5500,year:2022,status:"active",desc:"Passive exoskeleton for lower back support during lifting. No batteries — uses mechanical springs. 3 kg total weight. Used in BMW, VW factories.",specs:{weight_kg:3,type:"Passive mechanical",support_kg:25,battery:"None (passive)"},score:cs({performance:68,reliability:85,ease_of_use:88,intelligence:40,value:85,ecosystem:65,safety:82,design:80}),breakdown:{performance:68,reliability:85,ease_of_use:88,intelligence:40,value:85,ecosystem:65,safety:82,design:80}},
  {slug:"ottobock-paexo-shoulder",name:"Ottobock Paexo Shoulder",mfr:"ottobock",cat:"medical",price:5900,year:2022,status:"active",desc:"Passive shoulder exoskeleton for overhead work. Supports 2-7 kg per arm. No power needed. Used in automotive assembly, aircraft maintenance.",specs:{weight_kg:1.9,type:"Passive mechanical",support_per_arm_kg:7,battery:"None (passive)"},score:cs({performance:66,reliability:85,ease_of_use:90,intelligence:38,value:88,ecosystem:62,safety:82,design:82}),breakdown:{performance:66,reliability:85,ease_of_use:90,intelligence:38,value:88,ecosystem:62,safety:82,design:82}},
  {slug:"sarcos-guardian-xo-2",name:"Sarcos Guardian XO 2",mfr:"sarcos",cat:"medical",price:null,year:2024,status:"active",desc:"Full-body powered exoskeleton for industrial use. Enables users to lift 200 lbs repeatedly without strain. 8-hour battery. Military and industrial applications.",specs:{weight_kg:68,payload_kg:90,battery_hrs:8,dof:24,compute:"Custom"},score:cs({performance:82,reliability:72,ease_of_use:65,intelligence:70,value:55,ecosystem:48,safety:80,design:78}),breakdown:{performance:82,reliability:72,ease_of_use:65,intelligence:70,value:55,ecosystem:48,safety:80,design:78}},
  {slug:"suitx-maxv2",name:"SuitX MAX V2",mfr:"suitx",cat:"medical",price:null,year:2023,status:"active",desc:"Modular powered exoskeleton. Individual back, shoulder, and leg modules can be used separately or combined. Industrial and medical applications.",specs:{weight_kg:15,type:"Modular powered",modules:"Back, Shoulder, Leg",battery_hrs:6},score:cs({performance:72,reliability:74,ease_of_use:72,intelligence:60,value:65,ecosystem:52,safety:78,design:72}),breakdown:{performance:72,reliability:74,ease_of_use:72,intelligence:60,value:65,ecosystem:52,safety:78,design:72}},
  {slug:"ekso-exonr-2",name:"Ekso EksoNR 2.0",mfr:"ekso-bionics",cat:"medical",price:150000,year:2024,status:"active",desc:"Robotic exoskeleton for neurorehabilitation. Variable Assist software adapts support in real-time. Used in 350+ rehab centers worldwide.",specs:{weight_kg:22,battery_hrs:4,variable_assist:true,gait_modes:5,centers_deployed:350},score:cs({performance:78,reliability:82,ease_of_use:75,intelligence:76,value:58,ecosystem:72,safety:88,design:75}),breakdown:{performance:78,reliability:82,ease_of_use:75,intelligence:76,value:58,ecosystem:72,safety:88,design:75}},
  {slug:"ekso-evo",name:"Ekso EVO",mfr:"ekso-bionics",cat:"construction",price:null,year:2023,status:"active",desc:"Construction exoskeleton for overhead work. Supports up to 7 kg per arm. No batteries required. Reduces shoulder fatigue by 80%.",specs:{weight_kg:4.3,type:"Passive mechanical",support_per_arm_kg:7,fatigue_reduction:"80%"},score:cs({performance:65,reliability:85,ease_of_use:88,intelligence:35,value:82,ecosystem:55,safety:85,design:78}),breakdown:{performance:65,reliability:85,ease_of_use:88,intelligence:35,value:82,ecosystem:55,safety:85,design:78}},
  {slug:"fourier-exomotion",name:"Fourier ExoMotion",mfr:"fourier-intelligence",cat:"medical",price:65000,year:2024,status:"active",desc:"Lower-limb rehabilitation exoskeleton with AI-adaptive gait training. Cloud-connected for remote therapy monitoring. Available in 40+ countries.",specs:{weight_kg:18,battery_hrs:5,dof:12,ai_adaptive:true,countries:40},score:cs({performance:76,reliability:78,ease_of_use:78,intelligence:80,value:68,ecosystem:65,safety:85,design:78}),breakdown:{performance:76,reliability:78,ease_of_use:78,intelligence:80,value:68,ecosystem:65,safety:85,design:78}},
  {slug:"wandercraft-atalante",name:"Wandercraft Atalante X",mfr:"fourier-intelligence",cat:"medical",price:null,year:2024,status:"active",desc:"Self-balancing medical exoskeleton. Only exoskeleton that walks without crutches. 12 DOF. Used in 50+ hospitals in Europe and US.",specs:{weight_kg:35,dof:12,self_balancing:true,crutch_free:true},score:cs({performance:80,reliability:76,ease_of_use:72,intelligence:82,value:55,ecosystem:58,safety:82,design:82}),breakdown:{performance:80,reliability:76,ease_of_use:72,intelligence:82,value:55,ecosystem:58,safety:82,design:82}},

  // ═══ RETAIL & HOSPITALITY (15) — "consumer" category ═══
  {slug:"simbe-tally-3",name:"Simbe Tally 3.0",mfr:"simbe",cat:"warehouse",price:null,year:2024,status:"active",desc:"Autonomous retail shelf-scanning robot. Captures shelf inventory data 3x daily. Computer vision identifies out-of-stocks, price mismatches, and planogram compliance. Deployed at Schnucks, Wakefern.",specs:{height_cm:100,weight_kg:16,battery_hrs:10,scan_speed:"Autonomous full-store",frequency:"3x daily"},score:cs({performance:78,reliability:80,ease_of_use:82,intelligence:85,value:72,ecosystem:70,safety:82,design:72}),breakdown:{performance:78,reliability:80,ease_of_use:82,intelligence:85,value:72,ecosystem:70,safety:82,design:72}},
  {slug:"badger-sentinel",name:"Badger Sentinel",mfr:"badger-technologies",cat:"warehouse",price:null,year:2023,status:"active",desc:"Retail floor-scanning robot for spill detection, hazard identification, and inventory monitoring. Navigates store aisles autonomously.",specs:{sensors:"3D LiDAR, cameras",battery_hrs:12,alerts:"Spill, hazard, out-of-stock"},score:cs({performance:72,reliability:78,ease_of_use:80,intelligence:76,value:70,ecosystem:62,safety:82,design:70}),breakdown:{performance:72,reliability:78,ease_of_use:80,intelligence:76,value:70,ecosystem:62,safety:82,design:70}},
  {slug:"softbank-pepper",name:"SoftBank Pepper",mfr:"softbank-robotics",cat:"consumer",price:25000,year:2015,status:"active",desc:"Humanoid social robot for retail, hospitality, and education. 120 cm tall, emotion recognition, multi-language. 25,000+ units deployed globally.",specs:{height_cm:120,weight_kg:28,battery_hrs:12,languages:20,dof:20,sensors:"Cameras, microphones, sonar, laser, IMU"},score:cs({performance:62,reliability:70,ease_of_use:78,intelligence:72,value:65,ecosystem:75,safety:78,design:85}),breakdown:{performance:62,reliability:70,ease_of_use:78,intelligence:72,value:65,ecosystem:75,safety:78,design:85}},
  {slug:"softbank-whiz",name:"SoftBank Whiz",mfr:"softbank-robotics",cat:"consumer",price:null,year:2020,status:"active",desc:"Autonomous commercial vacuum robot. Route teaching via manual push, then autonomous operation. Deployed in offices, hotels, airports worldwide.",specs:{cleaning_width_cm:66,battery_hrs:3,capacity_sqm:1500,nav:"SLAM + taught routes"},score:cs({performance:72,reliability:78,ease_of_use:85,intelligence:68,value:70,ecosystem:68,safety:80,design:72}),breakdown:{performance:72,reliability:78,ease_of_use:85,intelligence:68,value:70,ecosystem:68,safety:80,design:72}},
  {slug:"bear-servi-plus",name:"Bear Robotics Servi Plus",mfr:"bear-robotics",cat:"consumer",price:null,year:2024,status:"active",desc:"Restaurant delivery robot. Multi-tray design carries food from kitchen to tables. LiDAR navigation. Deployed at Denny's, Chili's, and hundreds of Asian restaurants.",specs:{payload_kg:40,trays:4,battery_hrs:12,nav:"LiDAR SLAM",speed_ms:1.2},score:cs({performance:74,reliability:78,ease_of_use:85,intelligence:72,value:78,ecosystem:72,safety:80,design:78}),breakdown:{performance:74,reliability:78,ease_of_use:85,intelligence:72,value:78,ecosystem:72,safety:80,design:78}},
  {slug:"keenon-dinerbot-t10",name:"Keenon Dinerbot T10",mfr:"keenon",cat:"consumer",price:15000,year:2024,status:"active",desc:"Restaurant service robot with AI voice interaction. 4-tier tray design, 40kg payload. Auto elevator integration. 80,000+ units deployed in 60+ countries.",specs:{payload_kg:40,trays:4,battery_hrs:10,voice_ai:true,units_deployed:80000},score:cs({performance:76,reliability:80,ease_of_use:82,intelligence:74,value:85,ecosystem:78,safety:80,design:80}),breakdown:{performance:76,reliability:80,ease_of_use:82,intelligence:74,value:85,ecosystem:78,safety:80,design:80}},
  {slug:"keenon-w3",name:"Keenon W3",mfr:"keenon",cat:"consumer",price:12000,year:2023,status:"active",desc:"Hotel delivery robot with cabin. Delivers room service, amenities, and laundry autonomously. Elevator integration. Used by Hilton, Marriott.",specs:{cabin_volume_l:30,payload_kg:10,battery_hrs:12,elevator:true,hotels:"Hilton, Marriott, Aloft"},score:cs({performance:72,reliability:78,ease_of_use:84,intelligence:72,value:82,ecosystem:74,safety:80,design:78}),breakdown:{performance:72,reliability:78,ease_of_use:84,intelligence:72,value:82,ecosystem:74,safety:80,design:78}},
  {slug:"lg-cloi-servebot",name:"LG CLOi ServeBot",mfr:"lg-electronics",cat:"consumer",price:null,year:2023,status:"active",desc:"LG's commercial service robot for restaurants and hotels. 3-tier tray, LiDAR nav, AI face recognition. Part of LG's CLOi robot family.",specs:{payload_kg:30,trays:3,battery_hrs:11,nav:"LiDAR + camera",face_recognition:true},score:cs({performance:72,reliability:80,ease_of_use:80,intelligence:74,value:70,ecosystem:72,safety:80,design:82}),breakdown:{performance:72,reliability:80,ease_of_use:80,intelligence:74,value:70,ecosystem:72,safety:80,design:82}},
  {slug:"lg-cloi-guidebot",name:"LG CLOi GuideBot",mfr:"lg-electronics",cat:"consumer",price:null,year:2023,status:"active",desc:"Information and guidance robot for airports, hotels, and retail. 10.1-inch display, multi-language, autonomous navigation.",specs:{display_in:10.1,battery_hrs:8,languages:10,nav:"LiDAR SLAM"},score:cs({performance:68,reliability:78,ease_of_use:82,intelligence:72,value:65,ecosystem:68,safety:80,design:82}),breakdown:{performance:68,reliability:78,ease_of_use:82,intelligence:72,value:65,ecosystem:68,safety:80,design:82}},
  {slug:"samsung-bot-handy",name:"Samsung Bot Handy",mfr:"samsung",cat:"consumer",price:null,year:2024,status:"coming_soon",desc:"Samsung's home assistant robot with single-arm manipulation. Can set the table, load dishwasher, pour drinks. AI-powered object recognition.",specs:{arm_dof:6,payload_kg:1.5,compute:"Custom AI",vision:"Multi-camera depth"},score:cs({performance:65,reliability:62,ease_of_use:72,intelligence:78,value:60,ecosystem:55,safety:72,design:85}),breakdown:{performance:65,reliability:62,ease_of_use:72,intelligence:78,value:60,ecosystem:55,safety:72,design:85}},
  {slug:"pudu-bellabot",name:"Pudu BellaBot",mfr:"pudu-robotics",cat:"consumer",price:16000,year:2022,status:"active",desc:"Cat-themed restaurant delivery robot. Touch-sensitive ears, multi-tray, SLAM navigation. 56,000+ units deployed in 60+ countries. Integrates with POS systems.",specs:{payload_kg:40,trays:4,battery_hrs:10,units_deployed:56000,nav:"Visual SLAM + LiDAR"},score:cs({performance:74,reliability:78,ease_of_use:86,intelligence:72,value:82,ecosystem:78,safety:80,design:88}),breakdown:{performance:74,reliability:78,ease_of_use:86,intelligence:72,value:82,ecosystem:78,safety:80,design:88}},
  {slug:"pudu-kettybot-2",name:"Pudu KettyBot 2",mfr:"pudu-robotics",cat:"consumer",price:13000,year:2024,status:"active",desc:"Multi-function service robot: delivery, advertising, cruise reception. 18.5-inch display. Photo-taking feature. Used in restaurants, malls, events.",specs:{display_in:18.5,payload_kg:30,battery_hrs:12,functions:"Delivery, advertising, reception"},score:cs({performance:72,reliability:76,ease_of_use:84,intelligence:70,value:80,ecosystem:74,safety:78,design:82}),breakdown:{performance:72,reliability:76,ease_of_use:84,intelligence:70,value:80,ecosystem:74,safety:78,design:82}},
  {slug:"richtech-adam",name:"Richtech ADAM",mfr:"richtech",cat:"consumer",price:null,year:2024,status:"active",desc:"Dual-arm barista robot. Makes lattes, pour-over coffee, boba tea. Serves 200+ drinks/day. Deployed in Las Vegas hotels and airports.",specs:{arms:2,drinks_per_day:200,types:"Coffee, tea, boba, cocktails",ai:"Visual recognition"},score:cs({performance:72,reliability:74,ease_of_use:78,intelligence:70,value:68,ecosystem:55,safety:75,design:85}),breakdown:{performance:72,reliability:74,ease_of_use:78,intelligence:70,value:68,ecosystem:55,safety:75,design:85}},
  {slug:"avidbots-neo-2",name:"Avidbots Neo 2",mfr:"avidbots",cat:"consumer",price:null,year:2024,status:"active",desc:"Autonomous commercial floor scrubber. AI-driven cleaning path optimization. 26-inch cleaning path. Used in airports, malls, hospitals worldwide.",specs:{cleaning_width_cm:66,battery_hrs:6,capacity_sqm:5000,ai_path_optimization:true},score:cs({performance:78,reliability:82,ease_of_use:82,intelligence:78,value:72,ecosystem:72,safety:82,design:75}),breakdown:{performance:78,reliability:82,ease_of_use:82,intelligence:78,value:72,ecosystem:72,safety:82,design:75}},
  {slug:"gaussian-phantas",name:"Gaussian Phantas",mfr:"gaussian-robotics",cat:"consumer",price:null,year:2024,status:"active",desc:"Industrial-grade autonomous cleaning robot. Cleans 6,000+ sqm/hr. Multi-sensor navigation. Used in warehouses, factories, airports.",specs:{cleaning_sqm_hr:6000,battery_hrs:5,nav:"LiDAR + ultrasonic + camera"},score:cs({performance:76,reliability:78,ease_of_use:80,intelligence:74,value:74,ecosystem:65,safety:80,design:72}),breakdown:{performance:76,reliability:78,ease_of_use:80,intelligence:74,value:74,ecosystem:65,safety:80,design:72}},

  // ═══ LOGISTICS & SORTATION (15) — "warehouse" category ═══
  {slug:"autostore-r5-pro",name:"AutoStore R5 Pro",mfr:"autostore",cat:"warehouse",price:null,year:2023,status:"active",desc:"Cube-storage goods-to-person robot. Operates on grid above stacked bins. 1,200+ installations worldwide. 4x storage density vs. traditional shelving.",specs:{payload_kg:30,speed_ms:3.1,battery_hrs:20,storage_density:"4x traditional",installations:1200},score:cs({performance:88,reliability:90,ease_of_use:80,intelligence:82,value:72,ecosystem:85,safety:85,design:78}),breakdown:{performance:88,reliability:90,ease_of_use:80,intelligence:82,value:72,ecosystem:85,safety:85,design:78}},
  {slug:"autostore-b1",name:"AutoStore B1",mfr:"autostore",cat:"warehouse",price:null,year:2024,status:"active",desc:"Next-gen AutoStore robot. 25% faster than R5. Handles 650mm tall bins. Built-in camera for real-time bin inspection.",specs:{speed_ms:4,payload_kg:35,battery_hrs:24,bin_height_mm:650,vision:"Built-in camera"},score:cs({performance:90,reliability:88,ease_of_use:80,intelligence:84,value:70,ecosystem:85,safety:85,design:80}),breakdown:{performance:90,reliability:88,ease_of_use:80,intelligence:84,value:70,ecosystem:85,safety:85,design:80}},
  {slug:"ocado-600-series",name:"Ocado 600 Series Bot",mfr:"ocado",cat:"warehouse",price:null,year:2023,status:"active",desc:"High-speed grocery fulfillment robot. Operates on Ocado Smart Platform grid. Picks and delivers grocery totes in 50-customer-per-hour facilities. Used by Kroger.",specs:{speed_ms:4,payload_kg:30,battery_hrs:2,swappable_battery:true,partners:"Kroger, Sobeys, AEON"},score:cs({performance:88,reliability:85,ease_of_use:75,intelligence:82,value:68,ecosystem:78,safety:82,design:75}),breakdown:{performance:88,reliability:85,ease_of_use:75,intelligence:82,value:68,ecosystem:78,safety:82,design:75}},
  {slug:"dematic-multishuttle",name:"Dematic Multishuttle",mfr:"dematic",cat:"warehouse",price:null,year:2022,status:"active",desc:"High-density storage and retrieval shuttle system. Each shuttle handles one level, moving totes horizontally at up to 4 m/s. Scales to millions of SKUs.",specs:{speed_ms:4,payload_kg:50,tote_sizes:"Multiple",scalability:"Millions of SKUs"},score:cs({performance:85,reliability:88,ease_of_use:70,intelligence:78,value:68,ecosystem:82,safety:85,design:70}),breakdown:{performance:85,reliability:88,ease_of_use:70,intelligence:78,value:68,ecosystem:82,safety:85,design:70}},
  {slug:"berkshire-grey-rps",name:"Berkshire Grey Robotic Pick Station",mfr:"berkshire-grey",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered robotic picking system for e-commerce fulfillment. Picks individual items from totes. 99.5% accuracy. 450+ picks per hour per station.",specs:{picks_per_hour:450,accuracy:"99.5%",ai:"Computer vision + deep learning",items:"Variable geometry"},score:cs({performance:85,reliability:82,ease_of_use:78,intelligence:90,value:72,ecosystem:72,safety:82,design:75}),breakdown:{performance:85,reliability:82,ease_of_use:78,intelligence:90,value:72,ecosystem:72,safety:82,design:75}},
  {slug:"righthand-rp1",name:"RightHand RightPick 3",mfr:"righthand-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"AI-powered piece-picking robot for e-commerce. Handles 20,000+ unique SKUs. Vision-guided suction and finger gripper. 600+ picks/hour.",specs:{picks_per_hour:600,sku_range:"20,000+",gripper:"Suction + finger hybrid",ai:"RightPick AI"},score:cs({performance:84,reliability:80,ease_of_use:76,intelligence:88,value:72,ecosystem:70,safety:80,design:72}),breakdown:{performance:84,reliability:80,ease_of_use:76,intelligence:88,value:72,ecosystem:70,safety:80,design:72}},
  {slug:"covariant-pick",name:"Covariant Robotic Pick",mfr:"covariant",cat:"warehouse",price:null,year:2024,status:"active",desc:"Foundation-model powered robotic picking. Covariant Brain processes vision and language for zero-shot pick planning. Handles novel items without retraining.",specs:{ai:"Covariant Brain (foundation model)",picks_per_hour:500,novel_items:"Zero-shot capable"},score:cs({performance:82,reliability:78,ease_of_use:80,intelligence:92,value:70,ecosystem:68,safety:78,design:75}),breakdown:{performance:82,reliability:78,ease_of_use:80,intelligence:92,value:70,ecosystem:68,safety:78,design:75}},
  {slug:"plus-one-induct",name:"Plus One Robotics InductOne",mfr:"plus-one-robotics",cat:"warehouse",price:null,year:2023,status:"active",desc:"AI + human-in-the-loop parcel induction system. Robots singulate and induct parcels onto sorters. Remote crew operators intervene for edge cases.",specs:{parcels_per_hour:1800,human_in_loop:true,ai:"Computer vision"},score:cs({performance:80,reliability:82,ease_of_use:78,intelligence:82,value:75,ecosystem:68,safety:80,design:70}),breakdown:{performance:80,reliability:82,ease_of_use:78,intelligence:82,value:75,ecosystem:68,safety:80,design:70}},
  {slug:"vecna-pallet-jack",name:"Vecna Robotics Autonomous Pallet Jack",mfr:"vecna-robotics",cat:"warehouse",price:null,year:2023,status:"active",desc:"Autonomous pallet jack for warehouse floor transport. Self-driving pallet movement between dock doors, staging, and storage. Fleet orchestration included.",specs:{payload_kg:2000,speed_ms:2,battery_hrs:8,nav:"LiDAR + natural feature"},score:cs({performance:80,reliability:82,ease_of_use:78,intelligence:76,value:75,ecosystem:72,safety:82,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:78,intelligence:76,value:75,ecosystem:72,safety:82,design:72}},
  {slug:"vecna-counterbalance",name:"Vecna Robotics Autonomous Counterbalance",mfr:"vecna-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Self-driving counterbalance forklift. Lifts pallets to 30 ft. Mixed human/robot fleet management via Pivotal orchestration platform.",specs:{payload_kg:1500,lift_height_m:9,speed_ms:2.5,orchestration:"Pivotal platform"},score:cs({performance:82,reliability:80,ease_of_use:75,intelligence:78,value:72,ecosystem:74,safety:82,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:75,intelligence:78,value:72,ecosystem:74,safety:82,design:72}},
  {slug:"mir-600",name:"MiR600",mfr:"mir",cat:"warehouse",price:null,year:2023,status:"active",desc:"Heavy-payload AMR for pallet transport. 600 kg capacity. IP52. Designed for demanding environments like automotive and heavy manufacturing.",specs:{payload_kg:600,speed_ms:2,battery_hrs:8,ip_rating:"IP52"},score:cs({performance:82,reliability:85,ease_of_use:80,intelligence:78,value:72,ecosystem:82,safety:85,design:75}),breakdown:{performance:82,reliability:85,ease_of_use:80,intelligence:78,value:72,ecosystem:82,safety:85,design:75}},
  {slug:"mir-1350",name:"MiR1350",mfr:"mir",cat:"warehouse",price:null,year:2023,status:"active",desc:"Ultra-heavy AMR for full pallet transport. 1,350 kg payload. Operates in mixed traffic with humans and forklifts. EN 1525 safety certified.",specs:{payload_kg:1350,speed_ms:1.5,battery_hrs:6,safety_cert:"EN 1525"},score:cs({performance:84,reliability:85,ease_of_use:78,intelligence:78,value:70,ecosystem:82,safety:88,design:72}),breakdown:{performance:84,reliability:85,ease_of_use:78,intelligence:78,value:70,ecosystem:82,safety:88,design:72}},
  {slug:"geek-plus-picking",name:"Geek+ PopPick",mfr:"geek-plus",cat:"warehouse",price:null,year:2024,status:"active",desc:"Goods-to-person picking workstation with tote-carrying robots. Multi-level bin presentation. 300+ picks/hour per station. 20,000+ robots deployed globally.",specs:{picks_per_station_hr:300,robots_deployed:20000,bin_levels:4},score:cs({performance:82,reliability:82,ease_of_use:78,intelligence:80,value:78,ecosystem:80,safety:82,design:75}),breakdown:{performance:82,reliability:82,ease_of_use:78,intelligence:80,value:78,ecosystem:80,safety:82,design:75}},
  {slug:"amazon-proteus",name:"Amazon Proteus",mfr:"amazon",cat:"warehouse",price:null,year:2022,status:"active",desc:"Amazon's first fully autonomous warehouse robot. Navigates without cages using advanced perception. Moves GoCarts through fulfillment centers. Not for sale externally.",specs:{payload_kg:360,nav:"Advanced perception",autonomous:true},score:cs({performance:82,reliability:80,ease_of_use:70,intelligence:85,value:60,ecosystem:65,safety:82,design:78}),breakdown:{performance:82,reliability:80,ease_of_use:70,intelligence:85,value:60,ecosystem:65,safety:82,design:78}},
  {slug:"amazon-sparrow",name:"Amazon Sparrow",mfr:"amazon",cat:"warehouse",price:null,year:2023,status:"active",desc:"AI-powered robotic arm for individual item picking. Computer vision identifies and picks millions of different products. Deployed in Amazon fulfillment centers.",specs:{picks_per_hour:1000,items_recognized:"Millions",ai:"Custom vision AI"},score:cs({performance:85,reliability:78,ease_of_use:72,intelligence:90,value:65,ecosystem:62,safety:80,design:72}),breakdown:{performance:85,reliability:78,ease_of_use:72,intelligence:90,value:65,ecosystem:62,safety:80,design:72}},

  // ═══ UNDERWATER / MARINE (6) — "construction" category ═══
  {slug:"saab-sabertooth",name:"Saab Sabertooth",mfr:"saab-seaeye",cat:"construction",price:null,year:2022,status:"active",desc:"Hybrid AUV/ROV for deepwater operations. Operates to 3,000m depth. Autonomous survey and remotely operated intervention in one vehicle.",specs:{depth_m:3000,weight_kg:3400,speed_knots:6,battery_hrs:20,mode:"Hybrid AUV/ROV"},score:cs({performance:88,reliability:85,ease_of_use:62,intelligence:82,value:55,ecosystem:60,safety:85,design:78}),breakdown:{performance:88,reliability:85,ease_of_use:62,intelligence:82,value:55,ecosystem:60,safety:85,design:78}},
  {slug:"saab-leopard",name:"Saab Leopard",mfr:"saab-seaeye",cat:"construction",price:null,year:2023,status:"active",desc:"Electric work-class ROV. 300 HP. 3,000m depth. Used for subsea construction, pipeline inspection, and offshore energy installation.",specs:{depth_m:3000,hp:300,thrusters:8,manipulators:2},score:cs({performance:85,reliability:85,ease_of_use:60,intelligence:72,value:55,ecosystem:62,safety:82,design:72}),breakdown:{performance:85,reliability:85,ease_of_use:60,intelligence:72,value:55,ecosystem:62,safety:82,design:72}},
  {slug:"blueye-x3",name:"Blueye X3",mfr:"blueye-robotics",cat:"construction",price:30000,year:2023,status:"active",desc:"Compact underwater inspection drone. 300m depth. Modular payload system. Easy to deploy from small boats or docks. 4K camera.",specs:{depth_m:300,weight_kg:9.5,battery_hrs:2,camera:"4K 30fps",payload:"Modular"},score:cs({performance:74,reliability:78,ease_of_use:85,intelligence:70,value:78,ecosystem:65,safety:80,design:82}),breakdown:{performance:74,reliability:78,ease_of_use:85,intelligence:70,value:78,ecosystem:65,safety:80,design:82}},
  {slug:"boxfish-luna",name:"Boxfish Luna",mfr:"boxfish-research",cat:"construction",price:60000,year:2023,status:"active",desc:"Professional underwater ROV with 8K camera. 1,000m depth. Real-time 4K streaming. Used for marine research, infrastructure inspection, film production.",specs:{depth_m:1000,camera:"8K",weight_kg:25,battery_hrs:4,streaming:"4K real-time"},score:cs({performance:82,reliability:78,ease_of_use:75,intelligence:72,value:68,ecosystem:55,safety:78,design:85}),breakdown:{performance:82,reliability:78,ease_of_use:75,intelligence:72,value:68,ecosystem:55,safety:78,design:85}},
  {slug:"ocean-infinity-armada",name:"Ocean Infinity Armada",mfr:"ocean-infinity",cat:"construction",price:null,year:2024,status:"active",desc:"Fleet of uncrewed surface vessels (USVs) for ocean mapping, pipeline inspection, and environmental survey. Each 21-36m, fully autonomous.",specs:{vessel_length_m:"21-36",fleet_size:17,autonomous:true,operations:"Mapping, inspection, survey"},score:cs({performance:88,reliability:82,ease_of_use:65,intelligence:85,value:62,ecosystem:58,safety:80,design:78}),breakdown:{performance:88,reliability:82,ease_of_use:65,intelligence:85,value:62,ecosystem:58,safety:80,design:78}},
  {slug:"ocean-infinity-surveyor",name:"Ocean Infinity Surveyor AUV",mfr:"ocean-infinity",cat:"construction",price:null,year:2024,status:"active",desc:"Deep-sea autonomous underwater vehicle for seabed mapping. Launched from Armada USVs. Multi-sensor: sonar, camera, environmental.",specs:{depth_m:6000,sensors:"Multi-beam sonar, camera, CTD",deployment:"USV-launched"},score:cs({performance:86,reliability:80,ease_of_use:60,intelligence:82,value:58,ecosystem:55,safety:78,design:75}),breakdown:{performance:86,reliability:80,ease_of_use:60,intelligence:82,value:58,ecosystem:55,safety:78,design:75}},

  // ═══ SPACE ROBOTS (4) — "construction" category ═══
  {slug:"astrobotic-cuberover",name:"Astrobotic CubeRover",mfr:"astrobotic",cat:"construction",price:null,year:2024,status:"active",desc:"Ultra-compact lunar rover. 2 kg class. Designed for NASA's Commercial Lunar Payload Services program. Solar-powered exploration on the Moon.",specs:{weight_kg:2,power:"Solar",compute:"Custom radiation-hardened",wheels:4,program:"NASA CLPS"},score:cs({performance:65,reliability:68,ease_of_use:45,intelligence:72,value:50,ecosystem:45,safety:70,design:75}),breakdown:{performance:65,reliability:68,ease_of_use:45,intelligence:72,value:50,ecosystem:45,safety:70,design:75}},
  {slug:"gitai-s2",name:"GITAI S2",mfr:"gitai",cat:"construction",price:null,year:2024,status:"active",desc:"Space robot arm for ISS and commercial stations. Demonstrated autonomous solar panel assembly. Dual-arm dexterous manipulation.",specs:{arms:2,reach_m:1.5,payload_kg:10,environment:"Space (ISS)",demonstrated:"Solar panel assembly"},score:cs({performance:78,reliability:72,ease_of_use:55,intelligence:80,value:50,ecosystem:45,safety:75,design:80}),breakdown:{performance:78,reliability:72,ease_of_use:55,intelligence:80,value:50,ecosystem:45,safety:75,design:80}},
  {slug:"gitai-inchworm",name:"GITAI Inchworm",mfr:"gitai",cat:"construction",price:null,year:2025,status:"coming_soon",desc:"Crawling robot for spacecraft exterior inspection and maintenance. Moves like an inchworm along rails. Designed for commercial space stations.",specs:{locomotion:"Inchworm crawling",environment:"Space exterior",compute:"Custom"},score:0,breakdown:{performance:0,reliability:0,ease_of_use:0,intelligence:0,value:0,ecosystem:0,safety:0,design:0}},
  {slug:"astrobotic-peregrine",name:"Astrobotic Peregrine",mfr:"astrobotic",cat:"construction",price:null,year:2024,status:"active",desc:"Lunar lander carrying multiple payloads to the Moon's surface. First commercial US lunar lander under NASA CLPS program. 90 kg payload capacity.",specs:{payload_kg:90,destination:"Lunar surface",program:"NASA CLPS",propulsion:"Hypergolic"},score:cs({performance:72,reliability:65,ease_of_use:40,intelligence:68,value:48,ecosystem:45,safety:70,design:72}),breakdown:{performance:72,reliability:65,ease_of_use:40,intelligence:68,value:48,ecosystem:45,safety:70,design:72}},

  // ═══ MINING (5) — "construction" category ═══
  {slug:"epiroc-st18",name:"Epiroc Scooptram ST18 AutoMine",mfr:"epiroc",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous underground mining loader. 18 tonne capacity. AutoMine system enables fully autonomous tramming and loading. Zero-emission option available.",specs:{payload_tonnes:18,autonomous:true,system:"AutoMine",emission:"Zero-emission option"},score:cs({performance:85,reliability:85,ease_of_use:68,intelligence:80,value:65,ecosystem:72,safety:85,design:68}),breakdown:{performance:85,reliability:85,ease_of_use:68,intelligence:80,value:65,ecosystem:72,safety:85,design:68}},
  {slug:"epiroc-mt65",name:"Epiroc Minetruck MT65 AutoMine",mfr:"epiroc",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous underground mine truck. 65 tonne payload. AutoMine autonomous haulage system. Operates 24/7 without operators underground.",specs:{payload_tonnes:65,autonomous:true,system:"AutoMine",operation:"24/7"},score:cs({performance:88,reliability:85,ease_of_use:65,intelligence:80,value:62,ecosystem:72,safety:88,design:65}),breakdown:{performance:88,reliability:85,ease_of_use:65,intelligence:80,value:62,ecosystem:72,safety:88,design:65}},
  {slug:"cat-797f-autonomous",name:"Caterpillar 797F AHS",mfr:"caterpillar",cat:"construction",price:null,year:2022,status:"active",desc:"Autonomous haul truck for surface mining. 400-ton class. Cat MineStar Command system. Deployed at Rio Tinto, BHP, Fortescue mines.",specs:{payload_tonnes:363,system:"MineStar Command",gross_weight_tonnes:623,deployment:"Rio Tinto, BHP, Fortescue"},score:cs({performance:90,reliability:88,ease_of_use:65,intelligence:82,value:60,ecosystem:78,safety:88,design:65}),breakdown:{performance:90,reliability:88,ease_of_use:65,intelligence:82,value:60,ecosystem:78,safety:88,design:65}},
  {slug:"asi-autonomous-dozer",name:"ASI Mobius Autonomous Dozer",mfr:"asi-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous bulldozer system. Retrofit kit converts existing dozers to autonomous operation. Used in mining, earthmoving, and construction.",specs:{type:"Retrofit autonomous kit",compatible:"CAT, Komatsu, Deere dozers",operation:"Fully autonomous"},score:cs({performance:78,reliability:75,ease_of_use:70,intelligence:78,value:72,ecosystem:65,safety:80,design:65}),breakdown:{performance:78,reliability:75,ease_of_use:70,intelligence:78,value:72,ecosystem:65,safety:80,design:65}},
  {slug:"asi-autonomous-drill",name:"ASI Mobius Autonomous Drill",mfr:"asi-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous drilling system for surface mining. Robotic drill pattern execution. Integrates with mine planning software.",specs:{type:"Autonomous drill control",operation:"Pattern drilling",integration:"Mine planning software"},score:cs({performance:76,reliability:76,ease_of_use:68,intelligence:76,value:70,ecosystem:62,safety:82,design:62}),breakdown:{performance:76,reliability:76,ease_of_use:68,intelligence:76,value:70,ecosystem:62,safety:82,design:62}},

  // ═══ ELDERCARE / EDUCATION (5) — "consumer" or "medical" ═══
  {slug:"paro-therapeutic",name:"PARO Therapeutic Robot",mfr:"paro-intelligent",cat:"medical",price:6100,year:2004,status:"active",desc:"Therapeutic baby seal robot for dementia care. FDA-cleared Class II medical device. 5 sensors: tactile, light, auditory, temperature, posture. Reduces agitation by 60%.",specs:{weight_kg:2.5,sensors:5,fda_class:"II",battery_hrs:1.5,fur:"Antibacterial"},score:cs({performance:65,reliability:82,ease_of_use:90,intelligence:55,value:72,ecosystem:58,safety:92,design:90}),breakdown:{performance:65,reliability:82,ease_of_use:90,intelligence:55,value:72,ecosystem:58,safety:92,design:90}},
  {slug:"embodied-moxie",name:"Embodied Moxie",mfr:"embodied",cat:"consumer",price:799,year:2022,status:"active",desc:"AI companion robot for children. Promotes social-emotional learning through conversation, stories, and activities. GPT-4 powered. $39/mo subscription.",specs:{height_cm:38,ai:"GPT-4 powered",subscription:"$39/mo",features:"Conversation, stories, breathing exercises"},score:cs({performance:68,reliability:72,ease_of_use:88,intelligence:80,value:72,ecosystem:55,safety:85,design:88}),breakdown:{performance:68,reliability:72,ease_of_use:88,intelligence:80,value:72,ecosystem:55,safety:85,design:88}},
  {slug:"miko-mini",name:"Miko Mini",mfr:"miko",cat:"consumer",price:149,year:2024,status:"active",desc:"Affordable AI companion robot for kids. Conversational AI, stories, games, learning activities. Screen-free design. Parental controls via app.",specs:{ai:"Custom conversational AI",battery_hrs:4,screen_free:true,age_range:"5-12"},score:cs({performance:62,reliability:72,ease_of_use:88,intelligence:70,value:90,ecosystem:58,safety:88,design:82}),breakdown:{performance:62,reliability:72,ease_of_use:88,intelligence:70,value:90,ecosystem:58,safety:88,design:82}},
  {slug:"intuition-robotics-elliq",name:"Intuition Robotics ElliQ",mfr:"embodied",cat:"medical",price:null,year:2022,status:"active",desc:"AI companion for older adults. Proactive engagement — initiates conversations, suggests activities, tracks health goals. Reduces loneliness by 95% in trials.",specs:{ai:"Proactive AI",features:"Conversation, health reminders, video calls, games",loneliness_reduction:"95%"},score:cs({performance:72,reliability:78,ease_of_use:88,intelligence:82,value:72,ecosystem:58,safety:85,design:82}),breakdown:{performance:72,reliability:78,ease_of_use:88,intelligence:82,value:72,ecosystem:58,safety:85,design:82}},
  {slug:"amazon-astro-enterprise",name:"Amazon Astro for Business",mfr:"amazon",cat:"consumer",price:null,year:2024,status:"active",desc:"Enterprise version of Amazon Astro. Autonomous patrol robot for small businesses. Perimeter monitoring, visitor detection, Alexa integration.",specs:{nav:"SLAM + visual",battery_hrs:4,features:"Patrol, visitor detection, Alexa",camera:"1080p periscope"},score:cs({performance:68,reliability:72,ease_of_use:82,intelligence:75,value:68,ecosystem:72,safety:78,design:80}),breakdown:{performance:68,reliability:72,ease_of_use:82,intelligence:75,value:68,ecosystem:72,safety:78,design:80}},

  // ═══ ADDITIONAL COBOTS / INDUSTRIAL (20) — "manufacturing" ═══
  {slug:"yaskawa-hc10dt",name:"Yaskawa HC10DT",mfr:"yaskawa",cat:"manufacturing",price:38000,year:2022,status:"active",desc:"10 kg payload cobot. Easy direct teaching with 6 torque sensors. IP67 rated for wash-down environments. 1,200mm reach.",specs:{payload_kg:10,reach_mm:1200,dof:6,repeatability_mm:0.05,ip_rating:"IP67"},score:cs({performance:82,reliability:85,ease_of_use:82,intelligence:75,value:80,ecosystem:78,safety:85,design:75}),breakdown:{performance:82,reliability:85,ease_of_use:82,intelligence:75,value:80,ecosystem:78,safety:85,design:75}},
  {slug:"yaskawa-hc20dt",name:"Yaskawa HC20DT",mfr:"yaskawa",cat:"manufacturing",price:48000,year:2023,status:"active",desc:"20 kg cobot for heavy palletizing and machine tending. 1,700mm reach. ISO 10218-1 compliant. Integrates with Yaskawa's Smart Series ecosystem.",specs:{payload_kg:20,reach_mm:1700,dof:6,repeatability_mm:0.05},score:cs({performance:84,reliability:85,ease_of_use:80,intelligence:76,value:78,ecosystem:80,safety:85,design:74}),breakdown:{performance:84,reliability:85,ease_of_use:80,intelligence:76,value:78,ecosystem:80,safety:85,design:74}},
  {slug:"omron-tm14",name:"Omron TM14",mfr:"omron-robotics",cat:"manufacturing",price:42000,year:2023,status:"active",desc:"14 kg cobot with built-in vision system. TM Landmark navigation for precise positioning. Integrated camera on wrist — no external vision needed.",specs:{payload_kg:14,reach_mm:1100,dof:6,vision:"Built-in 5MP wrist camera",repeatability_mm:0.05},score:cs({performance:82,reliability:82,ease_of_use:85,intelligence:82,value:78,ecosystem:76,safety:82,design:78}),breakdown:{performance:82,reliability:82,ease_of_use:85,intelligence:82,value:78,ecosystem:76,safety:82,design:78}},
  {slug:"omron-ld-250",name:"Omron LD-250",mfr:"omron-robotics",cat:"warehouse",price:null,year:2022,status:"active",desc:"Autonomous mobile robot for factory material transport. 250 kg payload. Self-navigating with LiDAR. Fleet management via Omron Fleet Manager.",specs:{payload_kg:250,speed_ms:1.8,battery_hrs:8,nav:"LiDAR SLAM"},score:cs({performance:80,reliability:82,ease_of_use:78,intelligence:76,value:72,ecosystem:78,safety:82,design:72}),breakdown:{performance:80,reliability:82,ease_of_use:78,intelligence:76,value:72,ecosystem:78,safety:82,design:72}},
  {slug:"denso-cobotta-pro",name:"Denso Cobotta Pro 900",mfr:"denso-robotics",cat:"manufacturing",price:32000,year:2023,status:"active",desc:"Ultra-compact 6 kg cobot. 900mm reach. Designed for confined spaces. 0.02mm repeatability — highest precision in its class.",specs:{payload_kg:6,reach_mm:900,dof:6,repeatability_mm:0.02,weight_kg:25},score:cs({performance:80,reliability:84,ease_of_use:82,intelligence:74,value:82,ecosystem:72,safety:82,design:80}),breakdown:{performance:80,reliability:84,ease_of_use:82,intelligence:74,value:82,ecosystem:72,safety:82,design:80}},
  {slug:"staubli-tx2-60",name:"Stäubli TX2-60",mfr:"staubli",cat:"manufacturing",price:45000,year:2022,status:"active",desc:"High-speed collaborative robot. 3.5 kg payload, 920mm reach. Unique: runs at full industrial speed in collaborative mode with SIL3 safety.",specs:{payload_kg:3.5,reach_mm:920,dof:6,speed_ms:8,safety:"SIL3"},score:cs({performance:85,reliability:86,ease_of_use:75,intelligence:76,value:72,ecosystem:70,safety:88,design:78}),breakdown:{performance:85,reliability:86,ease_of_use:75,intelligence:76,value:72,ecosystem:70,safety:88,design:78}},
  {slug:"kawasaki-cx110l",name:"Kawasaki CX110L duAro",mfr:"kawasaki-robotics",cat:"manufacturing",price:null,year:2023,status:"active",desc:"Dual-arm SCARA cobot. Two 3 kg arms on a single base. Designed for assembly tasks requiring two-handed coordination.",specs:{payload_per_arm_kg:3,arms:2,dof:"4 per arm",type:"SCARA dual-arm"},score:cs({performance:78,reliability:82,ease_of_use:78,intelligence:72,value:70,ecosystem:68,safety:82,design:78}),breakdown:{performance:78,reliability:82,ease_of_use:78,intelligence:72,value:70,ecosystem:68,safety:82,design:78}},
  {slug:"fanuc-m-710ic",name:"FANUC M-710iC/50",mfr:"fanuc",cat:"manufacturing",price:65000,year:2020,status:"active",desc:"Mid-range industrial robot. 50 kg payload, 2,050mm reach. Workhorse for spot welding, material handling, and machine tending.",specs:{payload_kg:50,reach_mm:2050,dof:6,repeatability_mm:0.04,ip_rating:"IP67"},score:cs({performance:88,reliability:92,ease_of_use:70,intelligence:72,value:75,ecosystem:90,safety:78,design:68}),breakdown:{performance:88,reliability:92,ease_of_use:70,intelligence:72,value:75,ecosystem:90,safety:78,design:68}},
  {slug:"fanuc-cr-35ia",name:"FANUC CR-35iA",mfr:"fanuc",cat:"manufacturing",price:85000,year:2019,status:"active",desc:"World's strongest collaborative robot. 35 kg payload. Green soft-cover design. Works alongside humans without safety fencing.",specs:{payload_kg:35,reach_mm:1813,dof:6,repeatability_mm:0.03},score:cs({performance:85,reliability:90,ease_of_use:75,intelligence:72,value:68,ecosystem:88,safety:85,design:72}),breakdown:{performance:85,reliability:90,ease_of_use:75,intelligence:72,value:68,ecosystem:88,safety:85,design:72}},
  {slug:"kuka-lbr-iisy-11",name:"KUKA LBR iisy 11",mfr:"kuka",cat:"manufacturing",price:40000,year:2023,status:"active",desc:"KUKA's newest cobot line. 11 kg payload. iiQKA operating system with app-based programming. IP54 as standard.",specs:{payload_kg:11,reach_mm:1300,dof:6,os:"iiQKA",ip_rating:"IP54"},score:cs({performance:82,reliability:84,ease_of_use:85,intelligence:78,value:78,ecosystem:80,safety:85,design:82}),breakdown:{performance:82,reliability:84,ease_of_use:85,intelligence:78,value:78,ecosystem:80,safety:85,design:82}},
  {slug:"kuka-kr-quantec-2",name:"KUKA KR QUANTEC 2",mfr:"kuka",cat:"manufacturing",price:null,year:2022,status:"active",desc:"High-payload industrial robot family. 120-300 kg payload range. Ultra-high precision for automotive, aerospace. KUKA's flagship industrial line.",specs:{payload_kg:"120-300",reach_mm:"2700-3100",dof:6,repeatability_mm:0.05},score:cs({performance:92,reliability:90,ease_of_use:68,intelligence:75,value:70,ecosystem:88,safety:82,design:72}),breakdown:{performance:92,reliability:90,ease_of_use:68,intelligence:75,value:70,ecosystem:88,safety:82,design:72}},
  {slug:"abb-gofa-crb-15000-2",name:"ABB GoFa CRB 15000-12",mfr:"abb-robotics",cat:"manufacturing",price:50000,year:2024,status:"active",desc:"12 kg cobot with class-leading motion smoothness. Ideal for surface finishing, polishing, and assembly. ABB's SafeMove collaborative safety.",specs:{payload_kg:12,reach_mm:1200,dof:6,safety:"SafeMove",repeatability_mm:0.02},score:cs({performance:84,reliability:85,ease_of_use:82,intelligence:78,value:75,ecosystem:85,safety:88,design:80}),breakdown:{performance:84,reliability:85,ease_of_use:82,intelligence:78,value:75,ecosystem:85,safety:88,design:80}},
  {slug:"abb-irb-1300",name:"ABB IRB 1300",mfr:"abb-robotics",cat:"manufacturing",price:35000,year:2020,status:"active",desc:"Compact industrial robot. 7-11 kg payload. 25% faster than predecessor. IP67. Machine tending, assembly, quality inspection.",specs:{payload_kg:11,reach_mm:900,dof:6,ip_rating:"IP67",repeatability_mm:0.01},score:cs({performance:86,reliability:88,ease_of_use:75,intelligence:74,value:80,ecosystem:85,safety:82,design:75}),breakdown:{performance:86,reliability:88,ease_of_use:75,intelligence:74,value:80,ecosystem:85,safety:82,design:75}},
  {slug:"abb-swifti-crb",name:"ABB SWIFTI CRB 1100",mfr:"abb-robotics",cat:"manufacturing",price:null,year:2022,status:"active",desc:"High-speed collaborative robot. 4 kg payload at up to 5 m/s — 5x faster than typical cobots. SafeMove with laser scanner for cage-free operation.",specs:{payload_kg:4,reach_mm:580,dof:6,speed_ms:5,safety:"SafeMove + scanner"},score:cs({performance:86,reliability:84,ease_of_use:78,intelligence:76,value:72,ecosystem:82,safety:85,design:78}),breakdown:{performance:86,reliability:84,ease_of_use:78,intelligence:76,value:72,ecosystem:82,safety:85,design:78}},
  {slug:"doosan-h2017",name:"Doosan H2017",mfr:"doosan-robotics",cat:"manufacturing",price:42000,year:2023,status:"active",desc:"17 kg cobot with 1,700mm reach. 6 torque sensors per joint (industry-leading). Direct teaching with intuitive cockpit mode.",specs:{payload_kg:17,reach_mm:1700,dof:6,torque_sensors:36,repeatability_mm:0.05},score:cs({performance:84,reliability:82,ease_of_use:84,intelligence:76,value:80,ecosystem:72,safety:85,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:84,intelligence:76,value:80,ecosystem:72,safety:85,design:78}},
  {slug:"doosan-a0509",name:"Doosan A0509",mfr:"doosan-robotics",cat:"manufacturing",price:28000,year:2023,status:"active",desc:"5 kg entry-level cobot. 900mm reach. Most affordable Doosan model. Ideal for small shops starting with automation.",specs:{payload_kg:5,reach_mm:900,dof:6,repeatability_mm:0.03},score:cs({performance:76,reliability:80,ease_of_use:85,intelligence:74,value:88,ecosystem:72,safety:82,design:78}),breakdown:{performance:76,reliability:80,ease_of_use:85,intelligence:74,value:88,ecosystem:72,safety:82,design:78}},
  {slug:"techman-tm20",name:"Techman TM20",mfr:"techman-robot",cat:"manufacturing",price:55000,year:2024,status:"active",desc:"20 kg cobot with built-in smart vision. TMvision identifies objects without external camera. AI-based defect detection. 1,300mm reach.",specs:{payload_kg:20,reach_mm:1300,dof:6,vision:"Built-in TMvision",ai:"Defect detection"},score:cs({performance:84,reliability:82,ease_of_use:85,intelligence:82,value:75,ecosystem:76,safety:82,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:85,intelligence:82,value:75,ecosystem:76,safety:82,design:78}},
  {slug:"franka-fr3-2",name:"Franka Production 3",mfr:"franka-emika",cat:"manufacturing",price:25000,year:2024,status:"active",desc:"Research-grade cobot with sub-millimeter force sensitivity. 3 kg payload. 0.1 N force resolution. Ideal for delicate assembly and research.",specs:{payload_kg:3,reach_mm:855,dof:7,force_resolution_n:0.1,repeatability_mm:0.01},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:82,value:82,ecosystem:78,safety:85,design:85}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:82,value:82,ecosystem:78,safety:85,design:85}},
  {slug:"ur-ur30-2",name:"Universal Robots UR30",mfr:"universal-robots",cat:"manufacturing",price:62000,year:2023,status:"active",desc:"UR's largest cobot. 30 kg payload, 1,300mm reach. Palletizing, heavy machine tending. Same UR footprint despite 2x UR20 payload.",specs:{payload_kg:30,reach_mm:1300,dof:6,footprint:"Same as UR5e",repeatability_mm:0.05},score:cs({performance:88,reliability:86,ease_of_use:85,intelligence:80,value:78,ecosystem:95,safety:88,design:80}),breakdown:{performance:88,reliability:86,ease_of_use:85,intelligence:80,value:78,ecosystem:95,safety:88,design:80}},

  // ═══ MORE DRONES (6) — "drone" category ═══
  {slug:"parrot-anafi-usa",name:"Parrot ANAFI Ai",mfr:"parrot",cat:"drone",price:4500,year:2022,status:"active",desc:"4G-connected enterprise drone. Streams over cellular network — no range limit. NDAA-compliant. 48MP camera, 32x zoom. French-made.",specs:{weight_kg:0.9,flight_time_min:32,camera:"48MP, 32x zoom",connectivity:"4G LTE",ndaa:true},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:76,value:82,ecosystem:72,safety:78,design:82}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:76,value:82,ecosystem:72,safety:78,design:82}},
  {slug:"flyability-elios-3",name:"Flyability Elios 3",mfr:"flyability",cat:"drone",price:25000,year:2023,status:"active",desc:"Indoor/confined space inspection drone. Protective cage allows collision-tolerant flight. LiDAR SLAM. Used in boilers, tanks, mines, nuclear facilities.",specs:{weight_kg:1.8,flight_time_min:12,cage:"Collision-tolerant protective",lidar:"Ouster OS0",applications:"Confined spaces"},score:cs({performance:82,reliability:80,ease_of_use:82,intelligence:80,value:70,ecosystem:72,safety:90,design:85}),breakdown:{performance:82,reliability:80,ease_of_use:82,intelligence:80,value:70,ecosystem:72,safety:90,design:85}},
  {slug:"dji-dock-2",name:"DJI Dock 2 + Matrice 3D",mfr:"dji",cat:"drone",price:18000,year:2024,status:"active",desc:"Autonomous drone-in-a-box system. DJI Dock 2 houses Matrice 3D/3TD. Fully autonomous takeoff, mission, landing, charging. Remote monitoring.",specs:{drone:"Matrice 3D",flight_time_min:50,dock_weight_kg:34,charging_time_min:32,remote_operation:true},score:cs({performance:88,reliability:85,ease_of_use:85,intelligence:85,value:78,ecosystem:88,safety:82,design:82}),breakdown:{performance:88,reliability:85,ease_of_use:85,intelligence:85,value:78,ecosystem:88,safety:82,design:82}},
  {slug:"dji-mini-4-pro",name:"DJI Mini 4 Pro",mfr:"dji",cat:"drone",price:759,year:2023,status:"active",desc:"Sub-249g consumer drone. 4K/60fps. Omnidirectional obstacle sensing. 34 min flight time. No registration required in most countries.",specs:{weight_g:249,flight_time_min:34,camera:"4K 60fps, 48MP",obstacle_sensing:"Omnidirectional",range_km:20},score:cs({performance:82,reliability:82,ease_of_use:90,intelligence:78,value:90,ecosystem:88,safety:80,design:88}),breakdown:{performance:82,reliability:82,ease_of_use:90,intelligence:78,value:90,ecosystem:88,safety:80,design:88}},
  {slug:"zipline-p2",name:"Zipline P2 Zip",mfr:"zipline",cat:"drone",price:null,year:2024,status:"active",desc:"Last-mile delivery drone. Launches from Zipline P2 Platform. Descends on tether to deliver packages at doorstep. Serves Walmart, healthcare systems.",specs:{delivery_weight_kg:3.6,range_km:16,speed_kmh:100,delivery_method:"Tether descent",partners:"Walmart, healthcare"},score:cs({performance:85,reliability:82,ease_of_use:80,intelligence:82,value:72,ecosystem:75,safety:85,design:82}),breakdown:{performance:85,reliability:82,ease_of_use:80,intelligence:82,value:72,ecosystem:75,safety:85,design:82}},
  {slug:"wingtra-ray",name:"WingtraRAY",mfr:"wingtra",cat:"drone",price:25000,year:2025,status:"active",desc:"Next-gen VTOL mapping drone. 59-min endurance. Compact VTOL takeoff. Sub-centimeter accuracy with PPK. Swiss-made for surveyors.",specs:{weight_kg:4.5,flight_time_min:59,takeoff:"VTOL",accuracy_cm:1,survey_area_km2:5},score:cs({performance:86,reliability:84,ease_of_use:82,intelligence:80,value:72,ecosystem:72,safety:82,design:80}),breakdown:{performance:86,reliability:84,ease_of_use:82,intelligence:80,value:72,ecosystem:72,safety:82,design:80}},

  // ═══ MORE CONSTRUCTION (8) — "construction" category ═══
  {slug:"rugged-mark1",name:"Rugged Robotics Mark 1",mfr:"rugged-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous construction layout robot. Prints full-scale floor plans directly on concrete. Eliminates manual measuring and chalk lines.",specs:{accuracy_mm:3,speed:"1000 sqft/hr",method:"Direct print on concrete",autonomy:true},score:cs({performance:78,reliability:76,ease_of_use:82,intelligence:78,value:72,ecosystem:58,safety:80,design:75}),breakdown:{performance:78,reliability:76,ease_of_use:82,intelligence:78,value:72,ecosystem:58,safety:80,design:75}},
  {slug:"canvas-drywalling",name:"Canvas Drywall Robot",mfr:"canvas-construction",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous drywall finishing robot. 3D scans walls, then applies joint compound with robotic arm. 3x faster than manual taping/mudding.",specs:{speed:"3x manual",method:"3D scan + robotic application",finish:"Level 4-5"},score:cs({performance:78,reliability:74,ease_of_use:75,intelligence:80,value:70,ecosystem:52,safety:78,design:72}),breakdown:{performance:78,reliability:74,ease_of_use:75,intelligence:80,value:70,ecosystem:52,safety:78,design:72}},
  {slug:"trimble-xr10",name:"Trimble XR10 with HoloLens",mfr:"trimble",cat:"construction",price:5500,year:2022,status:"active",desc:"Mixed reality hardhat for construction BIM overlay. Shows 3D building models overlaid on real construction site. Trimble Connect integration.",specs:{display:"HoloLens 2 mixed reality",hardhat:"ANSI Z89.1 Class E",battery_hrs:3,bim_integration:"Trimble Connect"},score:cs({performance:72,reliability:75,ease_of_use:68,intelligence:80,value:65,ecosystem:72,safety:78,design:78}),breakdown:{performance:72,reliability:75,ease_of_use:68,intelligence:80,value:65,ecosystem:72,safety:78,design:78}},
  {slug:"spot-construction-ai",name:"Boston Dynamics Spot + Construction AI",mfr:"boston-dynamics",cat:"construction",price:95000,year:2024,status:"active",desc:"Spot configured for construction monitoring. Autonomous site walks with 360° capture. Integrates with HoloBuilder/DroneDeploy for progress tracking.",specs:{base:"Spot Enterprise",payload:"360° camera array",integration:"HoloBuilder, DroneDeploy",frequency:"Daily autonomous walks"},score:cs({performance:86,reliability:85,ease_of_use:78,intelligence:88,value:68,ecosystem:85,safety:88,design:88}),breakdown:{performance:86,reliability:85,ease_of_use:78,intelligence:88,value:68,ecosystem:85,safety:88,design:88}},
  {slug:"built-rpd35",name:"Built Robotics RPD35",mfr:"built-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Autonomous piling robot for solar farm construction. Drives piles with GPS precision. 20% faster than manual crews for utility-scale solar.",specs:{type:"Autonomous pile driver",accuracy_cm:2,speed:"20% faster than manual",application:"Solar farm construction"},score:cs({performance:82,reliability:78,ease_of_use:72,intelligence:78,value:72,ecosystem:60,safety:82,design:68}),breakdown:{performance:82,reliability:78,ease_of_use:72,intelligence:78,value:72,ecosystem:60,safety:82,design:68}},
  {slug:"built-exo-trencher",name:"Built Robotics Exosystem Trencher",mfr:"built-robotics",cat:"construction",price:null,year:2023,status:"active",desc:"Autonomous trenching retrofit for excavators. Converts standard excavators to autonomous trench-digging machines. GPS-guided precision.",specs:{type:"Retrofit autonomous trencher",accuracy_cm:5,compatible:"Standard excavators",guidance:"GPS RTK"},score:cs({performance:80,reliability:76,ease_of_use:70,intelligence:78,value:72,ecosystem:62,safety:80,design:65}),breakdown:{performance:80,reliability:76,ease_of_use:70,intelligence:78,value:72,ecosystem:62,safety:80,design:65}},
  {slug:"hilti-bim-robot",name:"Hilti BIM Robotic Total Station",mfr:"hilti",cat:"construction",price:35000,year:2023,status:"active",desc:"Robotic layout instrument connecting BIM models to jobsite. Auto-calculates layout points from 3D model. One-person layout operation.",specs:{accuracy_mm:1,range_m:500,bim:"Direct Hilti BIM import",operation:"Single person"},score:cs({performance:82,reliability:84,ease_of_use:78,intelligence:78,value:72,ecosystem:76,safety:80,design:75}),breakdown:{performance:82,reliability:84,ease_of_use:78,intelligence:78,value:72,ecosystem:76,safety:80,design:75}},
  {slug:"hilti-jaibot-2",name:"Hilti Jaibot 2",mfr:"hilti",cat:"construction",price:null,year:2024,status:"active",desc:"Semi-autonomous ceiling drilling robot. Drills holes from BIM data. Second-gen with improved battery and navigation. Reduces overhead drilling injuries.",specs:{drilling:"Automated from BIM",battery_hrs:8,nav:"Improved SLAM",application:"Ceiling MEP installations"},score:cs({performance:78,reliability:80,ease_of_use:78,intelligence:78,value:70,ecosystem:72,safety:85,design:75}),breakdown:{performance:78,reliability:80,ease_of_use:78,intelligence:78,value:70,ecosystem:72,safety:85,design:75}},

  // ═══ MORE CONSUMER HOME (10) ═══
  {slug:"dreame-l40-ultra",name:"Dreame L40 Ultra",mfr:"dreame",cat:"consumer",price:1599,year:2024,status:"active",desc:"Premium robot vacuum + mop. 11,000 Pa suction. Auto-mop lifting. Self-cleaning base with hot water wash. AI obstacle avoidance.",specs:{suction_pa:11000,battery_hrs:3.5,noise_db:65,dustbin_ml:350,water_tank_ml:80,ai_obstacle:true},score:cs({performance:88,reliability:82,ease_of_use:88,intelligence:85,value:78,ecosystem:72,safety:80,design:85}),breakdown:{performance:88,reliability:82,ease_of_use:88,intelligence:85,value:78,ecosystem:72,safety:80,design:85}},
  {slug:"ecovacs-x5-omni",name:"Ecovacs DEEBOT X5 Omni",mfr:"ecovacs",cat:"consumer",price:1499,year:2024,status:"active",desc:"Square-shaped robot vacuum for edge cleaning. 12,800 Pa suction. TruEdge adaptive cleaning. AI-powered AIVI 3D obstacle avoidance.",specs:{suction_pa:12800,shape:"Square",battery_hrs:3,ai:"AIVI 3D",edge_cleaning:"TruEdge adaptive"},score:cs({performance:88,reliability:80,ease_of_use:86,intelligence:85,value:80,ecosystem:75,safety:80,design:85}),breakdown:{performance:88,reliability:80,ease_of_use:86,intelligence:85,value:80,ecosystem:75,safety:80,design:85}},
  {slug:"roborock-saros-z70",name:"Roborock Saros Z70",mfr:"roborock",cat:"consumer",price:2400,year:2025,status:"active",desc:"First robot vacuum with robotic arm. OmniGrip arm picks up socks, small objects before vacuuming. 22,000 Pa suction. Self-cleaning station.",specs:{suction_pa:22000,arm:"OmniGrip robotic arm",payload_g:300,battery_hrs:3,ai:"StarSight 2.0"},score:cs({performance:90,reliability:78,ease_of_use:86,intelligence:88,value:72,ecosystem:78,safety:80,design:90}),breakdown:{performance:90,reliability:78,ease_of_use:86,intelligence:88,value:72,ecosystem:78,safety:80,design:90}},
  {slug:"irobot-roomba-s9",name:"iRobot Roomba s9+",mfr:"irobot",cat:"consumer",price:999,year:2019,status:"active",desc:"iRobot's premium robot vacuum. D-shape design for corner cleaning. 40x suction vs Roomba 600 series. Auto-empty base. PerfectEdge technology.",specs:{suction:"40x base",shape:"D-shape",dustbin_ml:400,battery_min:120},score:cs({performance:84,reliability:82,ease_of_use:85,intelligence:80,value:72,ecosystem:85,safety:80,design:80}),breakdown:{performance:84,reliability:82,ease_of_use:85,intelligence:80,value:72,ecosystem:85,safety:80,design:80}},
  {slug:"switchbot-k10-pro",name:"SwitchBot K10+ Pro",mfr:"dreame",cat:"consumer",price:399,year:2024,status:"active",desc:"Ultra-compact robot vacuum. Only 9.3 cm diameter — world's smallest. Fits under furniture other robots can't reach. 3,000 Pa suction.",specs:{diameter_cm:9.3,suction_pa:3000,battery_min:120,weight_kg:1.2},score:cs({performance:70,reliability:74,ease_of_use:88,intelligence:70,value:88,ecosystem:62,safety:80,design:85}),breakdown:{performance:70,reliability:74,ease_of_use:88,intelligence:70,value:88,ecosystem:62,safety:80,design:85}},
  {slug:"dreame-d10s-pro",name:"Dreame D10s Pro",mfr:"dreame",cat:"consumer",price:299,year:2024,status:"active",desc:"Budget robot vacuum with LiDAR navigation. 5,000 Pa suction. Multi-floor mapping. Best value LiDAR robot under $300.",specs:{suction_pa:5000,nav:"LiDAR SLAM",battery_min:280,water_tank_ml:235},score:cs({performance:76,reliability:76,ease_of_use:82,intelligence:74,value:92,ecosystem:68,safety:78,design:75}),breakdown:{performance:76,reliability:76,ease_of_use:82,intelligence:74,value:92,ecosystem:68,safety:78,design:75}},
  {slug:"roborock-q-revo-pro",name:"Roborock Q Revo Pro",mfr:"roborock",cat:"consumer",price:699,year:2024,status:"active",desc:"Mid-range robot vacuum + mop. 7,000 Pa suction. Dual spinning mop pads. Auto-mop lifting. Self-cleaning and drying station.",specs:{suction_pa:7000,mop:"Dual spinning pads",battery_min:180,auto_mop_lift:true},score:cs({performance:82,reliability:80,ease_of_use:86,intelligence:80,value:85,ecosystem:78,safety:80,design:80}),breakdown:{performance:82,reliability:80,ease_of_use:86,intelligence:80,value:85,ecosystem:78,safety:80,design:80}},
  {slug:"ecovacs-n20-pro-plus",name:"Ecovacs DEEBOT N20 Pro Plus",mfr:"ecovacs",cat:"consumer",price:499,year:2024,status:"active",desc:"Value robot vacuum with strong suction. 8,000 Pa. TrueMapping LiDAR. Auto-empty station included. Excellent mid-range option.",specs:{suction_pa:8000,nav:"TrueMapping LiDAR",battery_min:300,auto_empty:true},score:cs({performance:80,reliability:78,ease_of_use:84,intelligence:78,value:86,ecosystem:72,safety:78,design:75}),breakdown:{performance:80,reliability:78,ease_of_use:84,intelligence:78,value:86,ecosystem:72,safety:78,design:75}},
  {slug:"unitree-go2-pro",name:"Unitree Go2 Pro",mfr:"unitree-robotics",cat:"consumer",price:2800,year:2024,status:"active",desc:"Mid-tier robot dog. LiDAR mapping, 4G connectivity, voice commands. Autonomous obstacle avoidance. Developer SDK for custom applications.",specs:{height_cm:40,weight_kg:15,payload_kg:5,battery_hrs:2.5,max_speed_ms:3.5,lidar:true},score:cs({performance:80,reliability:76,ease_of_use:82,intelligence:78,value:85,ecosystem:78,safety:70,design:84}),breakdown:{performance:80,reliability:76,ease_of_use:82,intelligence:78,value:85,ecosystem:78,safety:70,design:84}},
  {slug:"unitree-b2-w",name:"Unitree B2-W",mfr:"unitree-robotics",cat:"construction",price:null,year:2024,status:"active",desc:"Wheeled variant of B2 quadruped. Switches between legs and wheels. 80 kg payload. IP67. For inspection in large facilities and outdoor terrain.",specs:{weight_kg:70,payload_kg:80,max_speed_ms:8,ip_rating:"IP67",modes:"Legs + Wheels"},score:cs({performance:88,reliability:80,ease_of_use:75,intelligence:82,value:75,ecosystem:72,safety:82,design:82}),breakdown:{performance:88,reliability:80,ease_of_use:75,intelligence:82,value:75,ecosystem:72,safety:82,design:82}},

  // ═══ MORE MEDICAL (6) ═══
  {slug:"intuitive-da-vinci-xi",name:"Intuitive da Vinci Xi",mfr:"intuitive-surgical",cat:"medical",price:1800000,year:2014,status:"active",desc:"Fourth-gen da Vinci surgical system. 4 overhead-mounted arms. Multi-quadrant access. Most widely deployed robotic surgical system version.",specs:{arms:4,instruments:"Wristed EndoWrist",vision:"3D HD",mounting:"Overhead boom",procedures:"Multi-quadrant"},score:cs({performance:88,reliability:90,ease_of_use:80,intelligence:82,value:68,ecosystem:95,safety:90,design:82}),breakdown:{performance:88,reliability:90,ease_of_use:80,intelligence:82,value:68,ecosystem:95,safety:90,design:82}},
  {slug:"mazor-x-stealth",name:"Medtronic Mazor X Stealth",mfr:"medtronic",cat:"medical",price:1200000,year:2020,status:"active",desc:"Robotic guidance system for spine surgery. 3D planning with intraoperative CT verification. 150+ per surgeons globally. Reduces screw misplacement.",specs:{application:"Spine surgery",planning:"3D preoperative",guidance:"Robotic arm",verification:"Intraoperative CT"},score:cs({performance:84,reliability:85,ease_of_use:72,intelligence:82,value:65,ecosystem:78,safety:88,design:75}),breakdown:{performance:84,reliability:85,ease_of_use:72,intelligence:82,value:65,ecosystem:78,safety:88,design:75}},
  {slug:"globus-excelsius-gps",name:"Globus ExcelsiusGPS",mfr:"medtronic",cat:"medical",price:900000,year:2021,status:"active",desc:"Robotic navigation for spine surgery. GPS-like guidance for screw placement. Rigid robotic arm provides real-time positional feedback.",specs:{application:"Spine surgery",guidance:"Robotic arm + navigation",accuracy_mm:1.5},score:cs({performance:82,reliability:82,ease_of_use:74,intelligence:80,value:68,ecosystem:72,safety:86,design:72}),breakdown:{performance:82,reliability:82,ease_of_use:74,intelligence:80,value:68,ecosystem:72,safety:86,design:72}},
  {slug:"think-surgical-tmini",name:"Think Surgical TSolution One",mfr:"stryker",cat:"medical",price:800000,year:2023,status:"active",desc:"Open-platform surgical robot for total knee replacement. Works with any implant brand — not locked to a single manufacturer's implants.",specs:{application:"Total knee replacement",platform:"Open (any implant)",planning:"CT-based 3D"},score:cs({performance:80,reliability:80,ease_of_use:74,intelligence:78,value:72,ecosystem:65,safety:85,design:72}),breakdown:{performance:80,reliability:80,ease_of_use:74,intelligence:78,value:72,ecosystem:65,safety:85,design:72}},
  {slug:"diligent-moxi-2",name:"Diligent Moxi Gen 2",mfr:"diligent-robotics",cat:"medical",price:null,year:2024,status:"active",desc:"Hospital delivery robot. Autonomously delivers supplies, lab samples, medications between departments. Elevator integration. 200+ hospitals.",specs:{payload_kg:14,battery_hrs:12,nav:"LiDAR SLAM",elevator:true,hospitals:200},score:cs({performance:76,reliability:80,ease_of_use:82,intelligence:78,value:72,ecosystem:68,safety:85,design:78}),breakdown:{performance:76,reliability:80,ease_of_use:82,intelligence:78,value:72,ecosystem:68,safety:85,design:78}},
  {slug:"aethon-tug-t3",name:"Aethon TUG T3",mfr:"stryker",cat:"medical",price:null,year:2023,status:"active",desc:"Autonomous hospital transport robot by ST Robotics (Aethon, acquired by Stryker). Delivers meals, medications, linens, lab specimens. 600+ hospitals.",specs:{payload_kg:450,battery_hrs:10,hospitals:600,deliveries:"Meals, meds, linens, labs"},score:cs({performance:78,reliability:82,ease_of_use:78,intelligence:76,value:72,ecosystem:75,safety:85,design:70}),breakdown:{performance:78,reliability:82,ease_of_use:78,intelligence:76,value:72,ecosystem:75,safety:85,design:70}},

  // ═══ MORE DELIVERY (4) ═══
  {slug:"nuro-r3",name:"Nuro R3",mfr:"nuro",cat:"delivery",price:null,year:2024,status:"active",desc:"Purpose-built autonomous road vehicle for local goods delivery. No passenger compartment. Temperature-controlled cargo. NHTSA exemption. Partners: Walmart, Kroger, 7-Eleven.",specs:{speed_mph:25,cargo_volume_l:350,temperature_control:true,partners:"Walmart, Kroger, 7-Eleven"},score:cs({performance:82,reliability:78,ease_of_use:80,intelligence:85,value:68,ecosystem:72,safety:85,design:82}),breakdown:{performance:82,reliability:78,ease_of_use:80,intelligence:85,value:68,ecosystem:72,safety:85,design:82}},
  {slug:"serve-gen4",name:"Serve Robotics Gen 4",mfr:"serve-robotics",cat:"delivery",price:null,year:2024,status:"active",desc:"Fourth-gen sidewalk delivery robot from Uber spinoff. Level 4 autonomy. Deployed in Los Angeles via Uber Eats. AI-powered navigation.",specs:{autonomy_level:4,payload_kg:11,partners:"Uber Eats",city:"Los Angeles"},score:cs({performance:76,reliability:76,ease_of_use:82,intelligence:80,value:72,ecosystem:72,safety:80,design:78}),breakdown:{performance:76,reliability:76,ease_of_use:82,intelligence:80,value:72,ecosystem:72,safety:80,design:78}},
  {slug:"gatik-autonomous-van",name:"Gatik Autonomous B2B Van",mfr:"nuro",cat:"delivery",price:null,year:2023,status:"active",desc:"Autonomous middle-mile delivery van. B2B short-haul logistics. Operates fixed routes between warehouses and stores. Partners: Walmart, Loblaw.",specs:{type:"Class 3-6 van",autonomy_level:4,routes:"Fixed B2B",partners:"Walmart, Loblaw"},score:cs({performance:80,reliability:78,ease_of_use:72,intelligence:82,value:68,ecosystem:62,safety:82,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:72,intelligence:82,value:68,ecosystem:62,safety:82,design:72}},
  {slug:"tinymile-delivery",name:"TinyMile Delivery Robot",mfr:"kiwibot",cat:"delivery",price:null,year:2023,status:"active",desc:"Compact sidewalk delivery robot operating in Miami. Last-mile food delivery. Remote teleoperator assistance. Small form factor for dense urban areas.",specs:{payload_kg:8,max_speed_mph:3,city:"Miami",autonomy:"Hybrid + teleop"},score:cs({performance:68,reliability:72,ease_of_use:80,intelligence:70,value:75,ecosystem:58,safety:78,design:75}),breakdown:{performance:68,reliability:72,ease_of_use:80,intelligence:70,value:75,ecosystem:58,safety:78,design:75}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 3 Import: 190 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`📂 Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  ❌ Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`🏭 Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  ❌ ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  ❌ ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  ❌ ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`📊 Wave 3 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
