/**
 * Robotomated — Wave 14 Robot Import: 50 New Robots
 * Focus: Automated Guided Vehicles, heavy-payload AMRs, tuggers, pallet movers
 * Run: npx tsx scripts/import-robots-wave14.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  { slug: "geekplus", name: "Geek+", country: "CN", founded_year: 2015, website: "https://geekplus.com" },
  { slug: "greyorange", name: "GreyOrange", country: "SG", founded_year: 2011, website: "https://greyorange.com" },
  { slug: "hai-robotics", name: "Hai Robotics", country: "CN", founded_year: 2016, website: "https://hairobotics.com" },
  { slug: "quicktron", name: "Quicktron", country: "CN", founded_year: 2014, website: "https://quicktron.com" },
  { slug: "forwardx", name: "ForwardX Robotics", country: "CN", founded_year: 2016, website: "https://forwardx.com" },
];

// ═══════════════════════════════════════════════════════════════
// ROBOTS — 50 total (10 Geek+, 8 GreyOrange, 8 Hai, 8 Quicktron, 8 ForwardX, 8 other)
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

// ═══ Geek+ Robots (10) ═══
{slug:"geekplus-p800",name:"Geek+ P800 Picking Robot",mfr:"geekplus",cat:"warehouse",price:35000,year:2024,status:"active",desc:"Goods-to-person shelf-moving AMR with 800 kg lift capacity. Uses QR code navigation to bring shelving pods to pick stations at speeds up to 2 m/s. Deployed in 10,000+ units globally across Amazon and DHL.",specs:{type:"Shelf-moving AMR",payload_kg:800,speed_m_s:2,nav:"QR code + inertial",lift_height_mm:300,battery_hrs:8,deployments:"10,000+ globally"},score:cs({performance:82,reliability:82,ease_of_use:80,intelligence:76,value:84,ecosystem:78,safety:80,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:80,intelligence:76,value:84,ecosystem:78,safety:80,design:74}},
{slug:"geekplus-p40",name:"Geek+ P40 Compact Picker",mfr:"geekplus",cat:"warehouse",price:22000,year:2024,status:"active",desc:"Compact goods-to-person AMR designed for narrow-aisle operations. 500 kg payload with a 600 mm minimum aisle width requirement. Ideal for legacy warehouses with limited floor space.",specs:{type:"Compact shelf-moving AMR",payload_kg:500,speed_m_s:1.5,min_aisle_mm:600,nav:"QR code + SLAM hybrid",battery_hrs:10,application:"Narrow-aisle legacy warehouses"},score:cs({performance:78,reliability:80,ease_of_use:82,intelligence:74,value:86,ecosystem:76,safety:80,design:74}),breakdown:{performance:78,reliability:80,ease_of_use:82,intelligence:74,value:86,ecosystem:76,safety:80,design:74}},
{slug:"geekplus-m1000c",name:"Geek+ M1000C Heavy-Duty Mover",mfr:"geekplus",cat:"warehouse",price:45000,year:2024,status:"active",desc:"Heavy-payload AMR carrying loads up to 1000 kg for pallet and heavy-goods movement. Combines QR code navigation with LiDAR for mixed-traffic environments. Fork or conveyor-top configurations available.",specs:{type:"Heavy-duty AMR",payload_kg:1000,speed_m_s:1.5,nav:"QR code + LiDAR",configurations:"Fork, conveyor-top, platform",battery_hrs:6,application:"Heavy goods, pallet transport"},score:cs({performance:82,reliability:80,ease_of_use:76,intelligence:76,value:78,ecosystem:76,safety:82,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:76,intelligence:76,value:78,ecosystem:76,safety:82,design:72}},
{slug:"geekplus-s20c",name:"Geek+ S20C Sorting Robot",mfr:"geekplus",cat:"warehouse",price:18000,year:2024,status:"active",desc:"High-speed parcel sorting AMR that navigates a sorting grid to drop parcels into destination chutes. Fleet of 300+ robots sorts 10,000+ parcels per hour. Used by SF Express and Yanwen for e-commerce parcel sorting.",specs:{type:"Sorting AMR",payload_kg:20,speed_m_s:3,throughput:"10,000+ parcels/hr (300 fleet)",nav:"QR code grid",application:"Parcel sorting",partners:"SF Express, Yanwen"},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:74,value:82,ecosystem:76,safety:78,design:74}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:74,value:82,ecosystem:76,safety:78,design:74}},
{slug:"geekplus-c200m",name:"Geek+ C200M Conveyor AMR",mfr:"geekplus",cat:"warehouse",price:38000,year:2024,status:"active",desc:"AMR with integrated roller conveyor top for automated tote/case transfer. Autonomously docks at workstations and conveyor lines for hands-free load exchange. 200 kg payload with SLAM navigation.",specs:{type:"Conveyor-top AMR",payload_kg:200,speed_m_s:1.8,nav:"SLAM + QR code",conveyor:"Integrated roller top",docking:"Automatic station docking",battery_hrs:8},score:cs({performance:80,reliability:80,ease_of_use:82,intelligence:78,value:78,ecosystem:76,safety:80,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:82,intelligence:78,value:78,ecosystem:76,safety:80,design:76}},
{slug:"geekplus-rs5n",name:"Geek+ RS5N RoboShuttle",mfr:"geekplus",cat:"warehouse",price:null,year:2024,status:"active",desc:"Vertical shuttle robot that climbs racking to retrieve totes from heights up to 10 m. Combines horizontal travel with vertical climbing for dense cube storage. Deployed in Nike and Decathlon DCs. From $2M system.",specs:{type:"Vertical climbing shuttle",max_height_m:10,payload_kg:30,movement:"Horizontal + vertical climbing",storage:"Dense cube racking",deployments:"Nike, Decathlon",system_price_min:2000000},score:cs({performance:84,reliability:82,ease_of_use:74,intelligence:80,value:74,ecosystem:78,safety:82,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:74,intelligence:80,value:74,ecosystem:78,safety:82,design:78}},
{slug:"geekplus-f16l",name:"Geek+ F16L Forklift AMR",mfr:"geekplus",cat:"warehouse",price:55000,year:2024,status:"active",desc:"Autonomous forklift AMR for pallet handling at heights up to 5.2 m. Natural-feature SLAM navigation requires no infrastructure modification. 1600 kg lift capacity handles standard Euro and US pallets.",specs:{type:"Autonomous forklift AMR",payload_kg:1600,lift_height_m:5.2,nav:"SLAM natural-feature",pallet_types:"Euro, US standard",speed_m_s:1.2,battery_hrs:6},score:cs({performance:80,reliability:78,ease_of_use:76,intelligence:80,value:76,ecosystem:76,safety:82,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:76,intelligence:80,value:76,ecosystem:76,safety:82,design:72}},
{slug:"geekplus-mp1000r",name:"Geek+ MP1000R PopPick",mfr:"geekplus",cat:"warehouse",price:null,year:2025,status:"active",desc:"Next-generation picking system combining vertical tote retrieval with robotic arm picking. PopPick stations present totes at ergonomic height while robotic arms handle repetitive picks. 450 picks/hr. From $500K/station.",specs:{type:"Robotic pick station",picks_per_hour:450,method:"Vertical retrieval + robot arm",ergonomic:"Optimal pick height",vision:"3D + AI pick planning",application:"E-commerce fulfillment",station_price:500000},score:cs({performance:82,reliability:78,ease_of_use:76,intelligence:84,value:72,ecosystem:76,safety:80,design:76}),breakdown:{performance:82,reliability:78,ease_of_use:76,intelligence:84,value:72,ecosystem:76,safety:80,design:76}},
{slug:"geekplus-t800d",name:"Geek+ T800D Tow Tractor",mfr:"geekplus",cat:"warehouse",price:40000,year:2024,status:"active",desc:"Autonomous tow tractor AMR pulling carts of up to 800 kg through warehouse and manufacturing facilities. Follows predefined routes or dynamic SLAM paths. Supports cart train configurations of up to 4 trailers.",specs:{type:"Autonomous tow tractor",tow_capacity_kg:800,trailers_max:4,nav:"SLAM + predefined routes",speed_m_s:1.5,battery_hrs:10,application:"Cart-based material transport"},score:cs({performance:78,reliability:80,ease_of_use:80,intelligence:74,value:80,ecosystem:76,safety:80,design:72}),breakdown:{performance:78,reliability:80,ease_of_use:80,intelligence:74,value:80,ecosystem:76,safety:80,design:72}},
{slug:"geekplus-v5a",name:"Geek+ V5A Moving Robot",mfr:"geekplus",cat:"warehouse",price:28000,year:2024,status:"active",desc:"Versatile shelf-to-person AMR optimized for pharmaceutical and small-parts fulfillment. 500 kg lift capacity with precision positioning for automated dispensing integration. GMP-compliant design.",specs:{type:"Pharma-grade shelf AMR",payload_kg:500,speed_m_s:1.5,nav:"QR code + inertial",compliance:"GMP-ready",application:"Pharmaceutical, small parts",positioning:"Precision for auto-dispensing"},score:cs({performance:80,reliability:82,ease_of_use:80,intelligence:74,value:80,ecosystem:74,safety:84,design:74}),breakdown:{performance:80,reliability:82,ease_of_use:80,intelligence:74,value:80,ecosystem:74,safety:84,design:74}},

// ═══ GreyOrange Robots (8) ═══
{slug:"greyorange-ranger-gtp-2024",name:"GreyOrange Ranger GTP",mfr:"greyorange",cat:"warehouse",price:38000,year:2024,status:"active",desc:"Goods-to-person AMR carrying mobile shelving units to operator pick stations. AI-driven GreyMatter software dynamically slots inventory based on demand velocity. 600 kg payload at 1.5 m/s.",specs:{type:"Goods-to-person AMR",payload_kg:600,speed_m_s:1.5,software:"GreyMatter AI slotting",nav:"QR code + camera",battery_hrs:8,application:"E-commerce fulfillment"},score:cs({performance:82,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:76,safety:80,design:76}),breakdown:{performance:82,reliability:80,ease_of_use:78,intelligence:82,value:78,ecosystem:76,safety:80,design:76}},
{slug:"greyorange-ranger-sort",name:"GreyOrange Ranger Sort",mfr:"greyorange",cat:"warehouse",price:20000,year:2024,status:"active",desc:"Grid-based sorting robot for parcel and order sortation. Travels on an elevated sorting platform to drop items into destination bins. Fleet of 200 handles 5,000+ sorts per hour.",specs:{type:"Grid sorting AMR",payload_kg:30,speed_m_s:2.5,throughput:"5,000+ sorts/hr (200 fleet)",nav:"Grid + camera",platform:"Elevated sorting deck",battery_hrs:6},score:cs({performance:82,reliability:78,ease_of_use:78,intelligence:76,value:80,ecosystem:74,safety:78,design:74}),breakdown:{performance:82,reliability:78,ease_of_use:78,intelligence:76,value:80,ecosystem:74,safety:78,design:74}},
{slug:"greyorange-ranger-asrs",name:"GreyOrange Ranger AS/RS",mfr:"greyorange",cat:"warehouse",price:null,year:2024,status:"active",desc:"Vertical shuttle robot that climbs racking structures up to 8 m to retrieve totes. GreyMatter AI coordinates fleet to optimize throughput based on real-time order priorities. From $1.5M system.",specs:{type:"Vertical climbing AS/RS bot",max_height_m:8,payload_kg:25,software:"GreyMatter AI coordination",storage:"Dense racking",throughput:"Varies by fleet size",system_price_min:1500000},score:cs({performance:82,reliability:80,ease_of_use:74,intelligence:82,value:72,ecosystem:76,safety:82,design:76}),breakdown:{performance:82,reliability:80,ease_of_use:74,intelligence:82,value:72,ecosystem:76,safety:82,design:76}},
{slug:"greyorange-ranger-mobile",name:"GreyOrange Ranger Mobile",mfr:"greyorange",cat:"warehouse",price:42000,year:2024,status:"active",desc:"Flexible AMR platform for goods transport across warehouse zones. SLAM navigation operates without infrastructure changes. Configurable top modules for shelves, conveyor, or custom fixtures.",specs:{type:"Flexible transport AMR",payload_kg:400,speed_m_s:1.8,nav:"SLAM natural-feature",modules:"Shelf, conveyor, custom",battery_hrs:10,application:"Cross-zone transport"},score:cs({performance:80,reliability:78,ease_of_use:82,intelligence:78,value:78,ecosystem:74,safety:80,design:76}),breakdown:{performance:80,reliability:78,ease_of_use:82,intelligence:78,value:78,ecosystem:74,safety:80,design:76}},
{slug:"greyorange-ranger-pick",name:"GreyOrange Ranger Pick",mfr:"greyorange",cat:"warehouse",price:null,year:2025,status:"active",desc:"Integrated AMR and robotic arm system for autonomous piece picking. Travels to storage locations, identifies items with 3D vision, and picks at 400 items per hour. GreyMatter orchestrates multi-robot workflows. From $180K.",specs:{type:"Mobile picking robot",picks_per_hour:400,vision:"3D depth + AI",arm:"6-axis integrated",nav:"SLAM",software:"GreyMatter orchestration",unit_price:180000},score:cs({performance:78,reliability:76,ease_of_use:74,intelligence:84,value:70,ecosystem:76,safety:80,design:76}),breakdown:{performance:78,reliability:76,ease_of_use:74,intelligence:84,value:70,ecosystem:76,safety:80,design:76}},
{slug:"greyorange-flexbot-pallet",name:"GreyOrange FlexBot Pallet",mfr:"greyorange",cat:"warehouse",price:52000,year:2024,status:"active",desc:"Heavy-duty pallet mover AMR with 1200 kg capacity. Handles standard pallet jacking and transport without infrastructure changes. Dual-mode operation with autonomous and remote control.",specs:{type:"Pallet mover AMR",payload_kg:1200,speed_m_s:1.2,nav:"SLAM + safety LiDAR",operation:"Autonomous + remote",pallet_types:"Standard, Euro",battery_hrs:6},score:cs({performance:80,reliability:78,ease_of_use:76,intelligence:76,value:76,ecosystem:74,safety:82,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:76,intelligence:76,value:76,ecosystem:74,safety:82,design:72}},
{slug:"greyorange-ranger-max",name:"GreyOrange Ranger Max",mfr:"greyorange",cat:"warehouse",price:48000,year:2025,status:"active",desc:"Next-generation shelf-to-person AMR with 1000 kg payload and multi-tier shelf handling. Can lift shelving units with up to 5 tiers without destabilizing. Enhanced acceleration for 20% faster cycle times.",specs:{type:"Heavy shelf-to-person AMR",payload_kg:1000,speed_m_s:2,tiers_supported:5,cycle_improvement:"20% faster",nav:"QR + LiDAR hybrid",battery_hrs:8},score:cs({performance:84,reliability:80,ease_of_use:78,intelligence:78,value:76,ecosystem:76,safety:80,design:76}),breakdown:{performance:84,reliability:80,ease_of_use:78,intelligence:78,value:76,ecosystem:76,safety:80,design:76}},
{slug:"greyorange-flexbot-tugger",name:"GreyOrange FlexBot Tugger",mfr:"greyorange",cat:"warehouse",price:36000,year:2024,status:"active",desc:"Autonomous tugger robot pulling cart trains through warehouses and manufacturing plants. Tows up to 600 kg across 3 carts on predefined or dynamic routes. Auto-docking cart coupling mechanism.",specs:{type:"Autonomous tugger",tow_capacity_kg:600,carts_max:3,nav:"SLAM",docking:"Auto-coupling",speed_m_s:1.5,battery_hrs:8,application:"Cart-train material flow"},score:cs({performance:78,reliability:78,ease_of_use:80,intelligence:74,value:80,ecosystem:74,safety:80,design:72}),breakdown:{performance:78,reliability:78,ease_of_use:80,intelligence:74,value:80,ecosystem:74,safety:80,design:72}},

// ═══ Hai Robotics (8) ═══
{slug:"hai-haipick-a42t",name:"Hai Robotics HAIPICK A42T",mfr:"hai-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Tote-to-person ACR (Autonomous Case-handling Robot) that climbs racking up to 10 m to retrieve totes and deliver them to pick stations. Handles 8 totes simultaneously with telescopic arms. From $60K per unit.",specs:{type:"ACR tote retrieval",max_height_m:10,totes_per_trip:8,arm:"Telescopic double-deep",speed_m_s:1.5,nav:"QR code + encoder",unit_price:60000},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:80,value:76,ecosystem:74,safety:82,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:80,value:76,ecosystem:74,safety:82,design:76}},
{slug:"hai-haipick-a42",name:"Hai Robotics HAIPICK A42",mfr:"hai-robotics",cat:"warehouse",price:48000,year:2023,status:"active",desc:"Standard ACR model reaching shelving heights up to 5.4 m. Retrieves up to 4 totes per trip using extendable forks. Over 30,000 units deployed across 500+ customer sites including LG and Decathlon.",specs:{type:"ACR tote retrieval",max_height_m:5.4,totes_per_trip:4,arm:"Extendable fork",deployments:"30,000+ units, 500+ sites",speed_m_s:1.5,nav:"QR code + encoder"},score:cs({performance:82,reliability:82,ease_of_use:78,intelligence:78,value:80,ecosystem:76,safety:82,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:78,intelligence:78,value:80,ecosystem:76,safety:82,design:74}},
{slug:"hai-haipick-a3",name:"Hai Robotics HAIPICK A3 Forklift",mfr:"hai-robotics",cat:"warehouse",price:55000,year:2024,status:"active",desc:"ACR with integrated forklift mechanism for pallet-level operations up to 4 m. Bridges gap between tote-level automation and pallet handling. Handles pallets up to 1000 kg in mixed tote-pallet warehouses.",specs:{type:"ACR with forklift",max_height_m:4,payload_kg:1000,handling:"Totes + pallets",speed_m_s:1.2,nav:"QR code + LiDAR",application:"Mixed tote-pallet operations"},score:cs({performance:80,reliability:78,ease_of_use:74,intelligence:78,value:76,ecosystem:74,safety:80,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:74,intelligence:78,value:76,ecosystem:74,safety:80,design:72}},
{slug:"hai-haiport-w3600",name:"Hai Robotics HaiPort W3600",mfr:"hai-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Multi-level workstation for HAIPICK systems. ACRs deliver totes to workstation at 3 presentation levels. Ergonomic design with put-to-light guidance achieves 500+ picks per hour per operator. From $120K.",specs:{type:"ACR workstation",presentation_levels:3,picks_per_hour:500,guidance:"Put-to-light",ergonomic:"Multi-height presentation",integration:"HAIPICK fleet",station_price:120000},score:cs({performance:82,reliability:82,ease_of_use:84,intelligence:76,value:76,ecosystem:76,safety:82,design:78}),breakdown:{performance:82,reliability:82,ease_of_use:84,intelligence:76,value:76,ecosystem:76,safety:82,design:78}},
{slug:"hai-haipick-a100",name:"Hai Robotics HAIPICK A100",mfr:"hai-robotics",cat:"warehouse",price:65000,year:2025,status:"active",desc:"Next-generation ACR with 12-tote simultaneous handling capacity and 12 m maximum racking height. Faster telescopic arms reduce retrieval cycle time by 30% versus A42T. Designed for ultra-high-density warehouses.",specs:{type:"Next-gen ACR",max_height_m:12,totes_per_trip:12,improvement:"30% faster retrieval",arm:"High-speed telescopic",application:"Ultra-high-density storage",speed_m_s:2},score:cs({performance:86,reliability:80,ease_of_use:76,intelligence:82,value:74,ecosystem:74,safety:82,design:78}),breakdown:{performance:86,reliability:80,ease_of_use:76,intelligence:82,value:74,ecosystem:74,safety:82,design:78}},
{slug:"hai-haipick-b100",name:"Hai Robotics HAIPICK B100 Pallet ACR",mfr:"hai-robotics",cat:"warehouse",price:72000,year:2025,status:"active",desc:"Pallet-handling ACR that retrieves full pallets from racking up to 8 m high. 1500 kg lift capacity with double-deep retrieval. Targets cold storage and heavy-goods distribution centers.",specs:{type:"Pallet ACR",max_height_m:8,payload_kg:1500,retrieval:"Double-deep",application:"Cold storage, heavy goods",speed_m_s:1,environment:"Cold storage rated to -25C"},score:cs({performance:82,reliability:80,ease_of_use:72,intelligence:78,value:74,ecosystem:72,safety:82,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:72,intelligence:78,value:74,ecosystem:72,safety:82,design:72}},
{slug:"hai-haipick-ct",name:"Hai Robotics HAIPICK CT Conveyor Top",mfr:"hai-robotics",cat:"warehouse",price:42000,year:2024,status:"active",desc:"ACR variant with integrated conveyor top for seamless tote handoff to sortation lines. Eliminates manual transfer at workstations. Processes 80+ totes per hour per unit in continuous-flow operations.",specs:{type:"Conveyor-top ACR",totes_per_hour:80,conveyor:"Integrated roller top",handoff:"Automatic to sortation",max_height_m:5,speed_m_s:1.5,application:"Continuous-flow fulfillment"},score:cs({performance:80,reliability:80,ease_of_use:80,intelligence:78,value:78,ecosystem:74,safety:80,design:76}),breakdown:{performance:80,reliability:80,ease_of_use:80,intelligence:78,value:78,ecosystem:74,safety:80,design:76}},
{slug:"hai-haichain-sortbot",name:"Hai Robotics HaiChain SortBot",mfr:"hai-robotics",cat:"warehouse",price:16000,year:2024,status:"active",desc:"Compact grid-based sorting robot operating on elevated sorting platforms. 15 kg payload capacity for parcel and small-order sorting. Fleet of 200 achieves 8,000 sorts per hour. Low cost enables rapid ROI.",specs:{type:"Grid sorting AMR",payload_kg:15,speed_m_s:2.5,throughput:"8,000 sorts/hr (200 fleet)",platform:"Elevated grid",battery_hrs:6,application:"Parcel sorting, order consolidation"},score:cs({performance:80,reliability:78,ease_of_use:80,intelligence:72,value:86,ecosystem:72,safety:78,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:80,intelligence:72,value:86,ecosystem:72,safety:78,design:72}},

// ═══ Quicktron Robots (8) ═══
{slug:"quicktron-m800",name:"Quicktron M800 Shelf Mover",mfr:"quicktron",cat:"warehouse",price:30000,year:2024,status:"active",desc:"Goods-to-person shelf-carrying AMR with 800 kg payload. QR code navigation with inertial backup. Deployed in 20,000+ units across Alibaba, Cainiao, and STO Express for e-commerce fulfillment.",specs:{type:"Shelf-carrying AMR",payload_kg:800,speed_m_s:1.8,nav:"QR code + inertial",deployments:"20,000+ units",partners:"Alibaba, Cainiao, STO",battery_hrs:8},score:cs({performance:82,reliability:80,ease_of_use:80,intelligence:74,value:86,ecosystem:76,safety:78,design:72}),breakdown:{performance:82,reliability:80,ease_of_use:80,intelligence:74,value:86,ecosystem:76,safety:78,design:72}},
{slug:"quicktron-q200",name:"Quicktron Q200 Sort Bot",mfr:"quicktron",cat:"warehouse",price:14000,year:2024,status:"active",desc:"Ultra-compact parcel sorting robot at industry-leading price point. 8 kg payload on grid sorting platforms. Fleet of 500 processes 20,000 parcels per hour for logistics providers across China.",specs:{type:"Grid sorting AMR",payload_kg:8,speed_m_s:3,throughput:"20,000 parcels/hr (500 fleet)",nav:"QR code grid",battery_hrs:4,application:"High-volume parcel sorting"},score:cs({performance:80,reliability:76,ease_of_use:80,intelligence:72,value:90,ecosystem:72,safety:76,design:72}),breakdown:{performance:80,reliability:76,ease_of_use:80,intelligence:72,value:90,ecosystem:72,safety:76,design:72}},
{slug:"quicktron-m1500",name:"Quicktron M1500 Heavy Mover",mfr:"quicktron",cat:"warehouse",price:48000,year:2024,status:"active",desc:"Heavy-duty shelf and pallet mover AMR with 1500 kg payload capacity. Handles oversized racking units and loaded pallets. Industrial-grade construction for demanding manufacturing logistics.",specs:{type:"Heavy-duty AMR",payload_kg:1500,speed_m_s:1.2,nav:"QR code + LiDAR",application:"Pallet and heavy shelf transport",construction:"Industrial grade",battery_hrs:6},score:cs({performance:82,reliability:80,ease_of_use:74,intelligence:74,value:78,ecosystem:74,safety:82,design:70}),breakdown:{performance:82,reliability:80,ease_of_use:74,intelligence:74,value:78,ecosystem:74,safety:82,design:70}},
{slug:"quicktron-c200",name:"Quicktron C200 Conveyor AMR",mfr:"quicktron",cat:"warehouse",price:32000,year:2024,status:"active",desc:"AMR with roller conveyor top for automated tote and case transfer. 200 kg payload with auto-docking at conveyor lines and workstations. Designed for flexible material flow between zones.",specs:{type:"Conveyor-top AMR",payload_kg:200,speed_m_s:1.5,conveyor:"Integrated roller",docking:"Auto-docking conveyor interface",nav:"QR code + inertial",battery_hrs:8},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:76,value:82,ecosystem:74,safety:80,design:74}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:76,value:82,ecosystem:74,safety:80,design:74}},
{slug:"quicktron-f1600",name:"Quicktron F1600 Forklift AMR",mfr:"quicktron",cat:"warehouse",price:58000,year:2024,status:"active",desc:"Autonomous counterbalance forklift with 1600 kg lift capacity to 3.5 m. SLAM navigation with 3D obstacle detection. Handles racking put-away, retrieval, and dock-to-stock pallet movement.",specs:{type:"Autonomous forklift",payload_kg:1600,lift_height_m:3.5,nav:"SLAM + 3D obstacle detection",application:"Racking put-away, dock-to-stock",speed_m_s:1,battery_hrs:6},score:cs({performance:80,reliability:78,ease_of_use:74,intelligence:78,value:76,ecosystem:74,safety:82,design:70}),breakdown:{performance:80,reliability:78,ease_of_use:74,intelligence:78,value:76,ecosystem:74,safety:82,design:70}},
{slug:"quicktron-t600",name:"Quicktron T600 Tugger",mfr:"quicktron",cat:"warehouse",price:28000,year:2024,status:"active",desc:"Autonomous tugger AMR towing cart trains of up to 600 kg through factories and warehouses. Magnetic or QR-guided path following with obstacle avoidance. Auto-coupling cart attachment mechanism.",specs:{type:"Autonomous tugger",tow_capacity_kg:600,nav:"Magnetic/QR guided",coupling:"Auto-coupling",carts_max:3,speed_m_s:1.5,application:"Cart-based line-side delivery"},score:cs({performance:76,reliability:78,ease_of_use:80,intelligence:72,value:82,ecosystem:72,safety:80,design:70}),breakdown:{performance:76,reliability:78,ease_of_use:80,intelligence:72,value:82,ecosystem:72,safety:80,design:70}},
{slug:"quicktron-l500",name:"Quicktron L500 Latent Lifter",mfr:"quicktron",cat:"warehouse",price:25000,year:2024,status:"active",desc:"Ultra-low-profile AMR that slides under roll cages and shelf units to lift and move them. 75 mm height allows access under standard warehouse fixtures. 500 kg payload.",specs:{type:"Latent lift AMR",payload_kg:500,height_mm:75,speed_m_s:1.8,nav:"QR code",application:"Roll cage and fixture transport",battery_hrs:8,profile:"Ultra-low — slides under fixtures"},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:72,value:84,ecosystem:72,safety:78,design:72}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:72,value:84,ecosystem:72,safety:78,design:72}},
{slug:"quicktron-h100",name:"Quicktron H100 Mini Shelf Bot",mfr:"quicktron",cat:"warehouse",price:18000,year:2024,status:"active",desc:"Compact and lightweight shelf-moving AMR for small-item fulfillment. 300 kg payload in a 500 mm wide chassis for narrow-aisle deployment. Popular in pharmaceutical and cosmetics distribution.",specs:{type:"Compact shelf AMR",payload_kg:300,width_mm:500,speed_m_s:1.5,nav:"QR code",application:"Pharma, cosmetics fulfillment",battery_hrs:10,form_factor:"Narrow-aisle compact"},score:cs({performance:76,reliability:78,ease_of_use:84,intelligence:72,value:86,ecosystem:72,safety:80,design:74}),breakdown:{performance:76,reliability:78,ease_of_use:84,intelligence:72,value:86,ecosystem:72,safety:80,design:74}},

// ═══ ForwardX Robots (8) ═══
{slug:"forwardx-apex-c1500",name:"ForwardX Apex C1500 Forklift",mfr:"forwardx",cat:"warehouse",price:62000,year:2024,status:"active",desc:"Autonomous counterbalance forklift with 1500 kg capacity lifting to 4.5 m. Visual SLAM navigation with deep learning obstacle classification. Handles truck unloading, put-away, and replenishment autonomously.",specs:{type:"Autonomous forklift",payload_kg:1500,lift_height_m:4.5,nav:"Visual SLAM + deep learning",application:"Unloading, put-away, replenishment",speed_m_s:1.2,battery_hrs:6},score:cs({performance:82,reliability:78,ease_of_use:76,intelligence:82,value:76,ecosystem:72,safety:82,design:74}),breakdown:{performance:82,reliability:78,ease_of_use:76,intelligence:82,value:76,ecosystem:72,safety:82,design:74}},
{slug:"forwardx-apex-c2000",name:"ForwardX Apex C2000 Heavy Forklift",mfr:"forwardx",cat:"warehouse",price:78000,year:2024,status:"active",desc:"Heavy-duty autonomous forklift with 2000 kg capacity and 6 m lift height. Designed for high-rack warehouses and cold storage environments. Operates in temperatures from -30C to 45C.",specs:{type:"Heavy autonomous forklift",payload_kg:2000,lift_height_m:6,nav:"Visual SLAM",temperature_range:"-30C to 45C",application:"High-rack, cold storage",speed_m_s:1},score:cs({performance:84,reliability:78,ease_of_use:74,intelligence:80,value:74,ecosystem:72,safety:82,design:72}),breakdown:{performance:84,reliability:78,ease_of_use:74,intelligence:80,value:74,ecosystem:72,safety:82,design:72}},
{slug:"forwardx-flex-200s",name:"ForwardX Flex 200S Transport AMR",mfr:"forwardx",cat:"warehouse",price:32000,year:2024,status:"active",desc:"Versatile transport AMR with 200 kg payload and modular top configurations. SLAM navigation with 360-degree safety LiDAR. Supports shelf, conveyor, and custom fixture tops for flexible workflows.",specs:{type:"Transport AMR",payload_kg:200,speed_m_s:1.8,nav:"SLAM + 360 LiDAR",modules:"Shelf, conveyor, custom",battery_hrs:10,application:"Flexible material transport"},score:cs({performance:78,reliability:78,ease_of_use:82,intelligence:78,value:80,ecosystem:72,safety:82,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:82,intelligence:78,value:80,ecosystem:72,safety:82,design:76}},
{slug:"forwardx-flex-600t",name:"ForwardX Flex 600T Tugger",mfr:"forwardx",cat:"warehouse",price:35000,year:2024,status:"active",desc:"Autonomous tugger AMR towing 600 kg across cart trains in manufacturing and warehouse environments. Visual SLAM with pedestrian prediction for mixed-traffic operation. Auto-release cart decoupling.",specs:{type:"Autonomous tugger",tow_capacity_kg:600,nav:"Visual SLAM",pedestrian_ai:"Prediction-based avoidance",coupling:"Auto-release",speed_m_s:1.5,battery_hrs:8},score:cs({performance:78,reliability:78,ease_of_use:80,intelligence:78,value:80,ecosystem:72,safety:82,design:74}),breakdown:{performance:78,reliability:78,ease_of_use:80,intelligence:78,value:80,ecosystem:72,safety:82,design:74}},
{slug:"forwardx-apex-s1400",name:"ForwardX Apex S1400 Stacker",mfr:"forwardx",cat:"warehouse",price:52000,year:2024,status:"active",desc:"Autonomous stacker forklift with 1400 kg capacity lifting to 5.5 m. Narrow-aisle compatible at 2.1 m aisle width. Designed for high-density pallet racking operations.",specs:{type:"Autonomous stacker",payload_kg:1400,lift_height_m:5.5,min_aisle_m:2.1,nav:"Visual SLAM",application:"High-density pallet racking",speed_m_s:1},score:cs({performance:80,reliability:78,ease_of_use:74,intelligence:80,value:76,ecosystem:72,safety:82,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:74,intelligence:80,value:76,ecosystem:72,safety:82,design:72}},
{slug:"forwardx-oasis-300c",name:"ForwardX Oasis 300C Delivery Bot",mfr:"forwardx",cat:"warehouse",price:28000,year:2024,status:"active",desc:"Indoor delivery AMR for hospitals, hotels, and office buildings. 300 kg payload with secure compartment access via PIN or QR code. Autonomous elevator integration for multi-floor delivery.",specs:{type:"Indoor delivery AMR",payload_kg:300,speed_m_s:1.2,nav:"SLAM",access:"PIN/QR secure compartment",elevator:"Autonomous integration",application:"Hospital, hotel, office delivery"},score:cs({performance:76,reliability:78,ease_of_use:84,intelligence:78,value:78,ecosystem:70,safety:82,design:78}),breakdown:{performance:76,reliability:78,ease_of_use:84,intelligence:78,value:78,ecosystem:70,safety:82,design:78}},
{slug:"forwardx-apex-p2200",name:"ForwardX Apex P2200 Pallet Mover",mfr:"forwardx",cat:"warehouse",price:42000,year:2024,status:"active",desc:"Autonomous pallet jack AMR handling loads up to 2200 kg. Low-profile design for standard pallet openings. Handles dock-to-stock and stock-to-staging pallet transport in distribution centers.",specs:{type:"Autonomous pallet jack",payload_kg:2200,speed_m_s:1.5,nav:"Visual SLAM",profile:"Low-profile pallet jack",application:"Dock-to-stock, staging",battery_hrs:8},score:cs({performance:80,reliability:78,ease_of_use:78,intelligence:76,value:78,ecosystem:72,safety:80,design:70}),breakdown:{performance:80,reliability:78,ease_of_use:78,intelligence:76,value:78,ecosystem:72,safety:80,design:70}},
{slug:"forwardx-oasis-180",name:"ForwardX Oasis 180 Service Bot",mfr:"forwardx",cat:"warehouse",price:22000,year:2024,status:"active",desc:"Compact service delivery AMR for restaurants, retail stores, and small warehouses. 60 kg payload with multi-tier tray configuration. Friendly interactive display for customer-facing deployments.",specs:{type:"Service delivery AMR",payload_kg:60,speed_m_s:1,nav:"SLAM",trays:"Multi-tier configurable",display:"Interactive touchscreen",application:"Restaurant, retail, small warehouse"},score:cs({performance:72,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:68,safety:80,design:80}),breakdown:{performance:72,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:68,safety:80,design:80}},

// ═══ Other AGV/AMR Manufacturers (8) ═══
{slug:"mir-250-hook",name:"MiR250 Hook",mfr:"mir",cat:"warehouse",price:42000,year:2024,status:"active",desc:"MiR250 base with integrated hook mechanism for autonomous cart towing. Hooks and unhooks carts automatically at designated stations. 500 kg tow capacity for manufacturing line-side delivery.",specs:{type:"Cart-towing AMR",tow_capacity_kg:500,hook:"Automatic hook/unhook",base:"MiR250 platform",nav:"SLAM",speed_m_s:2,battery_hrs:10},score:cs({performance:80,reliability:84,ease_of_use:82,intelligence:78,value:76,ecosystem:82,safety:84,design:78}),breakdown:{performance:80,reliability:84,ease_of_use:82,intelligence:78,value:76,ecosystem:82,safety:84,design:78}},
{slug:"mir-1200-pallet",name:"MiR1200 Pallet Jack",mfr:"mir",cat:"warehouse",price:65000,year:2024,status:"active",desc:"Autonomous pallet jack built on the MiR1200 platform. 1200 kg capacity with floor-level pallet pickup. SLAM navigation with 360-degree safety sensors rated to PLd/Cat 3.",specs:{type:"Autonomous pallet jack",payload_kg:1200,nav:"SLAM 360-degree",safety_rating:"PLd Cat 3",speed_m_s:1.5,pickup:"Floor-level auto-fork",battery_hrs:8},score:cs({performance:82,reliability:84,ease_of_use:80,intelligence:80,value:74,ecosystem:82,safety:86,design:76}),breakdown:{performance:82,reliability:84,ease_of_use:80,intelligence:80,value:74,ecosystem:82,safety:86,design:76}},
{slug:"fetch-rolltop-900",name:"Fetch RollTop 900",mfr:"fetch-robotics",cat:"warehouse",price:48000,year:2024,status:"active",desc:"AMR with motorized roller conveyor for seamless integration with existing conveyor infrastructure. 900 kg payload capacity. Auto-transfers totes and cases at conveyor line speed without stopping.",specs:{type:"Conveyor-integrated AMR",payload_kg:900,conveyor:"Motorized roller top",transfer:"Auto at line speed",nav:"SLAM",speed_m_s:1.5,application:"Conveyor line extension"},score:cs({performance:80,reliability:82,ease_of_use:80,intelligence:78,value:76,ecosystem:80,safety:82,design:74}),breakdown:{performance:80,reliability:82,ease_of_use:80,intelligence:78,value:76,ecosystem:80,safety:82,design:74}},
{slug:"fetch-cart500",name:"Fetch CartConnect 500",mfr:"fetch-robotics",cat:"warehouse",price:35000,year:2024,status:"active",desc:"Cart-towing AMR from Fetch Robotics designed for manufacturing environments. Automatically engages and disengages carts at pickup and drop-off stations. 500 kg tow capacity.",specs:{type:"Cart-towing AMR",tow_capacity_kg:500,coupling:"Auto engage/disengage",nav:"SLAM",speed_m_s:1.5,battery_hrs:10,application:"Manufacturing line-side delivery"},score:cs({performance:78,reliability:82,ease_of_use:82,intelligence:76,value:78,ecosystem:80,safety:82,design:74}),breakdown:{performance:78,reliability:82,ease_of_use:82,intelligence:76,value:78,ecosystem:80,safety:82,design:74}},
{slug:"6rs-chuck-2",name:"6 River Systems Chuck 2.0",mfr:"six-river-systems",cat:"warehouse",price:null,year:2024,status:"active",desc:"Second-generation collaborative mobile robot for zone-based picking. LED-guided picking displays direct workers to items. Integrated with Shopify Fulfillment Network. 90 kg payload. $3,000/mo RaaS.",specs:{type:"Collaborative picking AMR",payload_kg:90,guidance:"LED pick-to-light",speed_m_s:1.5,integration:"Shopify Fulfillment Network",subscription_monthly:3000,method:"Zone-based collaborative"},score:cs({performance:78,reliability:80,ease_of_use:88,intelligence:76,value:76,ecosystem:80,safety:84,design:80}),breakdown:{performance:78,reliability:80,ease_of_use:88,intelligence:76,value:76,ecosystem:80,safety:84,design:80}},
{slug:"6rs-chuck-pallet",name:"6 River Systems Chuck Pallet",mfr:"six-river-systems",cat:"warehouse",price:null,year:2025,status:"active",desc:"Heavy-duty variant of Chuck designed for pallet-level operations. Supports full pallet transport through collaborative workflows. Workers scan and robots route autonomously. $4,500/mo RaaS.",specs:{type:"Collaborative pallet AMR",payload_kg:500,method:"Collaborative pallet workflows",nav:"SLAM",integration:"Shopify Fulfillment",subscription_monthly:4500,speed_m_s:1.2},score:cs({performance:78,reliability:78,ease_of_use:86,intelligence:76,value:74,ecosystem:80,safety:82,design:76}),breakdown:{performance:78,reliability:78,ease_of_use:86,intelligence:76,value:74,ecosystem:80,safety:82,design:76}},
{slug:"mir-600-lift",name:"MiR600 Pallet Lift",mfr:"mir",cat:"warehouse",price:72000,year:2024,status:"active",desc:"Heavy-duty AMR with integrated pallet lift for 600 kg payload transport. CE and UL safety certified for mixed human-robot environments. Handles EU and US standard pallets with auto-centering.",specs:{type:"Pallet lift AMR",payload_kg:600,nav:"SLAM",safety:"CE + UL certified",pallets:"EU and US standard",centering:"Auto-centering lift",speed_m_s:1.5},score:cs({performance:82,reliability:84,ease_of_use:80,intelligence:78,value:74,ecosystem:82,safety:86,design:76}),breakdown:{performance:82,reliability:84,ease_of_use:80,intelligence:78,value:74,ecosystem:82,safety:86,design:76}},
{slug:"fetch-hmishelf",name:"Fetch HMIShelf",mfr:"fetch-robotics",cat:"warehouse",price:38000,year:2024,status:"active",desc:"Shelf-carrying AMR with integrated HMI touchscreen for operator interaction. Workers scan items at the robot's display for put-to-robot workflows. 600 kg payload with adjustable shelf heights.",specs:{type:"Shelf AMR with HMI",payload_kg:600,display:"Integrated touchscreen HMI",workflow:"Put-to-robot scanning",shelves:"Adjustable height",nav:"SLAM",speed_m_s:1.5},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:76,value:78,ecosystem:80,safety:82,design:78}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:76,value:78,ecosystem:80,safety:82,design:78}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 14 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 14 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
