/**
 * Robotomated — Wave 9 Robot Import: 50 New Robots
 * Security & Hospitality focused wave.
 *
 * Run: npx tsx scripts/import-robots-wave9.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  security: ["https://images.unsplash.com/photo-1558002038-1055907df827?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&h=400&fit=crop"],
  hospitality: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.security;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  // Security
  { slug: "knightscope", name: "Knightscope", country: "US", founded_year: 2013, website: "https://knightscope.com" },
  { slug: "cobalt-robotics", name: "Cobalt Robotics", country: "US", founded_year: 2016, website: "https://cobaltrobotics.com" },
  { slug: "turing-video", name: "Turing Video", country: "US", founded_year: 2016, website: "https://turingvideo.com" },
  { slug: "rad-robotics", name: "RAD (Robotic Assistance Devices)", country: "US", founded_year: 2016, website: "https://rfrrad.com" },
  { slug: "gamma2-robotics", name: "Gamma 2 Robotics", country: "US", founded_year: 2013, website: "https://integrateddefense.us" },
  // Hospitality
  { slug: "bear-robotics", name: "Bear Robotics", country: "US", founded_year: 2017, website: "https://bearrobotics.ai" },
  { slug: "richtech-robotics", name: "Richtech Robotics", country: "US", founded_year: 2016, website: "https://richtechrobotics.com" },
  { slug: "savioke", name: "Savioke", country: "US", founded_year: 2013, website: "https://savioke.com" },
  { slug: "maidbot", name: "Maidbot", country: "US", founded_year: 2017, website: "https://maidbot.com" },
  { slug: "keenon-robotics", name: "Keenon Robotics", country: "CN", founded_year: 2010, website: "https://keenonrobot.com" },
  { slug: "orionstar", name: "OrionStar", country: "CN", founded_year: 2016, website: "https://ainirobot.com" },
  { slug: "pudu-robotics", name: "Pudu Robotics", country: "CN", founded_year: 2016, website: "https://pudurobotics.com" },
];

// ═══════════════════════════════════════════════════════════════
// ALL ROBOTS — 50 new entries
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

  // ═══ SECURITY (25) ═══
  {slug:"knightscope-k5",name:"K5 Autonomous Security Robot",mfr:"knightscope",cat:"security",price:7500,year:2023,status:"active",desc:"Outdoor autonomous patrol robot by Knightscope. 5-foot tall, 400-lb unit patrols parking lots, campuses, and corporate grounds. 360-degree cameras, thermal imaging, license plate recognition, and anomaly detection. Leased at $7,500/month as a Security-as-a-Service model.",specs:{weight_kg:181,height_m:1.52,max_speed_ms:1.3,battery_life_hours:8,operating_temp:"-20C to 50C",ip_rating:"IP65",connectivity:"4G LTE, WiFi, Bluetooth",sensors:"360 cameras, thermal, LPR, ultrasonic, lidar"},score:cs({performance:76,reliability:74,ease_of_use:78,intelligence:80,value:62,ecosystem:65,safety:82,design:76}),breakdown:{performance:76,reliability:74,ease_of_use:78,intelligence:80,value:62,ecosystem:65,safety:82,design:76}},
  {slug:"knightscope-k3",name:"K3 Indoor Security Robot",mfr:"knightscope",cat:"security",price:6000,year:2023,status:"active",desc:"Indoor autonomous security robot designed for shopping malls, hospitals, and office buildings. Compact form factor navigates hallways and elevators. Real-time anomaly detection with human-in-the-loop escalation. Continuous patrol with automatic charging.",specs:{weight_kg:159,height_m:1.22,max_speed_ms:1.0,battery_life_hours:10,operating_temp:"0C to 40C",ip_rating:"IP44",connectivity:"WiFi, 4G LTE, Bluetooth",sensors:"HD cameras, thermal, microphone array, badge reader"},score:cs({performance:72,reliability:72,ease_of_use:80,intelligence:78,value:64,ecosystem:65,safety:80,design:74}),breakdown:{performance:72,reliability:72,ease_of_use:80,intelligence:78,value:64,ecosystem:65,safety:80,design:74}},
  {slug:"knightscope-k1",name:"K1 Stationary Security Robot",mfr:"knightscope",cat:"security",price:5000,year:2022,status:"active",desc:"Stationary security kiosk by Knightscope for fixed entry points and lobbies. Visitor check-in, ID scanning, badge verification, and intercom. Integrates with existing access control systems. Low-cost alternative to staffed security desks.",specs:{weight_kg:136,height_m:1.07,max_speed_ms:0,battery_life_hours:24,operating_temp:"0C to 40C",ip_rating:"IP44",connectivity:"WiFi, Ethernet, 4G LTE",sensors:"HD camera, ID scanner, badge reader, intercom, thermal"},score:cs({performance:68,reliability:78,ease_of_use:84,intelligence:74,value:72,ecosystem:65,safety:78,design:72}),breakdown:{performance:68,reliability:78,ease_of_use:84,intelligence:74,value:72,ecosystem:65,safety:78,design:72}},
  {slug:"knightscope-k7",name:"K7 Multi-Terrain Security Robot",mfr:"knightscope",cat:"security",price:9000,year:2024,status:"active",desc:"All-terrain autonomous security robot built on a four-wheeled chassis for rugged environments. Patrols construction sites, solar farms, and large industrial perimeters. Enhanced off-road capability with GPS waypoint navigation and extended battery life.",specs:{weight_kg:340,height_m:1.6,max_speed_ms:1.8,battery_life_hours:12,operating_temp:"-30C to 55C",ip_rating:"IP67",connectivity:"4G LTE, WiFi, satellite optional",sensors:"360 cameras, thermal FLIR, LiDAR, radar, GPS RTK"},score:cs({performance:80,reliability:76,ease_of_use:74,intelligence:82,value:60,ecosystem:62,safety:84,design:74}),breakdown:{performance:80,reliability:76,ease_of_use:74,intelligence:82,value:60,ecosystem:62,safety:84,design:74}},
  {slug:"cobalt-r2",name:"Cobalt R2",mfr:"cobalt-robotics",cat:"security",price:3000,year:2023,status:"active",desc:"Indoor office security robot with human-in-the-loop monitoring. Patrols autonomously while a remote security specialist monitors feeds. 60+ sensors detect tailgating, propped doors, unauthorized access, and environmental anomalies. Used across Fortune 500 campuses.",specs:{weight_kg:55,height_m:1.2,max_speed_ms:1.0,battery_life_hours:8,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, 4G LTE",sensors:"60+ including cameras, thermal, lidar, badge reader, air quality"},score:cs({performance:78,reliability:80,ease_of_use:82,intelligence:82,value:70,ecosystem:72,safety:85,design:80}),breakdown:{performance:78,reliability:80,ease_of_use:82,intelligence:82,value:70,ecosystem:72,safety:85,design:80}},
  {slug:"cobalt-r3",name:"Cobalt R3",mfr:"cobalt-robotics",cat:"security",price:4500,year:2024,status:"active",desc:"Next-generation enterprise security robot with enhanced AI and expanded sensor suite. Improved navigation handles complex multi-floor buildings. Advanced behavioral analytics detect unusual patterns. Seamless elevator integration and automatic charging.",specs:{weight_kg:60,height_m:1.25,max_speed_ms:1.2,battery_life_hours:10,operating_temp:"5C to 40C",ip_rating:"IP44",connectivity:"WiFi 6E, 5G, Bluetooth 5.3",sensors:"80+ sensors, 4K cameras, thermal, lidar, mmWave radar"},score:cs({performance:82,reliability:82,ease_of_use:84,intelligence:86,value:68,ecosystem:75,safety:86,design:82}),breakdown:{performance:82,reliability:82,ease_of_use:84,intelligence:86,value:68,ecosystem:75,safety:86,design:82}},
  {slug:"turing-turing-shield",name:"Turing Shield",mfr:"turing-video",cat:"security",price:2500,year:2024,status:"active",desc:"AI-powered security monitoring robot that combines autonomous patrol with advanced video analytics. Detects weapons, aggressive behavior, and PPE compliance. Cloud-based Turing AI platform provides centralized management for multi-site deployments.",specs:{weight_kg:45,height_m:1.1,max_speed_ms:0.8,battery_life_hours:12,operating_temp:"0C to 45C",ip_rating:"IP54",connectivity:"WiFi 6, 5G, LoRaWAN",sensors:"4K cameras, thermal, weapon detection AI, audio analytics"},score:cs({performance:76,reliability:76,ease_of_use:80,intelligence:84,value:74,ecosystem:68,safety:84,design:76}),breakdown:{performance:76,reliability:76,ease_of_use:80,intelligence:84,value:74,ecosystem:68,safety:84,design:76}},
  {slug:"turing-turing-vision",name:"Turing Vision",mfr:"turing-video",cat:"security",price:1500,year:2023,status:"active",desc:"Stationary AI video analytics platform by Turing Video. Processes feeds from existing CCTV cameras to add intelligent threat detection. Identifies weapons, intrusions, loitering, and fire. Retrofits legacy camera systems with modern AI capabilities.",specs:{weight_kg:8,height_m:0.3,max_speed_ms:0,battery_life_hours:0,operating_temp:"0C to 50C",ip_rating:"IP40",connectivity:"Ethernet, WiFi, 4G",sensors:"AI vision processing unit, HDMI input for existing cameras"},score:cs({performance:74,reliability:80,ease_of_use:86,intelligence:82,value:82,ecosystem:70,safety:82,design:68}),breakdown:{performance:74,reliability:80,ease_of_use:86,intelligence:82,value:82,ecosystem:70,safety:82,design:68}},
  {slug:"rad-roameo",name:"RAD ROAMEO",mfr:"rad-robotics",cat:"security",price:5500,year:2024,status:"active",desc:"Fully autonomous outdoor patrol robot by Robotic Assistance Devices. All-weather operation with rugged construction. Navigates complex outdoor environments including parking structures and corporate campuses. Integrates with RAD's RADICLE AI analytics platform.",specs:{weight_kg:200,height_m:1.4,max_speed_ms:1.5,battery_life_hours:10,operating_temp:"-25C to 50C",ip_rating:"IP66",connectivity:"5G, WiFi 6, LoRa mesh",sensors:"PTZ cameras, thermal FLIR, LiDAR, ultrasonic, radar"},score:cs({performance:78,reliability:76,ease_of_use:76,intelligence:80,value:66,ecosystem:64,safety:82,design:74}),breakdown:{performance:78,reliability:76,ease_of_use:76,intelligence:80,value:66,ecosystem:64,safety:82,design:74}},
  {slug:"rad-ava",name:"RAD AVA",mfr:"rad-robotics",cat:"security",price:3000,year:2023,status:"active",desc:"AI-powered access control and visitor management solution by RAD. Handles visitor check-in, temperature screening, ID verification, and access badge issuance. Touchscreen interface with natural language AI concierge. Replaces lobby security staff.",specs:{weight_kg:90,height_m:1.5,max_speed_ms:0,battery_life_hours:24,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi, Ethernet, 4G",sensors:"HD camera, thermal, ID scanner, NFC reader, touchscreen"},score:cs({performance:72,reliability:78,ease_of_use:84,intelligence:76,value:76,ecosystem:64,safety:78,design:74}),breakdown:{performance:72,reliability:78,ease_of_use:84,intelligence:76,value:76,ecosystem:64,safety:78,design:74}},
  {slug:"rad-wally",name:"RAD WALLY",mfr:"rad-robotics",cat:"security",price:2000,year:2022,status:"active",desc:"Wall-mounted AI security sentry by RAD. Compact fixed unit that provides continuous video surveillance with AI analytics. Detects intrusions, loitering, and unauthorized access. Low-cost entry point for autonomous security monitoring.",specs:{weight_kg:12,height_m:0.4,max_speed_ms:0,battery_life_hours:0,operating_temp:"-20C to 50C",ip_rating:"IP65",connectivity:"WiFi, Ethernet, PoE",sensors:"4K camera, thermal, microphone, motion detector"},score:cs({performance:68,reliability:80,ease_of_use:88,intelligence:74,value:84,ecosystem:64,safety:78,design:68}),breakdown:{performance:68,reliability:80,ease_of_use:88,intelligence:74,value:84,ecosystem:64,safety:78,design:68}},
  {slug:"rad-rosa-3",name:"RAD ROSA 3.0",mfr:"rad-robotics",cat:"security",price:1800,year:2024,status:"active",desc:"Third-generation stationary AI security monitor by RAD. Pedestal-mounted unit with 360-degree camera coverage and advanced analytics. Detects weapons, fights, falls, and safety violations. RADICLE AI cloud platform for remote management.",specs:{weight_kg:35,height_m:1.0,max_speed_ms:0,battery_life_hours:0,operating_temp:"-10C to 45C",ip_rating:"IP55",connectivity:"WiFi 6, Ethernet, 4G",sensors:"360 camera array, thermal, AI analytics processor, speaker"},score:cs({performance:70,reliability:80,ease_of_use:86,intelligence:78,value:82,ecosystem:66,safety:80,design:70}),breakdown:{performance:70,reliability:80,ease_of_use:86,intelligence:78,value:82,ecosystem:66,safety:80,design:70}},
  {slug:"gamma2-vigilus",name:"Gamma 2 VIGILUS",mfr:"gamma2-robotics",cat:"security",price:4000,year:2023,status:"active",desc:"Autonomous perimeter patrol robot by Gamma 2 Robotics (now Integrated Defense). Designed for critical infrastructure protection including data centers, power plants, and government facilities. Military-grade sensors and encrypted communications.",specs:{weight_kg:160,height_m:1.3,max_speed_ms:1.5,battery_life_hours:8,operating_temp:"-30C to 55C",ip_rating:"IP67",connectivity:"Encrypted 4G/5G, mesh radio, WiFi",sensors:"Thermal FLIR, 4K PTZ, LiDAR, gunshot detection, chemical/bio"},score:cs({performance:80,reliability:78,ease_of_use:72,intelligence:82,value:68,ecosystem:60,safety:88,design:72}),breakdown:{performance:80,reliability:78,ease_of_use:72,intelligence:82,value:68,ecosystem:60,safety:88,design:72}},
  {slug:"spot-security",name:"Spot for Security (Boston Dynamics)",mfr:"boston-dynamics",cat:"security",price:120000,year:2024,status:"active",desc:"Boston Dynamics Spot configured as an autonomous security patrol platform. Quadruped locomotion handles stairs, rough terrain, and confined spaces. Thermal and visual cameras with AI anomaly detection. Autonomous route patrol with exception-based alerting.",specs:{weight_kg:32,height_m:0.84,max_speed_ms:1.6,battery_life_hours:1.5,operating_temp:"-20C to 45C",ip_rating:"IP54",connectivity:"WiFi 6, 4G LTE, Ethernet dock",sensors:"Spot CAM+, thermal FLIR, 360 cameras, LiDAR, audio"},score:cs({performance:88,reliability:86,ease_of_use:76,intelligence:86,value:56,ecosystem:85,safety:88,design:90}),breakdown:{performance:88,reliability:86,ease_of_use:76,intelligence:86,value:56,ecosystem:85,safety:88,design:90}},
  {slug:"ascento-guard",name:"Ascento Guard",mfr:"ascento",cat:"security",price:35000,year:2024,status:"active",desc:"Two-wheeled self-balancing security robot from Swiss startup Ascento. Navigates outdoor terrain including stairs, curbs, and uneven ground that defeat wheeled competitors. Autonomous perimeter patrol with HD and thermal cameras for 24/7 monitoring.",specs:{weight_kg:40,height_m:0.7,max_speed_ms:2.8,battery_life_hours:6,operating_temp:"-15C to 40C",ip_rating:"IP55",connectivity:"WiFi, 4G LTE",sensors:"HD stereo cameras, thermal, IMU, ultrasonic, GPS"},score:cs({performance:76,reliability:72,ease_of_use:76,intelligence:78,value:68,ecosystem:55,safety:80,design:84}),breakdown:{performance:76,reliability:72,ease_of_use:76,intelligence:78,value:68,ecosystem:55,safety:80,design:84}},
  {slug:"prosegur-hybrid",name:"Prosegur Hybrid Robot",mfr:"prosegur",cat:"security",price:45000,year:2024,status:"active",desc:"Corporate campus security robot developed by global security firm Prosegur. Combines autonomous patrol with remote human oversight. License plate recognition, facial detection, and behavioral analytics. Integrates with Prosegur's global security operations centers.",specs:{weight_kg:120,height_m:1.35,max_speed_ms:1.2,battery_life_hours:10,operating_temp:"-10C to 45C",ip_rating:"IP65",connectivity:"5G, WiFi 6, proprietary mesh",sensors:"4K PTZ, thermal, LPR, facial detection, lidar, microphone array"},score:cs({performance:78,reliability:80,ease_of_use:80,intelligence:82,value:64,ecosystem:72,safety:84,design:76}),breakdown:{performance:78,reliability:80,ease_of_use:80,intelligence:82,value:64,ecosystem:72,safety:84,design:76}},
  {slug:"smp-s5-2",name:"SMP Robotics S5.2",mfr:"smp-robotics",cat:"security",price:25000,year:2023,status:"active",desc:"Outdoor autonomous patrol robot by SMP Robotics. Rugged four-wheeled platform designed for perimeter security in all weather conditions. Pre-programmed patrol routes with deviation detection. Wide sensor array for comprehensive monitoring.",specs:{weight_kg:140,height_m:0.9,max_speed_ms:1.4,battery_life_hours:16,operating_temp:"-30C to 50C",ip_rating:"IP66",connectivity:"WiFi, 4G, GPS",sensors:"PTZ camera, thermal, ultrasonic, microphone, weather station"},score:cs({performance:74,reliability:78,ease_of_use:76,intelligence:74,value:72,ecosystem:58,safety:80,design:68}),breakdown:{performance:74,reliability:78,ease_of_use:76,intelligence:74,value:72,ecosystem:58,safety:80,design:68}},
  {slug:"otsaw-o-r3",name:"OTSAW O-R3",mfr:"otsaw",cat:"security",price:30000,year:2024,status:"active",desc:"Autonomous outdoor security robot from Singapore with a unique deployable surveillance drone. Patrols ground-level while deploying an aerial drone for elevated vantage points during incidents. 3D LiDAR SLAM navigation and facial recognition.",specs:{weight_kg:110,height_m:1.0,max_speed_ms:1.8,battery_life_hours:8,operating_temp:"0C to 45C",ip_rating:"IP65",connectivity:"5G, WiFi 6, Bluetooth",sensors:"360 cameras, facial recognition, 3D LiDAR, deployable drone"},score:cs({performance:80,reliability:74,ease_of_use:74,intelligence:84,value:66,ecosystem:60,safety:82,design:80}),breakdown:{performance:80,reliability:74,ease_of_use:74,intelligence:84,value:66,ecosystem:60,safety:82,design:80}},
  {slug:"enova-enova",name:"Enova Robotics",mfr:"enova-robotics",cat:"security",price:55000,year:2023,status:"active",desc:"Tunisian-made autonomous security robot designed for border patrol and critical infrastructure protection. Rugged construction for desert and harsh environments. Long-range thermal detection and integrated communication relay for remote area operations.",specs:{weight_kg:250,height_m:1.5,max_speed_ms:2.0,battery_life_hours:14,operating_temp:"-20C to 60C",ip_rating:"IP67",connectivity:"Satellite, 4G, mesh radio",sensors:"Long-range thermal, 4K PTZ, radar, LiDAR, chemical detector"},score:cs({performance:82,reliability:76,ease_of_use:68,intelligence:80,value:60,ecosystem:52,safety:86,design:70}),breakdown:{performance:82,reliability:76,ease_of_use:68,intelligence:80,value:60,ecosystem:52,safety:86,design:70}},
  {slug:"nightscope-ns50",name:"Nightscope NS50",mfr:"nightscope",cat:"security",price:22000,year:2024,status:"active",desc:"Compact perimeter security robot optimized for cost-effective outdoor patrol. Lightweight design with extended battery life for 24/7 operation with minimal charging downtime. AI-powered anomaly detection and automated incident reporting.",specs:{weight_kg:80,height_m:0.8,max_speed_ms:1.2,battery_life_hours:18,operating_temp:"-15C to 45C",ip_rating:"IP65",connectivity:"WiFi, 4G LTE",sensors:"HD cameras, thermal, ultrasonic, PIR motion, GPS"},score:cs({performance:72,reliability:76,ease_of_use:80,intelligence:74,value:78,ecosystem:56,safety:78,design:70}),breakdown:{performance:72,reliability:76,ease_of_use:80,intelligence:74,value:78,ecosystem:56,safety:78,design:70}},
  {slug:"pal-ari",name:"PAL Robotics ARI",mfr:"pal-robotics",cat:"security",price:45000,year:2023,status:"active",desc:"Social humanoid robot from PAL Robotics (Barcelona) adapted for security reception and visitor management. Handles check-in, badge printing, and wayfinding. Conversational AI provides natural interaction. Dual-use as security greeter and information concierge.",specs:{weight_kg:50,height_m:1.65,max_speed_ms:0.8,battery_life_hours:6,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, Bluetooth 5, Ethernet dock",sensors:"RGB-D cameras, lidar, microphone array, touchscreen, NFC"},score:cs({performance:72,reliability:76,ease_of_use:82,intelligence:80,value:62,ecosystem:68,safety:78,design:82}),breakdown:{performance:72,reliability:76,ease_of_use:82,intelligence:80,value:62,ecosystem:68,safety:78,design:82}},
  {slug:"promobot-v4-security",name:"Promobot V.4 Security",mfr:"promobot",cat:"security",price:35000,year:2023,status:"active",desc:"Russian-designed humanoid robot adapted for security check-in and visitor management. Face recognition, ID scanning, and conversational interaction. Deployed in government buildings and corporate lobbies. Handles first-line security screening.",specs:{weight_kg:65,height_m:1.5,max_speed_ms:0.5,battery_life_hours:8,operating_temp:"0C to 35C",ip_rating:"IP42",connectivity:"WiFi, 4G, Ethernet",sensors:"Face recognition cameras, ID scanner, microphone, touchscreen"},score:cs({performance:70,reliability:74,ease_of_use:78,intelligence:76,value:66,ecosystem:60,safety:76,design:76}),breakdown:{performance:70,reliability:74,ease_of_use:78,intelligence:76,value:66,ecosystem:60,safety:76,design:76}},
  {slug:"sg-robotics-s1",name:"SG Robotics S1",mfr:"sg-robotics",cat:"security",price:28000,year:2024,status:"active",desc:"Compact autonomous surveillance robot for indoor and semi-outdoor environments. Low-profile design navigates crowded spaces without disruption. AI video analytics with behavior recognition. Cloud-based fleet management for multi-site deployments.",specs:{weight_kg:45,height_m:0.6,max_speed_ms:1.0,battery_life_hours:12,operating_temp:"-5C to 40C",ip_rating:"IP54",connectivity:"WiFi 6, 5G, Bluetooth",sensors:"4K cameras, thermal, LiDAR, mmWave radar, microphone"},score:cs({performance:74,reliability:76,ease_of_use:80,intelligence:80,value:70,ecosystem:62,safety:80,design:76}),breakdown:{performance:74,reliability:76,ease_of_use:80,intelligence:80,value:70,ecosystem:62,safety:80,design:76}},
  {slug:"anybots-qb",name:"Anybots QB",mfr:"anybots",cat:"security",price:15000,year:2022,status:"active",desc:"Telepresence security robot enabling remote guard patrols. Operators control the robot remotely for virtual walkthroughs of facilities. Two-way audio and video communication. Cost-effective alternative to physical security guards for after-hours patrol.",specs:{weight_kg:15,height_m:1.5,max_speed_ms:1.0,battery_life_hours:6,operating_temp:"5C to 35C",ip_rating:"IP40",connectivity:"WiFi, 4G LTE",sensors:"HD camera, microphone, speaker, laser pointer, proximity"},score:cs({performance:64,reliability:70,ease_of_use:82,intelligence:68,value:74,ecosystem:54,safety:72,design:72}),breakdown:{performance:64,reliability:70,ease_of_use:82,intelligence:68,value:74,ecosystem:54,safety:72,design:72}},
  {slug:"husarion-patrol",name:"Husarion Patrol Bot",mfr:"husarion",cat:"security",price:18000,year:2023,status:"active",desc:"Open-source-friendly warehouse security robot built on Husarion's ROSbot platform. ROS 2 compatible for customization. Patrols warehouse aisles detecting intrusions, fire, and safety hazards. Fleet coordination via Husarion Cloud.",specs:{weight_kg:25,height_m:0.5,max_speed_ms:1.2,battery_life_hours:8,operating_temp:"0C to 40C",ip_rating:"IP44",connectivity:"WiFi, 4G, ROS 2 DDS",sensors:"LiDAR, depth cameras, thermal, smoke detector, IMU"},score:cs({performance:70,reliability:74,ease_of_use:76,intelligence:74,value:78,ecosystem:68,safety:78,design:68}),breakdown:{performance:70,reliability:74,ease_of_use:76,intelligence:74,value:78,ecosystem:68,safety:78,design:68}},

  // ═══ HOSPITALITY (25) ═══
  {slug:"bear-servi",name:"Bear Robotics Servi",mfr:"bear-robotics",cat:"hospitality",price:999,year:2023,status:"active",desc:"Restaurant food delivery robot by Bear Robotics. Multi-tray design carries food from kitchen to tables autonomously. 3D obstacle avoidance navigates busy dining rooms. Used in 5,000+ restaurants including Denny's and Chili's. Leased at $999/month.",specs:{weight_kg:36,height_m:1.1,max_speed_ms:0.8,battery_life_hours:12,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi",sensors:"3D cameras, LiDAR, ultrasonic, cliff sensors, encoders"},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:78,value:82,ecosystem:74,safety:82,design:78}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:78,value:82,ecosystem:74,safety:82,design:78}},
  {slug:"bear-servi-plus",name:"Bear Robotics Servi Plus",mfr:"bear-robotics",cat:"hospitality",price:1299,year:2024,status:"active",desc:"Premium food service robot with larger tray capacity and advanced navigation. Enhanced AI handles peak-hour congestion. Interactive touchscreen for menu display and customer interaction. Built-in advertising display for restaurant promotions.",specs:{weight_kg:42,height_m:1.2,max_speed_ms:1.0,battery_life_hours:14,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, Bluetooth",sensors:"3D cameras, LiDAR, ultrasonic, touchscreen, speakers"},score:cs({performance:82,reliability:82,ease_of_use:88,intelligence:82,value:78,ecosystem:76,safety:82,design:82}),breakdown:{performance:82,reliability:82,ease_of_use:88,intelligence:82,value:78,ecosystem:76,safety:82,design:82}},
  {slug:"bear-servi-mini",name:"Bear Robotics Servi Mini",mfr:"bear-robotics",cat:"hospitality",price:799,year:2024,status:"active",desc:"Compact food delivery robot designed for smaller restaurants and cafes. Narrow form factor navigates tight spaces between tables. Two-tray design optimized for drinks and small plates. Most affordable entry point in the Bear Robotics lineup.",specs:{weight_kg:28,height_m:0.9,max_speed_ms:0.7,battery_life_hours:10,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi",sensors:"2D LiDAR, depth cameras, ultrasonic, cliff sensors"},score:cs({performance:72,reliability:78,ease_of_use:88,intelligence:74,value:86,ecosystem:74,safety:80,design:76}),breakdown:{performance:72,reliability:78,ease_of_use:88,intelligence:74,value:86,ecosystem:74,safety:80,design:76}},
  {slug:"bear-carti",name:"Bear Robotics Carti",mfr:"bear-robotics",cat:"hospitality",price:1099,year:2024,status:"active",desc:"Cart-style delivery robot for larger food orders and catering environments. Open-shelf design accommodates trays, plates, and beverage containers. Suited for hotel banquets, cafeterias, and large dining halls. Seamless integration with Bear Robotics fleet.",specs:{weight_kg:48,height_m:1.0,max_speed_ms:0.8,battery_life_hours:12,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6",sensors:"3D cameras, LiDAR, ultrasonic, load sensors, cliff sensors"},score:cs({performance:76,reliability:80,ease_of_use:84,intelligence:76,value:78,ecosystem:76,safety:80,design:74}),breakdown:{performance:76,reliability:80,ease_of_use:84,intelligence:76,value:78,ecosystem:76,safety:80,design:74}},
  {slug:"savioke-relay",name:"Savioke Relay",mfr:"savioke",cat:"hospitality",price:2000,year:2022,status:"active",desc:"Hotel room delivery robot that autonomously navigates hallways and elevators to deliver amenities to guest rooms. Secure compartment for privacy. Integrates with hotel PMS and elevator systems. Pioneer in hotel robotics, deployed in 80+ hotels.",specs:{weight_kg:41,height_m:0.9,max_speed_ms:0.7,battery_life_hours:8,operating_temp:"10C to 30C",ip_rating:"IP40",connectivity:"WiFi, elevator API",sensors:"LiDAR, 3D depth cameras, bumper sensors, encoders"},score:cs({performance:74,reliability:78,ease_of_use:84,intelligence:76,value:68,ecosystem:70,safety:82,design:78}),breakdown:{performance:74,reliability:78,ease_of_use:84,intelligence:76,value:68,ecosystem:70,safety:82,design:78}},
  {slug:"savioke-relay-plus",name:"Savioke Relay+",mfr:"savioke",cat:"hospitality",price:2500,year:2023,status:"active",desc:"Upgraded hotel delivery robot with larger cargo bay and enhanced navigation. Faster elevator integration and multi-floor mapping. Improved guest interaction with touchscreen and voice. Used for room service, amenity delivery, and guest engagement.",specs:{weight_kg:45,height_m:0.95,max_speed_ms:0.9,battery_life_hours:10,operating_temp:"10C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, Bluetooth",sensors:"LiDAR, 3D cameras, touchscreen, speaker, ultrasonic"},score:cs({performance:78,reliability:80,ease_of_use:86,intelligence:78,value:66,ecosystem:72,safety:82,design:80}),breakdown:{performance:78,reliability:80,ease_of_use:86,intelligence:78,value:66,ecosystem:72,safety:82,design:80}},
  {slug:"maidbot-rosie",name:"Maidbot Rosie",mfr:"maidbot",cat:"hospitality",price:3500,year:2024,status:"active",desc:"Autonomous hotel floor cleaning robot. Vacuums and scrubs hotel hallways, lobbies, and common areas during off-peak hours. Learns facility layout and optimizes cleaning routes. Addresses labor shortages in hotel housekeeping departments.",specs:{weight_kg:55,height_m:0.7,max_speed_ms:0.5,battery_life_hours:4,operating_temp:"10C to 30C",ip_rating:"IP43",connectivity:"WiFi, Bluetooth",sensors:"LiDAR, cameras, cliff sensors, bumper, dirt detection"},score:cs({performance:74,reliability:76,ease_of_use:80,intelligence:76,value:68,ecosystem:60,safety:80,design:72}),breakdown:{performance:74,reliability:76,ease_of_use:80,intelligence:76,value:68,ecosystem:60,safety:80,design:72}},
  {slug:"maidbot-rosie-mini",name:"Maidbot Rosie Mini",mfr:"maidbot",cat:"hospitality",price:2500,year:2023,status:"active",desc:"Compact room-service and light-cleaning robot for hotels. Handles amenity delivery and quick room touch-ups between guests. Smaller form factor fits through standard doorways and tight corridors. Complements the full-size Rosie for comprehensive hotel robotics.",specs:{weight_kg:30,height_m:0.5,max_speed_ms:0.6,battery_life_hours:6,operating_temp:"10C to 30C",ip_rating:"IP42",connectivity:"WiFi",sensors:"LiDAR, depth camera, bumper, proximity sensors"},score:cs({performance:68,reliability:74,ease_of_use:82,intelligence:72,value:72,ecosystem:58,safety:78,design:72}),breakdown:{performance:68,reliability:74,ease_of_use:82,intelligence:72,value:72,ecosystem:58,safety:78,design:72}},
  {slug:"keenon-t5",name:"Keenon T5",mfr:"keenon-robotics",cat:"hospitality",price:15000,year:2023,status:"active",desc:"Restaurant delivery robot from Keenon with multi-layer tray system. Serves 3-4 tables per trip. Intelligent traffic management coordinates multiple robots in the same venue. Over 80,000 units deployed globally across 60+ countries.",specs:{weight_kg:38,height_m:1.15,max_speed_ms:0.8,battery_life_hours:12,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi, 4G optional",sensors:"3D cameras, LiDAR, ultrasonic, cliff, bumper"},score:cs({performance:78,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:78,safety:80,design:76}),breakdown:{performance:78,reliability:82,ease_of_use:84,intelligence:78,value:80,ecosystem:78,safety:80,design:76}},
  {slug:"keenon-t6",name:"Keenon T6",mfr:"keenon-robotics",cat:"hospitality",price:18000,year:2024,status:"active",desc:"Commercial-grade delivery robot for hotels, hospitals, and large venues. Enhanced payload capacity for heavier items. Built-in elevator integration for multi-floor operations. Advanced fleet management for coordinating 50+ robots per site.",specs:{weight_kg:48,height_m:1.2,max_speed_ms:1.0,battery_life_hours:14,operating_temp:"0C to 40C",ip_rating:"IP44",connectivity:"WiFi 6, 4G, Bluetooth",sensors:"3D cameras, LiDAR, ultrasonic, load cells, elevator API"},score:cs({performance:82,reliability:82,ease_of_use:84,intelligence:80,value:76,ecosystem:80,safety:82,design:78}),breakdown:{performance:82,reliability:82,ease_of_use:84,intelligence:80,value:76,ecosystem:80,safety:82,design:78}},
  {slug:"keenon-t8",name:"Keenon T8",mfr:"keenon-robotics",cat:"hospitality",price:22000,year:2024,status:"active",desc:"Premium hotel service robot with enclosed compartment for secure deliveries. UV-C sanitization of cargo bay between deliveries. Interactive display screen for guest wayfinding. Handles room service, minibar restocking, and laundry pickup scheduling.",specs:{weight_kg:55,height_m:1.3,max_speed_ms:0.9,battery_life_hours:12,operating_temp:"5C to 35C",ip_rating:"IP44",connectivity:"WiFi 6, 5G, Bluetooth 5",sensors:"3D cameras, LiDAR, UV-C module, touchscreen, NFC reader"},score:cs({performance:80,reliability:82,ease_of_use:82,intelligence:82,value:72,ecosystem:78,safety:84,design:82}),breakdown:{performance:80,reliability:82,ease_of_use:82,intelligence:82,value:72,ecosystem:78,safety:84,design:82}},
  {slug:"keenon-w3",name:"Keenon W3",mfr:"keenon-robotics",cat:"hospitality",price:12000,year:2023,status:"active",desc:"Specialized drink and beverage delivery robot by Keenon. Cup-holder design securely transports drinks without spills. Voice interaction greets guests and announces arrivals. Popular in bubble tea shops, cafes, and cocktail bars across Asia.",specs:{weight_kg:32,height_m:1.0,max_speed_ms:0.7,battery_life_hours:10,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi, Bluetooth",sensors:"2D LiDAR, depth cameras, ultrasonic, spill prevention gyro"},score:cs({performance:74,reliability:80,ease_of_use:86,intelligence:74,value:82,ecosystem:76,safety:80,design:80}),breakdown:{performance:74,reliability:80,ease_of_use:86,intelligence:74,value:82,ecosystem:76,safety:80,design:80}},
  {slug:"orionstar-lucki",name:"OrionStar Lucki",mfr:"orionstar",cat:"hospitality",price:25000,year:2023,status:"active",desc:"Hotel concierge and service robot by OrionStar (Cheetah Mobile subsidiary). Multi-language conversational AI for guest assistance. Handles check-in guidance, facility directions, and local recommendations. Large touchscreen with interactive hotel information.",specs:{weight_kg:52,height_m:1.4,max_speed_ms:0.8,battery_life_hours:8,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, 4G, Bluetooth",sensors:"RGB-D cameras, LiDAR, microphone array, touchscreen, speaker"},score:cs({performance:74,reliability:76,ease_of_use:82,intelligence:82,value:66,ecosystem:68,safety:78,design:80}),breakdown:{performance:74,reliability:76,ease_of_use:82,intelligence:82,value:66,ecosystem:68,safety:78,design:80}},
  {slug:"orionstar-mini",name:"OrionStar Mini",mfr:"orionstar",cat:"hospitality",price:12000,year:2024,status:"active",desc:"Compact cafe and restaurant service robot by OrionStar. Affordable entry point for small food service venues. Simple setup with app-based table mapping. Voice announcements in multiple languages for tourist-heavy locations.",specs:{weight_kg:28,height_m:0.9,max_speed_ms:0.7,battery_life_hours:10,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi, Bluetooth",sensors:"2D LiDAR, cameras, ultrasonic, cliff sensors"},score:cs({performance:70,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:66,safety:78,design:76}),breakdown:{performance:70,reliability:76,ease_of_use:86,intelligence:74,value:82,ecosystem:66,safety:78,design:76}},
  {slug:"pudu-bellabot",name:"Pudu BellaBot",mfr:"pudu-robotics",cat:"hospitality",price:16000,year:2023,status:"active",desc:"Cat-themed restaurant delivery robot beloved for its expressive display face. Four-tray capacity serves multiple tables per trip. Touch-responsive ears and playful animations engage diners. Deployed in 60+ countries with over 56,000 units sold worldwide.",specs:{weight_kg:36,height_m:1.1,max_speed_ms:0.8,battery_life_hours:10,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi, Bluetooth",sensors:"3D cameras, LiDAR, ultrasonic, touch-sensitive top, cliff sensors"},score:cs({performance:78,reliability:82,ease_of_use:88,intelligence:76,value:80,ecosystem:80,safety:80,design:88}),breakdown:{performance:78,reliability:82,ease_of_use:88,intelligence:76,value:80,ecosystem:80,safety:80,design:88}},
  {slug:"pudu-kettybot",name:"Pudu KettyBot",mfr:"pudu-robotics",cat:"hospitality",price:18000,year:2024,status:"active",desc:"Dual-function reception and delivery robot by Pudu. Large 18.5-inch display handles advertising, wayfinding, and menu presentation. Switches between greeter mode and food delivery mode. Voice interaction in 20+ languages for international venues.",specs:{weight_kg:42,height_m:1.2,max_speed_ms:0.9,battery_life_hours:12,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi 6, Bluetooth",sensors:"3D cameras, LiDAR, ultrasonic, 18.5-inch touchscreen"},score:cs({performance:80,reliability:82,ease_of_use:86,intelligence:80,value:76,ecosystem:80,safety:80,design:84}),breakdown:{performance:80,reliability:82,ease_of_use:86,intelligence:80,value:76,ecosystem:80,safety:80,design:84}},
  {slug:"pudu-holabot",name:"Pudu HolaBot",mfr:"pudu-robotics",cat:"hospitality",price:14000,year:2023,status:"active",desc:"Busser robot designed for dish collection and return. Enclosed compartment hides dirty dishes from guest view. Summoned via IoT button on tables for on-demand bussing. Reduces busser labor by 50% in high-volume restaurants.",specs:{weight_kg:40,height_m:1.05,max_speed_ms:0.8,battery_life_hours:10,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi, IoT button",sensors:"3D cameras, LiDAR, ultrasonic, IoT receiver, cliff sensors"},score:cs({performance:76,reliability:82,ease_of_use:86,intelligence:74,value:80,ecosystem:78,safety:80,design:76}),breakdown:{performance:76,reliability:82,ease_of_use:86,intelligence:74,value:80,ecosystem:78,safety:80,design:76}},
  {slug:"pudu-pudubot-2",name:"Pudu PuduBot 2",mfr:"pudu-robotics",cat:"hospitality",price:13000,year:2024,status:"active",desc:"Second-generation open-tray delivery robot optimized for high throughput. Faster navigation and improved multi-robot coordination. Budget-friendly option in Pudu's lineup. Ideal for casual dining, food courts, and canteens.",specs:{weight_kg:34,height_m:1.0,max_speed_ms:1.0,battery_life_hours:12,operating_temp:"0C to 40C",ip_rating:"IP42",connectivity:"WiFi",sensors:"2D LiDAR, depth cameras, ultrasonic, cliff, bumper"},score:cs({performance:76,reliability:80,ease_of_use:86,intelligence:74,value:84,ecosystem:78,safety:80,design:74}),breakdown:{performance:76,reliability:80,ease_of_use:86,intelligence:74,value:84,ecosystem:78,safety:80,design:74}},
  {slug:"richtech-adam",name:"Richtech Adam",mfr:"richtech-robotics",cat:"hospitality",price:60000,year:2024,status:"active",desc:"Dual-arm bartender robot that mixes and serves cocktails autonomously. Two 6-DOF arms handle bottles, shakers, and glasses with precision. Touchscreen ordering interface. Creates 100+ cocktail recipes. Deployed in Las Vegas hotels and cruise ships.",specs:{weight_kg:120,height_m:1.7,max_speed_ms:0,battery_life_hours:16,operating_temp:"10C to 30C",ip_rating:"IP44",connectivity:"WiFi 6, Ethernet",sensors:"3D cameras, force-torque sensors, liquid level, touchscreen"},score:cs({performance:82,reliability:76,ease_of_use:78,intelligence:84,value:56,ecosystem:62,safety:82,design:88}),breakdown:{performance:82,reliability:76,ease_of_use:78,intelligence:84,value:56,ecosystem:62,safety:82,design:88}},
  {slug:"richtech-matradee-l",name:"Richtech Matradee L",mfr:"richtech-robotics",cat:"hospitality",price:18000,year:2023,status:"active",desc:"Large-capacity food service robot by Richtech. Four open trays for maximum delivery volume. LED display for branding and promotions. Smart queuing coordinates with kitchen order management systems. Designed for high-volume dining operations.",specs:{weight_kg:44,height_m:1.15,max_speed_ms:0.8,battery_life_hours:12,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi, Bluetooth",sensors:"3D cameras, LiDAR, ultrasonic, LED display panel"},score:cs({performance:76,reliability:78,ease_of_use:84,intelligence:76,value:76,ecosystem:66,safety:80,design:76}),breakdown:{performance:76,reliability:78,ease_of_use:84,intelligence:76,value:76,ecosystem:66,safety:80,design:76}},
  {slug:"richtech-dust-e",name:"Richtech Dust-E",mfr:"richtech-robotics",cat:"hospitality",price:15000,year:2024,status:"active",desc:"Commercial floor cleaning robot for hospitality venues. Handles sweeping, vacuuming, and mopping in restaurants, hotels, and event spaces. Operates during off-hours with scheduled cleaning routes. Reduces janitorial labor costs by 40%.",specs:{weight_kg:55,height_m:0.65,max_speed_ms:0.5,battery_life_hours:5,operating_temp:"5C to 35C",ip_rating:"IP43",connectivity:"WiFi, Bluetooth",sensors:"LiDAR, cameras, cliff sensors, dirt detection, bumper"},score:cs({performance:74,reliability:76,ease_of_use:82,intelligence:74,value:76,ecosystem:64,safety:78,design:72}),breakdown:{performance:74,reliability:76,ease_of_use:82,intelligence:74,value:76,ecosystem:64,safety:78,design:72}},
  {slug:"temi-v3",name:"Temi V3",mfr:"temi",cat:"hospitality",price:2000,year:2023,status:"active",desc:"Personal assistant robot used in hotels and retail for guest interaction and wayfinding. Autonomous navigation with escort-to-destination feature. Video calling, information kiosk, and entertainment. Affordable platform for small hospitality businesses.",specs:{weight_kg:12,height_m:1.0,max_speed_ms:0.7,battery_life_hours:8,operating_temp:"5C to 35C",ip_rating:"IP40",connectivity:"WiFi, 4G optional, Bluetooth",sensors:"LiDAR, RGB-D camera, microphone array, 10-inch display"},score:cs({performance:68,reliability:74,ease_of_use:86,intelligence:74,value:86,ecosystem:68,safety:78,design:78}),breakdown:{performance:68,reliability:74,ease_of_use:86,intelligence:74,value:86,ecosystem:68,safety:78,design:78}},
  {slug:"botlr-hotel",name:"Botlr Hotel Robot",mfr:"savioke",cat:"hospitality",price:35000,year:2022,status:"active",desc:"Aloft Hotels' branded room service robot built on Savioke's Relay platform. Delivers toothbrushes, towels, snacks, and amenities to guest rooms. Named 'Botlr' as a robotic butler. Pioneered hotel robot adoption in the Marriott/Starwood family.",specs:{weight_kg:41,height_m:0.9,max_speed_ms:0.7,battery_life_hours:8,operating_temp:"10C to 30C",ip_rating:"IP40",connectivity:"WiFi, elevator API",sensors:"LiDAR, 3D cameras, bumper, proximity, phone notification"},score:cs({performance:72,reliability:78,ease_of_use:82,intelligence:74,value:62,ecosystem:70,safety:80,design:78}),breakdown:{performance:72,reliability:78,ease_of_use:82,intelligence:74,value:62,ecosystem:70,safety:80,design:78}},
  {slug:"lg-cloi-servebot",name:"LG CLOi ServeBot",mfr:"lg-electronics",cat:"hospitality",price:28000,year:2024,status:"active",desc:"Hotel and restaurant service robot by LG. Three-tier open tray design with spill-resistant surfaces. LG ThinQ AI integration for smart building connectivity. Smooth navigation in crowded environments. Multi-language voice announcements.",specs:{weight_kg:45,height_m:1.1,max_speed_ms:0.9,battery_life_hours:10,operating_temp:"5C to 35C",ip_rating:"IP42",connectivity:"WiFi 6, Bluetooth, LG ThinQ",sensors:"3D cameras, LiDAR, ultrasonic, microphone, display"},score:cs({performance:78,reliability:82,ease_of_use:84,intelligence:78,value:72,ecosystem:78,safety:82,design:80}),breakdown:{performance:78,reliability:82,ease_of_use:84,intelligence:78,value:72,ecosystem:78,safety:82,design:80}},
  {slug:"panasonic-hospi",name:"Panasonic HOSPI",mfr:"panasonic",cat:"hospitality",price:45000,year:2023,status:"active",desc:"Autonomous delivery robot by Panasonic for hospitals and hotels. Secure compartment with ID-authenticated access. Navigates complex multi-floor buildings via elevator integration. Originally developed for hospital pharmacy delivery, now expanded to hotel operations.",specs:{weight_kg:60,height_m:1.3,max_speed_ms:0.8,battery_life_hours:8,operating_temp:"10C to 30C",ip_rating:"IP42",connectivity:"WiFi, Ethernet dock, elevator API",sensors:"LiDAR, cameras, ultrasonic, ID authentication, bumper"},score:cs({performance:76,reliability:84,ease_of_use:80,intelligence:78,value:64,ecosystem:72,safety:86,design:74}),breakdown:{performance:76,reliability:84,ease_of_use:80,intelligence:78,value:64,ecosystem:72,safety:86,design:74}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 9 Import: 50 New Robots");
  console.log("  Categories: Security & Hospitality");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 9 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
