/**
 * Robotomated — Wave 15 Robot Import: 50 New Robots
 * Focus: AS/RS systems, shuttle systems, goods-to-person, vertical lift modules, sortation systems
 * Run: npx tsx scripts/import-robots-wave15.ts
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// RoboScore weights: performance 25%, reliability 20%, ease_of_use 15%,
// intelligence 15%, value 10%, ecosystem 8%, safety 5%, design 2%
function cs(b: Record<string, number>): number {
  return Math.round(
    (b.performance * 0.25 + b.reliability * 0.20 + b.ease_of_use * 0.15 +
     b.intelligence * 0.15 + b.value * 0.10 + b.ecosystem * 0.08 +
     b.safety * 0.05 + b.design * 0.02) * 10
  ) / 10;
}

// Placeholder images by category
const catImgs: Record<string, string[]> = {
  manufacturing: ["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&h=400&fit=crop"],
  warehouse: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=400&fit=crop"],
  consumer: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1563207153-f403bf289096?w=600&h=400&fit=crop"],
  medical: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=600&h=400&fit=crop"],
  construction: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&h=400&fit=crop"],
  agricultural: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&h=400&fit=crop"],
  delivery: ["https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=400&fit=crop"],
  drone: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=600&h=400&fit=crop"],
  software: ["https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop"],
};
const imgC: Record<string, number> = {};
function gi(cat: string): { url: string; alt: string }[] {
  const s = catImgs[cat] || catImgs.software;
  const i = imgC[cat] || 0; imgC[cat] = i + 1;
  return [{ url: s[i % s.length], alt: `${cat} robot` }];
}

interface R {
  slug: string; name: string; mfr: string; cat: string;
  price: number | null; year: number; status: string;
  desc: string; specs: Record<string, unknown>;
  score: number; breakdown: Record<string, number>;
}

// ── New manufacturers ──
const newMfrs = [
  { slug: "exotec", name: "Exotec", country: "FR", founded_year: 2015, website: "https://exotec.com" },
  { slug: "knapp", name: "KNAPP", country: "AT", founded_year: 1952, website: "https://knapp.com" },
  { slug: "ssi-schaefer", name: "SSI SCHAEFER", country: "DE", founded_year: 1937, website: "https://ssi-schaefer.com" },
  { slug: "tgw-logistics", name: "TGW Logistics", country: "AT", founded_year: 1969, website: "https://tgw-group.com" },
  { slug: "kardex", name: "Kardex", country: "CH", founded_year: 1898, website: "https://kardex.com" },
  { slug: "vanderlande", name: "Vanderlande", country: "NL", founded_year: 1949, website: "https://vanderlande.com" },
  { slug: "honeywell-robotics", name: "Honeywell Robotics", country: "US", founded_year: 1906, website: "https://honeywell.com" },
  { slug: "dematic", name: "Dematic", country: "US", founded_year: 1819, website: "https://dematic.com" },
];

// ═══════════════════════════════════════════════════════════════
// ROBOTS — 50 total (8 Exotec, 6 KNAPP, 6 SSI SCHAEFER, 6 TGW, 6 Kardex, 6 Vanderlande, 6 Honeywell, 6 Dematic)
// ═══════════════════════════════════════════════════════════════
const robots: R[] = [

// ═══ Exotec Robots (8) ═══
{slug:"exotec-skypod-standard",name:"Exotec Skypod System Standard",mfr:"exotec",cat:"warehouse",price:null,year:2024,status:"active",desc:"3D goods-to-person AS/RS where Skypod robots climb racking up to 12 m high, retrieve bins, and deliver them to pick stations. 5x storage density vs traditional shelving. Deployed at Uniqlo, Decathlon, and Carrefour. From $3M system.",specs:{type:"3D AS/RS shuttle",max_height_m:12,throughput_picks_per_hour:400,storage_positions:30000,robot_speed_m_s:4,climbing_speed_m_s:1.5,bin_payload_kg:30,system_price_min:3000000},score:cs({performance:88,reliability:84,ease_of_use:76,intelligence:84,value:72,ecosystem:80,safety:84,design:82}),breakdown:{performance:88,reliability:84,ease_of_use:76,intelligence:84,value:72,ecosystem:80,safety:84,design:82}},
{slug:"exotec-skypod-high-bay",name:"Exotec Skypod High Bay",mfr:"exotec",cat:"warehouse",price:null,year:2024,status:"active",desc:"Extended-height Skypod configuration reaching 24 m for maximum vertical density. Handles 50,000+ storage positions per aisle with sustained throughput of 450 picks/hr per station. Ideal for land-constrained urban DCs. From $5M system.",specs:{type:"High-bay 3D AS/RS",max_height_m:24,throughput_picks_per_hour:450,storage_positions:50000,robot_speed_m_s:4,climbing_speed_m_s:1.5,aisle_width_m:1.5,system_price_min:5000000},score:cs({performance:88,reliability:84,ease_of_use:74,intelligence:84,value:70,ecosystem:80,safety:86,design:80}),breakdown:{performance:88,reliability:84,ease_of_use:74,intelligence:84,value:70,ecosystem:80,safety:86,design:80}},
{slug:"exotec-skypod-compact",name:"Exotec Skypod Compact",mfr:"exotec",cat:"warehouse",price:null,year:2024,status:"active",desc:"Smaller-footprint Skypod system for mid-size DCs and brownfield retrofits. 8 m max height with 10,000 storage positions. Lower entry cost makes 3D AS/RS accessible to mid-market operators. From $1.5M system.",specs:{type:"Compact 3D AS/RS",max_height_m:8,throughput_picks_per_hour:300,storage_positions:10000,robot_speed_m_s:4,aisle_width_m:1.5,footprint:"Reduced for brownfield",system_price_min:1500000},score:cs({performance:82,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:78,safety:84,design:80}),breakdown:{performance:82,reliability:84,ease_of_use:78,intelligence:82,value:76,ecosystem:78,safety:84,design:80}},
{slug:"exotec-skypod-3d",name:"Exotec Skypod 3D Multi-Temp",mfr:"exotec",cat:"warehouse",price:null,year:2025,status:"active",desc:"Temperature-controlled Skypod variant operating in ambient, chilled (+2C), and frozen (-25C) zones within a single system. Robots transition seamlessly between temperature zones. Deployed in grocery and pharma cold chains. From $4M.",specs:{type:"Multi-temp 3D AS/RS",max_height_m:12,temperature_range:"-25C to ambient",zones:"Ambient, chilled, frozen",throughput_picks_per_hour:350,storage_positions:25000,application:"Grocery, pharma cold chain",system_price_min:4000000},score:cs({performance:86,reliability:82,ease_of_use:74,intelligence:84,value:70,ecosystem:78,safety:86,design:78}),breakdown:{performance:86,reliability:82,ease_of_use:74,intelligence:84,value:70,ecosystem:78,safety:86,design:78}},
{slug:"exotec-skypod-mini",name:"Exotec Skypod Mini",mfr:"exotec",cat:"warehouse",price:null,year:2025,status:"active",desc:"Entry-level Skypod system with 6 m max height and 5,000 storage positions. Designed for e-commerce startups and 3PL micro-fulfillment centers. Modular design allows expansion as volume grows. From $800K.",specs:{type:"Entry-level 3D AS/RS",max_height_m:6,throughput_picks_per_hour:200,storage_positions:5000,robot_speed_m_s:4,modular:"Expandable by module",application:"Micro-fulfillment, startups",system_price_min:800000},score:cs({performance:78,reliability:82,ease_of_use:80,intelligence:80,value:78,ecosystem:76,safety:84,design:78}),breakdown:{performance:78,reliability:82,ease_of_use:80,intelligence:80,value:78,ecosystem:76,safety:84,design:78}},
{slug:"exotec-skypod-robot-unit",name:"Exotec Skypod Robot Unit",mfr:"exotec",cat:"warehouse",price:65000,year:2024,status:"active",desc:"Individual Skypod robot for fleet expansion within existing systems. Each robot navigates 3D racking autonomously at 4 m/s horizontally and 1.5 m/s vertically. 30 kg bin payload with battery swap in under 60 seconds.",specs:{type:"3D AS/RS shuttle robot",speed_horizontal_m_s:4,speed_vertical_m_s:1.5,payload_kg:30,battery_swap_seconds:60,nav:"3D rail + onboard intelligence",dimensions:"600x400x300mm"},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:82,value:74,ecosystem:80,safety:84,design:82}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:82,value:74,ecosystem:80,safety:84,design:82}},
{slug:"exotec-skypod-high-throughput",name:"Exotec Skypod High Throughput",mfr:"exotec",cat:"warehouse",price:null,year:2025,status:"active",desc:"Performance-optimized Skypod configuration with dual-station output and 200+ robot fleet for peak throughput of 900 picks/hr per station. Built for Black Friday-scale e-commerce operations. From $6M.",specs:{type:"High-throughput 3D AS/RS",max_height_m:16,throughput_picks_per_hour:900,stations:2,fleet_size:200,storage_positions:40000,application:"Peak e-commerce fulfillment",system_price_min:6000000},score:cs({performance:88,reliability:82,ease_of_use:74,intelligence:86,value:68,ecosystem:80,safety:84,design:80}),breakdown:{performance:88,reliability:82,ease_of_use:74,intelligence:86,value:68,ecosystem:80,safety:84,design:80}},
{slug:"exotec-skypicker",name:"Exotec Skypicker Robotic Arm",mfr:"exotec",cat:"warehouse",price:180000,year:2025,status:"active",desc:"AI-powered robotic pick arm integrated with Skypod stations. Uses 3D vision and deep learning to pick 600 items/hr from presented bins. Handles 90% of typical e-commerce SKU profiles autonomously.",specs:{type:"Robotic pick arm",pick_rate_per_hour:600,accuracy_pct:99.2,vision:"3D depth + deep learning",sku_coverage:"90% e-commerce profiles",payload_kg:2,integration:"Skypod station mount"},score:cs({performance:84,reliability:80,ease_of_use:74,intelligence:88,value:72,ecosystem:78,safety:82,design:78}),breakdown:{performance:84,reliability:80,ease_of_use:74,intelligence:88,value:72,ecosystem:78,safety:82,design:78}},

// ═══ KNAPP Robots (6) ═══
{slug:"knapp-osr-shuttle-evo",name:"KNAPP OSR Shuttle Evo",mfr:"knapp",cat:"warehouse",price:null,year:2024,status:"active",desc:"High-performance shuttle AS/RS for totes and cartons. Single-level shuttles operate independently on each racking level with vertical lifts connecting levels. 1,000+ picks/hr per aisle at 99.99% availability. Deployed at Puma, Würth, and pharma leaders. From $2.5M.",specs:{type:"Shuttle AS/RS",throughput_picks_per_hour:1000,storage_positions:80000,height_m:20,aisle_width_m:0.9,accuracy_pct:99.99,payload_kg:50,system_price_min:2500000},score:cs({performance:88,reliability:88,ease_of_use:76,intelligence:82,value:74,ecosystem:84,safety:86,design:78}),breakdown:{performance:88,reliability:88,ease_of_use:76,intelligence:82,value:74,ecosystem:84,safety:86,design:78}},
{slug:"knapp-pick-it-easy-robot",name:"KNAPP Pick-it-Easy Robot",mfr:"knapp",cat:"warehouse",price:250000,year:2024,status:"active",desc:"AI-driven robotic piece-picking system using Covariant-trained neural networks. Picks 1,000 items/hr from heterogeneous totes with 99.5% accuracy. Handles deformable packaging, polybags, and blister packs that defeat traditional vision systems.",specs:{type:"Robotic piece picker",pick_rate_per_hour:1000,accuracy_pct:99.5,ai:"Covariant neural networks",payload_kg:2,items_handled:"Polybags, blisters, deformable",integration:"OSR Shuttle, conveyor"},score:cs({performance:86,reliability:82,ease_of_use:74,intelligence:88,value:72,ecosystem:82,safety:84,design:78}),breakdown:{performance:86,reliability:82,ease_of_use:74,intelligence:88,value:72,ecosystem:82,safety:84,design:78}},
{slug:"knapp-open-shuttle",name:"KNAPP Open Shuttle",mfr:"knapp",cat:"warehouse",price:55000,year:2024,status:"active",desc:"Flexible AMR that bridges fixed AS/RS infrastructure with dynamic floor transport. Carries totes between OSR Shuttle systems, workstations, and shipping areas. SLAM navigation with fleet coordination through KiSoft software.",specs:{type:"Infrastructure-bridging AMR",payload_kg:40,speed_m_s:2,nav:"SLAM",software:"KiSoft fleet management",integration:"OSR Shuttle compatible",battery_hrs:8,application:"AS/RS to workstation transport"},score:cs({performance:80,reliability:84,ease_of_use:80,intelligence:80,value:76,ecosystem:84,safety:84,design:76}),breakdown:{performance:80,reliability:84,ease_of_use:80,intelligence:80,value:76,ecosystem:84,safety:84,design:76}},
{slug:"knapp-open-shuttle-fork",name:"KNAPP Open Shuttle Fork",mfr:"knapp",cat:"warehouse",price:72000,year:2024,status:"active",desc:"Pallet-handling variant of Open Shuttle with integrated fork mechanism for loads up to 1000 kg. Connects pallet-level AS/RS with shipping docks and staging areas. Auto-docking at racking and conveyor interfaces.",specs:{type:"Pallet AMR with fork",payload_kg:1000,speed_m_s:1.5,lift_height_m:1.8,nav:"SLAM + safety LiDAR",docking:"Auto-dock racking and conveyor",software:"KiSoft coordination"},score:cs({performance:82,reliability:84,ease_of_use:76,intelligence:80,value:74,ecosystem:84,safety:84,design:74}),breakdown:{performance:82,reliability:84,ease_of_use:76,intelligence:80,value:74,ecosystem:84,safety:84,design:74}},
{slug:"knapp-knapp-store",name:"KNAPP-Store Automated Storage",mfr:"knapp",cat:"warehouse",price:null,year:2024,status:"active",desc:"Central-belt shuttle system for ultra-high-density storage of small parts and pharmaceuticals. Single robot serves entire aisle on central belt mechanism. 99.999% accuracy with integrated vision verification. From $1.8M.",specs:{type:"Central-belt shuttle AS/RS",throughput_picks_per_hour:500,storage_positions:100000,height_m:14,accuracy_pct:99.999,payload_kg:5,application:"Pharma, small parts",system_price_min:1800000},score:cs({performance:84,reliability:88,ease_of_use:72,intelligence:80,value:74,ecosystem:82,safety:86,design:74}),breakdown:{performance:84,reliability:88,ease_of_use:72,intelligence:80,value:74,ecosystem:82,safety:86,design:74}},
{slug:"knapp-osr-shuttle-evo-plus",name:"KNAPP OSR Shuttle Evo+",mfr:"knapp",cat:"warehouse",price:null,year:2025,status:"active",desc:"Next-generation OSR Shuttle with dual-tote handling per shuttle for 40% throughput increase. Enhanced energy recovery reduces power consumption by 25%. AI-predictive maintenance via KiSoft Analytics. From $3M.",specs:{type:"Next-gen shuttle AS/RS",throughput_picks_per_hour:1400,storage_positions:100000,height_m:22,totes_per_shuttle:2,energy_saving:"25% vs prior gen",software:"KiSoft Analytics predictive",system_price_min:3000000},score:cs({performance:88,reliability:86,ease_of_use:76,intelligence:84,value:72,ecosystem:84,safety:86,design:78}),breakdown:{performance:88,reliability:86,ease_of_use:76,intelligence:84,value:72,ecosystem:84,safety:86,design:78}},

// ═══ SSI SCHAEFER Robots (6) ═══
{slug:"ssi-cuby",name:"SSI SCHAEFER Cuby",mfr:"ssi-schaefer",cat:"warehouse",price:null,year:2024,status:"active",desc:"Cube storage AS/RS where shuttle robots operate on a 3D grid to retrieve bins from dense stacked storage. Robots traverse grid top and descend to extract bins. 40,000 positions in 300 sq m footprint. Deployed at Intersport and MediaMarkt. From $2M.",specs:{type:"Cube storage AS/RS",storage_positions:40000,footprint_sqm:300,height_m:8,throughput_picks_per_hour:350,payload_kg:35,grid:"3D traverse + vertical extraction",system_price_min:2000000},score:cs({performance:84,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:80,safety:84,design:78}),breakdown:{performance:84,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:80,safety:84,design:78}},
{slug:"ssi-navette",name:"SSI SCHAEFER Navette Shuttle",mfr:"ssi-schaefer",cat:"warehouse",price:null,year:2024,status:"active",desc:"Multi-level shuttle AS/RS with single-deep and double-deep storage configurations. Each shuttle handles 120 double cycles per hour per level. Supports totes, trays, and cartons up to 50 kg. Deployed in pharma and automotive. From $2.5M.",specs:{type:"Multi-level shuttle AS/RS",throughput_picks_per_hour:800,storage_positions:60000,height_m:18,aisle_width_m:0.85,double_cycles_per_hour:120,payload_kg:50,system_price_min:2500000},score:cs({performance:86,reliability:86,ease_of_use:74,intelligence:80,value:74,ecosystem:82,safety:86,design:76}),breakdown:{performance:86,reliability:86,ease_of_use:74,intelligence:80,value:74,ecosystem:82,safety:86,design:76}},
{slug:"ssi-piece-picking",name:"SSI SCHAEFER Piece Picking Robot",mfr:"ssi-schaefer",cat:"warehouse",price:220000,year:2024,status:"active",desc:"AI-powered robotic arm for automated piece picking from totes and cartons. Integrated with SSI Carrier and Navette systems for end-to-end automation. 800 picks/hr with 99.3% accuracy. Handles irregular shapes via 3D vision and adaptive grip.",specs:{type:"Robotic piece picker",pick_rate_per_hour:800,accuracy_pct:99.3,vision:"3D depth + AI classification",gripper:"Adaptive multi-mode",payload_kg:2.5,integration:"SSI Carrier, Navette"},score:cs({performance:84,reliability:82,ease_of_use:74,intelligence:86,value:74,ecosystem:82,safety:84,design:76}),breakdown:{performance:84,reliability:82,ease_of_use:74,intelligence:86,value:74,ecosystem:82,safety:84,design:76}},
{slug:"ssi-flat-pack-shuttle",name:"SSI SCHAEFER Flat Pack Shuttle",mfr:"ssi-schaefer",cat:"warehouse",price:null,year:2024,status:"active",desc:"Specialized shuttle system for flat-pack goods like furniture, flooring, and large-format items. Handles items up to 2.4 m long and 80 kg. Deep-lane storage with FIFO sequencing for outbound sortation. From $3M.",specs:{type:"Flat-pack shuttle AS/RS",item_length_max_m:2.4,payload_kg:80,storage_mode:"Deep-lane FIFO",throughput_picks_per_hour:200,height_m:12,application:"Furniture, flooring, large format",system_price_min:3000000},score:cs({performance:82,reliability:84,ease_of_use:72,intelligence:78,value:72,ecosystem:80,safety:84,design:74}),breakdown:{performance:82,reliability:84,ease_of_use:72,intelligence:78,value:72,ecosystem:80,safety:84,design:74}},
{slug:"ssi-flexi-shuttle",name:"SSI SCHAEFER Flexi Shuttle",mfr:"ssi-schaefer",cat:"warehouse",price:null,year:2025,status:"active",desc:"Flexible aisle-changing shuttle that transfers between racking aisles via cross-transfer cars. Reduces fleet size by 30% versus fixed-aisle shuttles while maintaining throughput. Ideal for facilities with variable demand across zones. From $2.2M.",specs:{type:"Aisle-changing shuttle AS/RS",throughput_picks_per_hour:600,storage_positions:45000,height_m:16,aisle_transfer:"Cross-transfer car",fleet_reduction:"30% vs fixed-aisle",payload_kg:50,system_price_min:2200000},score:cs({performance:84,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:80,safety:84,design:76}),breakdown:{performance:84,reliability:84,ease_of_use:76,intelligence:82,value:76,ecosystem:80,safety:84,design:76}},
{slug:"ssi-schaefer-carrier",name:"SSI SCHAEFER SSI Carrier",mfr:"ssi-schaefer",cat:"warehouse",price:null,year:2024,status:"active",desc:"Overhead carrier transport system using autonomous carriers on a rail network. Connects AS/RS, workstations, and shipping areas without floor-level traffic. 2,500 carriers handle 15,000 totes/hr across complex facility layouts. From $4M.",specs:{type:"Overhead carrier transport",items_per_hour:15000,carriers:2500,payload_kg:30,transport:"Overhead rail network",destinations:50,application:"Intra-facility tote transport",system_price_min:4000000},score:cs({performance:86,reliability:86,ease_of_use:72,intelligence:80,value:70,ecosystem:82,safety:86,design:76}),breakdown:{performance:86,reliability:86,ease_of_use:72,intelligence:80,value:70,ecosystem:82,safety:86,design:76}},

// ═══ TGW Logistics Robots (6) ═══
{slug:"tgw-rovolution",name:"TGW Rovolution Shuttle",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2024,status:"active",desc:"High-speed shuttle AS/RS with roaming shuttles that change levels via integrated lifts. Each shuttle handles 150 double cycles per hour. Deployed at Puma, EDEKA, and MediaMarkt for omnichannel fulfillment. From $2.5M.",specs:{type:"Roaming shuttle AS/RS",throughput_picks_per_hour:900,storage_positions:70000,height_m:20,double_cycles_per_hour:150,aisle_width_m:0.9,payload_kg:50,system_price_min:2500000},score:cs({performance:88,reliability:86,ease_of_use:76,intelligence:82,value:74,ecosystem:82,safety:86,design:78}),breakdown:{performance:88,reliability:86,ease_of_use:76,intelligence:82,value:74,ecosystem:82,safety:86,design:78}},
{slug:"tgw-flashpick",name:"TGW FlashPick Goods-to-Person",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Integrated goods-to-person system combining Rovolution shuttles with ergonomic pick stations. Presents source and target totes simultaneously for one-touch order fulfillment. 1,200 picks/hr per station with put-to-light guidance. From $3.5M.",specs:{type:"Goods-to-person system",throughput_picks_per_hour:1200,stations:"Ergonomic dual-tote",guidance:"Put-to-light",source:"Rovolution shuttle feed",accuracy_pct:99.9,application:"Omnichannel fulfillment",system_price_min:3500000},score:cs({performance:88,reliability:86,ease_of_use:82,intelligence:82,value:72,ecosystem:82,safety:84,design:80}),breakdown:{performance:88,reliability:86,ease_of_use:82,intelligence:82,value:72,ecosystem:82,safety:84,design:80}},
{slug:"tgw-pickcenter",name:"TGW PickCenter Robotic",mfr:"tgw-logistics",cat:"warehouse",price:280000,year:2025,status:"active",desc:"Robotic piece-picking station with AI-trained vision and multi-mode gripper for autonomous picking from shuttle-delivered totes. 700 picks/hr with 99.4% accuracy. Designed as drop-in upgrade for existing FlashPick installations.",specs:{type:"Robotic pick station",pick_rate_per_hour:700,accuracy_pct:99.4,vision:"AI-trained 3D",gripper:"Multi-mode adaptive",integration:"FlashPick drop-in",payload_kg:2},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:86,value:72,ecosystem:82,safety:84,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:86,value:72,ecosystem:82,safety:84,design:78}},
{slug:"tgw-stingray",name:"TGW Stingray Shuttle",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Pallet shuttle AS/RS for deep-lane storage up to 25 channels deep. Each Stingray handles pallets up to 1500 kg at heights to 40 m in high-bay configurations. FIFO and LIFO modes. Used in beverage and FMCG distribution. From $4M.",specs:{type:"Pallet shuttle AS/RS",payload_kg:1500,height_m:40,channels_deep:25,storage_mode:"FIFO/LIFO configurable",throughput_picks_per_hour:180,application:"Beverage, FMCG high-bay",system_price_min:4000000},score:cs({performance:86,reliability:86,ease_of_use:72,intelligence:78,value:74,ecosystem:82,safety:86,design:74}),breakdown:{performance:86,reliability:86,ease_of_use:72,intelligence:78,value:74,ecosystem:82,safety:86,design:74}},
{slug:"tgw-natrix",name:"TGW Natrix Sorter",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2024,status:"active",desc:"High-speed tilt-tray sortation system processing 12,000 items per hour across 200+ destinations. Integrated induction stations with vision-based singulation. Handles items from polybags to shoeboxes. From $1.8M.",specs:{type:"Tilt-tray sorter",items_per_hour:12000,destinations:200,accuracy_pct:99.8,induction:"Vision-based singulation",item_range:"Polybags to shoeboxes",payload_kg:5,system_price_min:1800000},score:cs({performance:86,reliability:84,ease_of_use:78,intelligence:78,value:76,ecosystem:82,safety:82,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:78,intelligence:78,value:76,ecosystem:82,safety:82,design:76}},
{slug:"tgw-rovolution-micro",name:"TGW Rovolution Micro",mfr:"tgw-logistics",cat:"warehouse",price:null,year:2025,status:"active",desc:"Compact Rovolution variant for micro-fulfillment centers and urban DCs. 6 m max height with 8,000 storage positions in under 200 sq m. Quick-deploy modular design installs in 8 weeks versus 6 months for standard systems. From $1.2M.",specs:{type:"Micro-fulfillment shuttle AS/RS",max_height_m:6,storage_positions:8000,footprint_sqm:200,throughput_picks_per_hour:400,install_weeks:8,modular:"Quick-deploy",system_price_min:1200000},score:cs({performance:80,reliability:84,ease_of_use:80,intelligence:80,value:78,ecosystem:80,safety:84,design:78}),breakdown:{performance:80,reliability:84,ease_of_use:80,intelligence:80,value:78,ecosystem:80,safety:84,design:78}},

// ═══ Kardex Robots (6) ═══
{slug:"kardex-shuttle-xp-500",name:"Kardex Shuttle XP 500",mfr:"kardex",cat:"warehouse",price:120000,year:2024,status:"active",desc:"Vertical Lift Module (VLM) with 500 kg tray capacity delivering stored items to an ergonomic access opening. Up to 16 m tall with 90+ trays per unit. Dynamic tray height adjustment maximizes vertical density. Deployed across 100,000+ units globally.",specs:{type:"Vertical Lift Module",height_m:16,tray_capacity_kg:500,trays_per_unit:90,access:"Ergonomic pick opening",density:"Dynamic tray height",deployments:"100,000+ globally"},score:cs({performance:82,reliability:86,ease_of_use:84,intelligence:76,value:80,ecosystem:82,safety:86,design:78}),breakdown:{performance:82,reliability:86,ease_of_use:84,intelligence:76,value:80,ecosystem:82,safety:86,design:78}},
{slug:"kardex-shuttle-xp-1000",name:"Kardex Shuttle XP 1000",mfr:"kardex",cat:"warehouse",price:165000,year:2024,status:"active",desc:"Heavy-duty VLM with 1000 kg tray capacity for industrial parts and tooling storage. Dual-tray delivery for simultaneous put and pick operations. Integrated pick-to-light for operator guidance. 14 m max height.",specs:{type:"Heavy-duty VLM",height_m:14,tray_capacity_kg:1000,delivery:"Dual-tray simultaneous",guidance:"Pick-to-light integrated",application:"Industrial parts, tooling"},score:cs({performance:84,reliability:86,ease_of_use:82,intelligence:76,value:78,ecosystem:82,safety:86,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:82,intelligence:76,value:78,ecosystem:82,safety:86,design:76}},
{slug:"kardex-remstar-lm",name:"Kardex Remstar LR 35",mfr:"kardex",cat:"warehouse",price:95000,year:2024,status:"active",desc:"Vertical carousel storage system with rotating shelves that deliver items to a pick window. 35 kg per carrier with rapid rotation for high-frequency small-parts picking. 350 picks/hr per unit. Compact footprint.",specs:{type:"Vertical carousel",payload_per_carrier_kg:35,throughput_picks_per_hour:350,rotation:"Bi-directional shortest path",access:"Fixed pick window",footprint:"Compact single-column",application:"Small parts, pharma"},score:cs({performance:78,reliability:86,ease_of_use:84,intelligence:72,value:82,ecosystem:80,safety:86,design:76}),breakdown:{performance:78,reliability:86,ease_of_use:84,intelligence:72,value:82,ecosystem:80,safety:86,design:76}},
{slug:"kardex-autostore-port",name:"Kardex FulfillX AutoStore Port",mfr:"kardex",cat:"warehouse",price:null,year:2024,status:"active",desc:"Kardex-integrated AutoStore port workstation optimized for ergonomic order fulfillment. Presents bins at tilt angle with integrated scales and vision verification. 450 picks/hr with put-to-light. Part of Kardex FulfillX AutoStore partnership. From $2M system.",specs:{type:"AutoStore-compatible workstation",throughput_picks_per_hour:450,verification:"Vision + weight check",guidance:"Put-to-light tilt presentation",integration:"AutoStore grid",ergonomic:"Tilted bin presentation",system_price_min:2000000},score:cs({performance:82,reliability:84,ease_of_use:86,intelligence:78,value:74,ecosystem:82,safety:84,design:80}),breakdown:{performance:82,reliability:84,ease_of_use:86,intelligence:78,value:74,ecosystem:82,safety:84,design:80}},
{slug:"kardex-shuttle-xp-twin",name:"Kardex Shuttle XP Twin",mfr:"kardex",cat:"warehouse",price:210000,year:2025,status:"active",desc:"Dual-column VLM with two independent extractors operating simultaneously. Doubles throughput versus single-extractor models at 600+ picks/hr. Ideal for high-volume kitting and assembly line feeding.",specs:{type:"Dual-column VLM",extractors:2,throughput_picks_per_hour:600,height_m:14,tray_capacity_kg:500,application:"High-volume kitting, assembly",improvement:"2x throughput vs single"},score:cs({performance:86,reliability:84,ease_of_use:82,intelligence:78,value:74,ecosystem:82,safety:86,design:78}),breakdown:{performance:86,reliability:84,ease_of_use:82,intelligence:78,value:74,ecosystem:82,safety:86,design:78}},
{slug:"kardex-power-pick-global",name:"Kardex Power Pick Global WMS",mfr:"kardex",cat:"warehouse",price:50000,year:2024,status:"active",desc:"Warehouse management software for coordinating fleets of VLMs, carousels, and AutoStore systems. Manages inventory across mixed storage technologies with batch optimization and wave planning. Licenses from $50K.",specs:{type:"WMS software platform",manages:"VLMs, carousels, AutoStore",features:"Batch optimization, wave planning",inventory:"Real-time across mixed storage",integration:"SAP, Oracle, Manhattan",api:"REST + WebSocket",license_from:50000},score:cs({performance:80,reliability:84,ease_of_use:80,intelligence:82,value:78,ecosystem:84,safety:80,design:74}),breakdown:{performance:80,reliability:84,ease_of_use:80,intelligence:82,value:78,ecosystem:84,safety:80,design:74}},

// ═══ Vanderlande Robots (6) ═══
{slug:"vanderlande-adapto",name:"Vanderlande ADAPTO Shuttle",mfr:"vanderlande",cat:"warehouse",price:null,year:2024,status:"active",desc:"3D shuttle AS/RS where robots navigate freely across a multi-level grid to store and retrieve totes. Unlike rail-bound shuttles, ADAPTO robots share space and self-organize for optimal throughput. Deployed at Zalando and Action. From $3M.",specs:{type:"3D grid shuttle AS/RS",throughput_picks_per_hour:500,storage_positions:50000,height_m:12,movement:"Free-roaming 3D grid",payload_kg:35,self_organizing:true,system_price_min:3000000},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:84,value:72,ecosystem:80,safety:84,design:80}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:84,value:72,ecosystem:80,safety:84,design:80}},
{slug:"vanderlande-pouch-system",name:"Vanderlande POUCH Sorting System",mfr:"vanderlande",cat:"warehouse",price:null,year:2024,status:"active",desc:"Overhead pouch sortation system where individual items travel in hanging pouches on a track network. 15,000 items/hr with 300+ sort destinations. Ideal for fashion and apparel returns processing. Deployed at Zalando and ASOS. From $2.5M.",specs:{type:"Overhead pouch sorter",items_per_hour:15000,destinations:300,accuracy_pct:99.9,transport:"Overhead hanging pouches",application:"Fashion, apparel, returns",partners:"Zalando, ASOS",system_price_min:2500000},score:cs({performance:86,reliability:84,ease_of_use:78,intelligence:80,value:74,ecosystem:80,safety:84,design:78}),breakdown:{performance:86,reliability:84,ease_of_use:78,intelligence:80,value:74,ecosystem:80,safety:84,design:78}},
{slug:"vanderlande-bagflow",name:"Vanderlande BAGFLOW",mfr:"vanderlande",cat:"warehouse",price:null,year:2024,status:"active",desc:"Airport baggage handling system with tote-based individual bag tracking. Handles 5,000 bags/hr per line with 99.5% sortation accuracy and full chain-of-custody tracking. Deployed at Schiphol, Dubai, and Singapore Changi. From $10M.",specs:{type:"Airport baggage handling",items_per_hour:5000,accuracy_pct:99.5,tracking:"Individual tote-based",destinations:200,application:"Airport baggage sortation",system_price_min:10000000},score:cs({performance:86,reliability:88,ease_of_use:72,intelligence:80,value:68,ecosystem:82,safety:88,design:76}),breakdown:{performance:86,reliability:88,ease_of_use:72,intelligence:80,value:68,ecosystem:82,safety:88,design:76}},
{slug:"vanderlande-fleet",name:"Vanderlande FLEET AMR",mfr:"vanderlande",cat:"warehouse",price:58000,year:2024,status:"active",desc:"Warehouse transport AMR bridging ADAPTO shuttle systems with workstations and shipping areas. Carries totes at 2.5 m/s with predictive fleet coordination. Integrates seamlessly with Vanderlande conveyor and sortation infrastructure.",specs:{type:"Infrastructure-bridging AMR",payload_kg:40,speed_m_s:2.5,nav:"SLAM + fleet coordination",integration:"ADAPTO, conveyor, sortation",battery_hrs:10,application:"AS/RS to workstation"},score:cs({performance:82,reliability:84,ease_of_use:78,intelligence:82,value:74,ecosystem:82,safety:84,design:78}),breakdown:{performance:82,reliability:84,ease_of_use:78,intelligence:82,value:74,ecosystem:82,safety:84,design:78}},
{slug:"vanderlande-evosort",name:"Vanderlande EVOSORT",mfr:"vanderlande",cat:"warehouse",price:null,year:2024,status:"active",desc:"Cross-belt sortation system for parcel and e-commerce distribution. 20,000 items/hr with 400 destinations. Handles parcels from 50g to 35 kg. Modular design allows reconfiguration as sort profiles change. From $3M.",specs:{type:"Cross-belt sorter",items_per_hour:20000,destinations:400,accuracy_pct:99.7,weight_range:"50g to 35kg",modular:"Reconfigurable destinations",application:"Parcel, e-commerce distribution",system_price_min:3000000},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:78,value:74,ecosystem:80,safety:84,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:78,value:74,ecosystem:80,safety:84,design:76}},
{slug:"vanderlande-smartsort",name:"Vanderlande SMARTSORT",mfr:"vanderlande",cat:"warehouse",price:null,year:2025,status:"active",desc:"AI-optimized tray sortation with dynamic destination allocation. Machine learning predicts sort patterns and pre-positions trays for 30% faster cycle times. 10,000 items/hr with vision-based induction. From $2M.",specs:{type:"AI tray sorter",items_per_hour:10000,destinations:150,accuracy_pct:99.8,ai:"ML destination prediction",improvement:"30% faster cycles",induction:"Vision-based auto",system_price_min:2000000},score:cs({performance:84,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:80,safety:82,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:80,safety:82,design:78}},

// ═══ Honeywell Robotics (6) ═══
{slug:"honeywell-intelligrated-as-rs",name:"Honeywell Intelligrated AS/RS",mfr:"honeywell-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Mini-load AS/RS for totes and cases with crane-based retrieval up to 20 m. Dual-mast cranes handle 300+ double cycles per hour per aisle. Deployed across Honeywell's installed base of 2,000+ DC projects. From $3M.",specs:{type:"Mini-load crane AS/RS",throughput_picks_per_hour:600,storage_positions:60000,height_m:20,double_cycles_per_hour:300,aisle_width_m:1.2,payload_kg:50,system_price_min:3000000},score:cs({performance:84,reliability:86,ease_of_use:74,intelligence:78,value:74,ecosystem:84,safety:86,design:74}),breakdown:{performance:84,reliability:86,ease_of_use:74,intelligence:78,value:74,ecosystem:84,safety:86,design:74}},
{slug:"honeywell-robotic-sortation",name:"Honeywell Robotic Sortation",mfr:"honeywell-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Robotic sortation wall system where AI-coordinated arms sort items into 200+ put locations at 1,500 items/hr per station. Vision system handles mixed SKUs without pre-scanning. Retrofit-friendly for existing DC layouts. From $800K per station.",specs:{type:"Robotic sortation wall",items_per_hour:1500,destinations:200,accuracy_pct:99.5,vision:"AI mixed-SKU recognition",installation:"Retrofit-friendly",station_price:800000},score:cs({performance:82,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:82,safety:82,design:76}),breakdown:{performance:82,reliability:82,ease_of_use:78,intelligence:84,value:76,ecosystem:82,safety:82,design:76}},
{slug:"honeywell-robotic-depalletizer",name:"Honeywell Smart Flexible Depalletizer",mfr:"honeywell-robotics",cat:"warehouse",price:350000,year:2024,status:"active",desc:"AI-powered robotic depalletizer handling mixed-SKU pallets without pre-programming. 3D vision identifies and plans pick sequences for 1,200 cases/hr. Handles 95% of retail case configurations including shrink-wrapped multi-packs.",specs:{type:"Robotic depalletizer",pick_rate_per_hour:1200,accuracy_pct:99.2,vision:"3D pallet mapping + AI",sku_handling:"Mixed without pre-programming",case_coverage:"95% retail configs",payload_kg:30},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:86,value:74,ecosystem:82,safety:84,design:74}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:86,value:74,ecosystem:82,safety:84,design:74}},
{slug:"honeywell-robotic-palletizer",name:"Honeywell Robotic Palletizer",mfr:"honeywell-robotics",cat:"warehouse",price:300000,year:2024,status:"active",desc:"High-speed robotic palletizer building mixed-SKU pallets optimized for truck loading density. AI pallet planning maximizes cube utilization at 800 cases/hr. Supports 50+ case dimensions simultaneously.",specs:{type:"Robotic palletizer",pick_rate_per_hour:800,accuracy_pct:99.5,ai:"Pallet plan optimization",cube_utilization:"AI-maximized",case_dimensions:"50+ simultaneous",payload_kg:25},score:cs({performance:82,reliability:82,ease_of_use:76,intelligence:84,value:76,ecosystem:82,safety:84,design:74}),breakdown:{performance:82,reliability:82,ease_of_use:76,intelligence:84,value:76,ecosystem:82,safety:84,design:74}},
{slug:"honeywell-universal-sorter",name:"Honeywell Universal Sorter",mfr:"honeywell-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"Modular cross-belt sortation system handling items from small polybags to 35 kg parcels. 18,000 items/hr with 350 destinations. Quick-change carrier design enables maintenance without line shutdown. From $2.5M.",specs:{type:"Cross-belt sorter",items_per_hour:18000,destinations:350,accuracy_pct:99.6,weight_range:"Polybags to 35kg",maintenance:"Quick-change carriers",modular:"Configurable loop",system_price_min:2500000},score:cs({performance:86,reliability:84,ease_of_use:78,intelligence:78,value:74,ecosystem:82,safety:84,design:76}),breakdown:{performance:86,reliability:84,ease_of_use:78,intelligence:78,value:74,ecosystem:82,safety:84,design:76}},
{slug:"honeywell-transnorm-sorter",name:"Honeywell Transnorm Shoe Sorter",mfr:"honeywell-robotics",cat:"warehouse",price:null,year:2024,status:"active",desc:"High-speed sliding shoe sorter for flat and polybag items at 15,000 items/hr. Ultra-gentle handling for fragile goods. 250 destinations with bi-directional divert. Industry workhorse for fashion and media distribution. From $1.8M.",specs:{type:"Sliding shoe sorter",items_per_hour:15000,destinations:250,accuracy_pct:99.7,handling:"Ultra-gentle",divert:"Bi-directional",application:"Fashion, media, fragile goods",system_price_min:1800000},score:cs({performance:84,reliability:86,ease_of_use:78,intelligence:76,value:76,ecosystem:82,safety:84,design:76}),breakdown:{performance:84,reliability:86,ease_of_use:78,intelligence:76,value:76,ecosystem:82,safety:84,design:76}},

// ═══ Dematic Robots (6) ═══
{slug:"dematic-multishuttle",name:"Dematic Multishuttle",mfr:"dematic",cat:"warehouse",price:null,year:2024,status:"active",desc:"Industry-leading shuttle AS/RS with level-changing shuttles via integrated lifts. Handles 120,000+ storage positions per system with 1,000+ double cycles/hr. Powers fulfillment for Zalando, Nike, and 50+ Fortune 500 companies. From $3M.",specs:{type:"Shuttle AS/RS",throughput_picks_per_hour:1000,storage_positions:120000,height_m:24,double_cycles_per_hour:1000,aisle_width_m:0.8,payload_kg:50,system_price_min:3000000},score:cs({performance:88,reliability:88,ease_of_use:76,intelligence:82,value:72,ecosystem:86,safety:86,design:78}),breakdown:{performance:88,reliability:88,ease_of_use:76,intelligence:82,value:72,ecosystem:86,safety:86,design:78}},
{slug:"dematic-rapidpick",name:"Dematic RapidPick Goods-to-Person",mfr:"dematic",cat:"warehouse",price:null,year:2024,status:"active",desc:"Goods-to-person system integrating Multishuttle with ergonomic pick-and-pack stations. Presents source and target containers with zone-pick optimization. 800 picks/hr per operator with 99.9% accuracy and put-to-light guidance. From $4M.",specs:{type:"Goods-to-person system",throughput_picks_per_hour:800,accuracy_pct:99.9,guidance:"Put-to-light zone-pick",source:"Multishuttle feed",stations:"Ergonomic pick-and-pack",application:"E-commerce fulfillment",system_price_min:4000000},score:cs({performance:86,reliability:86,ease_of_use:82,intelligence:82,value:72,ecosystem:86,safety:84,design:78}),breakdown:{performance:86,reliability:86,ease_of_use:82,intelligence:82,value:72,ecosystem:86,safety:84,design:78}},
{slug:"dematic-easypick",name:"Dematic EasyPick Robotic",mfr:"dematic",cat:"warehouse",price:260000,year:2025,status:"active",desc:"AI robotic picking station for autonomous piece picking from Multishuttle-delivered totes. 650 picks/hr with 99.3% accuracy. Handles 85% of typical e-commerce SKU mix including deformable items and polybags.",specs:{type:"Robotic piece picker",pick_rate_per_hour:650,accuracy_pct:99.3,vision:"3D AI classification",gripper:"Multi-mode suction + finger",sku_coverage:"85% e-commerce mix",integration:"Multishuttle compatible"},score:cs({performance:84,reliability:82,ease_of_use:76,intelligence:86,value:72,ecosystem:84,safety:84,design:78}),breakdown:{performance:84,reliability:82,ease_of_use:76,intelligence:86,value:72,ecosystem:84,safety:84,design:78}},
{slug:"dematic-amr-piece-picking",name:"Dematic Goods-to-Robot",mfr:"dematic",cat:"warehouse",price:null,year:2025,status:"active",desc:"Fully automated goods-to-robot solution combining Multishuttle, AMR transport, and robotic pick arms for lights-out fulfillment. End-to-end automation from storage to shipping with 500 orders/hr. From $8M.",specs:{type:"Lights-out fulfillment system",orders_per_hour:500,automation:"End-to-end storage to ship",components:"Multishuttle + AMR + pick arms",pick_rate_per_hour:600,accuracy_pct:99.5,application:"Lights-out fulfillment",system_price_min:8000000},score:cs({performance:86,reliability:82,ease_of_use:70,intelligence:88,value:68,ecosystem:84,safety:84,design:78}),breakdown:{performance:86,reliability:82,ease_of_use:70,intelligence:88,value:68,ecosystem:84,safety:84,design:78}},
{slug:"dematic-pocket-sorter",name:"Dematic Pocket Sorter",mfr:"dematic",cat:"warehouse",price:null,year:2024,status:"active",desc:"Overhead pocket sortation for fashion and apparel with 20,000 items/hr. Individual items travel in hanging pockets on rail network with 500+ destinations. Automatic pocket loading and unloading at workstations. From $3.5M.",specs:{type:"Overhead pocket sorter",items_per_hour:20000,destinations:500,accuracy_pct:99.8,transport:"Overhead hanging pockets",loading:"Automatic at stations",application:"Fashion, apparel, returns",system_price_min:3500000},score:cs({performance:86,reliability:84,ease_of_use:76,intelligence:80,value:72,ecosystem:84,safety:84,design:78}),breakdown:{performance:86,reliability:84,ease_of_use:76,intelligence:80,value:72,ecosystem:84,safety:84,design:78}},
{slug:"dematic-colby-pallet-asrs",name:"Dematic Colby Pallet AS/RS",mfr:"dematic",cat:"warehouse",price:null,year:2024,status:"active",desc:"Full-pallet crane AS/RS for high-bay warehouses up to 45 m. SRM cranes handle 1500 kg pallets with 200 double cycles/hr per aisle. Powers food, beverage, and CPG distribution for Costco, Woolworths, and 3PL operators. From $5M.",specs:{type:"Pallet crane AS/RS",payload_kg:1500,height_m:45,double_cycles_per_hour:200,aisle_width_m:1.5,storage_positions:40000,application:"Food, beverage, CPG high-bay",system_price_min:5000000},score:cs({performance:86,reliability:88,ease_of_use:72,intelligence:78,value:72,ecosystem:86,safety:88,design:74}),breakdown:{performance:86,reliability:88,ease_of_use:72,intelligence:78,value:72,ecosystem:86,safety:88,design:74}},
];

// ═══════════════════════════════════════════════════════════════
// MAIN IMPORT
// ═══════════════════════════════════════════════════════════════
async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log("  Robotomated — Wave 15 Import: 50 New Robots");
  console.log("═══════════════════════════════════════════════════\n");

  // 1. Load categories
  const { data: cats } = await supabase.from("robot_categories").select("id, slug");
  const catMap = new Map<string, string>();
  for (const c of cats || []) catMap.set(c.slug, c.id);
  console.log(`[DIR] Categories: ${catMap.size}\n`);

  // 2. Load + create manufacturers
  const { data: existingMfrs } = await supabase.from("manufacturers").select("id, slug");
  const mfrMap = new Map<string, string>();
  for (const m of existingMfrs || []) mfrMap.set(m.slug, m.id);

  let mfrsCreated = 0;
  for (const mfr of newMfrs) {
    if (mfrMap.has(mfr.slug)) continue;
    const { data, error } = await supabase.from("manufacturers").insert({
      slug: mfr.slug, name: mfr.name, country: mfr.country,
      founded_year: mfr.founded_year, website: mfr.website, verified: true,
    }).select("id").single();
    if (error) { console.error(`  [ERR] Mfr ${mfr.slug}: ${error.message}`); continue; }
    mfrMap.set(mfr.slug, data!.id);
    mfrsCreated++;
  }
  console.log(`[MFR] Manufacturers: ${mfrsCreated} new, ${mfrMap.size} total\n`);

  // 3. Insert robots
  let inserted = 0, skipped = 0, errored = 0;
  for (const r of robots) {
    const { data: existing } = await supabase.from("robots").select("id").eq("slug", r.slug).single();
    if (existing) { skipped++; continue; }

    const mfrId = mfrMap.get(r.mfr);
    const catId = catMap.get(r.cat);
    if (!mfrId) { console.error(`  [ERR] ${r.slug}: mfr "${r.mfr}" not found`); errored++; continue; }
    if (!catId) { console.error(`  [ERR] ${r.slug}: cat "${r.cat}" not found`); errored++; continue; }

    const { error } = await supabase.from("robots").insert({
      slug: r.slug, name: r.name, manufacturer_id: mfrId, category_id: catId,
      price_msrp: r.price, price_current: r.price, year_released: r.year,
      status: r.status as "active" | "discontinued" | "coming_soon",
      description_short: r.desc, specs: r.specs, images: gi(r.cat),
      robo_score: r.score > 0 ? r.score : null,
      score_breakdown: r.score > 0 ? r.breakdown : null,
      affiliate_url: null,
    });

    if (error) { console.error(`  [ERR] ${r.slug}: ${error.message}`); errored++; }
    else {
      inserted++;
      if (inserted % 10 === 0) process.stdout.write(`  ${inserted} inserted...\n`);
    }
  }

  // Get final count
  const { count } = await supabase.from("robots").select("*", { count: "exact", head: true });

  console.log(`\n${"═".repeat(50)}`);
  console.log(`[STATS] Wave 15 Import Summary`);
  console.log(`${"═".repeat(50)}`);
  console.log(`  Manufacturers: ${mfrsCreated} new`);
  console.log(`  Robots:        ${inserted} inserted, ${skipped} skipped, ${errored} errors`);
  console.log(`  Total in DB:   ${count}`);
  console.log(`${"═".repeat(50)}`);
}

main().catch(console.error);
